### ISSUE TITLE
Script for printing overview of data (document/element) stats

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1004]
I built a reql  and JS script that pumps out some simple stats about the documents/elements, which was needed for the  paper. Consider stashing this somewhere here, possibly print it out from a web service endpoint (e.g. `/api/document/stats`)?

```js
{
  "articles": 74,
  "entities": 302,
  "complexes": 28,
  "uniqueEntities": 263,
  "organisms": [
    "Homo sapiens",
    "Mus musculus",
    "Danio rerio",
    "Saccharomyces cervisiae",
    "Drosophila melanogaster",
    "Caenorhabditis elegans",
    "Escherichia coli"
  ],
  "interactions": 216
}
```

**Comment by maxkfranz** [comment]
﻿Putting it as-is in a route sounds good.  

Eventually someone’s going to ask for per-organism stats (e.g. articles per organism), but that may not be important now.  Are the organisms in the current array currently sorted by the number of corresponding factoids?

**Comment by jvwong** [comment]
> Are the organisms in the current array currently sorted by the number of corresponding factoids?

That order is just order of appearance (Set). It also not exactly clear to me what a unique complex is at this point, but I'll put up the code

**Comment by jvwong** [comment]
FYI:

```json
{
  "articles": 74,
  "entities": 302,
  "uniqueEntities": 263,
  "complexes": 28,
  "orgEntityMap": {
    "Homo sapiens": 203,
    "Mus musculus": 46,
    "Danio rerio": 4,
    "chemical": 28,
    "Saccharomyces cervisiae": 12,
    "Caenorhabditis elegans": 7,
    "Drosophila melanogaster": 1,
    "Escherichia coli": 1
  },
  "interactions": 216
}
```
