### ISSUE TITLE
Add direct link for article when sharing (e.g. explorer)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1041]
Add the direct link when posting to Twitter or elsewhere - Why ?

[re: Altmetric 'Sources of Attention'](https://help.altmetric.com/support/solutions/articles/6000235926-twitter)
> Altmetric tracks Twitter attention in real-time via an API. We automatically collect tweets, retweets, and quoted tweets that contain a direct link to a scholarly output. Without the direct link to an output, our system will not be able to match the tweet with the appropriate output.
> Altmetric does not track tweets that contain links to news stories or blog posts about scholarly outputs (e.g a tweet of a news story about a journal article). These are considered "second-order citations", as they are mentions of attention about the output and rather than the output itself.

**Comment by maxkfranz** [comment]
We'll have to consider how this may affect our cards if we use a different link

**Comment by jvwong** [comment]
Easiest solution is to append link ('Read the paper: https://doi.org/<doi>') to the auto-generated text of interactions.

**Comment by jvwong** [comment]
Basically, last url posted with a card wins (this is opposite what the [actual docs](https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started#multiple) say)
