### ISSUE TITLE
Error upon selecting an ungrounded node in Explorer view

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1049]
The Explorer will error out (blank screen) when you try to select any ungrounded entities.

aside: I noticed that someone  submitted a paper with only bunch of ungrounded entities. This is admittedly a weird edge case as this doc would not be automatically available to the public.

Reproduce: 
- create a document with blank/ungrounded entity
- select the entity in the Explorer (read-only) view

**Comment by maxkfranz** [comment]
What could have allowed an incomplete (ungrounded) doc to be allowed to be submitted?  Is that still blocked?

Could you upload the problematic doc json?

**Comment by jvwong** [comment]
You can submit a doc in editor with ungrounded entities (albeit with a warning) - it won't be given a `public` status automatically though.

https://biofactoid.org/document/c384ec22-4c83-41da-8e91-99ca2aeb0a4c
