### ISSUE TITLE
Long load time for search Documents impedes Carousel loading

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1055]
The home component makes two closely staggered web service calls to retrieve documents: First to retrieve all public docs for the search (longer running) then the carousel to retrieve a recent slice. It seems that when the cache is empty, the latter is bottle-necked by the former. This has the effect of making the carousel load slow at the cost of the search.

_Originally posted by @jvwong in https://github.com/PathwayCommons/factoid/issues/1054#issuecomment-1071456390_

**Comment by maxkfranz** [comment]
See also: https://rethinkdb.com/docs/secondary-indexes/javascript/

> You have to explicitly use the getAll command to take advantage of secondary indexes.

If we don't use the index, it will be slow

_Originally posted by @maxkfranz in https://github.com/PathwayCommons/factoid/issues/1054#issuecomment-1071637740_

**Comment by jvwong** [comment]
This issue is mitigated by updates in #1054. Will have to look at standalone search when DB size increases.
