### ISSUE TITLE
Slim "Add my article" form 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1056]
## Description

**Q: What is the name of the feature?**

A: Defer "Add my article" form details to submit-time

**Q: What does this feature enable the user to do?**

A: Enables rapid-entry to curation. This includes via homepage as well as other elements in web page.

**Q: What information must the user provide to use the feature?**

A: Article title or PMID or doi. At submit-time, can select name and offer email (may be optional).

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Identify any dependencies on deferred details in document workflow from initiation to submission.

Major risk is that a user would not have an emailed link to their document. For instance, if they lose the editor page somehow, or wish to defer creation until later, it won't be 'in their inbox'.

**Q: How does this feature affect each class of user (persona)?**

A: For naive homepage visitors, entry is 1-step + 1-click. For others (e.g. article component in Explorer) this enables 1-click entry.

### Mockup

Homepage (A)

![ezadd HOME](https://user-images.githubusercontent.com/4706307/159767547-07a6b954-b606-466d-8b81-c63677d203b5.png)

Homepage (B; no popup)

![ezadd HOME copy](https://user-images.githubusercontent.com/4706307/159770325-a872445b-5c85-4ac4-8d34-463b12f62c76.png)

Editor, submission stage

![Submit](https://user-images.githubusercontent.com/4706307/159767587-76d44f3a-721b-4063-ae23-3b011589fc21.png)

### Details

- Rationale
  - Requiring an email and name looks like a sign-up, but we sort of imply there's no sign up required and in fact we don't have accounts
    - Do we really even use the emails and names? We don' validate names or emails     
  - Once an author has added their paper and pathway, they are more likely to provide additional details (name, email)
  - If we have the paper, we can auto-populate forms (e.g. name or email or ORCID in PubMed) 
    - I don't recall encountering a submitted paper that didn't initially return a PubMed record  
  - Free text input of names are sometimes hard to match (below) 

#### Free text input for names can be problematic

Some actual examples of authors who input their name:

| Author name (PubMed)  | Doc | Provided name |
|-----------------------|-------------------|-------------------------|
| Kelsi O [KO] West | 6ddab5e5-aa9a-46bd-ab55-54faf022511c | Kelsi West              |
| Prabodh [P] Kapoor | 4e73841d-3c9c-470f-9be0-ddffac92f9f3 | Prabodh Kapoor, Ph.D.   |
| Matthew W D [MWD] Perry | d1f479b2-6652-40e7-ab2e-fc8d052190e6 | Matthew Perry           |
| Griselda [G] Velez-Aguilera | 3cee7c15-712d-4f89-839c-369856534bb4 | Griselda VELEZ AGUILERA |
| Sebastián [S] Pons | 52c87a77-9f83-40ea-bef6-ea48c8d3bb89 | SEBASTIAN PONS          |
| Stephan [S] Clavel | a002f088-6342-46ff-9878-b6242544928d | Clavel                  |
| Annalisa [A] Di Ruscio | 87c31b61-e29d-4cef-bdd5-9dd8167fb218 | di ruscio annalisa      |
| Syed Muhammad [SM] Hamid | cdd26bce-9d82-48e0-8380-7326c765b2af | Syed Hamid              |
| ??? | 5bbfce39-d639-4911-b69e-7f4423e8324f | Yu-Ning Liu |
| Benjamin T [BT] Goult | 63008749-2c2b-4863-8e73-386c851feb6a | Ben Goult               |
| Yu-Ning [YN] Lu | e44a7389-9336-4519-ae51-4ce24bfbe844 | YuNing Lu               |
| Dong-Min [DM] Yin | 69cdff5d-cf3c-4e9c-9d5e-cede9a334ed8 | Dongmin Yin             |

With #1065, the author field should be populated with an author profile, possibly containing an ORCID so that there is less ambiguity.

### Refs

- #1017

**Comment by jvwong** [comment]
"Who can submit" seems to be a pressing concern with journal editors - allowing authors to select from an existing list of ORCIDs at the pre-submit stage might be the least intrusive time to do this (but they'll have to authenticate via ORCID, more complexity, may not have an account etc.).

**Comment by maxkfranz** [comment]
> "Who can submit" seems to be a pressing concern with journal editors - allowing authors to select from an existing list of ORCIDs at the pre-submit stage might be the least intrusive time to do this (but they'll have to authenticate via ORCID, more complexity, may not have an account etc.).

To consider the practicality of this, it would be useful to have a sense of what proportion of prior contributors have an associated ORCID.  The explorer already shows all the authors with ORCIDs.

Just a quick look shows that at least some contributors don't have an ORCID.  So the trade-off would be that we may lose out on our contribution rate.

**Comment by jvwong** [comment]
Related is https://github.com/PathwayCommons/app-ui/issues/1434  - i.e. making 'Add my article' as simple and widely available as possible, simple form

**Comment by jvwong** [comment]
Based on recent discussion, propose a "zero input" call to action to launch the curation tool, which would be low-friction and potentially easier to 'share'. Editor already provides feature to fill out article/author details when missing, and treats it as as just another required step towards submission. 

![unstable factoid baderlab org_document_6b0759bb-bc7b-47c7-8286-1f46c79954e6_9ab2d031-1fd7-48d9-a9ea-ac588adc3f36](https://github.com/PathwayCommons/factoid/assets/4706307/12a61291-062d-4b49-8e6e-1d87757f2430)
