### ISSUE TITLE
Prevent Submission of Factoids without Interactions

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/factoid#1070]
@jvwong Should submissions like these be blocked that are just nodes without interactions?  

https://biofactoid.org/document/69cdff5d-cf3c-4e9c-9d5e-cede9a334ed8

**Comment by jvwong** [comment]
Yes, should add to warnings at Submit for case: zero interactions. 

Edge case: complex isn't technically interaction.

**Comment by jvwong** [comment]
A middle ground is to prevent a document from becoming public when a doc has no

a. interaction(s)
b. complex(es)

**Comment by jvwong** [comment]
Better: Currently, the submit UI  checks for >=1 entity (participant). Could change this to check for >=1 interaction.
