### ISSUE TITLE
Deleting previous query text in search bar: empty screen

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1075]
Would expect deleting text of previous query to show default (all).

**Comment by maxkfranz** [comment]
That’s a good catch.

By the way, are we measuring how much the search feature is used?

**Comment by jvwong** [comment]
> That’s a good catch. By the way, are we measuring how much the search feature is used?

Not currently. Related is #1053: I realized that I didn't really have enough detail about what we want to capture and how, so maybe we can table this for discussion. It's also important as I rev up the email campaign numbers.

**Comment by jvwong** [comment]
Reproducing this error is peculiar. 

Type `SENP1` then:

1. Slowly delete each character: Works as expected (list of all docs)
2. Quickly delete each character: Broken (empty screen)

![Untitled](https://user-images.githubusercontent.com/4706307/187783448-7d706c76-abc3-41b2-9bc3-060510ba73fd.gif)

**Comment by jvwong** [comment]
Bet guess what's happening is that the debounced searches are getting 'queued'. These queued searches can be dequeued following an empty search box, and in doing so, use an empty string as a query'
