### ISSUE TITLE
Using a connection pool for RethinkBD connections

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#1084]
## Description

From my understanding, Biofactoid currently uses a single RethinDB connection instance for handling all the requests (https://github.com/PathwayCommons/factoid/blob/unstable/src/server/db.js#L20). I suspect 
(but not totally sure) that a Rethinkdb connection instance is not thread-safe. I believe it may be a problem when multiple API requests use this RethinDB connection instance concurrently. Do you agree? If so can we use a connection pool instead of having a single DB connection instance? I see that there is a library written for this purpose (https://github.com/hden/rethinkdb-pool).

**Comment by maxkfranz** [comment]
What problem are you encountering?

JS code in Node runs on one thread and we only have one server instance deployed, right?

**Comment by metincansiper** [comment]
My concern is not related to whether we have one or multiple instances deployed. Even if we had multiple instances all of these would have their own connection instances so my point is not related to it.

My concern is more about what would happen inside that single server instance. JS code in Node runs on one thread but still allows concurrent operations. Let's say I make concurrent calls to an API endpoint that updates the database. These calls may be handled concurrently. Is that right? My point is about this case. Because in this case, multiple requests would be dealt with concurrently through this single connection instance. Let me know if you think that I am wrong.

**Comment by maxkfranz** [comment]
All I/O is like this for Node, so things like DB driver libraries and HTTP request libraries generally take into account this I/O model — meaning that well-designed libraries (e.g. well-known DB drivers) should generally function properly out of the box.  

Are there concrete errors that you’re able to reproduce?  Is there a particular, underlying, user-facing problem that you’re trying to solve?
