### ISSUE TITLE
Editable paper title/info

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1130]
It doesn't appear that editing the title is possible. I can do it through the admin.

I believe this would cause users to repeatedly add a paper through the call to action, and a lot of frustration.

**Comment by maxkfranz** [comment]
> I believe this would cause users to repeatedly add a paper through the call to action, and a lot of frustration.

In what case?  To correct a typo?

**Comment by jvwong** [comment]
Yes I noticed the input for paper isn't always input correctly for whatever reason. Not everyone is pasting I guess.

**Comment by maxkfranz** [comment]
How frequent are these typos?

**Comment by jvwong** [comment]
Only a handful, mostly people paste correctly.

**Comment by maxkfranz** [comment]
Do you have a clear sequence of user actions?  Did they open the editor and then go back, or did they create lots of documents before opening the editor?

**Comment by jvwong** [comment]
Seems like the user input it (wrong title) directly, then just went right ahead and submitted.   

> Hi  
> The pnas is right. I think I just clicked on what came up and it seemed right. Should I do something? Thanks! 
> 
> From: Jeffrey Wong 
> Sent: Wednesday, March 15, 2023 4:10 PM
> Subject: Re: Helping maximize the reuse of published findings
>
> Hi _ - thanks again for you help on Biofactoid. 
>
> There is a minor glitch that I'm trying to clear up:
> 
> Our system had trouble finding a PubMed entry for the Biofactoid submission with title "Structural insights into a novel mode of eIF4E regulation: the Z RING eIF4E complex".  The Biofactoid editable link is ...
>
> PubMed seems to want to match it with a PNAS paper "Structural characterization of the Z RING-eIF4E complex reveals a > distinct mode of control for eIF4E" ([https://pubmed.ncbi.nlm.nih.gov/20212144/]
> 
> Was the one in PubMed the paper you intended to submit? If so, do you recall why the paper title you submitted to Biofactoid differed from the PNAS article?
