### ISSUE TITLE
RethinkDB for testing purposes: Cleanly delete before each test

### ISSUE THREAD

**Issue by lindajiawenli** [PathwayCommons/factoid#1135]
The current way of clearing the testing RDB sometimes does not complete fully, resulting in errors when the test runs again ("Duplicate primary id found").

New Tentative Approach: Cleanly delete database before each test runs, and create a new empty one

**Comment by jvwong** [comment]
I found an NPM library `rethinkdb-fixtures` that lets you create database test fixtures directly from file (e.g. a direct dump of the database), and looks simpler.

 Let me put it up as PR and we can discuss.

https://rethinkdb.com/docs/frameworks-and-libraries/
