### ISSUE TITLE
Neo4j: addDocumentToNeo4j should operate on Document instance

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1138]
The `addDocumentToNeo4j` looks like it's taking in a plain object (converted from JSON) rather than a Document model instance. Also this function should be documented, for cases like this.

https://github.com/PathwayCommons/factoid/blob/d9f5d9b0597e8c8e76bc4c5e34866b7ed1b1c4e6/neo4j-test/doc-tests.js#L58-L66

**Comment by lindajiawenli** [comment]
Working on it in branch `iss1138-adddocumenttoneo4j`
