### ISSUE TITLE
Image endpoint: Avoid checking updates per request

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1151]
A reasonable estimate is that 99.9% of the time, submitted pathways / documents are never updated by the author after the fact. A very minor case (handful) is when it is updated, by us during post-curation or the author does do it post-submission. 

This suggests that we can prioritize the case where the network image stays the same on submit. Importantly, checking the time of last update on each document on image fetch is unnecessary and introduces a performance burden on each webpage load (home, search).

---

_Originally posted by @jvwong in https://github.com/PathwayCommons/factoid/issues/1143#issuecomment-1480158389_

> I'm finding the `getDoc` call to be a major offender following an initial load:
> 
> https://github.com/PathwayCommons/factoid/blob/eca68a131632c259a52f895741a9f8b406755cbb/src/server/routes/api/document/index.js#L1453-L1466
>
>Alternative to handle `imgCache` staleness is:
> - Fetch the JSON results from `/api/document/` (ttl is 24 hours)
>  - Find the matching document and it's `lastEditedDate`
>  - Hit the cache or regenerate as usual
>
>So the downside is authors won't see updates to their submitted docs within 24 hours. The p-limit code is still valid on initial load, the rest of the time the entire search browse page loads almost instantly.
>

**Comment by maxkfranz** [comment]
Other notes:

- If the docs are rarely changed, then don't even bother with cache invalidation.  Even when we do correct an author's document, do we change it visually?  It's probably just the grounding or interaction type, which doesn't make a visual change.
- Store images in the DB.
  - Pro: Simple.
  - Pro: Would make social cards faster and more reliable.  I think Twitter may bail out if the image loads too slowly.
  - Con: Bigger DB.

**Comment by jvwong** [comment]
> Other notes:
> 
> * If the docs are rarely changed, then don't even bother with cache invalidation.  Even when we do correct an author's document, do we change it visually?  It's probably just the grounding or interaction type, which doesn't make a visual change.

For whatever reason, the cache is returning true on every `has(id)`, regardless of the ttl, which in fact, is being set as expected. This means it behaves like you said above.
