### ISSUE TITLE
Neo4j: addAllDocumentsToNeo4j

### ISSUE THREAD

**Issue by lindajiawenli** [PathwayCommons/factoid#1156]
### Currently:
The function `addDocumentToNeo4j( doc )` takes in one document instance `(doc)` and makes the appropriate nodes and edges (works for complexes as well now) in a Neo4j database.

It is currently used in test suites, with a hard-coded RDB fixture called `factoid-neo4j-test`

### Goal:
Create a function `addAllDocumentsToNeo4j()` that makes the appropriate nodes and edges in Neo4j for *ALL the documents in the "real" `factoid` database. 

*with appropriate filters so that only public documents are used. Do not put demos, drafts, etc. into Neo4j.

**Comment by lindajiawenli** [comment]
> add all (public) docs: cron job could initiate (nightly) 
>add one: when an author hits "submit" on their document

Oh, I am not sure how to do that. That sounds more practical than what I have now though, which is just adding all public documents to neo4j when `node -r esm src/neo4j/add-all-docs.js` is run from the command line

**Comment by lindajiawenli** [comment]
Ok, sounds good to me. At least we've discovered that there aren't any errors (that I can immediately see) that come from adding all 194 public documents to Neo4j

**Comment by jvwong** [comment]
There's an error thrown on restoring an empty database (which only ever happens in dev mode):

1. clear the database
2. restore db from file

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: No response from database for ID c34266eb-0e76-4b8e-a91d-47fcb77bc03e
```

**Comment by jvwong** [comment]
The above bug arises because the restore adds to `document` and `element` tables, but of course, not all at once. So when a document is added, it looks for the associated data in other tables, which haven't been added yet (this is also a hidden bug of the database dump, but its set on a time delay).

**Comment by jvwong** [comment]
I still think it would be nice to "add all" under the following circumstances:

- [ ] Refresh at regular interval (e.g. nightly)
- [ ] Populate graphDB when a we spin up a new factoid instance (for convenience)
