### ISSUE TITLE
eslint complaining about class fields.

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1158]
eslint complains about class fields

https://github.com/PathwayCommons/factoid/blob/57cd4b12c16fd16b998edd4a5e3af08fa2918bfe/src/server/routes/api/document/p-limit.js#L23-L27

Not sure what settings to change.

**Comment by maxkfranz** [comment]
Probably upgrading and setting the ES version

**Comment by maxkfranz** [comment]
Or just set it to ignore this file

**Comment by jvwong** [comment]
I'm just going to ignore - the upgrade raises a whach-a-mole set of issues.
