### ISSUE TITLE
Neo4j: Add field for Interaction types 'activation', 'inhibition', 'undirected'

### ISSUE THREAD

**Issue by lindajiawenli** [PathwayCommons/factoid#1164]
### Currently:

Each edge in Neo4j is made with the type `INTERACTION` (including the edges that represent complexes) and has a property type of `phosphorylation`, `binding`, etc. 

However, there is something missing: the "type" in the sense of whether the interaction is an `activation`, `inhibition`, or `undirected`. There isn't anything in Neo4j indicating that yet.

I am making note of it here, in case we do want to add that bit of information in.

### Possible solutions:

Instead of `type: 'phosphorylation'`, we could have
- `type: [ 'phosphorylation', 'activation']`
- `type: 'activation-phosphorylation'`
- `type: 'phosphorylation'` and `interaction: 'activation'`

Or we can leave it as-is.

**Comment by jvwong** [comment]
Factoid applies a `group` (null, positive, negative) to the source or target. `type` is fine, as that's what factoid uses too.
