### ISSUE TITLE
Neo4j: Investigate unconnected nodes

### ISSUE THREAD

**Issue by lindajiawenli** [PathwayCommons/factoid#1166]
### Currently:

There are some nodes in the Neo4j database that do not have any edges connecting them with anything else (this is seen after running `addAllDocumentsToNeo4j`, #1157 ).

![Screen Shot 2023-04-05 at 11 46 35 AM](https://user-images.githubusercontent.com/66929920/230134100-e5036138-8179-46a1-bec4-1dd4cfa07cb6.png)

### Goal:

Print out the document ids that these nodes belong to and see what is going on before discussing next steps.

**Comment by jvwong** [comment]
Can you identify the data source?

**Comment by jvwong** [comment]
OK thanks - What I meant by 'source' is where did you obtain the data that was loaded into neo4j? i.e. if we wanted to reproduce your issue of orphan nodes.

**Comment by jvwong** [comment]
This one [a6b4351d-b474-49d9-bc3d-f044513d5a0c](https://biofactoid.org/document/a6b4351d-b474-49d9-bc3d-f044513d5a0c) doesn't seem to make sense - looks like it only has connected nodes

**Comment by lindajiawenli** [comment]
Yeah, I just saw that myself. So I got the data from a database dump you gave me a while back (installed it via pip). I think it was called `factoid_dump_2023-02-09_04-00-25-245.tar.gz`
