### ISSUE TITLE
Documents no longer posted to  Twitter

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1186]
Seem like anything submitted (public) after Created May-19-2023 isn't posted to Twitter.

Reproduced this locally, using the account: https://twitter.com/TestAcc87711534 

Console logging:
```
error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
```

**Comment by jvwong** [comment]
Grepped the production logs:

```
webapp        | 2023-05-23T21:42:11.914917795Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-05-23T23:43:29.878583451Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-05-25T02:57:27.774213479Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-05-31T06:22:50.814666665Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-05-31T07:00:29.332718417Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-05-31T10:13:46.937725680Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-05-31T13:01:05.542623208Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-06-01T14:32:17.047933921Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-06-01T19:39:15.457374621Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-06-02T06:42:35.467177060Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-06-08T17:06:55.478443833Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
webapp        | 2023-06-09T15:37:50.277829420Z error:   Error attempting to Tweet: [{"code":32,"message":"Could not authenticate you."}]
```

**Comment by jvwong** [comment]
@maxkfranz are the @TestAcc87711534 and @biofactoid developer apps listed under your account?

**Comment by jvwong** [comment]
Under biofactoid account: 

> This App has violated Twitter Rules and policies. As a result, it can no longer be accessed.

**Comment by jvwong** [comment]
Forums take home message:

- Can happen for no clear reason
- No way to actually open up a support ticket (even though they ask you to do so)
- Could also happen to people using paid tier

**Comment by gbader** [comment]
Does this mean we can no longer log into it from the web interface?  I 
don't see any issues accessing https://twitter.com/biofactoid

**Comment by jvwong** [comment]
> Does this mean we can no longer log into it from the web interface? I don't see any issues accessing https://twitter.com/biofactoid

We can log in etc as the account is fine. The problem is scoped to the "App" we created under the account. 

I'm hesistant to recreate the App, because this also happened to a separate App under an independent test account.

**Comment by gbader** [comment]
any workarounds?

**Comment by jvwong** [comment]
There's some indication that this might be a canned response to Apps that haven't been updated to match the new Twitter web service API.

I'll try to, in a local dev branch:
- Create test account 
- Create project and App under the [Free access tier](https://developer.twitter.com/en) which allows 1 app to tweet 1500/month
- Try to post tweet via web service client (e.g. curl, insomnia)
- Ensure we are using a suitable Twitter npm package to support Twitter API v2
- Determine if biofactoid submit leads to correctly posted Tweet

> That seems to be a standard message they use for apps that haven’t been updated to match the recent changes made to the Twitter API as documented here: Announcements - Twitter Developers 17
>
> In general people need to pick a suitable access tier, create a project (if none exists), move their “Standalone app” to the project (from the project itself) and move from v1.1 API to V2 API. 

https://twittercommunity.com/t/deprecation-of-legacy-access-tiers-in-the-twitter-api/196162

**Comment by jvwong** [comment]
> Worth looking into: [Academic Research access](https://developer.twitter.com/en/products/twitter-api/academic-research)

Academic access does not actually exist [as far as I can tell](https://developer.twitter.com/en/products/twitter-api/academic-research/application-info). 

<img width="600" alt="Screen Shot 2023-06-22 at 12 06 26 PM" src="https://github.com/PathwayCommons/factoid/assets/4706307/7028f916-0ea7-4e97-bd71-5c559c424f2c">
