### ISSUE TITLE
Disable automated layout/shortcuts

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1202]
A user complained that their document layout changed from what they desired during curation. There is a keyboard shortcut to perform layouts in the editor: 

https://github.com/PathwayCommons/factoid/blob/2878ce4dd9d0bea15e7883702fd20314c15b572b/src/client/components/editor/cy/layout.js#L34

The suggestion is to disable this and other layouts just in case.

**Comment by maxkfranz** [comment]
One edge case I thought of since our last email is PC/Biopax import. Those sorts of documents may still need layout support. 

The least invasive change for now would be to just comment out the keyboard shortcut.  If the issue comes up again, we can revisit it.

**Comment by jvwong** [comment]
Other key: functions I've noticed:

- 'f' : center
- 'a': select all
- 'delete': selected only
- menu
  - '1': add node
  - '2', '3', '4' : select edge types

I would disable 'f'...
