### ISSUE TITLE
Capture paper relations 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1203]
It's worth considering adding in an extra field for PubMed and CrossRef data to capture relations between preprints and articles. 

|Source  |ID Type                  |Article type attribute                 |Publishers Supported                    |Relations                |
|--------|-------------------------|---------------------------------------|----------------------------------------|-------------------------|
|PubMed  |PubMed uid (optional [PMCID, DOI])   |\<PublicationType\> (MESH: D000076942)   |bioRxiv; medRxiv; arXiv; Research Square|child, parent            |
|CrossRef|Digital Object Identifier|type: posted-content; subtype: preprint|multiple (members)                      |child, parent, equivalent|

_Originally posted by @jvwong in https://github.com/PathwayCommons/factoid/issues/961#issuecomment-1710749298_

**Comment by jvwong** [comment]
Sample for [ "The ATM-E6AP-MASTL axis mediates DNA damage checkpoint recovery." eLife 3023. PMID: 37672026; DOI: 10.7554/eLife.86976]()

`PubMedArticle`

```xml
<CommentsCorrectionsList>
  <CommentsCorrections RefType="UpdateOf">
	  <RefSource>doi: 10.1101/2023.02.22.529521</RefSource>
  </CommentsCorrections>
  <CommentsCorrections RefType="UpdateOf">
	  <RefSource>doi: 10.7554/eLife.86976.1</RefSource>
  </CommentsCorrections>
  <CommentsCorrections RefType="UpdateOf">
	  <RefSource>doi: 10.7554/eLife.86976.2</RefSource>
  </CommentsCorrections>
</CommentsCorrectionsList>
``` 

CrossRef Work

```json
		"relation": {
			"has-preprint": [
				{
					"id-type": "doi",
					"id": "10.7554\/eLife.86976.2",
					"asserted-by": "subject"
				}
			],
			"is-same-as": [
				{
					"id-type": "doi",
					"id": "10.7554\/eLife.86976.3",
					"asserted-by": "subject"
				}
			],
			"is-version-of": [
				{
					"id-type": "doi",
					"id": "10.7554\/eLife.86976.1",
					"asserted-by": "subject"
				},
				{
					"id-type": "doi",
					"id": "10.7554\/eLife.86976.2",
					"asserted-by": "subject"
				}
			]
		},

```

**Comment by jvwong** [comment]
All of the noted articles unrecognized by Biofactoid on initial submission (i.e. they were preprints) got updated by the CRON to their respective eLife Version of Record: https://github.com/PathwayCommons/factoid/issues/961#issuecomment-1645461211

We should keep this in mind regarding any update strategy. For instance, if we support a preprint and only update that (not a subsequent publication with the same title) it would be nice to link that to the publication in Biofactoid, make that obvious, so the author doesn't feel they need to create another record.

**Comment by maxkfranz** [comment]
Are you thinking of having two links, one for the preprint and one for the published article?

**Comment by jvwong** [comment]
- Sub-Tasks
  - [ ] relations: Capture PubMed article information in `CommentsCorrectionsList` that contains references to preprints etc.
  - [ ] update: Check for PubMed updates for any `Document` with publication type preprint 
  - [ ] UI: to reflect relations

**Comment by jvwong** [comment]
eLife Reviewed Preprints that eventually moved on to a Version of Record (VOR)

|created   |doi                  |id                                  |journal                         |pmid|title                                                                                                                                                            |type    |VOR|
|----------|---------------------|------------------------------------|--------------------------------|----|-----------------------------------------------------------------------------------------------------------------------------------------------------------------|--------|---|
|2023-11-30|10.7554/elife.87510.3|a5f9c7ef-4ba0-46a4-b410-5157bc3d12e7|elife                           |    |A positive feedback loop between ZEB2 and ACSL4 regulates lipid metabolism to promote breast cancer metastasis                                                   |Preprint|Y  |
|2023-12-13|10.7554/elife.88637.2|d3a5b322-661d-4b9f-8996-8cf881dbe9da|elife                           |    |Ulk4 promotes Shh signaling by regulating Stk36 ciliary localization and Gli2 phosphorylation                                                                    |Preprint|Y  |
|2023-12-26|10.7554/elife.89835.2|b3c87835-7976-4e50-9949-23e1039416e2|elife                           |    |Gle1 is required for tRNA to stimulate Dbp5 ATPase activity in vitro and to promote Dbp5 mediated tRNA export in vivo                                            |Preprint|Y  |
|2023-12-28|10.7554/elife.88328.3|667182df-ff59-4cec-abf4-96e2a3873e38|elife                           |    |Comparative Interactome Analysis of Œ±-arrestin Families in Human and Drosophila                                                                                 |Preprint|Y  |
|2024-01-09|10.7554/elife.90184.3|1b257dab-095b-4a63-8e57-60edbf32ff9a|eLife Sciences Publications, Ltd|    |14-3-3 protein augments the protein stability of phosphorylated spastin and promotes the recovery of spinal cord injury through its agonist intervention         |Preprint|Y  |
|2024-01-10|10.7554/elife.88808.3|f0eb960f-15b3-40d0-a16c-6eeae35ffe06|eLife Sciences Publications, Ltd|    |Orai mediated Calcium entry determines activity of central dopaminergic neurons by regulation of gene expression                                                 |Preprint|Y  |
|2024-01-23|10.7554/elife.90192.2|94f6073c-5567-4f40-bdce-a84719873463|eLife Sciences Publications, Ltd|    |Heparan sulfate promotes TRAIL-induced tumor cell apoptosis                                                                                                      |Preprint|Y  |
|2024-01-24|10.7554/elife.87559.3|01d5460e-c42c-4110-8f2b-b184b4dbc7ba|eLife Sciences Publications, Ltd|    |Coupling of Slack and NaV1.6 sensitizes Slack to quinidine blockade and guides anti-seizure strategy development                                                 |Preprint|Y  |
|2024-02-02|10.7554/elife.92731.2|d2827061-7442-4a1d-a81c-71bc2ae1fd29|eLife Sciences Publications, Ltd|    |Depletion of SMN Protein in Mesenchymal Progenitors Impairs the Development of Bone and Neuromuscular Junction in Spinal Muscular Atrophy                        |Preprint|Y  |
|2024-02-12|10.7554/elife.87386.2|a6068a85-beff-422c-b221-4d854528b0cf|elife                           |    |The acetylase activity of Cdu1 regulates bacterial exit from infected cells by protecting Chlamydia effectors from degradation                                   |Preprint|Y  |
|2024-02-20|10.7554/elife.88565.2|9f960e8a-8340-46cb-9955-c1b27fe0d271|elife                           |    |Delta-dependent Notch activation closes the early neuroblast temporal program to promote lineage progression and neurogenesis termination in Drosophila          |Preprint|Y  |
|2024-02-28|10.7554/elife.90051.3|adcf7c9e-74f2-406e-a511-90a5a8d28d34|eLife Sciences Publications, Ltd|    |Neuronal NPR-15 modulates molecular and behavioral immune responses via the amphid sensory neuron-intestinal axis in C. elegans                                  |Preprint|Y  |
|2024-03-04|10.7554/elife.93013.2|dd2da1ca-fc9f-4cf3-bba2-6e9937179945|eLife Sciences Publications, Ltd|    |The non–muscle actinopathy–associated mutation E334Q in cytoskeletal γ– actin perturbs interaction of actin filaments with myosin and ADF/cofilin family proteins|Preprint|Y  |
|2024-03-06|10.7554/elife.91218.2|a032f12a-fe30-44e7-b4b5-b8f27b89cf0a|eLife Sciences Publications, Ltd|    |A binding site for phosphoinositides described by multiscale simulations explains their modulation of voltage gated sodium channels                              |Preprint|Y  |
|2024-03-06|10.7554/elife.89045.3|8f846123-d500-4740-a016-92e5ddf6634d|eLife Sciences Publications, Ltd|    |Gut microbiota-derived gamma-aminobutyric acid from metformin treatment reduces hepatic ischemia/reperfusion injury through inhibiting ferroptosis               |Preprint|Y  |
|2024-03-09|10.7554/elife.88772.3|405c7f93-f10b-4b28-ab8d-be532dec745a|eLife Sciences Publications, Ltd|    |Imidacloprid disrupts larval molting regulation and nutrient energy metabolism, causing developmental delay in honey bee Apis mellifera                          |Preprint|Y  |
|2024-03-14|10.7554/elife.92755.2|60188d5a-8dc8-4d94-8f01-e6d7cddf850f|eLife Sciences Publications, Ltd|    |Rho GTPase signaling and mDia facilitate endocytosis via presynaptic actin                                                                                       |Preprint|Y  |
|2024-03-16|10.7554/elife.91040.2|7df07c27-0f7a-4223-b685-be33231e405a|eLife Sciences Publications, Ltd|    |Purine nucleosides replace cAMP in allosteric regulation of PKA in trypanosomatid pathogens                                                                      |Preprint|Y  |
|2024-03-17|10.7554/elife.91060.2|9ffc09f3-83a2-4528-9a2b-babf47119327|eLife Sciences Publications, Ltd|    |Intermittent fasting promotes ILC3s secreting IL-22 contributing to the beigeing of white adipose tissue                                                         |Preprint|N  |
|2024-03-23|10.7554/elife.89938.3|bb3983f5-8d1b-4e20-86ea-c63e14c460ee|eLife Sciences Publications, Ltd|    |Membrane contact sites regulate vacuolar fission via sphingolipid metabolism                                                                                     |Preprint|Y  |
|2024-03-25|10.7554/elife.89613.2|cdfe5b24-967c-4a7e-b255-13ed940ac87d|eLife Sciences Publications, Ltd|    |Mechanically stimulated osteocytes maintain tumor dormancy in bone metastasis of non-small cell lung cancer by releasing small extracellular vesicles            |Preprint|Y  |
|2024-03-29|10.7554/elife.90820.2|fa58260a-701a-4f16-a610-dc22c1ee6bb0|eLife Sciences Publications, Ltd|    |Interplay between charge distribution and DNA in shaping HP1 paralog phase separation and localization                                                           |Preprint|Y  |
|2024-04-09|10.7554/elife.90203.2|d2da1116-a42e-4ef2-b89a-c2efe3b79391|eLife Sciences Publications, Ltd|    |The Rapidly Evolving X-linked miR-506 Family Finetunes Spermatogenesis to Enhance Sperm Competition                                                              |Preprint|N  |
|2024-04-12|10.7554/elife.91864.2|3114fc5a-3686-48ba-aacf-41ac678e0026|eLife Sciences Publications, Ltd|    |Inhibition of the serine protease HtrA1 by SerpinE2 suggests an extracellular proteolytic pathway in the control of neural crest migration                       |Preprint|N  |
