### ISSUE TITLE
Query returns biorxiv preprint not published version

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#1241]
Article title "NOC1 is a direct MYC target, and its protein interactome dissects its activity in controlling nucleolar function" should return [PubMed record](https://pubmed.ncbi.nlm.nih.gov/38213308/) rather than actual, which is [bioRxiv preprint](https://www.biorxiv.org/content/10.1101/2023.09.12.557489v1).

Aside: User was clever enough to try `PMID: 38213308` but we don't parse these.

**Comment by maxkfranz** [comment]
Seems like a bug, since PM should generally take precedence over BR

**Comment by jvwong** [comment]
A direct call to EUTILS ESEARCH returns nothing. So the problem is on their end.
