### ISSUE TITLE
Promote extra Uniprot searches

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#147]
Background: In user testing, much confusion arose when entity names in text were unlike those Uniprot entry names, for instance, FasL (text) and TNFL6_HUMAN (UniProt entry name). Factoid in fact provides the required information in the ‘Protein names’ and ‘Gene names’ fields from UniProt, but most users were seemingly unaware of this or were merely willing to ‘skim’ this text for a match if the correct record was far down the list.

- Some searches have bad sorting
- Do extra queries on gene name, protein name
- Highlight matched field
- Promote separate query matches to top of regular uniprot list

**Comment by maxkfranz** [comment]
Addressed by restricting the search fields
