### ISSUE TITLE
Highlight entity textbox in red

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#148]
Background: In user testing, 4/10 networks were left ‘ungrounded’, meaning that a majority of proteins in the network were unassociated. Users may not have understood that this must be done deliberately; Alternatively, they may have confused this system with a hint or clue for the correct entity label. 

Nudge that the entity is ungrounded

**Comment by maxkfranz** [comment]
Addressed by adding a red message for named entities that are unassociated/ungrounded
