### ISSUE TITLE
Selecting edge direction and orientation

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#152]
Background: In user testing, users expressed a desire to indicate edge 'direction' but were unclear how to access this function. Invariably, users positioned the mouse over the ‘blue dot’ in the center of the edge. Some users eventually found the menu by clicking around the edge ‘dot’. It was also not clear how to select or reverse the arrow ‘orientation’ - the node at which the arrow terminates.

- On selection of edge, immediately display option (undirected, barbed, flat) for some half of the edge. Alternate (or cycle if hyper-edge) sides on subsequent selections.

**Comment by maxkfranz** [comment]
Addressed by 

https://github.com/PathwayCommons/factoid/commit/e6b3af0bc2ff62e14b8a1403e579577278e2aa22
