### ISSUE TITLE
Appearance of two termini for single edge

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#153]
Background: In user testing, a user managed to display an arrow with what appeared to be both a barbed and flat terminus (circled in screenshot below). 

Below is a screenshot from video capture (15:00 of 'HK_1.mov')

![screenshot at sep 21 16-32-32](https://user-images.githubusercontent.com/4706307/30717400-c85468ee-9eea-11e7-92f6-05c061f04cac.png)

**Comment by maxkfranz** [comment]
I think this should be resolved by my upcoming update to use the latest version of the edgehandles extension.

**Comment by maxkfranz** [comment]
This is how you create the issue:

![screen shot 2018-01-25 at 12 12 42 pm](https://user-images.githubusercontent.com/989043/35402007-38024d28-01c9-11e8-930d-9777f7dad488.png)

Remove C from the {A, B, C} interaction.

Now, you have two overlapping {A, B} interactions.

I suppose we could delete the entire interaction if we detect a case like this.

**Comment by maxkfranz** [comment]
The user can no longer create interactions with more than two participants through the UI.
