### ISSUE TITLE
PC query support

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#154]
Support for sending a Pathway Commons query and integrating the whole/partial result into the model.

**Comment by jvwong** [comment]
To clarify, could you describe a use case and how this would affect the UI/model?

**Comment by fdurupinar** [comment]
Use Case: 
Users are drawing a new pathway.  They send a PC query to find the paths between a group of genes.  They already have information about one or more relations based on their research. System draws the whole PC query result and  users remove the irrelevant/unwanted edges.

Or

In case multiple views are supported, users select the relevant edges from the resulting query and add them to the pathway they want to draw.

**Comment by jvwong** [comment]
This feature could be a key enhancement - under particular conditions.  

Suppose:
1. A version of Factoid accepts very rich annotation including names, species, database IDs, evidence/publications, modifications, comments etc.
2. A user wishes to express a 'known' interaction

A user wants to add interactions, especially well-known ones, in the most efficient way possible - 'Just Do It'. One method is the equivalent of a form autocomplete, but in this case we're adding all participants, interaction types and annotation fields for them. 

For an (impatient) user, the key tradeoff is: Is it easier just to draw a couple of nodes, a single edge and annotate the minimal number of fields that Factoid is making me add  - OR - is it easier to use this 'PC Query' feature? 

No one disputes how great this is from a data standpoint. I wonder when this would be worth all the development, testing and optimization effort...

**Comment by fdurupinar** [comment]
I'm not sure I understand this concern. When the user sends a PC query, it is about the unknown relations (to the user) that the user might want to include. The existing relations only set the basis for the query. So, the PC result will be more comprehensive and the user will be able to keep all or some of them. 
Anyway, we can help implement this feature. We'll start a new branch.

**Comment by davidserv** [comment]
Hello,

I am on the implementation of the PC query in factoid and right now I need to create another selector in the stylesheet.js so whenever pathway common identifies unknown relations with proteins already on screen I mark the edges (if any) between those proteins so when the user clicks on those particular edges I can display the result of the PC query.

The thing is I don't understand how the stylesheet is used in the system for example how the click event on an edge uses the values stored in the selector edge:selected ? How to "call" the selectors programmatically, i.e. with no click event ?

David S.

**Comment by maxkfranz** [comment]
You don't put business logic in Cy.js stylesheets, just as you wouldn't for CSS in HTML.

Stylesheets are for visual presentation only.  If you want to store state, you should use `data()` or `scratch()` as appropriate.

- http://js.cytoscape.org/#eles.data
- http://js.cytoscape.org/#cy.scratch

If you don't understand how stylesheets work, refer to the docs:

- Stylesheets : http://js.cytoscape.org/#style
- Selectors: http://js.cytoscape.org/#selectors

If you aren't familiar with CSS, you should probably read some background info on MDN beforehand: https://developer.mozilla.org/en-US/docs/Web/CSS

**Comment by davidserv** [comment]
Indeed I am not that familiar with all this and was not aware that it is related to cytoscape. Really appreciate your help.

David S.
________________________________

**Comment by sacdallago** [comment]
Generative:
 - When creating a new document from text, recognize entities via text mining and suggest PC networks that look alike

Validation of edited factoid:
- Be able to add PC references to assert validity of information in currently edited factoid

**Comment by fdurupinar** [comment]
For this version of factoid, we can focus on the validation of current information rather than the generative aspect.

**Comment by maxkfranz** [comment]
Related: PC entity linkouts #299

**Comment by sacdallago** [comment]
We should discuss specific use-cases
