### ISSUE TITLE
Instructional Video

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#156]
Background: In user testing, there was a call for a simple, short instructional video. Also suggested was adding text-captions. This could also help users understand that they should 'ground' entities, mentioned in #148.

Suggestion: 30s video for creating a grounded, directed interaction.

**Comment by gbader** [comment]
I'm hoping we don't need any real instructions or videos for the journal publication use case - we tried this before and I think it made the UI less usable.  But let's keep thinking about this.

**Comment by maxkfranz** [comment]
Closing for now, since we don't want to do a video for now.
