### ISSUE TITLE
Publications and evidence

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#157]
Supporting publications and attribution.

**Comment by sacdallago** [comment]
I assume this is in terms of giving more context?

**Comment by maxkfranz** [comment]
This could be the last stage of the interaction wizard, to be added later: https://github.com/PathwayCommons/factoid/issues/199

Basically, a publication DOI can be associated with an edge/interaction.

**Comment by maxkfranz** [comment]
Main case: Let the user explicitly enter a citation for an edge (interaction).

BioPAX: Export via publication xref
