### ISSUE TITLE
Allow toggle for all protein modifications 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#166]
An entity/protein can be modified in multiple ways, simultaneously. Enable toggle of any available protein modification ('inclusive OR').

**Comment by sacdallago** [comment]
Hi @jvwong 

- Can you elaborate? As far as I understand this is the duality of form-based vs graphical (node) based entry editing?
- Is this an enhancement or a feature?
- What's it's priority?

**Comment by jvwong** [comment]
I meant that a protein can have a zero or more modifications that are of distinct types. For instance,  P53 protein can be phosphorylated OR ubiquitinated OR both phosphorylated AND ubiquitinated.

**Comment by sacdallago** [comment]
Now I understand :) sorry, I was confusing interface issues with domain issues! Thanks
