### ISSUE TITLE
Restrict entity type used by Factoid to match grounding capabilities 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#168]
Currently, Factoid supports disambiguation of proteins and small molecules. Accordingly, it should restrict the entity 'type'  considered. In particular, for output of NLP/Reach these should be 

1. protein
2. simple-chemical 

e.g. Consider Reach output of "Transcription is meanwhile induced by Myc.". Here, the term  "transcription" is identified as the entity of type 'bioprocess' and xrefs the Gene Ontology.

**Comment by jvwong** [comment]
Alternative is explicit non-grounding

**Comment by maxkfranz** [comment]
Addressed on unstable in a724947

**Comment by jvwong** [comment]
I'm capturing entity types for Reach here, as I encountered a situation whereby I input a 'family' type (e.g. TGFBeta), that was being filtered out.  

> Protein
Bioprocess
Simple_chemical
Cellular_component
Gene_or_gene_product
Site
Complex
Family

**Comment by jvwong** [comment]
We might consider adding back / supporting type 'Family' which comes up a bunch. REACH detects this and uses [pfam](http://pfam.xfam.org/) as the database.
