### ISSUE TITLE
Design Discussion - Potential sbgn shapes for Factoid

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#174]
If we want to make Factoid be a sbgn editor, then we have to take a look at the current document model and figure out how to make it support sbgn elements.

To-do:
- [ ] learn how the editor creates new elements and adds them to the model
- [ ] learn how newt creates new elements and adapt that to Factoid

**Comment by d2fong** [comment]
Potential areas I want to discuss:
### Bilkent cytoscape.js vs sbgn-stylesheet

I haven't checked in ~8 months but Newt uses a modified version of cytoscape.js which means it takes more work to apply new features, build tools, performance improvements, and bug fixes from the main cytoscape.js repo.  The main benefit of this fork is that sbgn graphics are higher fidelity.

The sbgn-stylesheet is compatible with any version of cytoscape > 3.  Is more modular, and will work mostly out of the box.

**Comment by sacdallago** [comment]
I'm not so much concerned with high fidelity as much as speed. Also, it would be interesting to understand how complex the average pathway extracted from abstracts is.

**Comment by sacdallago** [comment]
As #175
