### ISSUE TITLE
Design Discussion - Factoid Submit Button

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#177]
Questions to ask

## Mock up ideas
[new doc 2018-02-02 13.24.40-20180202134850 (dragged).pdf](https://github.com/PathwayCommons/factoid/files/1690461/new.doc.2018-02-02.13.24.40-20180202134850.dragged.pdf)

**Comment by d2fong** [comment]
- statistics
- download biopax entry
- chance to review the form entry, graph in a static, non-editable way
- show graph, text form, biopax entry (potentially complex)

- show potential outcomes of contributing this entry to factoid

**Comment by sacdallago** [comment]
Depends on #200
