### ISSUE TITLE
Conversion to BioPAX

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#185]
- Consulted @IgorRodchenkov about how to take form input and generate BioPax
  - ideas discussed:
     - Generate BioPax w/ JS:
            - Not recommended.  Currently no JS tooling/packages/modules available to generate BioPax.  To do this, one would need to rewrite tons of java code to emulate the same functionality
      - Convert form input to model data that is flexible enough to eventually be transformed into BioPax using Java web services
          -  Most promising approach.  Given 9 well defined form [templates](https://docs.google.com/document/d/1g3da69QjnwYOsEvkI-5V4OGPmx9xO4Ej7CJNtEZph5w), Igor can assume things about the input that can make it feasible for him to generate the BioPax from the form data.
 

- Large amount of uncertainty related to how these templates could be represented in the current graph format that Factoid uses right now.  Might make sense to allow users to only choose one mode of input exclusively (graph/nlp vs form based entry) until this issue is resolved.

**Comment by d2fong** [comment]
## Template 1: Protein modification
![screen shot 2018-02-20 at 11 14 55 am](https://user-images.githubusercontent.com/2328291/36435329-5d6b687c-162f-11e8-826d-d3e9e067d837.png)


## Corresponding Output in JSON
1 Protien Reference Object that contains the following fields:
- xref (db, id)
- uri
- displayName / standardName
- entityFeature

3 Protein Objects that contain the following fields:
- entityReference (Protein Reference)
- uri
- displayName
-  one of (feature, notFeature)

2 Control Objects (controller -> Protein), (controlled -> BiochemicalReaction):
- left
- right
displayName

**Comment by IgorRodchenkov** [comment]
@d2fong, 

I was thinking of:
2 ProteinReference (PR) objects that contain fields:
- xref (db, id); but if we only allow HGNC Symbols as input, then 'db' is not required here
- uri (http://identifiers.org/hgnc.symbol/<symbol>); again, such URI can be later auto-generated by a json-biopax converter;
- displayName
- entityFeature
- **organism** (taxonomy ID or/and name); if we only work with human data, then this is optional

3 Protein (physical state) objects that contain the following fields:
- entityReference (value: a ProteinReference)
- uri (we can auto-generate later on)
- displayName (could be based upon the PR's name, modifications and location)
- one of (feature, notFeature -> value one of EntityFeatures defined in the PR)

1 Control Object (together with the corresponding reaction; we can split them later if needed):
- controller -> Protein
- controlled -> BiochemicalReaction
- **controlType** (inhibition, activation)
- left -> a Protein (not modified)
- right -> the other Protein (modified)
- displayName (e.g., "(A inhibits) phosphorylation of B")

**Comment by ozgunbabur** [comment]
I like the last one. We want something intuitive to non-biopax people. You
can even remove the "name" field, and merge "left" and "right" into
"modified protein". If we allow "dephosphorylated" in the "mod"
("modification" may be a better name) field, then they don't need to
mention what is left and right.

Of course this is still very simplistic. There are many modifications that
this template cannot be used for, but this is a big step from mere
protein-protein interactions to protein modifications.

**Comment by emekdemir** [comment]
I’d say that don’t call it the modified protein – but call it “modification”. Rather than representing the state – we should represent the “delta” – it is much more aligned with the biologists thinking ( and the semantics in the literature).

 

If we need to extend this further one can put in necessary modifications  - although this is strictly for future. 

 

ED

**Comment by IgorRodchenkov** [comment]
Great; considering Ozgun's and Emek's comments, I'd go with the following (See also: [Factoid templates doc](https://docs.google.com/document/d/1g3da69QjnwYOsEvkI-5V4OGPmx9xO4Ej7CJNtEZph5w):

1. Protein Modification (we'd generalize as protein/dna/rna Modification)
```
{
   'template' : 'Modification',
   'controller' : 'MAPKAPK2', //(or, better {'hgnc symbol' : 'MAPKAPK2'})
   'controlType' : 'inhibition',
   'protein' : 'DDX5', //(alt. - 'participant' : {'type':'protein', 'hgnc symbol':'DDX5'})
   'modification'  :  'phosphorylated (residue@site)'
}
```
2. Location Change (is it about transport or transport with reaction, or either?)
```
{
  'template' : 'Location Change',
  'controller' :  {'type':'protein', 'hgnc symbol'}, //(a complex could be set as {'name:'A/B/C','component':[{type:'protein','uniprot':'P12345'},{'type':'rna',...},]})
  'controlType' : 'activation',
  'oldLocation' : 'cell membrane',
  'newLocation' : 'cytoplasm',
  'participant' :  {'name':'p-Y-WRC:IRSp53/p...', 'component':[{type:'protein','uniprot':'P12345'},{'type':'rna',...},]}, //(a non-complex list of molecules could be an array: [{type:'protein','uniprot':'P12345'},{'type':'smallmolecule','name':'ATP'},]...)
}
``` 
3...9 {**ToDo**...}

@d2fong @emekdemir @ozgunbabur

**Comment by d2fong** [comment]
@IgorRodchenkov Can you confirm that this is all that I need to generate based on the input?
```
{
   'template' : 'Modification',
   'controller' : 'MAPKAPK2', //(or, better {'hgnc symbol' : 'MAPKAPK2'})
   'controlType' : 'inhibition',
   'protein' : 'DDX5', //(alt. - 'participant' : {'type':'protein', 'hgnc symbol':'DDX5'})
   'modification'  :  'phosphorylated (residue@site)'
}
```

Or do I still need to create 2 protein references, 3 proteins, 1 controller, etc.?

**Comment by IgorRodchenkov** [comment]
@d2fong yes, I belive so (and @emekdemir, @ozgunbabur kinda like this).
I think, for 'controller', and 'participant', you'd use {'type':'protein', 'hgnc symbol':'DDX5'} values (as  I mentioned in the "comments" above), because this way is more consistent and extensible (e.g., we can later use Dna, Rna and add e.g., 'name' field in addition to ID, etc.)

But if we do want this template apply only to Protein controllers and Protein participants, and always use 'HGNC symbol' type IDs, then we can shortcut -  use just IDs as values.

IR.

**Comment by maxkfranz** [comment]
The entire Factoid document is already serialisable to JSON and I've discussed at length with Jeff on how to convert from our model to Biopax.  We've had modifications represented in the Factoid model how Emek suggested today for some time now, for example.  I don't think it matters all that much whether the conversion is done by a PC service or directly from Factoid -- there are libs to generate XML from JS.  Whatever's easiest, I suppose.  It probably makes sense for Igor, Jeff, Dylan, and I to just discuss this in the lab on Thursday to make sure we're not rehashing things.

**Comment by IgorRodchenkov** [comment]
I am afraid, you cannot efficiently read/write/merge BioPAX (RDF/XML) using JS, despite there might be good XML libraries (it is possible, but hard, waste of time, even if we'd have a JS version of Jena or OWL-API libraries).

Indeed, it might be a good idea to use current Factoid document model. I bet, the amount of work and time it takes to consistently map those _9 factoid templates_ either to the new JSON schema (above) or express them via existing factoid document will be roughly the same. In my comments here, I am exactly  trying to take one practical step from [Factoid templates document](https://docs.google.com/document/d/1g3da69QjnwYOsEvkI-5V4OGPmx9xO4Ej7CJNtEZph5w)  -  some words and pictures - towards actual useful data (perhaps intermediate). So, a.f.a.i.k., this here issue was very specific - about how to go from those 9 templates via a **text** input form (js) to JSON objects, which would be easy to auto-convert to BioPAX.

Max could probably rewrite, e.g., templates 1 and 2 json (above) in terms of current Factoid document (I'd like to see how it looks, would it suffice, whether lots of other data is there, i.e., that's not required for mapping to biopax, etc...)

IR.

**Comment by sacdallago** [comment]
Depends on #199
