### ISSUE TITLE
Create INDRA document generator

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#190]

**Comment by d2fong** [comment]
INDRA has a statement model which is a inheritance hierarchy.  Each INDRA Statement has a type and based on the statement type, has different keys/objects associated with that type.

e.g
* statement type: "Phosphorylation" -> statement contains a "enz" key and a "sub" key
* statement type: "Activation" -> statement contains a "subj" key and a "obj" key
* statement type: "Inhibition" -> statement contains a "subj" key and a "obj" key
* statement type: "IncreaseAmount" -> statement contains a "sub" key and a "obj" key

**Comment by d2fong** [comment]
Found this:

http://indra.readthedocs.io/en/latest/modules/statements.html?highlight=statement

**Comment by d2fong** [comment]
Agents: 
- enz, sub, subj, obj, agent, gef, ras, gap are all these biological entities that have a name, etc.
Legend:
- enz -> enzyme
- sub -> substrate
- subj -> subject (responsible for the change in activity)
- obj -> object (whose activity is changed by the subject)
- agent -> agent in the particular active/inactive state
- activity -> The type of activity influenced by the given set of conditions (string)
- gef -> guanosine exchange factor
- ras -> GTPase protein
- gap -> GTPase activating protein
- members -> list of agents in the complex
- obj_to -> list of agents created by conversion
- obj_from -> list of agents consumed by conversion


Statements and the keys guaranteed to be in the statement (keys that appear only sometimes are omitted):
- Modification, AddModification, RemoveModification, Phosphorylation, Dephosphorylation, Hydroxylation, Dehydroxylation, Sumoylation, Desumoylation, Acetylation, Deacetylation, Glycosylation, Deglycosylation, Ribosylation, Deribosylation, Ubiquitination, Deubiquitination,  Farnesylation, Defarnesylation, Geranylgeranylation, Degeranylgeranylation, Palmitoylation, Depalmitoylation, Myristoylation, Demyristoylation, Methylation, Demethylation, 
   - enz
   - sub
- SelfModification, Autophosphorylation, Transphosphorylation
   - enz
- RegulateActivity, Inhibition, Activation
   - subj
   - obj
- ActiveForm, HasActivity
   - agent
   - activity
- Gef
   - gef
   - ras
- Gap
   - gap
   - ras
- Complex
   - members
- Translocation
   - agent
- RegulateAmount, IncreaseAmount, Influence, DecreaseAmount, 
   - subj
   - obj
- Conversion
   - subj
   - obj_from
   - obj_to

**Comment by d2fong** [comment]
Agent class documentation http://indra.readthedocs.io/en/latest/modules/statements.html?highlight=statement#indra.statements.Agent

**Comment by bgyori** [comment]
Let me know if you have any questions about Statements! It's important to note that the arguments of Statements which are Agents also have attributes including
- mods: a list of post-translational modifications with type, residue, position and possible negation flag
- mutations: a list of mutations with from / to amino acid and position
- bound_conditions: a list of bound Agents with possible negation flag
- activity: an activity type (e.g. kinase, transcriptional) with possible negation flag
- location: a GO cellular location

Whenever information from a knowledge source (like a reading system's output, or PathwayCommons for that matter) provides this state information, it is captured in the Agent. So one can propagate complex Agent conditions as arguments of events like "Phosphorylated BRAF-V600E not bound to Vemurafenib...".

**Comment by sacdallago** [comment]
As discussed today, let's keep this for a later point in time. @d2fong you can close if you feel like it's neccessary
