### ISSUE TITLE
Evaluate dockerized REACH

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#191]
Evaluate performance (aka. output) of calling the dockerized version of REACH ([here](https://hub.docker.com/r/pathwaycommons/reach-docker/) on a number (200?) of abstracts/papers/figure captions. Possibly a couple different types (e.g. 150 papers, 25 abstracts, 25 figure captions).

**Comment by jvwong** [comment]
A few of my observations on using this:

1. DockerHub automatically automatically builds for each commit to [pathwaycommons/reach-docker (master)](https://github.com/PathwayCommons/reach-docker)
2. My container would fail upon text submission if I was using a machine with less then 16GB memory
3. When the Docker container first run, the first time text is submitted, a response will take a long time (often 10 or 20 minutes). This is expected. I believe REACH is loading several NLP libraries (@JohnGiorgi).

**Comment by JohnGiorgi** [comment]
I can speak to point 3. Yes you should expect to take a few minutes (at least to spin up) as it’s loading NLP libraries (such as Stanford parser) and resources.

**Comment by fdurupinar** [comment]
The scripts to run dockerized REACH are at: https://github.com/fdurupinar/REACHTest. Scripts are written in Python 2.7. When you run reach-test.py, you can see the time performance plot in 3D. 

In these tests, REACH returns the output in indexcard format.

In REACHTest repository, pm.db database stores data acquired from PubMed and PMC. The fields of the database are:
- Id: PubMed ID
- PmcId: PMC ID
- Abstract: Acquired by PubMed ID from 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'
- WholeText: Acquired by PmcIdfrom 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi' and stripped off html tags
- Introduction: Not yet filled
 
Paper ids were acquired in another study to evaluate Reactome through REACH. These ids are stored in pmIds.txt. There 218 papers. 

## Performance

### Evaluation for Abstracts
- Abstracts for all the 218 papers are available. The abstracts also include author and publication information.

- performance.txt shows the text size in bytes, number of index cards that REACH returns and the run time in seconds.

- The performance plot is as follows:
![performance1](https://user-images.githubusercontent.com/13474166/36872200-4d055a7a-1d59-11e8-9fc4-881056e685c5.png)

Text size vs. performance follows a linear trend except some outliers. 

![image](https://user-images.githubusercontent.com/13474166/36872790-54db6986-1d5b-11e8-9bf9-86a2deab55b6.png)

- Maximum text size is 3272 bytes with 5.274 sec. run time. REACH returned 2 index cards for this input.
- Maximum run time is  14.491 sec. for 2356 bytes of data. REACH did not return any index cards for this query. 
- Minimum run time is  0.242 sec. for 277 bytes of data. REACH returned 2 index cards for this query.
- Maximum number of index cards is 22, extracted from 2485 bytes of data and 2.592 sec run time.

**Comment by sacdallago** [comment]
Closing for now
