### ISSUE TITLE
Labelled entity 'no data associated with it' is not editable

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#193]
## Environment info

- Browser version (client) : Chrome Version 64.0.3282.167 (Official Build) (64-bit)
- Live web app (http://factoid.baderlab.org/document/c14a6426-c5c3-443d-a862-606629f8ad14/f2c89f76-ee7d-4560-a685-e4ce4d39197c)

## Current (buggy) behaviour

Entity coming directly from text-mining is labelled, but has not data associated with it. It is not editable.

## Desired behaviour

I wish to associate data with it. e.g.ground.

## Minimum steps to reproduce

Document text: 
>Not depicted is weak activation of CYCD by MYC and explicit description of E2F mRNA and protein species.

![image](https://user-images.githubusercontent.com/4706307/36814760-8a25abe8-1ca6-11e8-8ddb-3df81d26c800.png)

**Comment by maxkfranz** [comment]
Addressed by https://github.com/PathwayCommons/factoid/commit/7d19ab7a35f74854debef1a3eb5b65591e5c03f0
