### ISSUE TITLE
Explicit indication that entity is 'complete'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#194]
## Entity complete cue

Provide some obvious cue to user in tooltip that particular entity is complete / there are no further steps. 

## Motivation for new feature

Consider a case where an entity is created, a label provided, and the search comes back with one correct suggestion. 

>Cells were treated as in Figure 3C (except synchronized at G2/M by nocodazole to allow S-phase BrdU incorporation, and assayed at 30 hr). 

![image](https://user-images.githubusercontent.com/4706307/36866270-d4dba9a8-1d5f-11e8-9008-45496c4a8eee.png)

This stage looks almost identical to the stage when the grounding is selected:

![image](https://user-images.githubusercontent.com/4706307/36866299-e5496654-1d5f-11e8-9f06-f03fd49b25db.png)

**Comment by maxkfranz** [comment]
Jeff originally suggested a green check in the top-right corner.  That's a good idea, but I've modified it a bit:

<img width="595" alt="green-check" src="https://user-images.githubusercontent.com/989043/37121802-48434790-222c-11e8-9db8-bb7edb7f570c.png">

The green check goes where the (disabled) forward arrow would normally go.  That's where a user is trained to look to go to the next stage.   This also guarantees that the green check is never obscured by rest of the content in the popover.

There is a tooltip to indicate what exactly the green check means, though I'm not sure that's completely necessary.

**Comment by jvwong** [comment]
Works for me. Now that you mention it, can we add a tooltip message on hover ('Next step', 'Previous step') for the arrows?

**Comment by maxkfranz** [comment]
I tried that before and it seemed annoying, but we could try it again.  I'll make a commit referencing this issue.

**Comment by jvwong** [comment]
Yeah good point - there would need to be a long delay for hover I guess.

**Comment by sacdallago** [comment]
I agree with the long delay and maybe a bit annoying. Not strictly necessary, if you ask me. I assume this issue is dealt with, anyway?

**Comment by maxkfranz** [comment]
OK, let's close for now then.
