### ISSUE TITLE
Small molecules are returned 'ungrounded'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#195]
## Environment info

- Browser version (client) : Version 64.0.3282.186 (Official Build) (64-bit)
- Node.js version (server) : 
- Live server example: http://factoid.baderlab.org/document/a43f6249-fdd7-47b1-ad25-bb130dc319af/e8017a6a-479e-446e-8df0-c292b932c78f 

## Current (buggy) behaviour

Mentions of small molecules in text seem to be well-recognized, but are returned as ungrounded in the resulting UI.

![image](https://user-images.githubusercontent.com/4706307/36867152-4cb63fae-1d62-11e8-8965-2a6ecb88def1.png)

 
## Desired behaviour

I expect these to be grounded from text-mining as REACH nails it.

## Minimum steps to reproduce

I enter a phrase with two chemicals (nocodazole, BrdU):

>Cells were treated as in Figure 3C (except synchronized at G2/M by nocodazole to allow S-phase BrdU incorporation, and assayed at 30 hr). 

But these are both returned as ungrounded. I look at the [REACH](http://192.168.81.173:8080/api/textBody) output and they look to be properly grounded:

```js
{ "events": {...},
  	"entities": {
		"frames": [
			{
				"text": "BrdU",
				"frame-id": "ment-api99-UAZ-r1-Reach-0-8702",
				"type": "simple-chemical",
				"frame-type": "entity-mention",
				"end-pos": {
					"reference": "pass-api99-UAZ-r1-Reach",
					"offset": 99,
					"object-type": "relative-pos"
				},
				"xrefs": [
					{
						"namespace": "pubchem",
						"object-type": "db-reference",
						"id": "6035"
					}
				],
				"object-type": "frame",
				"start-pos": {
					"reference": "pass-api99-UAZ-r1-Reach",
					"offset": 95,
					"object-type": "relative-pos"
				},
				"sentence": "sent-api99-UAZ-r1-Reach-0",
				"alt-xrefs": [
					{
						"namespace": "pubchem",
						"object-type": "db-reference",
						"id": "6035"
					}
				]
			},
			{
				"text": "nocodazole",
				"frame-id": "ment-api99-UAZ-r1-Reach-0-8701",
				"type": "simple-chemical",
				"frame-type": "entity-mention",
				"end-pos": {
					"reference": "pass-api99-UAZ-r1-Reach",
					"offset": 77,
					"object-type": "relative-pos"
				},
				"xrefs": [
					{
						"namespace": "pubchem",
						"object-type": "db-reference",
						"id": "4122"
					}
				],
				"object-type": "frame",
				"start-pos": {
					"reference": "pass-api99-UAZ-r1-Reach",
					"offset": 67,
					"object-type": "relative-pos"
				},
				"sentence": "sent-api99-UAZ-r1-Reach-0",
				"alt-xrefs": [
					{
						"namespace": "pubchem",
						"object-type": "db-reference",
						"id": "4122"
					}
				]
			}
		],
		"object-type": "frame-collection",
		"object-meta": {
			"processing-end": "2018-03-01T19:52:59Z",
			"doc-id": "api99",
			"component-type": "machine",
			"component": "Reach",
			"processing-start": "2018-03-01T19:52:59Z",
			"object-type": "meta-info",
			"organization": "UAZ"
		}
	},
...
```

**Comment by jvwong** [comment]
Currently, there is an attempt to map from PubChem to Chebi. This is done because of the lengthy synonyms list in PubChem, not all useful, that must be formatted for inclusion in tooltip/entity NER grounding.

**Comment by maxkfranz** [comment]
For reference, mapping: https://github.com/PathwayCommons/factoid/blob/7d19ab7a35f74854debef1a3eb5b65591e5c03f0/src/server/routes/api/document/reach.js#L114

**Comment by jvwong** [comment]
Replaced by #201
