### ISSUE TITLE
Stub various pages

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#196]
## Description of new feature

- Stub the following pages (nomenclature may change):
  - Seed page: this is where a user will be linked to from the landing page to start creating a new document (step 1 in workflow)
  - Graphical editor page: this is where the user will land by default when starting to edit a new document (step 2 in workflow)
  - Form editor page: Users can switch to this page _seemlessly_ from any other editing page to modify a document via a form interface (step 2 in workflow) 
  - Free text editor page: Users can switch to this page _seemlessly_ from any other editing page to modify a document via free text with highlighted extracted annotations (step 2 in workflow) 
  - Submit page: When users have finished editing in any of the three editing pages, users land here to review their work and submit it to PC

## Motivation for new feature

Stubbing the pages will help less experienced developers get started

**Comment by maxkfranz** [comment]
See also #200

**Comment by sacdallago** [comment]
Discussion in #200
