### ISSUE TITLE
Networks not initially 'fit to screen', elements offscreen

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#197]
## Environment info

- Browser version (client) :Version 64.0.3282.186 (Official Build) (64-bit)
- Node.js version (server) :
Live server example: http://factoid.baderlab.org/document/ecfddf58-8c5f-44ab-872b-24e0ebd1983b/28fd18c0-5d63-4146-828c-b15c092e1466

## Current (buggy) behaviour

Instance of three disconnected networks returned from text-mining but not all visible in screen area.
 
## Desired behaviour

Desire is to see all networks. Some were hidden offscreen and not shown after hitting the toolbar 'fit to screen' button. 

## Minimum steps to reproduce

[wong_mcell_v41_2011_MAIN.txt](https://github.com/PathwayCommons/factoid/files/1772694/wong_mcell_v41_2011_MAIN.txt)

![image](https://user-images.githubusercontent.com/4706307/36868513-8bb51456-1d66-11e8-9eed-a18f148e1072.png)

**Comment by maxkfranz** [comment]
We wanted to restrict the zoom level so you don't lose your place by zooming out too much.  We're probably going to have to be more liberal with the restriction on min zoom -- making the fit-to-screen button more important.

**Comment by maxkfranz** [comment]
I'm closing this for now, but let's re-open it if we notice other graphs that are problematic w.r.t. zoom.
