### ISSUE TITLE
Interaction completion wizard

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#199]
## Description of new feature

Add a wizard for interactions to allow for capturing more details about interactions.  Like the entity wizard, the user specifies one datum per stage.  The wizard constrains what the user can specify based on the data of previous stages.  Refer to the following figure:

![factoid-interaction-types page 1](https://user-images.githubusercontent.com/989043/37049514-0de61782-213f-11e8-9fc4-276cef8ca6d8.jpg)

Notes per step:

1. Click an edge
1. Popup is shown
1. Popup is moved down (quick animation)
    1. The popup must be shifted in order to accommodate the arrow popups in step 5.
1. Click edge/interaction type
    1. This sets the BioPAX-like interaction type/class.
    1. The shaded box indicates a notification.  The position could be on the side or on the top.
1. Select arrows
    1. The available arrows are constrained by the interaction type selected in step 4.
    1. The participant types (e.g. controller, controlled) are implied by the (interaction-type, arrow) tuple.

## Motivation for new feature

This allows us to capture interaction type information.  The per-element wizard UI is effective for entities (e.g. proteins), so we may expect some success with the same approach for interactions.  By capturing this information, we have enough data to be able to convert the Factoid model to BioPAX.  The (interaction-type, arrow) tuples are iterated in the following figure:

![factoid-interaction-types page 2](https://user-images.githubusercontent.com/989043/37049520-11810866-213f-11e8-89c6-f8c7c4d32dd5.jpg)

Of the above tuples, complex formation and chemical reactions (i.e. chemical-chemical) are question marks.  Eventually, we will need to address how to represent them -- fill in the black boxes.  But according to Gary, we can focus on the other tuples to start.

## PDF download

[factoid-interaction-types.pdf](https://github.com/PathwayCommons/factoid/files/1786114/factoid-interaction-types.pdf)

**Comment by sacdallago** [comment]
I would keep this for the version after next?

@jvwong

**Comment by IgorRodchenkov** [comment]
Do/can we stick to and work on just one "factoid templates" [document](https://docs.google.com/document/d/1g3da69QjnwYOsEvkI-5V4OGPmx9xO4Ej7CJNtEZph5w)?
