### ISSUE TITLE
Use PubChem results for grounding small molecules in entity tooltip search  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#201]
## Description of new feature
Add PubChem as service for entity grounding in tooltips (small molecules). 

## Motivation for new feature
Currently, ChEBI is used as one of the services for small molecule grounding in the entity tooltip. This is because of the conciseness and utility of the synonyms they provide. However, REACH text mining returns PubChem IDs and Factoid attempts to perform a mapping between the two. Just use PubChem alone.  

Replacing #195

**Comment by IgorRodchenkov** [comment]
Please, let's be clear whether we're talking about "PubChem Compound" or "PunChem Substance" IDs.
These are different databases, which, unfortunately, both have integer IDs (no official prefix; though unofficially some people use CID: or SID: prefixes...). An ID usually point to unrelated, different molecules in those databases.

**Comment by maxkfranz** [comment]
After this issue is addressed, we need to address this one: 

Pubchem has too many synonyms #202

**Comment by maxkfranz** [comment]
@IgorRodchenkov That's a good point, but we also store InChi -- so we can still uniquely identify the compound, right?

**Comment by IgorRodchenkov** [comment]
InChiKey, you mean? Yes, this is much better ID.

**Comment by metincansiper** [comment]
@jvwong @fdurupinar @maxkfranz @IgorRodchenkov 

I tried to debug the code. I see that in this [code segment](https://github.com/PathwayCommons/factoid/blob/master/src/server/routes/api/document/reach.js#L112) the desired things are done if ```ground.namespace``` is equal to ```'chemical'``` but as far as I see that value is eqaul to ```'pubchem'``` not ```'chemical'```. 

I experimented changing it as ```'pubchem'``` and see that the buggy behaviour is fixed, I got the following result:

<img width="903" alt="pubchem" src="https://user-images.githubusercontent.com/6534865/37065180-ab36a8b6-2154-11e8-8c69-d56504093753.png">

Should the ```case``` in that line be updated as ```case 'pubchem':```? 

I think that the original issue (#195) was about this bug. Should ChEBI layer still be removed and just PubChem be used alone as it is addressed in this issue if this change solves the bug safely?

**Comment by metincansiper** [comment]
Then I suppose that the only thing needed for this issue is changing the case that I mentioned in above comment as:

```js
case 'pubchem':
              return pubchem.get( q );
```

I am attaching the results to compare the old (ChEBI is used as well) and new (just PubChem) implementation for the example in #195
[new-results.txt](https://github.com/PathwayCommons/factoid/files/1791287/new-results.txt)
[old-results.txt](https://github.com/PathwayCommons/factoid/files/1791288/old-results.txt)

The attached files indicates that when CheBI is eliminated the results become pretty much bigger mainly because increased number of synonyms and so the tooltip contents does not fit into the page. However, seems like this is already something known and to be addressed in context of #202.

Therefore I created a PR (#203) to address this issue.

**Comment by maxkfranz** [comment]
Merged #203.  Closing

**Comment by maxkfranz** [comment]
So actually the previous change was not enough.  It was only for reach groundings.  The most important usecase is user groundings, and that was not switched over in the aggregate entity lookup service.  I've switched that over in the previous two commits.  Should be good now.

**Comment by maxkfranz** [comment]
We use Soerensen's Dice for the distance metric: https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient

**Comment by metincansiper** [comment]
@maxkfranz as far as I understand PubChem was supposed to be used instead of ChEBI for user groundings and your commit made it. However, as far as I understand when users query a chemical through the tooltip it should not be automatically grounded. Is it correct?

**Comment by maxkfranz** [comment]
An entity is grounded (`associated: true` in the Factoid model) when it has an `association` object with the grounding data (id, name, synonyms, etc.).  The `association` can be set two ways thus far:

(1) An grouding ID is received from textmining and Factoid makes a query to the relevant external service to get `association`.

(2) The user specifies an `association` from the entity wizard.  The model is updated as soon as the user specifies the `association`, but the UI does not display an element as complete until the end of the wizard.
