### ISSUE TITLE
Pubchem has too many synonyms

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#202]
## Environment info

- Browser version (client) : N/A
- Node.js version (server) : N/A

## Current (buggy) behaviour

Results from Pubchem return many synonyms.  Here's an example: https://pubchem.ncbi.nlm.nih.gov/compound/24393#section=Depositor-Supplied-Synonyms&fullscreen=true

We need to display at least some synonyms on the search stage of the entity wizard, because the user needs to have feedback about matches within synonyms (indicated by a yellow highlight in the UI).

When the list of synonyms is very long, there is too much noise.  Many synonyms are not relevant and the user has to scroll a lot.  One entity can take up the whole height of the screen.

## Desired behaviour

Filter the synonyms list somehow so the overall per-entity list is concise and contains relevant names.

One possibility is to only show synonyms that are highly-ranked matches, i.e. ones that are close to what the user typed.  Those are ones that would tend to have highlights (i.e. exact substring matches).  There may need to be a hard cut-off in case many synonyms are highly-ranked.  We may also need to remove synonym display completely from the entity info shown for grounded chemicals.  Maybe we could just show the IUPAC name under the name the user typed instead of the whole list of synonyms.

## Minimum steps to reproduce

You can take a look at Pubchem data outside of Factoid.  Just do a search on the Pubchem site, e.g. https://www.ncbi.nlm.nih.gov/pccompound?term=iron

Then choose a chemical and look at its synonyms list.  The list is very long a lot of the time.

**Comment by sacdallago** [comment]
To expand on 
> One possibility is to only show synonyms that are highly-ranked matches, i.e. ones that are close to what the user typed. Those are ones that would tend to have highlights (i.e. exact substring matches). There may need to be a hard cut-off in case many synonyms are highly-ranked. We may also need to remove synonym display completely from the entity info shown for grounded chemicals. Maybe we could just show the IUPAC name under the name the user typed instead of the whole list of synonyms.

we could assign weights to synonyms, for now just like this (higher value, more important):

- `2` for every synonym that matches the search query from the beginning of any word (Sort of regex's $ but word-wise)
- `1` if search term is matched as substring
- `0` for anything else

Then we could say: 10 picks from the sorted list? This will always prioritize the ones with `2`, but eventually we could come with other weights to add and then normalize

**Comment by maxkfranz** [comment]
OK, so the reason why we didn't have good examples on the call is because the user grounding searches were not updated by the pull request.  The PR only covered mapping reach groundings.

See #201 : https://github.com/PathwayCommons/factoid/issues/201#issuecomment-371664792

Now you should be able to see the problem.  Here's 'aspirin':

![screen shot 2018-03-08 at 6 50 14 pm](https://user-images.githubusercontent.com/989043/37182907-95226f8e-2301-11e8-9840-4d516ec3bae5.png)

**Comment by maxkfranz** [comment]
The aspirin query also gives a counter-example for why you might not want to filter based on highlight:  For aspirin, I'd expect to see acetylsalicylic acid and ASA as synonyms.

Maybe the answer is to not use pubchem directly.  Maybe there's a service we could use from wikimedia.  They seem to have nicer info, at least in their pages: https://en.wikipedia.org/wiki/Aspirin

**Comment by maxkfranz** [comment]
E.g. https://www.wikidata.org/wiki/Q18216

**Comment by maxkfranz** [comment]
> we could assign weights to synonyms, for now just like this (higher value, more important):

Just to re-iterate from the call so it's written down: We already have scores calculated per-synonym so it's just a matter of re-using that to sort the list.  And then as you said, trim based on a maximum length.

**Comment by fdurupinar** [comment]
Yes, that was also my point. I'd expect to see a acetylsalicylic acid for
aspirin,  and similarly, ferrum for iron.

Wikidata looks nice.

**Comment by metincansiper** [comment]
Yes, for #201 I just attempted to avoid using results from ChEBI and PubChem together.However, while looking at this issue I realized there is a problem with that and I was about to ask whether pubchem should be one of the providers in ```aggregate.js```. Thanks for the fix and update.

**Comment by maxkfranz** [comment]
> Wikidata looks nice.

I deleted that comment, because while the page is good the source data has the same problem:

Page : https://en.wikipedia.org/wiki/Aspirin
Source : https://www.wikidata.org/wiki/Q18216

The synonym list is also very long, but maybe the sorting is better.

**Comment by maxkfranz** [comment]
We need to make sure that whatever method we come up with has a good result for both (1) the user searching for a grounding and (2) the user viewing an already grounded entity.

The filtering idea is good for (1) but it's not good for (2).  Like Funda pointed out, a user expects to see the common name like ASA.

**Comment by metincansiper** [comment]
>> we could assign weights to synonyms, for now just like this (higher value, more important):

>Just to re-iterate from the call so it's written down: We already have scores calculated per-synonym so it's just a matter of re-using that to sort the list.  And then as you said, trim based on a maximum length.

I beleive that using a ```median of medians``` or ```max heap``` based solution would be better than sorting to select the top 10 highest scored entities if number of entities could be very high and performance matters. Then if needed we can sort the selected 10 entities instead.

**Comment by cannin** [comment]
I would caution against wikidata over pubchem. Wikidata may be great for a lot of entries, but here's a counter "5-hydroxytrytophan". The only entries mentioned on wikidata are related to the fact that it was mentioned in scientific articles. 

https://www.wikidata.org/w/index.php?search=&search=5-hydroxytrytophan&title=Special:Search&go=Go&searchToken=d7r9id4e4p620fg52rd01fhg0

However, it is in pubchem: 

https://pubchem.ncbi.nlm.nih.gov/compound/144

As far as too many synonyms. For one drug related project, we took the top 5 synonyms and have been decently happy. That would include ASA for aspirin that was mentioned. The entries could also be filtered for key databases + top N synonyms; database identifiers such as Pubchem, CAS-RN, Chebi, KEGG, CHEMBL, HMDB, are the ones that I see most often and consider most useful.

**Comment by maxkfranz** [comment]
> As far as too many synonyms. For one drug related project, we took the top 5 synonyms and have been decently happy. That would include ASA for aspirin that was mentioned. The entries could also be filtered for key databases + top N synonyms; database identifiers such as Pubchem, CAS-RN, Chebi, KEGG, CHEMBL, HMDB, are the ones that I see most often and consider most useful.

Yes, that makes sense.  We could try keeping the list to 10 maximum synonyms:

- 5 of the first synonyms, which seem to be based on popularity like @cannin suggested.
- 0-5 of the best-matching, remaining synonyms.
- Edge case: If the total number of synonyms are less than 11, just use them all.

**Comment by maxkfranz** [comment]
If we keep the list short (e.g. 10 items) and have better highlighting (#206), then the user can scan much more easily.

**Comment by maxkfranz** [comment]
This change should be applied to the aggregate search service.  This means that the approach will be applied to all individual search services.  That way, if we add other search services in future (e.g. Pfam) that have too many synonyms, then the same solution is applied:

https://github.com/PathwayCommons/factoid/blob/3b538af5d0b339156b5db0b925d316d7ddd9fc3f/src/server/routes/api/element-association/aggregate.js#L25

You could create a memoized function for `distanceMetric( val )` w.r.t. `searchTerm`, e.g. `cachedDistanceMetric( val )`.  Then `distance()` could re-use it.  Then there could be some new function, like `addShortSynonyms( ents )` that could add on the short list of synonyms -- using the `cachedDistanceMetric()` so we don't have to calculate distance twice for synonyms.  I would be hesitant to overwrite the existing `ent.synonyms` list, as we may need that somewhere else eventually.

**Comment by metincansiper** [comment]
@maxkfranz the first question comes in my mind is whether the synonyms should be cut off in this way just for the user search from tooltip. Should not the same logic be applied when a network is created from text using Reach? If I am not wrong this way will work for the first case (user search) but not for the second one (network from text). Am I right?

**Comment by metincansiper** [comment]
About my previous question. I see that this issue focuses on the search stage.

>We need to display at least some synonyms on the search stage of the entity wizard, because the user needs to have feedback about matches within synonyms (indicated by a yellow highlight in the UI).

However, the same problem would occur when a phase is entered to bring a network. For example when the example phase from #195 is used height of the tooltip contents exceed the height of page because of excessive number of synonyms.

>Cells were treated as in Figure 3C (except synchronized at G2/M by nocodazole to allow S-phase BrdU incorporation, and assayed at 30 hr).

**Comment by maxkfranz** [comment]
> @maxkfranz the first question comes in my mind is whether the synonyms should be cut off in this way just for the user search from tooltip. Should not the same logic be applied when a network is created from text using Reach? If I am not wrong this solution will work for the first case (user search) but not for the second one (network from text). Am I right?

The aggregate search service should be used for everything.  So this should be changed: https://github.com/PathwayCommons/factoid/blob/unstable/src/server/routes/api/document/reach.js#L109

I think the only reason it wasn't using the service directly was because of the chebi-pubchem lookups...

**Comment by maxkfranz** [comment]
You'll also have to change the UI to use `shortSynonyms` instead of the raw `synonyms`.

**Comment by maxkfranz** [comment]
> However, the same problem would occur when a phase is entered to bring a network. For example when the example phase from #195 is used height of the tooltip contents exceed the height of page because of excessive number of synonyms.

Maybe it's better to do this on the UI side.  It means having to recalculate the distances for synonyms on the client, but it avoids having to consider caching issues (i.e. modifying `shortSynonyms` on potentially shared-cache objects or always cloning) and inconsistencies between `aggregator.get()` (no search string) and `aggregator.search()` (search string)`.

**Comment by maxkfranz** [comment]
Relevant UI code: https://github.com/PathwayCommons/factoid/blob/04c1f01d6eb3b36a431ab13eb259e3b1adbdb455/src/client/components/element-info/entity-info.js#L296-L331

**Comment by metincansiper** [comment]
>You could create a memoized function for distanceMetric( val ) w.r.t. searchTerm, e.g. cachedDistanceMetric( val ). Then distance() could re-use it. Then there could be some new function, like addShortSynonyms( ents ) that could add on the short list of synonyms -- using the cachedDistanceMetric() so we don't have to calculate distance twice for synonyms. I would be hesitant to overwrite the existing ent.synonyms list, as we may need that somewhere else eventually.

I think you mean that ```addShortSynonyms( ents ) ``` is supposed to add a ```shortSynonyms``` field to each ```entry``` of ```ents``` parameter.  While doing it the distance between ```searchTerm``` and each synonym (other than first 5) will be calculated and you propose caching these distances to avoid recalculating the same distances inside ```distance()```. 

However, ```distance()``` just care about the minimum distance and the minimum distance candidate of synonyms is already guaranteed to be one of the ```shortSynonyms```.  Then it makes more sense to me if ```distance()``` use ```entry.shortSynonyms``` instead of ```entry.synonyms```. In this case we will not need to cache these distances. Because if number of synonyms is less than 11 then we will be calculating the distances for the first time in ```distance()```. If it is 11 or more than the minimum distance would come from one of the 6 synonyms and it is certain that we previously calculated only the distance for the 6th one among them.

**Comment by maxkfranz** [comment]
No, you'd need `cachedDistanceMetric = val => distanceMetric( searchTerm, val )` in the scope where searchTerm is available.  `distance()` would use `cachedDistanceMetric()`.  But it's moot anyway, since it looks like this should be done in the UI side.  The client will have to recalculate the values for display purposes.

**Comment by maxkfranz** [comment]
How about we address this in two stages?

(1) Just show the first 10 synonyms, based on the order they are now (from Pubchem).

(2) Use the rules I specified here https://github.com/PathwayCommons/factoid/issues/202#issuecomment-372358884

That way we have a basic solution quickly.  We may need to tweak and experiment with the rules for (2).

**Comment by cannin** [comment]
A tweak to (1). In addition to PubChem CID, show the top 4-5 synonyms + any of the following (formats from identifiers.org) present in the synonyms list:

KEGG Compound: ^C\d+$
KEGG Drug: ^D\d+$
CAS: ^\d{1,7}\-\d{2}\-\d$
HMDB: ^HMDB\d+$
CHEBI: ^CHEBI:\d+$
CHEMBL: ^CHEMBL\d+$

**Comment by maxkfranz** [comment]
Those look like ID formats rather than names.  If a user wants to find out IDs (dubious to me), then he can click the "more information" link and see detailed info on Pubchem.  Our goal for the synonyms is for users to ground entities.  They just need to recognise one of the names.  No user has shown interest or understanding of DB IDs.  In fact, they get confused by them.

The default sorting from Pubchem seems to be based on some kind of popularity.  So if our goal is user recognition of synonyms, then taking the top ten seems more sane to me than showing numeric IDs.

**Comment by maxkfranz** [comment]
I've pushed the simple solution to limit to the first 10.

Before:

![screen shot 2018-03-08 at 6 50 14 pm](https://user-images.githubusercontent.com/989043/37182907-95226f8e-2301-11e8-9840-4d516ec3bae5.png)

After:

![screen shot 2018-03-13 at 11 54 21 am](https://user-images.githubusercontent.com/989043/37353228-497dc9ae-26b5-11e8-9b7c-95ad48bcf2e6.png)

Maybe this is enough, probably not for all cases.  But it's a good-enough solution right away while Metin is trying out the sorting solution (2).

**Comment by cannin** [comment]
I can understand the concern for the IDs. That in mind are the formula/mass/charge of any use? Those are weaker for matching than the IDs.

**Comment by metincansiper** [comment]
>No, you'd need cachedDistanceMetric = val => distanceMetric( searchTerm, val ) in the scope where searchTerm is available. distance() would use cachedDistanceMetric(). But it's moot anyway, since it looks like this should be done in the UI side. The client will have to recalculate the values for display purposes.

As this is most likely to be done in client side then as you said client will recalculate the values anyways and nothing to discuss. But if it was to be done in server side I would like to discuss more about that. At least I would like to try explaining my concern more clearly.

**Comment by maxkfranz** [comment]
Charge: Differentiate between atoms with charge (ions) and atoms without charge.  Otherwise, you can't specify, for example, an iron ion.  This may be important.

Mass: You may want to identify a particular isotope, though that may be more of use to chemists than biologists.  I'm not sure.

IDs:  I can't think of a single example where a typical user (i.e. a bench biologist) would want to see an ID.  If there is, I'd love to see it so we can consider that usecase.

**Comment by metincansiper** [comment]
Should solution (2) be implemented in unstable or alpha(since it could be regarded as something experimental for now)?

**Comment by maxkfranz** [comment]
If there's something really experimental, we should use a feature branch off of unstable.  We shouldn't use alpha anymore, but we should keep it for now in case we need anything in it.
