### ISSUE TITLE
Allow the Highligher component to highlight multiple terms

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#206]
## Description of new feature

Change the multiplicity of the `term` prop in the Highlighter component.

Before: `term: 'foo bar'`
After: `terms: ['foo bar']` (highlight exactly 'foo bar') or `terms: ['foo', 'bar']` (highlight any 'foo' and any 'bar')

Each term should be highlighted in the search text, just as the single term is currently.

## Motivation for new feature

The main usecase of the highlighter is to show how well names match in the entity grounding UI.  When the user-typed name (term) is a space-separated, compound word, you can have very few highlights.  It would be useful to have partial matches, and allowing multiple terms in the Highlighter allows for this.

See also : Pubchem has too many synonyms #202

**Comment by sacdallago** [comment]
From call notes earlier today, related to this issue
- Highlight every word in space separated search query, e.g. `iron oxide`, highlight both `iron` and `oxide` in the synonyms list
- Recursively assign weights to synonyms first using the full match of the search and then using separate words in the search term

**Comment by metincansiper** [comment]
I created PR #210 to resolve this issue.
