### ISSUE TITLE
NLP error handling (Server)

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#207]
## Description of new feature

The server should log several different error cases and the UI should inform the user that something went wrong with NLP. The interesting cases are the following:
- [x] (1) REACH times out (504)
  - Log to server
  - Suggest to the user to _try again later_
- [x] (2) REACH fails (500)
  - Log to server
  - Suggest to the user to _try again later_
- [x] (3) NLP returns 0 entities (200)
  - Log to the server (the inputted text + the fact that 0 entities were recognized)
  - Tell the user that "_no entities were recognized_" and suggest to either change text or start on an empty document
- [ ] (4) NLP returns a response that can't be converted to factoid model (520)
  - Log to the server (the inputted text + the fact that the result can't be serialized)
  - Tell the user that "_there was a problem with processing your text_" and suggest to either change text or start on an empty document
  - business logic related to processing reach output -- sometimes there are errors produced (not well defined).

## Motivation for new feature

UI improvements, non-blocking behaviour for users, data collection to make NLP better

**Comment by d2fong** [comment]
Do we have concrete instances of inputs I can use to test for each of these cases?

**Comment by d2fong** [comment]
Just trying to understand what differentiates case 1 from case 4, and what differentiates case 2 and 4.

**Comment by jvwong** [comment]
Also can we be explicit about which REACH instance/web server we are discussing: 
a. U Arizona: http://agathon.sista.arizona.edu:8080/odinweb/api/
b. Local/Dockerized: https://hub.docker.com/r/pathwaycommons/reach-docker/

**Comment by maxkfranz** [comment]
I've updated the OP with proper numbers for reference.

**Comment by maxkfranz** [comment]
> Do we have concrete instances of inputs I can use to test for each of these cases?

(1) Configure the request made to reach to time out after a small amount of time, like 1s.  That would generate the error we can catch.

(2) I suppose any non-success HTTP code response from Reach means we send HTTP 500.  Could test by pointing the Reach server to a bad IP, I guess.

(3) I think this sentence gives nothing: `This isn't valid input.`

(4) This one isn't well defined yet, so let's worry about the concrete ones first.

> Also can we be explicit about which REACH instance/web server we are discussing:

All the CI servers use the Docker by default now.  You have to configure your local instances to point to whatever IP manually though.  Probably the default should be changed from U AZ so it gives an error by default so you know to set it.  Maybe `localhost` is a good default.

**Comment by d2fong** [comment]
For (3) do you think there is value in logging how many entities were recognized any time a document was created?

Example message:
REACH service at url ${REACH_URL} recognized ${entities.length} entities for the given text ${text}.

**Comment by maxkfranz** [comment]
Maybe at info level

**Comment by maxkfranz** [comment]
The zero case should be logged at error level

**Comment by d2fong** [comment]
Closing this issue because it is too large in scope.
