### ISSUE TITLE
Context aware user suggestions

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#218]
## Description of new feature

Components suggesting max. 3 actions the user could take next in a given scenario (what you can do).

![image](https://user-images.githubusercontent.com/6240943/37605207-18db5222-2b69-11e8-8603-cbfe12bb9424.png)

E.g.: 
- User in graph editor
  - Suggest to create a  new node
  - Suggest to define edges
  - Suggest to "submit the factoid" and explain how
- User in form editor
  - Suggest to create new row
  - Suggest to check to change template type
  - Suggest to submit

## Motivation for new feature

Help user "take the next action" without telling the user explicitly what to do.

**Comment by jvwong** [comment]
Is this related to #192, i.e. 'Help'?

**Comment by sacdallago** [comment]
Yes. I think this serves a dual purpose:

1. Creating the react component
2. Discussing which clues to display and where
