### ISSUE TITLE
App bar + Menu

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#219]
## Description of new feature

Create an app bar with the name of the tool (factoid) + a name for the factoid being edited (like a google doc). Put a menu button that toggles a menu which:

- Gives the user the possibility to navigate from one editor to another.
- Gives the user the possibility to create "new factoid" (link to /seed)
- Gives the user the possibility to view "my factoids", a.k.a. submitted factoids (just placeholder, for now / **user management** is something for the future)
- Toggle "timeline"

## Motivation for new feature

Give an overall context

**Comment by jvwong** [comment]
Related to #211
