### ISSUE TITLE
Mockup document list ("My factoids") page

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#221]
## Description of new feature

Mock up a page where the user can see all the factoids he/she has edited and their status
![image](https://user-images.githubusercontent.com/6240943/37607668-0fd8c672-2b6f-11e8-8d42-1a19ed19e733.png)

## Motivation for new feature

- Users can visualize the factoids created
- Users can edit "unfinished factoids"
- Users can submit unfinished factoids
- Users can see submission status

This might also provide a handy way to address the issue of "where to submit the factoid", although that option should also be available in the menu (#219) when the user is in one of the editors

**Comment by maxkfranz** [comment]
Note: This exists, but it only works with localstorage rather than user accounts.

**Comment by d2fong** [comment]
Also not included is the idea of submitting factoids.

**Comment by sacdallago** [comment]
Basic ui there
