### ISSUE TITLE
Landing Page - DB Identifier example information, figure that shows sample doc text, graph output in pic form, link to sample doc

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#224]
## Description of new feature
landing page should contain 2 new sections:
- A section that shows the motivation for grounding, and why linking identifiers is important
- A more fleshed out example document.  The current landing page includes a link to a sample document to the graph editor, but it can be expanded to include a step by step example process for the user.  e.g user has this text, show a picture of the resultant graph, let users click the link next to the picture to go and try it themselves.

## Motivation for new feature
- Lets users understand grounding/id linking
- Show users an example Factoid workflow

**Comment by sacdallago** [comment]
I indeed did write something relevant to this issue: https://github.com/PathwayCommons/factoid/issues/176#issuecomment-374234169

**Comment by sacdallago** [comment]
Oh, just let me reiterate over nomenclature: I use `components` to highlight that I would like these to be separate React components that could be used in other parts of the application as well, especially the components giving examples for what identifiers are :) If possible, of course :)

**Comment by d2fong** [comment]
Possibly add three new sections (as three new components that might be reused in other parts of the application):

1. Examples of text and what they turn into:

![image](https://user-images.githubusercontent.com/6240943/37601622-e554cc10-2b60-11e8-9b89-b08c425c2429.png)

Possibly make these clickable, such that a user clicking the "example" factoid will be forwarded to a new document page containing that network (useful for Demo purposes).

2. An explanation of what "IDs" are and how databases work. Nothing too fancy, just a list of 10(?) identifiers amongst proteins, chemicals and whatever not, their IDs, their common names, etc.

![image](https://user-images.githubusercontent.com/6240943/37601696-1af3620a-2b61-11e8-83c2-cc8ad8aae21e.png)

3. An explanation of what interaction types are (same as above, just a table with a couple examples of what "activates" means in text form).

![image](https://user-images.githubusercontent.com/6240943/37601778-410514b6-2b61-11e8-9397-4b08f1fa1e89.png)
