### ISSUE TITLE
Templates for the form MVP

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#226]
## Description of new feature

Templates to represent Biopax processes:
1. Protein modification
-Controller protein : text box (string)
-Control type (activation/inhibition) : select box of either activation or inhibition
-Modified protein: text box (string)
-Modification: select box of phosphorylation, methylation, acetylation, …. (https://www.uniprot.org/help/mod_res for starters -- other ontologies are also possible) 

2. Location change
-Controller protein : text box (string)
-Control type (activation/inhibition): select box of either activation or inhibition
-Old location : text box (string) 
-New location: text box (string)
-Molecule or (molecule list/complex):  → can be multiple entities
  -ID: string 
  -Molecule type : can be either DNA, RNA, small molecule or protein and will be selected based on ID. IDs can be:
    - DNA, RNA: Gene symbol 
    - Protein: Gene symbol or Uniprot ID
    - Small  molecule: Chebi ID 

3. Complex association
-Molecule list : text box (string)  → multiple entities

4. Complex dissociation
-Molecule list: text box (string) → multiple entities

5. Biochemical reaction
-Catalyzer : text box (string)
-Input small molecules: text box (string)  → multiple entities
-Output small molecules: text box (string) → multiple entities

6. Physical Interaction: A --- B
-List of molecules: text box (string)  → multiple entities

7. Activation/inhibition: A ---> B or A ----| B
-Source protein : text box (string)
-Type of effect (activation/inhibition): select box of either activation or inhibition
-Target protein: text box (string)

8. Regulation of expression
-Transcription factor: text box (string)
-Effect (activates/inhibits expression): select box of either activation or inhibition of expression
-Target protein: text box (string)

9. [Optional] Modification of complex member
-Controller protein: text box (string)
-Control type (activation/inhibition): select box of either activation or inhibition
-Unmodified members of complex: text box (string)  → multiple entities
-Modified members of complex + modification (phosphorylation etc)
   - Modified members: text box (string)  → multiple entities
   - Modification: select box (see above)

## Motivation for new feature

A different and more detailed editing mechanism for documents.

**Comment by fdurupinar** [comment]
@jvwong I opened a new branch form-templates for the implementation of this feature.

**Comment by fdurupinar** [comment]
Sample view
![image](https://user-images.githubusercontent.com/13474166/38266787-6d3d5498-372e-11e8-9878-6a84c62a1405.png)

**Comment by sacdallago** [comment]
Prettying up:
 - Change title names to user-friendly names (PROTEIN_MODIFICATION --> Protein modification)
 - Add a short paragraph description of what each "section" does, possibly with an example that links to a paper or PC entry

**Comment by d2fong** [comment]
@fdurupinar Do you think your form ui is solid enough to merge into alpha?  This would allow me to integrate your form with the other components and deploy it to alpha so others can see it for themselves.  

It doesnt have to be fully completed, and you can continue to create pull requests to alpha after the initial merge.

**Comment by fdurupinar** [comment]
@d2fong I'll do some updates first and I'll merge into alpha. I expect it to be done today.

**Comment by d2fong** [comment]
Okay great.  Thanks!

**Comment by fdurupinar** [comment]
Done.

**Comment by sacdallago** [comment]
How far is the merging all in alpha going @d2fong ? :) seems like now is a good stage to start doing this

**Comment by d2fong** [comment]
I believe Funda already merged it.  It is deployed to alpha.factoid.baderlab.org if you want to see the changes.
