### ISSUE TITLE
NLP Error messages in the (Client side UI)

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#227]
This is issue is a continuation of the unfinished work in #207 

## Description of new feature

Based on various errors from NLP services, display relevant messages to the users in the UI

 - [ ] (1) REACH times out (504)
   Suggest to the user to try again later
- [ ]  (2) REACH fails (500)
   Suggest to the user to try again later
- [ ] (3) NLP returns 0 entities (200)
   Tell the user that "no entities were recognized" and suggest to either change text or start on an 
   empty document
 

## Motivation for new feature

The hypothesis is that if users receive messages related to why NLP failed, they will tolerate these failures in the Factoid app and understand what their next steps should be

**Comment by sacdallago** [comment]
I agree with @maxkfranz , for simplicity also. Obviously from a CS perspective precise error messages are more _interesting_, but when dealing with users who in the first place don't want to be there...

I wonder if a user would feel cheated if this happens though. Maybe we shouldn't _promise_ that text mining will catch everything, on the other hand, that's a good selling pitch...
