### ISSUE TITLE
Pubchem is unreliable

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#228]
## Environment info

- Browser version (client) : All
- Node.js version (server) : Any

## Current (buggy) behaviour

Pubchem often does not respond to requests.  It sends "server busy" errors.  This makes the service unusable in a production system.

## Desired behaviour

Return the request properly.

## Minimum steps to reproduce

Try searching for many entities or entering a text into Reach that has many chemicals.  Try on a local instance or disable caching of services to make it easier to reproduce.

**Comment by maxkfranz** [comment]
Options:

(1) Switch back to Chebi.  Chebi actually works.  And the mapping error was a Pubchem problem rather than a Chebi one.

(2) Try using EBI webservices, which we may want to use anyway for protein families.

It's worth exploring (2) but for now we should implement (1) immediately for the interim so that the system is functional for demo purposes.

**Comment by sacdallago** [comment]
I would also argue that (3) is interesting. It highly depends on how "hard" this is to change.

@jvwong do you have any idea about this? If not: let's shout out to Mihai/whoever helped you with the docker container.

**Comment by jvwong** [comment]
@maxkfranz and I noticed this behaviour when testing full-text examples. Abstracts (the ones we used anyway) did not likely have many chemicals mentioned.

Yes, I will follow up with International Chemical Identifier (InChIKey) in REACH.

**Comment by jvwong** [comment]
Follow up with clulab/reach (https://github.com/clulab/reach/issues/579)
Related discussion on PubChem vs CheBI: https://github.com/clulab/reach/issues/167

**Comment by maxkfranz** [comment]
(2) does not solve our issue.  The EBI service is only for search (query string => id list), so we would still be reliant on Pubchem services to fill-in the data for entities.

**Comment by sacdallago** [comment]
From https://github.com/clulab/reach/issues/579 it seems like we can also discard 3.

Short term:

(1) Switch back to Chebi. Chebi actually works. And the mapping error was a Pubchem problem rather than a Chebi one. This is guaranteed to work, but it means you have to ignore Reach groundings -- at least for chemicals.

Long term:

(4) Email the PubChem team.
(5) Download the PubChem database and host it ourselves. We will have to maintain the system.

I'll discuss 4. with Chris, see if he know someone. Ideally, we would like to get a docker container you pass the raw db downloaded from PubChem and services the data.

**Comment by sacdallago** [comment]
Note: for now not ground chemicals via REACH because cannot ground chebi

**Comment by maxkfranz** [comment]
Re. 5, the data is available via FTP: ftp://ftp.ncbi.nlm.nih.gov/pubchem/Substance/CURRENT-Full/XML/

Unless they have a re-usable container, we'd have to index the data ourselves.

**Comment by maxkfranz** [comment]
We're now back to Chebi.  I'm leaving this open, because we haven't solved the issue.  I'm demoting the priority, because we've applied a temporary workaround: We either need reliable Pubchem support or we need to decide that we *always* use Chebi.  

The latter case would be more palatable if we didn't immediately apply Reach groundings: A missing chemical grounding from Reach is not so bad if our search shown in the UI returns the intended result near the top.  That may require reconsidering the design of the ungrounded ('?') nodes.  I've created a discussion ticket: https://github.com/PathwayCommons/factoid/issues/245

**Comment by sacdallago** [comment]
Ditching the chemicals for now.

**Comment by maxkfranz** [comment]
Let Pubchem queries fail optimistically: 

(1) If a search fails, catch the error and return an empty list so other services used by the aggregate search service are still returned.

(2) If a lookup fails (i.e. by the Reach mapper), then catch the error and return a near-empty grounding (just the ID -- all metadata missing).
