### ISSUE TITLE
Difficulty in having a user enter text (for textmining)

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#230]
As Jeff has found, there is little value in just using abstract text with textmining.  You more often than not just get back nothing.  So it makes sense to use full text: the abstract, the body, figure legends, etc.

That is not easy for a user to do.  As a user, I have to spend all sorts of time going over my paper, copying and pasting.  A user would rather just spend a few minutes drawing what he already knows than spending all sorts of time copying and pasting.

Discuss ways to address this.

**Comment by sacdallago** [comment]
Please @maxkfranz bring this up during our next call, on monday. I've put it in the meeting agenda.

**Comment by jvwong** [comment]
I wonder if allowing people to upload full-text or even part of an article has legal/liability implications?

**Comment by sacdallago** [comment]
I assume this depends on the deal with the publisher? On the other hand, also google reads all of your emails to run ML on them and extract info like upcoming flights etc., so there must be a way around this. Good thinking, we can also bring this up tomorrow.

**Comment by sacdallago** [comment]
Just as a note: @gbader @cccsander we should discuss if this makes sense (e.g. users will be able to display full text)

**Comment by sacdallago** [comment]
Still not discussed with @cccsander

**Comment by maxkfranz** [comment]
We can ignore all legal implications for now and assume that it's not an issue.  The only part that remains is whether or how a user could effectively input his paper's full text.

**Comment by jvwong** [comment]
For now it's clear that users will be able to paste in custom text and we won't worry about legal implications.
