### ISSUE TITLE
Use the uploadFile endpoint for REACH docker instance.

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#231]
## Description of new feature

I am making a request to use the REACH `/api/uploadFile` endpoint available on the REACH web service. This will allow analysis of text of size as large as a typical research paper (I have tried a 35 KB text file [wong_mcell_v41_2011_MAIN.txt](https://github.com/PathwayCommons/factoid/files/1843037/wong_mcell_v41_2011_MAIN.txt)). There appears to be no noticeable trade-off  on speed with smaller text passages (e.g. sentences).  

## Motivation for new feature

The `/api/textBody` endpoint appears to fail with large amounts of text. This precludes any  demonstration with full text.

![image](https://user-images.githubusercontent.com/4706307/37847745-418ac7c4-2ea8-11e8-9f31-6873ed6804fb.png)

## Notes

Notes: See prototype in [branch: reach-upload](https://github.com/PathwayCommons/factoid/tree/reach-upload)

**Comment by gbader** [comment]
Are we now using the updated version of reach that was last recommended to
us?
