### ISSUE TITLE
User Feedback in Editors - Determine the total set of events that we need to listen for and log 

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#234]
related #216
### Unknown requirements
We don't know all of the events that we want to have yet logged, so I can foresee situations where new events come down the requirement pipeline as development work continues.  Therefore I think it is important that some infrastructure is built to make it easy to change and configure the set of events that we need to listen to.

### Dependent problems
The set of TODOS that we push to the user as they edit the document depends on the events that we listen to here.  Therefore, the set of total events we need to listen to also depends of what TODOS we need to push to the user.  This is another unknown requirement and therefore more infrastructure is needed to safeguard against the reality and inevitability of vague and shifting requirements.

### Edge cases
This particular issue seems straightforward, but I can foresee dependent problems having edge cases.  Suppose we push a TODO to complete an entity after a 'add entity' event has been emitted.  Suppose then that the entity is removed.  What should we do to this now dangling TODO?  

Initial thoughts on this problem seemed to suggest a strictly listen only approach to the model, listening and logging events as needed.  However, it seems that to handle this particular edge case, both event listening AND model synchronization will be needed to satisfy all of the 'user related feedback' requirements.

**Comment by d2fong** [comment]
Potential todos:
- ground entities
- check grounded reach entities

**Comment by sacdallago** [comment]
> This particular issue seems straightforward, but I can foresee dependent problems having edge cases. Suppose we push a TODO to complete an entity after a 'add entity' event has been emitted. Suppose then that the entity is removed. What should we do to this now dangling TODO?

Well, maybe calling it a "notification collector" is a bit deceiving. Good catch. It definitely looks like it has to be aware of the current state of the document, and it's not just passively responding to user actions, but making sure whatever if/else chain it's going down to suggest something is backed by the state of the open document.

So, ultimately, yes: there's most likely a bit of business logic missing, it does not just take a notification and put in, rather a well thought through set of conditional statements that are tested whenever some action is performed.
