### ISSUE TITLE
Allow arbitrary organisms in the model

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#236]
## Description of new feature

Allow the use of arbitrary organisms in the model.  Currently, a set list of organisms is all that's allowed.  Searches and groundings are restricted by those organisms.

- [ ] Store the (organismId, latinName) pair in the grounding for organism-specific entities, like proteins.  This allows search results to display organisms not in our 'popular organism' list.
- [ ] Allow any organism to come up in a search result.
- [ ] Replace instances of `Organism.ALL` with dynamic organism creation and dynamic list creation.

## Motivation for new feature

- This would add support for organisms other than human, mouse, yeast, fly, e. coli, c. elegans, arabidopsis, rat, and zebrafish.
- This would resolve cases where the current interface shows 'Organism: other'.

**Comment by sacdallago** [comment]
Just to extend: I remember that another consideration for this was that when returning results, proteins belonging to the organism(s) already represented in the graph get upvoted.

**Comment by maxkfranz** [comment]
> Just to extend: I remember that another consideration for this was that when returning results, proteins belonging to the organism(s) already represented in the graph get upvoted.

That's considered by this:

> Replace instances of Organism.ALL with dynamic organism creation and dynamic list creation.

**Comment by maxkfranz** [comment]
Probably not so realistic for local grounding services: #424 

The data would be much larger for more organisms.

**Comment by maxkfranz** [comment]
Handled by grounding service

Closing
