### ISSUE TITLE
Link "try factoid" to creation of document

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#239]
## Description of new feature

Try factoid on landing page should give options to:
- Create new empty document
- Create a document from text via nlp and land directly on graph editor

## Motivation for new feature

- Chris and Gary will need this for demo purposes

## Notes

- Least effort approach
- Usable and integrated so that it's not buggy and looks decent

**Comment by maxkfranz** [comment]
Closing after merging 

https://github.com/PathwayCommons/factoid/pull/240

https://github.com/PathwayCommons/factoid/commit/5175930d72493d3e3b278e9e064d6719be068fd1
