### ISSUE TITLE
DataComponent

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#249]
## Description of new feature
As @maxkfranz suggested, create a DataComponent that uses data in place of state to hint React to render. Similar to EntityInfo: https://github.com/PathwayCommons/factoid/blob/master/src/client/components/element-info/entity-info.js#L121

Make DataComponent a subclass of DirtyComponent, similar to how @d2fong suggested. The EntityInfo component could eventually be refactored to also subclass DataComponent.

## Motivation for new feature

A cleaner approach than the one used in EntityInfo component.

**Comment by metincansiper** [comment]
For calling dirty() I think it could be better to do it without needing to change InteractionForm if possible.
