### ISSUE TITLE
Add interaction and participant type to Reach-created elements

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#252]
## Description of new feature

In the document JSON specified by the Reach service, currently interactions and participants have no type.  That results in all interactions being of type 'general' and participants being undirected.

Specify, where possible, the interaction type (`association`) and the participant sign (`group: positive | negative | unsigned`).  For example, for 'A phosphorylates B':

(1) The interaction should be of type `modification`.

(2) B should be marked as a `positive` participant.

(3) B should be marked with modification state `phosphorylated`.

Note that (3) is entity state.  As I recall, Reach does not specify entity state but it could be inferred based on the interaction type that Reach provides.

## Motivation for new feature

The interaction UI (#199) allows a user to specify all this information.  Where possible, we should capture the same information from Reach.

See also #245.  We may consider populating the interaction with the type data, but the interaction may be marked as incomplete.

**Comment by ozgunbabur** [comment]
We've just discussed a few things related to this issue. Consider the sentence

A phosphorylated B at S123

Current design models this by saying the interaction is modification, and marks node B with phosphorylation:

A   [modifies]   B-p

But what if there are other forms of B in the model? Assume unphosphorylated B is binding to C. There has to be two B nodes in the model that are visually identical, which can be confusing to users.

The solution is to move modifications to the interactions and leave the molecules featureless.

A   [phosphorylates at S123]   B

**Comment by fdurupinar** [comment]
In order to cover the interaction types represented in the form-based editor, the following should be added:
-TRANSLOCATION: A translocates B 
-MOLECULAR INTERACTION:   This will cover physical interaction, complex association and dissociation. Takes a list of molecules.
-ACTIVATION INHIBITION: Refers to protein-protein interaction

**Comment by maxkfranz** [comment]
Counterexample mentioned during the call : p-A interacts with B, where a precondition of the interaction is that A is phosphorylated.

**Comment by ozgunbabur** [comment]
You are right, if you are concerned about representing "p-A interacts with B", I agree that having protein **states** as distinct nodes is the best option. But having states without having processes is very problematic. If we have states, then we should be able to model how these states transform into each other. Let's think we are modeling the below sentence.

A phosphorylates B at S123

If we do this by saying the relation is "modification" and use the phosphorylated B as target (B-pS123), then the structure will be:

A   ----modifies--->   B-pS123

But this means that A modifies the phosphorylated B, implying that this modification is secondary and requires a phosphorylated B. So this structure is not really representing what we are trying to say. We did try to say A phosphorylates the unphosphorylated B. The solution here is to add the process that converts the unphosphorylated B into phosphorylated B.
```       
      A
      |
      V
B   ----->   p-B
````
The easiest way to introduce this is to add optional roles to interaction's participants such as input output and controller. Do you think that is possible?

**Comment by fdurupinar** [comment]
Also, I don't know if such a case can come up, but what if we want to say A methylates phosphorylated B?
We will show this in the model as:
A----modifies ---> Bpm 
which can be read as: A phosphorylates and methylates B.
