### ISSUE TITLE
Arrowheads can be obscured by labels

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#253]
## Environment info

- Browser version (client) : Reproduced in Chrome 65, should affect all
- Node.js version (server) : N/A

## Current (buggy) behaviour

Arrowheads can be obscured by labels, e.g.:

<img width="307" alt="screen shot 2018-04-25 at 3 38 44 pm" src="https://user-images.githubusercontent.com/989043/39268841-fe69a102-489e-11e8-8082-d6171ad56eff.png">

In the above image, the arrowhead is mostly hidden.  It can be entirely hidden in the worst case, e.g.:

<img width="300" alt="screen shot 2018-04-25 at 3 40 54 pm" src="https://user-images.githubusercontent.com/989043/39268900-27147e60-489f-11e8-8faa-71d75c0d3ae2.png">

## Desired behaviour

Avoid overlaps of edge arrows with labels.  This would require additions to Cytoscape.js.

In the interim, the following mitigations are used:

(1) Reduce the font size of labels a bit.

(2) Pop up edges to the top of the z-ordering when an edge is selected.

## Minimum steps to reproduce

Create an negative edge arrowhead (tee), like the above examples.

**Comment by maxkfranz** [comment]
See also #199, as the interaction wizard is used to create arrowheads.

**Comment by maxkfranz** [comment]
TODO open ticket in Cytoscape.js repo.

**Comment by maxkfranz** [comment]
Marking as low priority for now, as we have some (imperfect) mitigations applied for now.

**Comment by maxkfranz** [comment]
This feature will make it into `cytoscape@3.3.0`.  Once it's released, we can use it in Factoid.  For straight edges like we use, it works very well.

**Comment by sacdallago** [comment]
Should be updated with new design
