### ISSUE TITLE
Help system

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#255]
## Description of new feature

The help system gives the user an overview of the system.

The help system is shown on-demand, as this information is something that a user is likely to want to look at once.  The help system is activated in one click of the (i) info icon.

![photo 2018-05-01 17 04 45](https://user-images.githubusercontent.com/989043/39494904-247107de-4d66-11e8-83cb-a8bbdcdcdb62.jpg)

When help is enabled, the screen is faded out somewhat.  This indicates to the user that he is no longer in the normal editing mode and is now in help mode.

Concise tooltips are shown, pointing directly to the parts of the UI they describe:

- Tools : *TBD show a summary for all tools versus show each existing hover tooltip*.
- Entity : Open an entity (e.g. protein) to
  - Set the name
  - Set the modification state for proteins (e.g. phosphorylated)
- Interaction : Open an interaction to
  - Set the interaction type (e.g. expression)
  - Set direction with arrowheads
- Notification panel : Click to open the notification panel to (*TBD perhaps rename to task panel in the UI*)
  - See what's left to do

The help system can be closed by clicking any of the faded out background or by clicking the (i) info icon again.

Edge cases

- Empty document : Temporary, example elements must be added.
- Entity and interaction tooltips overlap : This may be able to be automatically mitigated.  Otherwise, example elements could be always used.

## Motivation for new feature

The help system lets the user know what he can do and where he can do it in a simple way without getting in the user's way.

- It is non-intrusive.
- It is easy to maintain, yet more or less informative as a video.
- It makes good use of location per topic.
- It does not waste any screen space.

**Comment by d2fong** [comment]
Concerns:
- It is hard to fit all these tooltips on the screen at once without overlap

**Comment by d2fong** [comment]
Ideas:
- use a button labelled 'help' along side the info icon instead of info icon alone (users may not be able to understand what this icon means
- cue / visual indicator that says the user can exit help mode by clicking the screen or clicking the same help button again
- show the example text alongside the sample pathway
