### ISSUE TITLE
Emitting completed event on EntityInfo component

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#259]
## Description of new feature

``EntityInfo`` emits an event on completed stage.

## Motivation for new feature

The components that includes an instance of ``EntityInfo`` would need to be informed when completed stage is reached. As an example, form editor pops an ``EntityInfo`` instance for grounding of entities. It should be updated to show that the grounding of entity is completed when ``EntityInfo`` instance reach the completed stage. 

``interactionInfo`` component emits events in certain cases so ``EntityInfo`` would be expected to be able to do it as well. @maxkfranz  Is there any drawback behind doing it?

**Comment by metincansiper** [comment]
Actually for better control emitting a similar event through the elements would be better and I think elements would already be emitting such an event.

**Comment by metincansiper** [comment]
Seems like ``Element`` already providing it. Just closing the issue.

**Comment by metincansiper** [comment]
Opening the issue back because I think that listening to completed event through the elements requires a lot of consideration since the scope of element is not limited to form editor. Removing event listener on an appropriate place would or would not be enough. I am not sure what is a good way of handling this in Factoid.

**Comment by maxkfranz** [comment]
I don't think this is valid.  An EntityInfo goes to the stage that the user selects.  It shouldn't be overridden by the app.  This was probably just a mis-use of the EntityInfo in the form, and it doesn't seem to be an issue with the current overlay method.  Closing for now
