### ISSUE TITLE
Form bugs -- sprint 3

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#276]
TODO 

- [x] Synchronize interaction type updates from document to form. 

- [x] Changing interaction direction on the graph should update the form.

- [x] Add delete button for molecular interaction entities.

-  [x] Interaction types need to be grounded in the form editor.

- [x] Add a hide/show info check box for all entities. This could be added to menu. 

- [x] "Interacts with" looks incomplete on the graph view because activation or inhibition status needs to be selected, which is irrelevant in this case. Select activation by default, or make activation<-->association, inhibition<-->dissociation. 

- [x] When an entity is updated after merging, the clones' info need to be updated as well.
- [x] Molecular entity deletion is not working correctly after merging

Concurrency with Graph Editor

- [x] When a new interaction is added on the graph editor side, the interaction is not consistently updated on the form editor side unless it is reloaded.  Even though a "remoteupdate" signal is sent to the form editor and the interaction's element count is correct,  the interaction's individual participants are null.

- [ ] When an entity is completed on the graph side, complete it on the form editor concurrently.

- [ ]   Add/deleting an interaction when both graph and form editors are open cause a warning " a promise was created in a handler at but was not returned from it" at syncher->load and syncher remoteupdate on element-set.js. (https://github.com/PathwayCommons/factoid/blob/8733a307c5fb1f781666bd7d11ebf12ecb745a96/src/model/element-set.js#L64)

**Comment by fdurupinar** [comment]
form-components

**Comment by jvwong** [comment]
Setup: Seeded with text from `wong_mcell_v41_2011_MAIN.txt` (Google Drive `Factoid/Testing/Full_text_articles`) 

 - [ ] After adding a 'inhibition' interaction ('RB inhibits E2F1'), checking 'Hide entity information for all' did not affect text display for inhibition interaction
