### ISSUE TITLE
Bold the interaction trigger word in the highlight mode

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#277]
## Description of new feature

In the highlight mode, make the interaction trigger word bold.  For example, "P53 **phosphorylates** MDM2".

## Motivation for new feature

If we can not get Brat output from Reach, then this is a good compromise.

**Comment by jvwong** [comment]
Does the 'interaction sentence' correspond to either the `text` or `verbose-text` JSON value in REACH output?

**Comment by metincansiper** [comment]
I created PR #281 that keeps underlining. I can make the required updates if it is not desired.
