### ISSUE TITLE
Basic Biopax export of the model

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#278]
## Description of new feature

Export 

- [ ] Proteins
- [ ] Chemicals (small molecules)
- [ ] General interaction
- [ ] Expression interaction
- [ ] Phosphorylation interaction
- [ ] Methylation interaction
- [ ] Ubiquination interaction
- [ ] Protein and chemical interaction

## Motivation for new feature

Exporting to PC

**Comment by metincansiper** [comment]
I made the following mappings between factoid interactions and type of binary relations [here](http://www.pathwaycommons.org/pc2/formats#sif):

For ``protein-chemical``
If the target is ``chemical`` then  ``controls-production-of`` or ``consumption-controled-by``
else ``chemical-affects``.

For ``expression``  - ``controls-expression-of``.

For general ``modification`` - ``controls-state-change-of``.

For ``modification`` subtypes including ``methylation``, ``phosphorylation`` and ``ubiquination`` - ``controls-phosphorylation-of`` by changing the effect on target protein.

For ``general`` - ``interacts-with``.

According to table at the [link]((http://www.pathwaycommons.org/pc2/formats#sif)) for ``interacts-with`` the participants are supposed to be proteins but in Factoid ``general`` interaction type would be added between not only proteins but it can be added between protein-chemical and chemical-chemical. Therefore, my mapping there would be wrong or incomplete. However, when I create molecular interactions between protein-chemical and chemical-chemical then export the graph to biopax and open it by chibe the interactions are rendered with no problem.

The following is visualization of a factoid graph where I created any kind of binary relations

<img width="1068" alt="factoid-to-export" src="https://user-images.githubusercontent.com/6534865/40379480-0f7a261c-5dab-11e8-831e-7477343aee77.png">

and the following is how the owl file exported from this graph is visualized by chibe

<img width="595" alt="chibe-viz" src="https://user-images.githubusercontent.com/6534865/40379546-3082b8e2-5dab-11e8-9206-547ab8d7ba4d.png">

Here are JSON representation of [factoid document](https://github.com/PathwayCommons/factoid/files/2027885/factoid-doc.txt) and [the exported owl file](https://github.com/PathwayCommons/factoid/files/2027880/311eb217-1832-4762-8491-7bc58b29ab17.txt).

While exporting to owl I am representing entities by their name accessible through ``entity.name()`` should it be replaced by something else that identifies them better?

Currently I am working on my [feature branch](https://github.com/metincansiper/factoid/commits/export-to-biopax).

**Comment by metincansiper** [comment]
I added a few missing relations in above comment.

Here is the new biopax file exported from factoid [new-biopax.txt](https://github.com/PathwayCommons/factoid/files/2028730/new-biopax.txt) and the following image is how it is visualized by chibe:

<img width="719" alt="chibe-viz" src="https://user-images.githubusercontent.com/6534865/40391578-9ab7a372-5dcd-11e8-974f-cba4c3580acf.png">

The followings are the representation of factoid graph where the biopax file is exported. Each line represents description of an interaction from factoid document. What each line is corresponding to in the biopax file and image above can be understood by the entity names:

- MDM2(Protein) inhibits the expression of TP53(Protein)
- P3(Protein) produces palladium(Chemical)
- P4(Protein) consumes nitro benzene(Chemical)
- iodine(Chemical) inhibits P6(Protein)
- atp(Chemical) activates P5(Protein)
- chem(Chemical) interacts with chemical(Chemical)
- P2(Protein) interacts with P1(Protein)
- P7(Protein) interacts with iodine atom(Chemical)
- P9(Protein) inhibits the phosphorylation of P8(Protein)
- P13(Protein) inhibits the ubiquination of P12(Protein)
- P11(Protein) inhibits the methylation of P10(Protein)

@ozgunbabur @emekdemir Does the exported biopax file seem correct for such a factoid graph?
