### ISSUE TITLE
Popovers move when the mouse scrolls

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#290]
## Environment info

- Browser version (client) : Version 66.0.3359.181 (Official Build) (64-bit)

- Node.js version (server) : 8.10.0

## Current (buggy) behaviour

When using popovers to display content, they will not stick to the target when scrolling.  This isn't a problem with the network editor but it is a problem for pages that scroll e.g. the landing page or the form editor page

## Desired behaviour

The popover should either close or stick to the target when someone scrolls.

## Minimum steps to reproduce

- Checkout the bar-redesign branch
- Go to the form editor
- Click the app bar button
- Scroll down the page
- The popover scrolls down too

**Comment by maxkfranz** [comment]
I think this may require upgrading tippy, which means we would need to address the tippy stutter that happens on the network editor with tippy@latest.

**Comment by metincansiper** [comment]
@maxkfranz Seems like already the latest versions of both of popperjs and tippyjs are used. I think that what causes this bug is [this line](https://github.com/PathwayCommons/factoid/blob/master/src/styles/popover/tippy.css#L5). This problem disappeared when I tried to remove the line.

**Comment by metincansiper** [comment]
Seems like it is already removed in sync-fix branch by https://github.com/PathwayCommons/factoid/commit/a4ca6e5554ac0da8454a01bea17d00ac39191fca

**Comment by maxkfranz** [comment]
That's right.  Dylan and I redid the entity infos as overlays to simplify things.  Closing
