### ISSUE TITLE
UI/UX improvements/tweaks/redesigns for form

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#296]
## Description of new feature

- [x] Make completion checks visually consistent with network editor (same green colour and icon, maybe)
- [x] Make delete 'x' icons the same as in the network editor
- [x] Simplify adding interactions by type.  It is confusing to list all interaction types how they are.  It looks like there are more interactions in the doc than the number that really exists.
- [x] A layout should be called when modifying the document by the form, within the form code itself.

## Motivation for new feature

TODO

**Comment by metincansiper** [comment]
@maxkfranz What do you mean by "Simplify adding interactions by type" or how to simplify (Sorry about that if this was already detailed in the previous call)?

**Comment by maxkfranz** [comment]
> I think it worths deciding on a more certain UI before implementing this. How about using only one "+ Add Interaction" button that does not add interaction directly but toggles visibility of a div that includes buttons for adding different kinds of interactions on click. And the descriptions of forms would be used as tooltip texts of buttons accordingly.

That's what I had in mind

**Comment by fdurupinar** [comment]
> How about using only one "+ Add Interaction" button that does not add interaction directly but toggles visibility of a div that includes buttons for adding different kinds of interactions on click. 

@metincansiper that would be good. 

>  And the descriptions of forms would be used as tooltip texts of buttons accordingly.

Not sure about this though. I think descriptions should be more available to the user than just waiting for tooltips to appear. 
Why don't you come up with a prototype so that we can discuss on it?

**Comment by maxkfranz** [comment]
See also #319
