### ISSUE TITLE
Move util code for biopax export to /client

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#300]
## Description of new feature

Refactor the biopax export code such that /util/file is in client/.

## Motivation for new feature

The file code is client-side only.  It uses file-saver and (global) fetch, which will not work on the server.  Only code that works on both client and server should be in util

**Comment by metincansiper** [comment]
@maxkfranz Shall I create a util folder under client and put file.js inside that folder? If not maybe I can rename it as something like file-util.js to specify that it is a utility file.
