### ISSUE TITLE
Put save and linkout buttons in the "..." menu

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#304]
## Description of new feature

Remove the icon buttons for save-to-biopax and share-link.  Replace them with text entries in the "..." menu.

## Motivation for new feature

These features shouldn't use much if any screen space by default, as they would be used infrequently.

**Comment by maxkfranz** [comment]
Ref https://github.com/PathwayCommons/factoid/issues/289

**Comment by maxkfranz** [comment]
See https://github.com/PathwayCommons/factoid/tree/move-to-menu

**Comment by maxkfranz** [comment]
Punting this for now

**Comment by jvwong** [comment]
Closing as implemented.
