### ISSUE TITLE
Sync problem of adding molecular interaction with more than 2 participants

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#317]
## Environment info

- Browser version (client) : Chrome 67.0.3396.87
- Node.js version (server) : 8.11.3
- rethinkdb 2.3.6 (CLANG 8.1.0 (clang-802.0.42))
- npm 5.6.0

## Current (buggy) behaviour

When a molecular interaction that contains more than 2 participants is added from form editor sometimes some of the participants does not look connected to the others in network editor. This must be a sync issue since they all look connected when the page is refreshed. Note that this only sometimes happens (I could not find out a pattern that reproduces the bug in a stable way).

## Desired behaviour

When a molecular interaction is added from form editor all of the participants should look connected in network editor without needing to refresh the page.

## Minimum steps to reproduce

- Checkout form-types branch of https://github.com/metincansiper/factoid/ that is based on sync-fix branch of the main repository (You can directly use sync-fix branch if #316 is already merged). This is needed because current sync-fix UI does not allow to create molecular interactions from form editor (You can use use a branch where form-types is merged at the top of sync-fix for a more up-to-date version).
- Add a molecular interaction with more than 2 participants from the form editor while a network editor is open in another tab. 
- Go and check network editor (do not refresh the page) to see if all participants of interactions are connected. Sometimes they are but sometimes not.
- I suppose there is no pattern to reproduce the bug in a stable way. At least I could not find out such a pattern so far.

**Comment by maxkfranz** [comment]
We decided some time ago to remove support for more than two participants in the UI.  The form should have the same restriction.

**Comment by metincansiper** [comment]
Okay then I think I should close the issue now. We can re-open it if needed.
