### ISSUE TITLE
Node positions in network editor are not synched correctly when docEl.reposition() is called

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#330]
## Environment info

- Browser version (client) : Chrome version 67.0.3396.87 
- Node.js version (server) : 8.11.3
- Npm version: 5.6.0
- Rethinkdb version: 2.3.6 (CLANG 8.1.0 (clang-802.0.42))

## Current (buggy) behaviour

Node positions in network editor are not synched correctly when ``docEl.reposition()`` is called from [here](https://github.com/metincansiper/factoid/blob/a0dab526c0328e19c295c4fa6593d978c99e8b29/src/model/document/document.js#L325). However, they are updated after refreshing the network editor (See #329 results).

## Desired behaviour

Node positions in network editor should be updated without needing to refresh the page.

## Minimum steps to reproduce

- Checkout [this branch](https://github.com/metincansiper/factoid/tree/form-layout). Currently it only has only one commit at the top of latest factoid unstable.
- Open the same document in both form and network editors. 
- Add a set of interactions from form editor (you can see the bug better if you switch between editors after adding each interaction).
- Switch to network editor to see unexpected layout.
- Refresh the page to see the expected layout.

**Comment by maxkfranz** [comment]
I'm not seeing this in the unstable or master branches, so I suspect it could be something to do with the commits in the form-layout branch

**Comment by metincansiper** [comment]
@maxkfranz 
Would be happening less frequently but I am able to see the same thing in unstable as well. The results below from my experiments in unstable branch.

The following is how network editor looks after adding some elements from form:

<img width="1429" alt="screen shot 2018-06-22 at 9 45 35 pm" src="https://user-images.githubusercontent.com/6534865/41805858-0a75e542-7666-11e8-8ca7-95a4381be3ae.png">

The followings are node positions for the graph above:

```
[{"x":36.781113061359974,"y":195.6263904197109},{"x":57.975886856398574,"y":30.71984839661434},{"x":272.90040685527856,"y":196.42354818615047},{"x":273.6856419851579,"y":31.970811132406197},{"x":58.645081666304804,"y":525.3828413978408},{"x":30.86630160898244,"y":361.91262959479866},{"x":0,"y":0},{"x":279.4523323113699,"y":360.48090089515745}]
```

The following is how the network editor of same document looks when I refresh the page:

<img width="1440" alt="screen shot 2018-06-22 at 9 46 08 pm" src="https://user-images.githubusercontent.com/6534865/41805872-54026b68-7666-11e8-8f1c-3d03391a0062.png">

And the followings are the node positions for the graph right above:

```
[{"x":36.781113061359974,"y":195.6263904197109},{"x":57.975886856398574,"y":30.71984839661434},{"x":272.90040685527856,"y":196.42354818615047},{"x":273.6856419851579,"y":31.970811132406197},{"x":58.645081666304804,"y":525.3828413978408},{"x":30.86630160898244,"y":361.91262959479866},{"x":272.451932924283,"y":525.6078406434356},{"x":279.4523323113699,"y":360.48090089515745}]
```

When you check the node positions you can see that before the refresh there is one node whose position is ``{x: 0, y: 0}`` and that node makes the difference. 

The same of form-layout branch there as well one or more nodes have position of ``{x: 0, y: 0}``  before refreshing the page and that causes the problem.

A hint on reproducing the problem would be switching to network editor after adding each of the interaction from form editor to see if there is a weird layout.

**Comment by metincansiper** [comment]
@maxkfranz 

The easiest consistent way that I can reproduce the problem in unstable branch is adding only one interaction from the form editor and then switching to the already opened network editor. In that case I have the following view at the network editor:

<img width="1440" alt="screen shot 2018-06-26 at 2 49 38 pm" src="https://user-images.githubusercontent.com/6534865/41941756-c6dbbf84-7951-11e8-88dc-b63412269688.png">

Why I have this view is that one of the nodes have the position of ``{x: 0, y: 0}``. If I refresh the page I get the following because nodes are rendered at the correct positions after refresh:

<img width="1440" alt="screen shot 2018-06-26 at 2 49 53 pm" src="https://user-images.githubusercontent.com/6534865/41942024-be005b26-7952-11e8-9451-77cfe5dfbfff.png">

Do you able to reproduce the same thing in unstable branch? Today we talked about that this would be a problem of calling a layout without an other one finish. I think that the main problem would not be related to confliction of multiple layouts. One reason making me think so is that there is only one layout call in this case but we still have the problem.

**Comment by metincansiper** [comment]
Debugged on unstable for the case of above comment (adding only one interaction from form editor) seems like the reason behind the issue is that [document.on('add', onAddEle)](https://github.com/PathwayCommons/factoid/blob/unstable/src/client/components/editor/cy/doc.js#L514) is not registered (which also means that [element listeners including the on for ``remoteupdate``](https://github.com/PathwayCommons/factoid/blob/unstable/src/client/components/editor/cy/doc.js#L384) are not registered) yet when [``remoteupdate`` is emitted from ``syncher.js``](https://github.com/PathwayCommons/factoid/blob/unstable/src/model/syncher.js#L142) . Therefore, [the function to handle remote position updates from network editor](https://github.com/PathwayCommons/factoid/blob/unstable/src/client/components/editor/cy/doc.js#L121) is not executed.
