### ISSUE TITLE
Tooltip error for unnamed entities

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#331]
## Environment info

- Browser version (client) : Chrome version 67.0.3396.87 
- Node.js version (server) : 8.11.3
- Npm version: 5.6.0
- Rethinkdb version: 2.3.6 (CLANG 8.1.0 (clang-802.0.42))

## Current (buggy) behaviour

When tooltip is opened for unnamed entities the following error is thrown (happens under some conditions see "Minimum steps to reproduce" section):

<img width="1430" alt="screen shot 2018-06-22 at 12 09 32 pm" src="https://user-images.githubusercontent.com/6534865/41794726-2b990d4a-7615-11e8-9d23-3b8a82b74e5e.png">

## Desired behaviour

No error should be thrown.

## Minimum steps to reproduce

- Checkout unstable branch.
- Add a new entity (new entities comes unnamed).
- Tap on screen or node itself to close the tooltip (automatically opened when a new entity is created).
- Tap the node to open the tooltip again.
- Check the developer console out to see the error.

**Comment by maxkfranz** [comment]
I think this is just a known issue with the Tippy lib.  Upgrading it removes the message, but it causes behavioural problems.  Since the message doesn't cause any issues, it's something we can ignore at the moment.

**Comment by jvwong** [comment]
Not present in 

- Version 69.0.3497.100 (Official Build) (64-bit)
- Firefox 62.0.3 (64-bit)
- Safari Version 11.0.1 (11604.3.5.1.1)
