### ISSUE TITLE
The textmining highlighter can repeat words

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#333]
## Environment info

- Browser version (client) : Firefox 60
- Node.js version (server) : Node v8.11.2

## Current (buggy) behaviour

The word 'phosphorylated' gets repeated:

<img width="874" alt="screen shot 2018-06-25 at 3 18 28 pm" src="https://user-images.githubusercontent.com/989043/41870801-101284e8-788b-11e8-9753-448cb32b9db8.png">

<img width="883" alt="screen shot 2018-06-25 at 3 18 34 pm" src="https://user-images.githubusercontent.com/989043/41870808-1448164a-788b-11e8-9d8f-e1aeb35be681.png">

## Desired behaviour

No repeated words.

## Minimum steps to reproduce

Use this text:

> The transforming growth factor beta (TGFB) superfamily of cytokines are involved in a multitude of activities. The TGFB1 ligand can activate the cell-surface receptor ALK5. In the cytoplasm, activated ALK5 phosphorylates the SMAD2 protein. Phosphorylated SMAD2 is able to bind to the common mediator SMAD4, which regulates transcription.

**Comment by maxkfranz** [comment]
When I tested this, I was also unable to go to the next step.  Maybe this caused a blocking error.  All I saw was 'unhandled rejection' in the console.

**Comment by sacdallago** [comment]
If this is truly blocking, should be next first thing on the todo list, as this might qualify as a hot-fix for the current stable branch

**Comment by metincansiper** [comment]
In my case I see the word "Phosphorylated" repeated as well but I am still able to proceed to the next page by clicking submit button. I will try to figure out why it is repeated and fix it.

**Comment by maxkfranz** [comment]
Maybe the error is unrelated but it happened at the same time, or it might not happen every time.  I'll have to try more times to see.

**Comment by metincansiper** [comment]
The problem was mainly about that based on the text mining results two different event frames would be pointing out to the exactly same event trigger. I created #342 to solve the problem. I provided more information about insight of the problem on the PR's page.

**Comment by sacdallago** [comment]
Merged
