### ISSUE TITLE
The search may not return any results

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#334]
## Environment info

- Browser version (client) : Firefox 60
- Node.js version (server) : Node 8.11.12

## Current (buggy) behaviour

The results don't show for SMAD2 when SMAD2 is generated from textmining.

## Desired behaviour

Show a non-empty results list.

## Minimum steps to reproduce

(1) Use this seed text:

> The transforming growth factor beta (TGFB) superfamily of cytokines are involved in a multitude of activities. The TGFB1 ligand can activate the cell-surface receptor ALK5. In the cytoplasm, activated ALK5 phosphorylates the SMAD2 protein. Phosphorylated SMAD2 is able to bind to the common mediator SMAD4, which regulates transcription.

(2) Click SMAD2

(3) Go back in the wizard

(4) Notice the list is empty

(5) Create a new SMAD2 node

(6) Notice the list is not empty

**Comment by maxkfranz** [comment]
Not reproducible anymore locally or on unstable.factoid.baderlab.org

**Comment by jvwong** [comment]
Can't reproduce.
