### ISSUE TITLE
End-to-end tests of the app

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#341]
## Description of task

Test the system end-to-end to make sure that the workflow we want to demo works well.  Identify bugs and UI issues, and create Github issues for each.

- Landing page to example document page
- New document wizard
  - Submit text
  - Select network editor
  - Select form editor
- Complete document solely in network
- Complete document solely in form
- Complete document switching between editors
- Complete document with editors side-by-side (network-network, form-network, form-form)

List of input text to try:

> The transforming growth factor beta (TGFB) superfamily of cytokines are involved in a multitude of activities. The TGFB1 ligand can activate the cell-surface receptor ALK5. In the cytoplasm, activated ALK5 phosphorylates the SMAD2 protein. Phosphorylated SMAD2 is able to bind to the common mediator SMAD4, which regulates transcription.

> Under normal conditions, p53 is a short-lived protein. The MDM2 protein, usually interacts with p53, and by virtue of its E3 ubiquitin ligase activity, mediates its degradation by the ubiquitin-proteasome machinery. Upon detection of DNA damage, the ATM kinase mediates the phosphorylation of the Mdm2 protein to block its interaction with p53. The p53 protein activates the transcription of cyclin-dependent kinase inhibitor, p21. p21 inactivates the CyclinE:Cdk2 complexes, which prevents entry into S-phase of the cell cycle.

## Motivation for task

Let's make sure that everything is running smoothly for demos.

**Comment by metincansiper** [comment]
Should the tests be done on unstable or master?

**Comment by maxkfranz** [comment]
Unstable, since we're still making minor UI tweaks

**Comment by d2fong** [comment]
On unstable.factoid.baderlab.org I noticed that the network and form editors weren't synching.

**Comment by maxkfranz** [comment]
The form still only shows completed interactions.  That is something we could turn off.  It would mean that the interaction type could change on the network side and the form would change the line.  However, the form would have no way of changing the type of a line other than to delete it and create a new one.

**Comment by jvwong** [comment]
> Under normal conditions, p53 is a short-lived protein. The MDM2 protein, usually interacts with p53, and by virtue of its E3 ubiquitin ligase activity, mediates its degradation by the ubiquitin-proteasome machinery. Upon detection of DNA damage, the ATM kinase mediates the phosphorylation of the Mdm2 protein to block its interaction with p53. The p53 protein activates the transcription of cyclin-dependent kinase inhibitor, p21. p21 inactivates the CyclinE:Cdk2 complexes, which prevents entry into S-phase of the cell cycle.

Expected result:

[Link to live doc](http://unstable.factoid.baderlab.org/document/718f6b06-73bb-4473-a4c8-54a8a88dda1f/08197331-3583-4f6b-b933-ab7b5b671fdc)

![p53_network](https://user-images.githubusercontent.com/4706307/41978061-f5898300-79ee-11e8-8a07-299bfa36b6fe.png)

**Comment by metincansiper** [comment]
One thing I realized is about changing types of interaction participants. For example, one can have 2 proteins and create a phosphorylation between the proteins. Then he can rename one of the protein and convert it to a chemical. Then he would end up with having a phosphorylation between a chemical and protein which is I suppose not valid.

There could be some precautions to disable such changes. I think it would be a longer term ticket if it seems not safe to change in short term.

**Comment by metincansiper** [comment]
#350

**Comment by jvwong** [comment]
The  model and UI changes will be significant and some of the related issues will be addressed. Also superseded by #373
