### ISSUE TITLE
Help system network drag

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#346]
## Environment info

- Browser version (client) : Firefox 60
- Node.js version (server) : Node 8

## Current (buggy) behaviour

It is possible to drag the network in the network editor while in help mode

## Desired behaviour

When you click the help system you should immediately not be able to interact with the network

## Minimum steps to reproduce

- Click the help system button
- Immediately after, drag the network
- The help system will appear and you can drag the network even though the help system should not allow that

**Comment by maxkfranz** [comment]
Maybe set pointer-events:none on the network container?

**Comment by maxkfranz** [comment]
Putting medium priority, since it doesn't break anything
