### ISSUE TITLE
Weird behaviour after opening document in network editor and clicking edge

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#350]
## Environment info

- Browser version (client) : Version 67.0.3396.99 (Official Build) (64-bit)
- Node.js version (server) : Getting it on [deployed unstable](http://unstable.factoid.baderlab.org/) not sure yet but I suppose I got a similar bug in my local server as well in the past (if that is the case my local node version is 8.11.3).

## Current (buggy) behaviour

Some elements become partially or totally invisible when an edge is clicked. In this case edge is partially invisible and one of its participants is totally invisible. However, the bug would be seen in different forms as well for different cases. Bug would be seen in a different way if you pan the elements to the center of the screen. I realized that it is working fine if the elements are rendered close to the center of canvas when the graph is first loaded (so I cannot make sure that you will be able to reproduce the bug from my example in a stable way) but it is problematic if they are rendered around top left corner. It would be related to rendering them around the toolbar at the top left. Other than this I do not know why panning of graph changes time to time.

<img width="641" alt="screen shot 2018-06-27 at 3 43 41 pm" src="https://user-images.githubusercontent.com/6534865/42003575-f07fb794-7a20-11e8-81a9-7578b2eff9df.png">

## Desired behaviour

Only tooltip of edge should popover it. Nothing should be broken like the following:

<img width="647" alt="screen shot 2018-06-27 at 3 43 12 pm" src="https://user-images.githubusercontent.com/6534865/42003553-d84f86e0-7a20-11e8-97e7-e2f81ad4df87.png">

## Minimum steps to reproduce

I get it in different cases. One case I caught is when I open http://unstable.factoid.baderlab.org/document/5963c62b-6f41-44e7-8a26-dcaec73a638e/5b1802b0-9217-4b9d-b047-24e5605fd540 then clicked on the edge (As I mentioned above it is not reproducable when the elements are rendered around center of screen).

**Comment by jvwong** [comment]
I can reproduce this error. 
I also notice that the initial rendering position on (re)load is unpredictable: {Centre, top-left corner}. I s this part of the bug?

**Comment by metincansiper** [comment]
>I also notice that the initial rendering position on (re)load is unpredictable: {Centre, top-left corner}. I s this part of the bug?

@jvwong 

I am not sure yet but it is most probably related to panning/zooming of graph. I think that would be a different bug but reproducing this bug would be related to that bug. 

For me this bug only appears when initial rendering is done around top left but does not appear when it is around center. Is it the case for you as well?

**Comment by jvwong** [comment]
yes, top left initial rendering.

**Comment by jvwong** [comment]
Can no longer reproduce on:

- Version 69.0.3497.100 (Official Build) (64-bit)
- Firefox 62.0.3 (64-bit)
- Safari Version 11.0.1 (11604.3.5.1.1)
