### ISSUE TITLE
DEMO button on landing page

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#351]
## Description of new feature

On the landing page, have a button (similar to _Try factoid_) that brings the users to the /new/seed page with a populated text-box (populated using the same abstract that is used for the _Try factoid_ button).

## Motivation for new feature

Showcase the whole process: insert text, extract annotations, select editor, edit.

**Comment by jvwong** [comment]
From the paper review:

> 6. Please consider providing a demo to try out the editing interface in a 'sandbox' without having to submit any information (article title, name, etc.). This can help users decide whether they can contribute and which articles may be most appropriate for them to work on.

**Comment by jvwong** [comment]
There's a bit of a lag on the demo (#995) when clicking the DEMO from homepage: anywhere from 3 - 6 seconds. May give the impression something is broken...
