### ISSUE TITLE
Switching between graph and form should be more prominent

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#352]
## Description of new feature

The toggle between network and form editor should be more prominent on both editors. 

- An easy fix: instead of having the switch to form/graph buried in the "..." menu, have it as a separate menu item
- A more visible solution: 
  - on the graph: bottom-left corner a _"Form"_ button, such as the Satellite button on gmaps ![screen shot 2018-06-29 at 9 52 09 am](https://user-images.githubusercontent.com/6240943/42096033-4f996f74-7b82-11e8-990b-9e2c64624687.png)
  - on the form: a button with text at the end of the interactions list saying "see network in graphical form"

## Motivation for new feature

A new user should be attracted by the idea of switching editors and seeing "_what does this do_", because ultimately a user could be more confident with one or the other editor (but not be aware of it).

**Comment by jvwong** [comment]
See 'Factoid: Meeting Notes' Google Doc, August 28th for updated mockups of this feature.
