### ISSUE TITLE
Factoid vs Reach

### ISSUE THREAD

**Issue by cannin** [PathwayCommons/factoid#357]
## Environment info

- Browser version (client) : Chrome OSX 67.0.3396.99
- Node.js version (server) :  Not sure, but what ever is on unstable at the filing of this bug report. 

## Current (buggy) behaviour

Factoid output does not include all the interactions that REACH produces 

![screen shot 2018-07-16 at 5 08 00 pm](https://user-images.githubusercontent.com/790284/42783845-37bd9488-891b-11e8-8533-0fa8b1a71fe0.png)

![screen shot 2018-07-16 at 4 11 33 pm](https://user-images.githubusercontent.com/790284/42783850-39c0578e-891b-11e8-949f-d50506e64ece.png)

## Desired behaviour

Factoid show return more of the interactions that REACH returns, specifically 1) CK2 phosphorylating SIRT1, 2) Cyclin B phosphorylating SIRT1, 3) JNK phosphorylating SIRT1. 

## Minimum steps to reproduce

Text used:

SIRT1 phosphorylation results in both stimulatory and inhibitory effects. Phosphorylation of SIRT1 by JNK occurs at three sites: S27, S47, and T530 in response to oxidative stress that stimulates its deacetylation activity [[A4]] [24]. In contrast, mTOR also phosphorylates SIRT1 in response to oxidative stress, but only at a single site, S47, resulting in the inhibition of SIRT1 [[A5]] suggesting a multi-site phosphorylation regulatory mechanism is in place; such a mechanism may be involved in the regulation of the timing of SIRT1 activity [25,26]. CK2 phosphorylates human SIRT1 at S659 and S661, both in vivo and in vitro, stimulating its deacetylation activity [[A4]] [27,28]. These two phosphorylation sites exist in a region of SIRT1 that are essential for SIRT1 activity both for its catalytic activity and ability to bind to substrates [29]. Cyclin B/Cdk1, a cell cycle-dependent kinase, can phosphorylate SIRT1 at T530 and S540 [[A6]]. Phosphorylation at these two sites decreases the activity of SIRT1 and disrupts progress of the cell cycle [30]. Similar to the case with mTOR and S47, T530 is a site phosphorylated by JNK and may also function as a part of a combinatorial modification program.

**Comment by jvwong** [comment]
Some prelim workup on this:

>Factoid show return more of the interactions that REACH returns, specifically 

> 1) CK2 phosphorylating SIRT1, 
> 2) Cyclin B phosphorylating SIRT1, 

I am going to assume you are referring to the text `"CK2 phosphorylates human SIRT1 at S659 and S661 , both in vivo and in vitro , stimulating its deacetylation activity [ [ A4 ] ] [ 27,28 ] ."` and `"Cyclin B/Cdk1, a cell cycle-dependent kinase, can phosphorylate SIRT1 at T530 and S540"` 

I suspect the offending item for Factoid is that in both cases, the controlled ("SIRT1 at S/T? and S/T?") references two items (i.e. the 'theme/protein' and the 'site'). I speculate that this 'site' entity may be gumming things up @maxkfranz ?

e.g.

```
"frame-id":"evem-api703-UAZ-r1-Reach-3-3927",
           "text":"phosphorylates human SIRT1 at S659 and S661",
           "arguments":[
              {
                 "text":"S661",
                 "argument-type":"entity",
                 "type":"site",
                 "object-type":"argument",
                 "index":0,
                 "arg":"ment-api703-UAZ-r1-Reach-3-14621"
              },
              {
                 "text":"SIRT1",
                 "argument-type":"entity",
                 "type":"theme",
                 "object-type":"argument",
                 "index":0,
                 "arg":"ment-api703-UAZ-r1-Reach-3-14615"
              }
           ],
           "type":"protein-modification",
           "frame-type":"event-mention",
           "subtype":"phosphorylation",
```  
 
> 3) JNK phosphorylating SIRT1.

JNK is a reference to a family, which we currently do not support (see #180).
Aside: Strangely the xref db of the entity is not PFAM but something called 'be' ?

```
{ 
  "events":{...},
  "events":{
    frames: [
    ...
        {
           "text":"JNK",
           "frame-id":"ment-api703-UAZ-r1-Reach-1-14620",
           "type":"family",
           "frame-type":"entity-mention",
           "end-pos":{
              "reference":"pass-api703-UAZ-r1-Reach",
              "offset":105,
              "object-type":"relative-pos"
           },
           "xrefs":[
              {
                 "namespace":"be",
                 "object-type":"db-reference",
                 "id":"JNK"
              }
           ],
           "object-type":"frame",
           "start-pos":{
              "reference":"pass-api703-UAZ-r1-Reach",
              "offset":102,
              "object-type":"relative-pos"
           },
           "sentence":"sent-api703-UAZ-r1-Reach-1",
           "alt-xrefs":[
              {
                 "namespace":"be",
                 "object-type":"db-reference",
                 "id":"JNK"
              }
           ]
        },
    ...
    ]
  },
...
}
```

**Comment by jvwong** [comment]
Update, best guess is that 'be' namespace is Sorger's 'Bioentities' now know as [Famplex](https://github.com/johnbachman/famplex)
