### ISSUE TITLE
RethinkDb port is there hard-coded (in tests)

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/factoid#360]
https://github.com/PathwayCommons/factoid/blob/d426172e454260dd3d461b739569e9ef0b2732a0/test/util/table.js#L22

**Comment by maxkfranz** [comment]
Yes, the tests always run locally anyway.  What usecase are you thinking of for parameterising the DB host and port?

**Comment by IgorRodchenkov** [comment]
I thought of simply reusing the same existing DB_PORT environment variable (and its default value 28015) throughout the code, incl. in tests; why not.
