### ISSUE TITLE
Template tweaks re. 'top bar' concept

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#361]
Implement:

- [x] Move the "..." menu to the very top-left of the screen and move several icons as text entries within it.
  - [x] Help
  - [x] Share
  - [x] Downloads
- [x] Put the logo on the top-left of the screen, to the right of the "..." menu.
- [x] Add the "Submit" button to the top-right of the screen.
  - [x] Add the button itself.
  - [x] Revise the task list component to be shown as a short summary in the submit popover.
- [x] Revise the toolbar to only contain the "Add entity" and "Add interaction" buttons.  Revise their icons to a circle and an angled line, respectively.
- [x] Add the button-group form-network switcher underneath the title.

When all of the above are complete:

- [ ] Port to form UI.
- [x] Port to publisher portal.

Mockup reference:

![factoid-123-re-bar page 1](https://user-images.githubusercontent.com/989043/45393241-0f1f6500-b5f9-11e8-91bf-0f1fcae5ab84.jpg)

![factoid-123-re-bar page 2](https://user-images.githubusercontent.com/989043/45393245-1181bf00-b5f9-11e8-85aa-3470d4b2966c.jpg)

![factoid-123-re-bar page 3](https://user-images.githubusercontent.com/989043/45393249-15addc80-b5f9-11e8-84f1-0085e47077cb.jpg)

![factoid-123-re-bar page 4](https://user-images.githubusercontent.com/989043/45393253-18103680-b5f9-11e8-8246-b47cdf3b2ffb.jpg)

![factoid-123-re-bar page 5](https://user-images.githubusercontent.com/989043/45393256-1b0b2700-b5f9-11e8-82c0-f9a2bf33092f.jpg)

**Comment by maxkfranz** [comment]
Preview of latest changes:

![screen shot 2018-09-11 at 7 31 16 pm](https://user-images.githubusercontent.com/989043/45393299-4ee64c80-b5f9-11e8-934e-67ea306dd209.png)

![screen shot 2018-09-11 at 7 31 29 pm](https://user-images.githubusercontent.com/989043/45393306-53ab0080-b5f9-11e8-9b56-ee7f8540d9d9.png)

**Comment by d2fong** [comment]
Okay I will work on the submit button
