### ISSUE TITLE
Distinguish between 'binding' and 'activation/inhibition' in model?

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#366]
Binding and activation/inhibition seem distinct. They are nonetheless a single category in the network editor, but distinct in the form. I believe the  model groups these as a single type, but it doesn't appear to me that edge direction is captured, which is fine for binding but not activation/inhibition.

**Comment by jvwong** [comment]
Limitation of the form itself possibly.

**Comment by sacdallago** [comment]
Limitation of the BioPAX format. Potentially: offer broader conversion.

**Comment by maxkfranz** [comment]
'Binding, activation, or inhibition' is the catch-all type that is analogous to the generic top-level interaction type in biopax.  The issue is getting the user to click the right type entry, which is why we had the catch-all entry in the first place.

**Comment by jvwong** [comment]
related to #348

**Comment by jvwong** [comment]
Apologies -  there is indeed a distinction in the Factoid data model between 'binding' and 'activation and inhibition'. However, this 'general' interaction type's `toBiopaxTemplate()` attribute dispenses with ideas of control type in preparing for export as MolecularInteraction.

Closing and opening more specific issue.
