### ISSUE TITLE
Handling mentions of the same interaction between a pair of nodes 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#367]
Background: In a longer text (e.g. full-text article), there are often several variations  of the same interaction mentioned. This is likely to be the norm rather than the exception.

Issue: In the network, was not clear initially that there were multiple edges between a pair of nodes. Moreover, I could not view/delete them individually. My workaround was to delete everything or go the form and access them individually.

This is related to another issue: Does the Factoid model store original REACH text/offset for the interaction? If so, then it is meaningful which interactions I delete or leave.    

---

Example: See Google Drive `/Factoid/Testing/Full_text_articles/wong_mcell_v41_2011_MAIN.txt` and resulting [document](http://unstable.factoid.baderlab.org/document/54052800-3d73-43bc-9f2e-b1cd88935c46/73aca69c-9f12-45af-8fb5-ea9ef0b12c98). In this case there are 10 instances of a MYC and E2F1 interaction.

![image](https://user-images.githubusercontent.com/4706307/45955531-2dfcfe80-bfde-11e8-94a7-8eb24a937a11.png)

**Comment by gbader** [comment]
Ideally the form would nicely organize these. I.e. group or collapse
similar and identical statements and show the original sentences for each.

**Comment by jvwong** [comment]
I have a PR (#450) for a post-REACH interaction filter. Tested by running full-text from a sample of Molecular Cell 'case studies' through Factoid either without filter (figures, left) or with filter (middle). Also included the hand-crafted document (right).  

---

```Clarke et al. PRMT5-Dependent Methylation of the TIP60 Coactivator RUVBL1 Is a Key Regulator of Homologous Recombination. Mol. Cell. Volume 65, Issue 5, 2 March 2017, Pages 900-916```

![clarke_topInteractions](https://user-images.githubusercontent.com/4706307/55745167-9d7b8e00-5a04-11e9-9bac-f5481f83f9b9.png)

---

``` He et al. mTORC1 Promotes Metabolic Reprogramming by the Suppression of GSK3-Dependent Foxk1 Phosphorylation. Mol. Cell. Volume 70, Issue 5, 7 June 2018, Pages 949-960 ```

![he_topInteractions](https://user-images.githubusercontent.com/4706307/55745178-a53b3280-5a04-11e9-8c49-207fa790e8bd.png)


---

```Jeong et al. A Constitutive Intrinsic Inflammatory Signaling Circuit Composed of miR-196b, Meis2, PPP3CC, and p65 Drives Prostate Cancer Castration Resistance. Mol. Cell. VOLUME 65, ISSUE 1, P154-167, JANUARY 05, 2017```

![jeong_topInteractions](https://user-images.githubusercontent.com/4706307/55745191-aa987d00-5a04-11e9-9a1c-fa5476aecb96.png)


---

```Jin et al. The PLAG1-GDH1 Axis Promotes Anoikis Resistance and Tumor Metastasis through CamKK2-AMPK Signaling in LKB1-Deficient Lung Cancer. Mol. Cell. Volume 69, Issue 1, 4 January 2018, Pages 87-99.e7```

![jin_topInteractions](https://user-images.githubusercontent.com/4706307/55744890-01ea1d80-5a04-11e9-938e-ba4a54b36897.png)

---

```Qian et al. Phosphoglycerate Kinase 1 Phosphorylates Beclin1 to Induce Autophagy. Mol. Cell. VOLUME 65, ISSUE 5, P917-931.E6, MARCH 02, 2017 ```

![qian_topInteractions](https://user-images.githubusercontent.com/4706307/55745053-64dbb480-5a04-11e9-96d5-5dbdf610af7c.png)


---

```Willemsen et al. Phosphorylation-Dependent Feedback Inhibition of RIG-I by DAPK1 Identified by Kinome-wide siRNA Screening. Mol. Cell. Volume 65, Issue 3, pp403-415. 8 February 02, 2017```

![willemsen_topInteractions](https://user-images.githubusercontent.com/4706307/55745307-f0554580-5a04-11e9-87ed-3270f406bad6.png)

---

```Yang et al. Reciprocal Regulation of HIF-1α and LincRNA-p21 Modulates the Warburg Effect. Mol. Cell. Volume 53, Issue 1, 9 January 2014, Pages 88-100```

![yang_topInteractions](https://user-images.githubusercontent.com/4706307/55745414-285c8880-5a05-11e9-9c34-918c9e9c10f2.png)

---
