### ISSUE TITLE
Help tour for the form editor

### ISSUE THREAD

**Issue by fdurupinar** [PathwayCommons/factoid#368]
## Description

**Q: What is the name of the feature?**

A: Help tour for the form editor

**Q: What does this feature enable the user to do?**

A: This feature gives the user an overview of how to use the form editor

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: The tour can't take up much of the user's time.  It should take under a minute.

### Mockup

*Phase 1 :  Welcome to Factoid* This is the same for all the use cases. 

---

![paper journal 1](https://user-images.githubusercontent.com/13474166/46097377-9b439780-c176-11e8-8971-2b44fcc02e0b.png)

*Phase 2 : Adding interactions*

---

![paper journal 2](https://user-images.githubusercontent.com/13474166/46097299-69323580-c176-11e8-90dd-b9900e115a8f.png)

*Phase 3 : Adding entities*

---

![paper journal 3](https://user-images.githubusercontent.com/13474166/46097315-75b68e00-c176-11e8-8bab-34e7a3c33854.png)
*Phase 4 : Deleting an interaction*

---

![paper journal 4](https://user-images.githubusercontent.com/13474166/46097324-7cdd9c00-c176-11e8-93cd-63e3b4128403.png)

*Phase 5 : Submiting

*

### Details

Phases:
- (1) Welcome to Factoid
Same as in https://github.com/PathwayCommons/factoid/issues/365#issue-361895260
- (2) Adding interactions
  - Animation steps:
    - (1) An interaction is a relationship, e.g. phosphorylation, between two entities.   To add one, start by clicking the add interaction button.
    - (2) Interaction dropdown list is shown.
    - (3) Select an interaction type. 
    - (4) Now select the details of your interaction.
    - (5) Is your interaction activating or inhibiting? 
    - (6) You selected an activating interaction.
    - (7) Select the type of this interaction. 
    - (8) You selected a phosphorylation reaction.
    - (9) You're done adding the interaction details. You created a phosphorylation activation relation. 
  - Summary:  An interaction is a relationship, e.g. phosphorylation, between two entities.   To add an interaction click the add interaction button, then select its details.
- (3) Adding interacting entities
  - Animation steps:
    - (1) An entity is a physical thing, such as a protein or chemical. To specify the first entity, start by selecting the first text box.
    - (2) Write the entity name.
    - (3) Select the best match for your entity.
    - (4) This is the information for your entity.
    - (5) You've added the first entity of this interaction.
    - (6-9) Repeat these steps for your second entity in the interaction.
  - Summary: An entity is a physical thing, such as a protein or chemical. To add an interacting entity  click on the corresponding text box and select the best match. Repeat this for all the entities in your interaction.
- (4) Deleting an interaction
 - Animation steps
   - (1)  If you are not satisfied with the interaction that you created and you want to delete it, click on the trash can icon on the top right corner of that interaction.
   - (2) Your interaction is deleted.
- Summary: If you want to delete the interaction that you created select the trash can icon on the top right corner of that interaction.
- (5) Submitting
  - Animation steps: 
    - (1) Review to ensure all entities and interactions are correct.  You can amend an entity or an interaction by clicking the pencil icon.
    - (2) Click submit when you're done.  Once you've confirmed your submission, it will be sent so that it can be distributed by your publisher.
  - Summary: Review your figure to ensure that all entities and interactions are correct.  When you're satisfied with the result, click the submit button and confirm.

**Comment by jvwong** [comment]
Could remove 'deletion' (4) as it is obvious to me.

**Comment by fdurupinar** [comment]
> Could remove 'deletion' (4) as it is obvious to me.

I agree; it also breaks the flow. Put it there just in case.

**Comment by maxkfranz** [comment]
Superseded by the video
