### ISSUE TITLE
config values are always the default values when requiring them from client code

### ISSUE THREAD

**Issue by d2fong** [PathwayCommons/factoid#370]
Steps to reproduce:

1. set the UNIPROT_LINK_BASE_URL in the env
```export UNIPROT_LINK_BASE_URL="http://blah.com"```
2. run the server
```npm run watch```
3. require the config in any client side file  e.g. src/client/components/element-assoc-display.js
4. console.log the values UNIPROT_LINK_BASE_URL
5.  Expect the value to be "http://blah.com/"
6.  Actual value logged is the default value:  "http://www.uniprot.org/uniprot/"

Expected behaviour:
I should be able to access the config value "http://blah.com" in any client file

**Comment by d2fong** [comment]
This also happens in appui's config as the two are similar.

**Comment by maxkfranz** [comment]
Ref 9ab4106a6e1f42758877f6899393c5ff4bd2dce9
