### ISSUE TITLE
Unstable branch: editor UIs appear 'broken' in Safari  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#377]
Branch: unstable
Safari: Version 11.0.1 (11604.3.5.1.1)

network:
![image](https://user-images.githubusercontent.com/4706307/47113736-c7a77c80-d227-11e8-9ccd-89e0bc401659.png)

form:
![image](https://user-images.githubusercontent.com/4706307/47113772-e1e15a80-d227-11e8-9b05-00bad9018daa.png)

To reproduce, start from http://unstable.factoid.baderlab.org and 'try factoid' without text.

**Comment by maxkfranz** [comment]
The woff2 icons should work on Safari or newer.

**Comment by jvwong** [comment]
Fine for Mojave, Safari v12.0.1.
