### ISSUE TITLE
Seed page should still exist for demo purposes

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#378]
## Description

This page:
![screen shot 2018-10-31 at 12 32 32 pm](https://user-images.githubusercontent.com/6240943/47803541-1f0a1a00-dd09-11e8-8bd8-c566407f87df.png)

Has now been substituted by:
![screen shot 2018-10-31 at 12 32 43 pm](https://user-images.githubusercontent.com/6240943/47803576-2fba9000-dd09-11e8-9006-665f98a4d184.png)

It's good to have the second page (as an idea for publishers etc.), but it **should not** substitute the other input system, aka. the first screenshot. For demo purposes, that page is fundamental! This way we are loosing the ability to show the highlight of text **and** the choice of the editors in an easy way.

**Comment by d2fong** [comment]
http://factoid.baderlab.org/debug/new-document/seed

**Comment by jvwong** [comment]
What is the problem here? Better route names?

**Comment by sacdallago** [comment]
Currently, in the new proposed version, we are missing a **workflow** that allows the following:

- Enter text
- Show that we have a system that performs NLP on that text and that some things **may** get extracted from that text
- Show that we have two, equally important editors to modify what is extracted from NLP
- Proceed to one of the editors

The above is possible by stitching together bits and pieces of what is currently on unstable.factoid.baderlab.org , but even with all of the design discussions that we have had previously, should they all be integrated, this specific workflow cannot be satisfied. This workflow is used by Chris S. and myself for demoing purposes and we have received positive feedback last Wednesday about its potential use to explain the concepts behind factoid for external stakeholders.

I understand that while the discussion in the past was "the choice of editor will be proposed in the email" and "users can toggle editor through a button in the UI of any of the two editors", the _demo_able one page editor choice has a huge advantage as it enables demoers to stop for one minute and explain why two editors exists, why we think it's important to have both, what's the conceptual difference between the two. Other approaches have the demoer go into an editor, which, by experience, overloads the current viewer with information and distracts the viewers with content (network/form editor) that will be touched upon in what the aforementioned workflow enables to do at a later step of the demo.

In a previous iteration of the system, which is the one currently living on factoid.barderlab.org, we had this workflow possibility.

Thus, my proposal is:

1. Create a simple, _reachable_ page, as in the first screenshot [here](https://github.com/PathwayCommons/factoid/issues/378#issue-376054875) that enables to input text and highlight reach output.
2. Make it such that the nomenclature isn't "debug" or anything of the sort
3. Add a disclaimer on the text input page stating something like _"Additionally to extracting annotations from text, Factoid tries to resolve naming conflicts from the extracted information. This means that the extracted pathway that you will be presented in the next screens could contain less information than what get's highlighted if you press the "Highlight Entities and Interactions" button."_
4. Change the _"Submit"_ button text to _"Next"_, and go to the editor selection page (formally /new/choice/...) 

The solution proposed by @d2fong doesn't satisfy the above requirements, and it introduces the concept of "public" vs "private" links, which I don't think is a relevant piece to explain the system vs. say the text highlight and the choice editor.

I recall in the previous call on Thursday @maxkfranz proposed to have the highlight in the pop-up of the "try factoid" button on the landing page. While I see that this could resolve points 1, 2 and 4, it doesn't enable us to notify the users using this workflow about what is discussed in point 3, which is also something that as @maxkfranz discussed is important to disclaim.

Thus, again, I argue that this be a separate page as above (1-4).

**Comment by jvwong** [comment]
Other than point 3 
> Add a disclaimer on the text input page stating something...."

I believe this is addressed in #398.
