### ISSUE TITLE
REACH text markup: Shifted bolded text and highlighted text 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#380]
Seems that the trigger word bolding and entity highlighting can be shifted in some cases.

---

Reproduce with abstract for [Liu et al. Nature volume 563, pages 131–136 (2018) ](https://www.nature.com/articles/s41586-018-0629-6)

Upload to [http://factoid.baderlab.org/new/seed](http://factoid.baderlab.org/new/seed) and click 'Highlight Entities and Interactions'. Note 5th sentence 'DNA damage induces nuclear translocation of cGAS...' compared to REACH out.

```text
Accurate repair of DNA double-stranded breaks by homologous recombination preserves genome integrity and inhibits tumorigenesis. Cyclic GMP–AMP synthase (cGAS) is a cytosolic DNA sensor that activates innate immunity by initiating the STING–IRF3–type I IFN signalling cascade. Recognition of ruptured micronuclei by cGAS links genome instability to the innate immune response, but the potential involvement of cGAS in DNA repair remains unknown. Here we demonstrate that cGAS inhibits homologous recombination in mouse and human models. DNA damage induces nuclear translocation of cGAS in a manner that is dependent on importin-α, and the phosphorylation of cGAS at tyrosine 215—mediated by B-lymphoid tyrosine kinase—facilitates the cytosolic retention of cGAS. In the nucleus, cGAS is recruited to double-stranded breaks and interacts with PARP1 via poly(ADP-ribose). The cGAS–PARP1 interaction impedes the formation of the PARP1–Timeless complex, and thereby suppresses homologous recombination. We show that knockdown of cGAS suppresses DNA damage and inhibits tumour growth both in vitro and in vivo. We conclude that nuclear cGAS suppresses homologous-recombination-mediated repair and promotes tumour growth, and that cGAS therefore represents a potential target for cancer prevention and therapy.
```

![image](https://user-images.githubusercontent.com/4706307/48085128-70158480-e1c7-11e8-84bb-198d426b3a58.png)

**Comment by jvwong** [comment]
Narrowed this bug to discord between REACH JSON `text` and original text. In particular, REACH frame `offset` reports the character offset in a modified text version where certain (UTF-8?) characters are swapped out with a (ASCII-based?) name.

Consider the phrase 'Importin-α phosphorylates cGAS.' The REACH JSON has `"verbose-text": "Importin-alpha phosphorylates cGAS." and reports the trigger work offset as 15.

**Comment by metincansiper** [comment]
Created PR #403 to solve this issue.
