### ISSUE TITLE
What does it mean?

### ISSUE THREAD

**Issue by IgorRodchenkov** [PathwayCommons/factoid#383]
https://github.com/PathwayCommons/factoid/blob/13d94464acbb5790466d23c421efbfb902a3b50f/src/model/element/element-type.js#L2
?
@d2fong @maxkfranz

**Comment by maxkfranz** [comment]
It's just the string values that are stored in the DB for each of the interaction types.

E.g. `INTERACTION_TYPE_VALS[INTERACTION_TYPE.BINDING] === 'binding'`

It's convenient if you want a map-like object to get the string values.  However, this is not strictly necessary as you could alternatively read `INTERACTION_TYPE.BINDING.value`.

**Comment by IgorRodchenkov** [comment]
Thanks @maxkfranz. Is this normal that the "const" is defined this way (using ':' in  INTERACTION_TYPE_VALS: INTERACTION_TYPE) and also never used in the file nor exported?
I see only INTERACTION_TYPE is used in the element-type.js, and guessed the line #2 is unnecessary, no?

**Comment by maxkfranz** [comment]
It was probably used at some point and never removed.  We can just delete it -- as I mentioned, it's a bit redundant anyway.

**Comment by IgorRodchenkov** [comment]
Why not simply:
`const {INTERACTION_TYPE} = require('./interaction-type/enum');`
?

**Comment by sacdallago** [comment]
Can be closed?
