### ISSUE TITLE
REACH to factoid mapping

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#388]
Reminder:

@jvwong put together a gdoc on REACH output.

**TODO:**

- [ ] Identify entities that can exist in factoid (green highlight: can be converted, orange highlight: may be converted)
- [ ] Create logic to pour REACH output into factoid model

**Comment by d2fong** [comment]
REACH to factoid notes
Intersection of Reach `simple events` and the interaction types supported by Factoid:
- phosphorylation
- dephosphorylation
- ubiquitination
- deubiquitination
- methylation
- demethylation
- transcription

## Google searches used to find test input:
- "* phosphorylates *", - "* methylates *", 
  - (CDK16 Phosphorylates and Degrades p53)[http://www.thno.org/v08p0650]
  - (EGFR phosphorylates FAM129B to promote Ras activation)[www.pnas.org/content/113/3/644]
  - (CARM1 Methylates GAPDH to Regulate Glucose)[https://www.cell.com/cell-reports/pdf/S2211-1247(18)31370-6.pdf]
 

## Findings
- while the REACH paper may say that phosphorylation, ubiquitination, and methylation may appear in simple events, my initial testing on our version of REACH ( which is not the latest ) leads me to believe that these interaction types appear as `nestedEvents` instead of `simpleEvents`.  

Possible reasons that the information in the paper differs from initial testing results:
- we are using an older version of REACH 
- we are using a different `grounding` from what the paper considers a `nestedEvent` and `simpleEvent`.  i.e. what we consider a `nestedEvent` is not what the paper considers is a `nestedEvent`

**Comment by IgorRodchenkov** [comment]
Note: Factoid model currently only supports bio events for which there is a controller defined, except for binding (molecular interaction) and "other" undirected interaction type. It does not support e.g. transcription, transport, biochemical reaction alone, without a control entity, such as catalysys, modulation or transcription reaction regulation also defined. But REACH produces all sorst of events, often not even properly associating them  (I bet we cannot reliably link e.g., a transcription factor to protein expressed/activated, or a controller protein to the other one it affects via phosphorylation)

**Comment by johnbachman** [comment]
@IgorRodchenkov Not sure exactly what you mean by this. REACH does extract events with their controllers from text. For example:

```
In [1]: from indra.sources import reach

In [2]: rp = reach.process_text('BRAF activation leads to the phosphorylation of MAPK1.')

In [3]: rp.statements
Out[3]: [Phosphorylation(BRAF(), MAPK1())]

In [4]: rp = reach.process_text('JUN activation leads to the expression of DUSP4.')

In [5]: rp.statements
Out[5]: [IncreaseAmount(JUN(), DUSP4())]
```

The INDRA Statements are derived from the REACH JSON output.

**Comment by IgorRodchenkov** [comment]
@johnbachman 
That's why we'd like once again to compare and test using INDRA vs. REACH (we service) for our model. I personally haven't done this before. And my previous comment was more for our team and about current Factoid data model, where we have not used so called REACH "simple events" yet (as I understand), e.g, a metabolic reaction, or protein activation/inactivation fact, gene expression (regardless TFs), etc.

We believe INDRA might do something smart on top of REACH output to get those statements. We also had examples where it was hard to combine REACH results and accurately infer controller and controlled interaction and all participant states.

By the way, how does `Out[5]: [IncreaseAmount(JUN(), DUSP4())]` statement suggest that it was about a template reaction regulation, and that JUN was activated?..

**Comment by johnbachman** [comment]
Hi @IgorRodchenkov , got it! INDRA is not doing anything fancy here--its using only information in the REACH output. For example, here is the `events` section of the REACH output for the sentence "BRAF activation leads to the phosphorylation of MAPK1":

```
  "events":{
    "frames":[
      {
        "frame-id":"evem-api2667-UAZ-r1-Reach-0-6510",
        "text":"phosphorylation of MAPK1",
        "arguments":[
          {
            "text":"MAPK1",
            "argument-type":"entity",
            "type":"theme",
            "object-type":"argument",
            "index":0,
            "arg":"ment-api2667-UAZ-r1-Reach-0-39661"
          }
        ],
        "type":"protein-modification",
        "frame-type":"event-mention",
        "subtype":"phosphorylation",
        "is-direct":false,
        "end-pos":{
          "reference":"pass-api2667-UAZ-r1-Reach",
          "offset":53,
          "object-type":"relative-pos"
        },
        "trigger":"phosphorylation",
        "object-type":"frame",
        "start-pos":{
          "reference":"pass-api2667-UAZ-r1-Reach",
          "offset":29,
          "object-type":"relative-pos"
        },
        "sentence":"sent-api2667-UAZ-r1-Reach-0",
        "found-by":"Phosphorylation_syntax_1a_noun",
        "verbose-text":"BRAF activation leads to the phosphorylation of MAPK1."
      },
      {
        "frame-id":"evem-api2667-UAZ-r1-Reach-0-6509",
        "text":"BRAF activation leads to the phosphorylation of MAPK1",
        "arguments":[
          {
            "text":"phosphorylation of MAPK1",
            "argument-type":"event",
            "type":"controlled",
            "object-type":"argument",
            "index":0,
            "arg":"evem-api2667-UAZ-r1-Reach-0-6510"
          },
          {
            "text":"BRAF",
            "argument-type":"entity",
            "type":"controller",
            "object-type":"argument",
            "index":0,
            "arg":"ment-api2667-UAZ-r1-Reach-0-39662"
          }
        ],
        "type":"regulation",
        "frame-type":"event-mention",
        "subtype":"positive-regulation",
        "is-direct":false,
        "end-pos":{
          "reference":"pass-api2667-UAZ-r1-Reach",
          "offset":53,
          "object-type":"relative-pos"
        },
        "trigger":"leads",
        "object-type":"frame",
        "start-pos":{
          "reference":"pass-api2667-UAZ-r1-Reach",
          "offset":0,
          "object-type":"relative-pos"
        },
        "sentence":"sent-api2667-UAZ-r1-Reach-0",
        "found-by":"Positive_regulation_syntax_7_verb",
        "verbose-text":"BRAF activation leads to the phosphorylation of MAPK1."
      }
    ],
```

As you can see, there are two events, one is the "phosphorylation of MAPK1", which has MAPK1 as the "theme" (object) but no controller, and the other is the `positive-regulation` event which has BRAF as the controller and the first event (phosphorylation of MAPK1) as the `controlled`. REACH generally links controllers to events by nesting events in this way.

For the second("JUN activation leads to  the expression of DUSP4"), those are good questions.
The REACH output again contains two nested events:

```  "events":{
    "frames":[
      {
        "frame-id":"evem-api2668-UAZ-r1-Reach-0-6511",
        "text":"JUN activation leads to the expression of DUSP4",
        "arguments":[
          {
            "text":"expression of DUSP4",
            "argument-type":"event",
            "type":"controlled",
            "object-type":"argument",
            "index":0,
            "arg":"evem-api2668-UAZ-r1-Reach-0-6512"
          },
          {
            "text":"JUN",
            "argument-type":"entity",
            "type":"controller",
            "object-type":"argument",
            "index":0,
            "arg":"ment-api2668-UAZ-r1-Reach-0-39664"
          }
        ],
        "type":"regulation",
        "frame-type":"event-mention",
        "subtype":"positive-regulation",
        "is-direct":false,
        "end-pos":{
          "reference":"pass-api2668-UAZ-r1-Reach",
          "offset":47,
          "object-type":"relative-pos"
        },
        "trigger":"leads",
        "object-type":"frame",
        "start-pos":{
          "reference":"pass-api2668-UAZ-r1-Reach",
          "offset":0,
          "object-type":"relative-pos"
        },
        "sentence":"sent-api2668-UAZ-r1-Reach-0",
        "found-by":"Positive_regulation_syntax_7_verb",
        "verbose-text":"JUN activation leads to the expression of DUSP4."
      },
      {
        "frame-id":"evem-api2668-UAZ-r1-Reach-0-6512",
        "text":"expression of DUSP4",
        "arguments":[
          {
            "text":"DUSP4",
            "argument-type":"entity",
            "type":"theme",
            "object-type":"argument",
            "index":0,
            "arg":"ment-api2668-UAZ-r1-Reach-0-39663"
          }
        ],
        "type":"transcription",
        "frame-type":"event-mention",
        "subtype":"transcription",
        "is-direct":false,
        "end-pos":{
          "reference":"pass-api2668-UAZ-r1-Reach",
          "offset":47,
          "object-type":"relative-pos"
        },
        "trigger":"expression",
        "object-type":"frame",
        "start-pos":{
          "reference":"pass-api2668-UAZ-r1-Reach",
          "offset":28,
          "object-type":"relative-pos"
        },
        "sentence":"sent-api2668-UAZ-r1-Reach-0",
        "found-by":"transcription_1b",
        "verbose-text":"JUN activation leads to the expression of DUSP4."
      }
    ],
    "object-type":"frame-collection",
    "object-meta":{
      "processing-end":"2018-11-28T11:10:25Z",
      "doc-id":"api2668",
      "component-type":"machine",
      "component":"Reach",
      "processing-start":"2018-11-28T11:10:25Z",
      "object-type":"meta-info",
      "organization":"UAZ"
    }
  },
```

The output contains an event of type "transcription" with DUSP4 as the controller. The fact that this reaction is typed as "transcription" would indicate that it is a template reaction. INDRA currently converts these to `IncreaseAmount` events, which in this form don't specifically identify transcriptional events (however, we could update the REACH processor to do so).

For your second question, REACH doesn't capture "JUN activation" as an event, nor does it capture "activity" as a necessary state of JUN, so this doesn't get propagated into the INDRA Statement. However, in modeling applications in INDRA, we will sometimes require that all controllers need to be in an active state, and so an activity condition would be assumed.
