### ISSUE TITLE
Godfrey et al. Molecular Cell Volume 65, Issue 3, 2017, Pages 393-402

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#414]
# Approach 

1. Provide article information
2. Provide expected pathway 
3. Provide Factoid NLP-drafted document
4. Provide Factoid manually-created document
5. Issues
 
## 1. Article information
[Molecular Cell, Volume 65, Issue 3, 2 February 2017, Pages 393-402](https://www.cell.com/molecular-cell/fulltext/S1097-2765(16)30856-5)
PP2ACdc55 Phosphatase Imposes Ordered Cell-Cycle Phosphorylation by Opposing Threonine Phosphorylation
Molly Godfrey,Sandra A. Touati,Meghna Kataria,Andrew Jones,Ambrosius P. Snijders,Frank Uhlmann

![fx1](https://user-images.githubusercontent.com/4706307/51137057-f83d8900-180b-11e9-8f15-06727ffd98b8.jpg)

## 2. Expected pathway

![network_expected](https://user-images.githubusercontent.com/4706307/51139382-b4e61900-1811-11e9-8692-a724513acd01.png)

## 3. Factoid NLP-drafted document

![reach_draft](https://user-images.githubusercontent.com/4706307/51139371-aef03800-1811-11e9-98af-c35321b8eff7.png)

## 4. Factoid manually-created document
![network_jvw](https://user-images.githubusercontent.com/4706307/51140443-90d80700-1814-11e9-803b-2e0f90606e2e.png)

## 5. Issues

- Grounding search
  - Would have liked Factoid to be 'aware' of the organism - always seemed to bury yeast/other
  - Confusing that organism was 'other' not Saccharomyces cerevisiae (as in UniProt linkout)

![isse_swe1_search](https://user-images.githubusercontent.com/4706307/51140766-63d82400-1815-11e9-85a2-a054f1582c22.png)

- Entity types
  - Detailed molecular descriptions
    - Describing amino-acid motifs on groups of targets (Serine, Threonine) 
- Quantitative, temporal aspects
    - Describing longer or shorter times (cdc55 causes delayed phosphorylation of Net1 relative Ask1)

**Comment by cannin** [comment]
@jvwong As you go through this exercise of finding papers, is it possible to write a comment (maybe here or in another issue) of what why the REACH output was less than optimal? REACH is a rule-based system and we could tweak the rules, but the discussion last week wasn't enough. One could even imagine that as a potential student project. 

Cell Systems published 150 articles last year, I worry without REACH (or something like it) to filter articles right for our system, we are shifting the bottleneck of the curation work. 

Augustin Luna

**Comment by maxkfranz** [comment]
> Would have liked Factoid to be 'aware' of the organism - always seemed to bury yeast/other
> Confusing that organism was 'other' not Saccharomyces cerevisiae (as in UniProt linkout)

This is because Uniprot lists different variants of yeast as completely different organisms.  It doesn't provide information in its API to determine the "root" organism.
