### ISSUE TITLE
Node tooltip notification name refers to last node tooltip clicked

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#422]
Clicking on an ungrounded node displays tooltips in which notifications are displayed (top). When there are at least two ungrounded nodes ('?'), the string name refers to the last clicked node and not the current one.

Reproduce: Create two nodes with different names (e.g. X and Y) and proceed only as far as the grounding search. Click between the nodes and examine the name in the notification e.g. "Select the best match for 'X'" will appear for 'Y' and vice versa.

**Comment by maxkfranz** [comment]
TODO cherry-pick fix to master
