### ISSUE TITLE
Entity grounding: Does not recognize valid IDs (cached failures)  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#443]
Trying to ground an entity with name "TP53" led to a long wait then displayed tooltip warning "No identifiers could be found. Try going back and renaming "TP53" to a clearer name." Every subsequent identical search (even in a new browser) immediately responds with this warning.  

I  expect that this input to provide a decent list of search hits.

Maybe caching is too aggressive.

**Comment by sacdallago** [comment]
Oh wow... Is this because of request timeouts? If not caching, maybe we should limit the response of requests to a fixed number (e.g. 50). I doubt that a normal user would scroll through a lot of entities in the grounding wizard

**Comment by jvwong** [comment]
Superseded by #424.
