### ISSUE TITLE
Help tour video (Pilot, Phase II)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#444]
## Description

**Q: What is the name of the feature?**

A: Help 

**Q: What does this feature enable the user to do?**

A: Understand how to complete a document containing a single interaction 

**Q: What information must the user provide to use the feature?**

A: None.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Embed video or link to  hosted

**Q: How does this feature affect each class of user (persona)?**

A: In most cases, (biologists, editors), this will provide a basic, concrete answers to the questions "What does the Factoid app look like? What can I do when I'm in it? and How do I use it?".   

### Mockup

Please refer to (Google Drive "Factoid/Pilots/Cell")
  - "Factoid Help Script" proposed text
  - "How does Factoid work?" storyboard

### Details

This is a provisional feature focused on  Pilot Phase II @ Molecular Cell (#365 #368). To summarize, Phase II @ Molecular Cell entails a single author, invited via email, using the network editor and notified post-submission about the location of their data via email (read-only and NDex).

**Comment by sacdallago** [comment]
This needs decoupling, I think. It's a _complex_ task:

- [ ] Create a video script
- [ ] Record the video (use camtasia? Buy license!)
- [ ] Chose video hosting site (youtube?)
- [ ] Change behavior of help button in menu to link to video

**Comment by jvwong** [comment]
An early edit: https://www.youtube.com/watch?v=5qTcWopNf7k&feature=youtu.be
