### ISSUE TITLE
Fatal error attempting to add existing database 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#452]
Booting up the app when the rethinkdb database/tables don't already exist throws an error: `ReqlOpFailedError: Database `factoid` already exists in:
r.dbCreate("factoid")`. 

To reproduce this, clear out the 'factoid' database and start the app. Strangely, the error doesn't always appear - no idea. I  originally noticed this behaviour trying to couple the app and Rethinkdb in docker containers. 

- node v10.15.3
- unstable branch (58dfff0fda9ca8f039ea940945121e9ada613469)

**Comment by maxkfranz** [comment]
Yeah, it's a known issue.  A newer version of the rdb driver may help.
