### ISSUE TITLE
Modifications to 'publisher portal' form fields for new papers. 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#453]
This references the data provided at `/new` which collects information about the article to be entered. Updates are necessary to reflect the new information from journal editors and from using the system:

- Remove: `Publication year` 
  - Won't know this at acceptance
- Change: `Corresponding author name/email`
  - To `Contributing author name/email`
- Add: `Author list (comma separated)`
  - Researchers can be especially touchy about this and the order 
- Remove: `Figure legends`
  - We'll leave `Text` as the catch-all. Abstract is generally fine to use/mine/reproduce, not so for text...

**Comment by maxkfranz** [comment]
> We'll leave Text as the catch-all. Abstract is generally fine to use/mine/reproduce, not so for text...

If we're the only ones using this page for now, it's simpler to just have one box I suppose.

> Add: Author list (comma separated)

We should store all author names in the model.  In the UI, we should probably just show first and last and maybe show the full list on click in a popover.

**Comment by jvwong** [comment]
I've noticed the `sendEmail` has been throwing an errors locally and on unstable site. I'm disabling here since we don't want anything automated at this point.
