### ISSUE TITLE
Complex support

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#455]
## Description

**Q: What is the name of the feature?**

A: Complex entity support

**Q: What does this feature enable the user to do?**

A: Create a complex, containing multiple entities

**Q: What information must the user provide to use the feature?**

A: The set of entities, perhaps also a manual name of the complex

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: A complex must contain at least two entities.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: Expects to create a complex by dragging nodes together.  May want to give a complex with a colloquial term to match the paper's terminology.
- Editor: Expects to see a complex as some kind of compartment or box.  Visual style should look as much like a PDF figure as possible.
- Computational biologist: Expects to be able to access details of the constituent entities, e.g. protein ID.
- Curator: Same as above three.

### Mockup

The behaviour should be like this demo: https://cytoscape.org/cytoscape.js-compound-drag-and-drop/

The name, by default, should be automatic.  For a complex with entities A, B, and C, the name should be A:B:C.  We may want to allow for manual renaming of the complex later.

In terms of model, we should add a new `Complex` class.  Its behaviour should be almost identical to `Interaction` in that it's mostly just using an `EntitySet`.

### Details

- When dragging together two nodes, A and B, a complex should be created: A:B.
- When dragging A out of A:B, the complex should be removed from the document.
- A complex should have an automatic name, based on the names of the constituent entities joined by colon characters (`:`).

**Comment by maxkfranz** [comment]
@metincansiper Don't worry about the visual style for the complex nodes right now.  The default is fine for now.

**Comment by metincansiper** [comment]
I just realized the issue. Therefore, I think the part related to naming of complexes is missing in my initial changes. I will update the feature branch in that way. Actually I was already planning to ask about manual renaming etc. of complexes based on events. I initially treated them just like other elements but I suppose most maybe the all of the listeners [here](https://github.com/PathwayCommons/factoid/blob/complex-support/src/client/components/editor/cy/doc.js#L413) should not be binded for complexes. Is it correct?

**Comment by maxkfranz** [comment]
For now, it's OK.  It should be good enough as a first version and we can improve it later.  I'll do a more thorough review and let you know once I have feedback.

This one is a bit more important for the short-term: https://github.com/PathwayCommons/factoid/issues/454

**Comment by maxkfranz** [comment]
I merged in the current complex branch into unstable.  So now we just have to address the separate issues for tweaks to the UI.
