### ISSUE TITLE
Shortterm deployment strategy 

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#466]
- [x] Set up a production VM for the app in the Bader Lab cluster.
- [x] Set up a production VM for the grounding service in the Bader Lab cluster.
- [ ] Set up JSON export backups to Dropbox.
- [x] Set up monitoring for the production app server and the grounding service server.
  - [x] factoid.baderlab.org

**Comment by maxkfranz** [comment]
To be filled in more by @maxkfranz and @jvwong

**Comment by maxkfranz** [comment]
@gbader These items would be good for @IgorRodchenkov to address, if possible.  They can be started now.

**Comment by IgorRodchenkov** [comment]
@maxkfranz @jvwong @gbader 
Do you need my help with all the steps or just to configure the Nginx on the production PC VM (which handles *pahwaycommons.org and *biopax.org, pushes standard access logs to internal Kibana, etc.; while other services of the lab go via a different public IP and Apache proxy, which I don't not configure) and monitoring (e.g., UptimeRobot)?

Also, instead of adding new VMs, how about we move the existing 195th (aka PC "beta" - ton's of RAM and Storage, barely used, has docker already) into the production cluster and use that for all the Factoid containers (I suppose we are going to docker compose containers, right)?

**Comment by jvwong** [comment]
@IgorRodchenkov - I tested out the Docker-Compose on X.X.X.195 and it worked fine. 

Notes:
  - Noticed that the rethinkdb container doesn't work with the Factoid app when stopped then restarted: Must remove and create new 
  - Ubuntu 16.04 needed a [minor tweak for elasticsearch container](https://github.com/docker-library/elasticsearch/issues/111#issuecomment-268511769)
  - compose service `indexer` which indexes elasticsearch, only needs to be run once, and it took ~2 hours

**Comment by jvwong** [comment]
I don't think anyone should be able to access the document creation route. Not sure if this should be handled upstream of the app.

**Comment by maxkfranz** [comment]
> I don't think anyone should be able to access the document creation route. Not sure if this should be handled upstream of the app.

That's more of an issue of not handing out the link of the route to everybody and his uncle.

**Comment by IgorRodchenkov** [comment]
I noticed that "view in pathway commons" link does not work after submitting a factoid (a.f.a.i. remember it's probably a config option, about which factoid instance the apps.pathwaycommons.org or appsbeta was configured to use to get the doc by id...)

**Comment by jvwong** [comment]
We don't use that feature in the production system. Also, I noticed before that there's a missing trailing slash in the cmd line FACTOID_URL env variable ...

**Comment by jvwong** [comment]
Fixed - i updated the app-ui instance with the env variable `FACTOID_URL=http://master.factoid.baderlab.org/`. E.g. output https://apps.pathwaycommons.org/factoids/0d8b5fce-5412-474a-8f92-87cc44e2dcc6

**Comment by maxkfranz** [comment]
Updated list of things to be tracked by stats.baderlab.org

> factoid.baderlab.org
> grounding.baderlab.org
> master.factoid.baderlab.org
> unstable.factoid.baderlab.org

**Comment by maxkfranz** [comment]
@IgorRodchenkov We've updated the list of items.  There is only monitoring and backups to sort out now.

**Comment by jvwong** [comment]
Short term back-up strategy:
  - Add cron job to dump rethinkdb factoid database 
    - Use `docker/dump_rethinkdb.sh` 
    - Get Jeff L to backup just this directory

**Comment by jvwong** [comment]
Add to the todo list: A GitHub remote for the pathwaycommons/rethinkdb:2.3.6 image. This is necessary because of the additional dependencies we require, e.g python client for database dumps, restore, etc.

**Comment by jvwong** [comment]
Added remote https://github.com/PathwayCommons/rethinkdb-docker. This is linked to a DockerHub remote of the same name https://hub.docker.com/repository/docker/pathwaycommons/rethinkdb-docker/. 
  - Testing in progress.
  - If satisfied, update `docker-compose.yml`, `.env` and [documentation](https://github.com/BaderLab/sysadmin/blob/master/websites/factoid.md)

**Comment by jvwong** [comment]
Remaining TODOs, when ready:

  - Tag and release
    - [ ] [factoid](https://github.com/PathwayCommons/factoid)
    - [ ] [grounding-search](https://github.com/PathwayCommons/grounding-search)
    - [ ] [rethinkdb-docker](https://github.com/PathwayCommons/rethinkdb-docker)
  -   [ ] Update docs with [environment variables](https://github.com/BaderLab/sysadmin/blob/master/websites/factoid.md)
  - [ ] Reboot production server with updated Docker images
  - [ ] Activate/uncomment cron job for rethinkdb dump

**Comment by jvwong** [comment]
@maxkfranz - I can't figure out how to Tweet to the @biofactoid account. The prod still ends up posting to the [test account](https://twitter.com/TestAcc87711534)

**Comment by maxkfranz** [comment]
@jvwong 

You need to use a different twitter key for the prod account.  A twitter API key is tied to a particular account.  The key for the test account won't work for prod.

**Comment by jvwong** [comment]
For backup details, pls refer to crontab and `/etc/crontab` on machine.
