### ISSUE TITLE
Interaction: 'Edit from the beginning' button does nothing 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#474]
An existing interaction provides a tooltip button to 'Edit from the beginning' (ie pencil). Clicking this does nothing, when it should allow user to  modify details.

To reproduce, view tooltip for any interaction and click pencil e.g.  http://unstable.factoid.baderlab.org/document/52c90fa4-7c07-40d5-83fd-d8da615d6be8/f927feec-b285-44b4-aab7-d22afc46ff04

**Comment by maxkfranz** [comment]
Ref : Remove back button on interaction wizard #456
