### ISSUE TITLE
Disable grounding service caching of results

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#479]
The new service is fast so we don't need the extra complexity

**Comment by metincansiper** [comment]
@maxkfranz is this to be done now or after the old service is completely replaced by the new one?

**Comment by metincansiper** [comment]
> @maxkfranz is this to be done now or after the old service is completely replaced by the new one?

Actually, I can disable the caching only for the interface of new service. Therefore, I can do it now.
