### ISSUE TITLE
Entity name with plus '+' character terminates grounding wizard  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#491]
Attempting to input a term containing '+' character in the node 'Entity Name' field terminates the grounding and closes the wizard.

The expected behaviour is to provide a list of matching records from each database supported.

Reproduce:
- Add entity
- Input `Ca2+` and hit enter.

**Comment by maxkfranz** [comment]
This is reproducible on the old service, the new service, or both?

**Comment by jvwong** [comment]
New service, with config var `USE_PC_GROUNDING_SEARCH=true`
