### ISSUE TITLE
Grounding to E. Coli K12 strain: Organism reports as 'other' 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#496]
![image](https://user-images.githubusercontent.com/4706307/59209039-69ddf100-8b78-11e9-8cc8-51461b52a2b2.png)

**Comment by maxkfranz** [comment]
If a taxon ID isn't listed in `Organism`, then it will display as "Other".  We'd have to add all strains for all organisms in order to support this.  Eventually, we could just store whatever organism data the grounding service sends us.
