### ISSUE TITLE
Use grounding.baderlab.org for the default GROUNDING_SEARCH_BASE_URL

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#500]
Benefits

- Allows anyone to manually spin up an instance of Factoid and have it working out-of-the-box.  This is productive for development.
- Make deployment easier.
- In future, allow for running the Factoid server in a separate location compared to the grounding service.

Tasks

- [x] Update the app to point to `grounding.baderlab.org` for the grounding service by default.  @maxkfranz 
- [x] Create the `grounding.baderlab.org` subdomain  @gbader 
- [x] Update the (PC) NGINX config  @IgorRodchenkov 
- [x] Extend the SSL certificate  @IgorRodchenkov 
- [x] Update the UT DNS for `grounding.baderlab.org` @ Jeff Liu

**Comment by IgorRodchenkov** [comment]
@jvwong  @maxkfranz 
Is the grounding service running now (as part of the docker stack on 192..195 or on a separate host)? Which port there is exposed for us to configure Nginx proxy for grounding.baderlab.org? It's unclear (or rather no host port is there mapped in that grounding container according to https://github.com/PathwayCommons/factoid/blob/unstable/docker/docker-compose.yml)... 

Note that port 3000 is already used by the app-ui on that VM (appsbeta.pathwaycommons.org).

**Comment by jvwong** [comment]
@maxkfranz would it make more sense to point it at the CI server instance?

**Comment by maxkfranz** [comment]
For grounding.baderlab.org, I think it should point to the docker instance to be consistent with factoid.baderlab.org.

If we also want an address for the CI grounding server, we could have an additional address like master.grounding.baderlab.org.

**Comment by jvwong** [comment]
I opened 192..195:3011 to point to grounding service.

**Comment by IgorRodchenkov** [comment]
Wait.. why @maxkfranz 
> If we also want an address for the CI grounding server, we could have an additional address like master.grounding.baderlab.org.
For CI and dev, we probably do not need any public nor internal domains - just use IP:port. This (producing domains like crazy) becomes habit I am afraid :/

**Comment by maxkfranz** [comment]
We have developers working from different locations, so you either need a universal VPN that everyone can use or public addresses.  The latter is far simpler.

**Comment by IgorRodchenkov** [comment]
Looks we're done here :)
