### ISSUE TITLE
Ground a named node by default

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#504]
If the grounding service is of sufficient quality in getting the expected grounding as the first result, then the UI for grounding a node should be simplified:

(1) The node popover is opened.

(2) The text box and notification in the popover are the same as today.  The wizard arrows are removed.  The user enters the name in the text box, say "p53".

(3) The top grounding result is shown underneath the text box.  The user has the option to click a button to select a different grounding entry if the top result is wrong, e.g. "not this p53".  When the user clicks this button, a grounding can be chosen from a list.  

(4) The way that the alternate groundings are presented could be smart.  For example, if there are many p53 entries and the main difference between them is the organism, we could simplify the question of "Which p53 do you mean?" to "Which organism do you mean?"  If the main difference between the entries is type, then we could simplify the question of "Which ER do you mean?" to "Do you mean this ER protein or this ER chemical?" (two entries listed side by side).

In most cases, the user is finished at step (2).  This makes it so there is only one step for the user to ground a node, and it's the only step the users really want to do.  A user just wants to name a node and be done, and this feature allows him to do just that.

To start, (4) could just be a simple list.  Later it could be improved to be smarter.

**Comment by jvwong** [comment]
This is related to a grounding test analysis performed on July 8, 2019, the details of which were in an email to Sorger group:

![Fig 1  Grounding summary ](https://user-images.githubusercontent.com/4706307/63186001-5728e200-c029-11e9-9052-24296b665b82.png)

![Fig 2  Failures_ Rank in returned records ](https://user-images.githubusercontent.com/4706307/63186012-5b54ff80-c029-11e9-9b70-0e4748ff3768.png)

![Fig 3  'Absent' failures ](https://user-images.githubusercontent.com/4706307/63186014-5d1ec300-c029-11e9-96b8-27e4e9f0b8b9.png)

**Comment by jvwong** [comment]
See #550.
