### ISSUE TITLE
Context

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#506]
A case that is commonly encountered in molecular biology articles is the description of molecular entities with covalent modifications to one or more of their residues/monomers. The most common case involves addition (or removal) of a chemical group to an amino acid at one or more positions.  

The issue here is to provide support for annotating an entity with a modification site and moiety. 

Examples from Molecular Cell:
  - [Jin et al. Molecular Cell, Volume 69, Issue 1, 4 January 2018, Pages 87-99 ](https://github.com/PathwayCommons/factoid/issues/429)
  - [Yang et al. Molecular Cell, Volume 53, Issue 1, 9 January 2014, Pages 88-100](https://github.com/PathwayCommons/factoid/issues/448)
  - [Sang et al. Molecular Cell, Volume 72, Issue 1, 4 October 2018, Pages 71-83](https://github.com/PathwayCommons/factoid/issues/449)
  - [Balsa et al. Molecular Cell, Volume 74, June 6 2019, Pages 1-14 ](https://github.com/PathwayCommons/factoid/issues/487)
  - [Li et al. Molecular Cell, Volume 74, June 20 2019, Pages 1-15](https://github.com/PathwayCommons/factoid/issues/488)
  - [Wang et al. Molecular Cell, Volume 74, June 20 2019, Pages 1-14](https://github.com/PathwayCommons/factoid/issues/490)

**Comment by jvwong** [comment]
Doing another round of article screening, this is old news but:

- Processes
- Modifications (incl mutation context)
- Cell types, tissue types (cellular context)

**Comment by jvwong** [comment]
From the maunscript review:

> 2. The amount of information collected for an interaction (that is, after the drawing just the type of molecular event) is not enough to really utilize the power of this approach in other projects. In particular not having an option to add some kind of biological context and detection methods is a missed opportunity. Please consider introducing an optional box for the biological context, in particular to name the tissue/cell line or the condition (healthy, cancer, etc.). This could come very useful when there are conflicting entries (A activates B; A inhibits B). With the biological context it could be clear that both are correct, otherwise it would look like the same interactors but different signs for the interaction and no further information. As for the type of detection, integrating the Molecular Interactions Controlled Vocabulary (https://www.ebi.ac.uk/ols/ontologies/mi) and facilitating data entry with autocomplete functions would provide useful extra information without overly increasing the time it takes to make a submission. Please consider updating Biofactoid to include this functionality. Please also clarify what ontology (if any) is used for relationships in Biofactoid.

**Comment by jvwong** [comment]
On how to find the right placeholder text (#999):
  - Try out 10 or so different versions, using real pathways from Biofactoid
  - Ask people their opinion
    - Lab members
    - Authors whom I've corresponded with personally for the project.

**Comment by jvwong** [comment]
| Title                                                                                                                                                                                                                                                        | Context                                                | Concepts                                 | ID                                                                                                                                           |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------------ | ---------------------------------------- | -------------------------------------------------------------------------------------------------------------------------------------------- |
| SENP1-Sirt3 Signaling Controls Mitochondrial Protein Acetylation and Metabolism.                                                                                                                                                                             | fasting; obesity                                       | physiological condition; disease         | [https://biofactoid.org/document/5df17c41-acb7-4c42-a37b-fe323688bc64](https://biofactoid.org/document/5df17c41-acb7-4c42-a37b-fe323688bc64) |
| The Crohn's Disease Risk Factor IRGM Limits NLRP3 Inflammasome Activation by Impeding Its Assembly and by Mediating Its Selective Autophagy.                                                                                                                 | inflammation; Crohn's                                  | physiological condition; disease         | [https://biofactoid.org/document/8ba702d2-3a88-4d8a-b93f-b614a347c2c3](https://biofactoid.org/document/8ba702d2-3a88-4d8a-b93f-b614a347c2c3) |
| Dachshund Depletion Disrupts Mammary Gland Development and Diverts the Composition of the Mammary Gland Progenitor Pool.                                                                                                                                     | mammary gland                                          | tissue; organ; developmental process     | [https://biofactoid.org/document/1ce367ea-74ad-4404-bd16-74a0b5373941](https://biofactoid.org/document/1ce367ea-74ad-4404-bd16-74a0b5373941) |
| Srebf1 Controls Midbrain Dopaminergic Neurogenesis.                                                                                                                                                                                                          | midbrain dopaminergic neurogenesis                     | tissue; developmental process            | [https://biofactoid.org/document/0710aa98-dbdd-49e4-98a9-4babf9161b48](https://biofactoid.org/document/0710aa98-dbdd-49e4-98a9-4babf9161b48) |
| IL6/STAT3 Signaling Hijacks Estrogen Receptor α Enhancers to Drive Breast Cancer Metastasis.                                                                                                                                                                 | breast; cancer                                         | tissue; disease                          | [https://biofactoid.org/document/78b31344-0896-44f2-8db1-6a48268eef00](https://biofactoid.org/document/78b31344-0896-44f2-8db1-6a48268eef00) |
| p27 controls Ragulator and mTOR activity in amino acid-deprived cells to regulate the autophagy-lysosomal pathway and coordinate cell cycle and cell growth                                                                                                  | autophagy; starvation                                  | process; physiological condition         | [https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880](https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880) |
| Atrx Deletion in Neurons Leads to Sexually Dimorphic Dysregulation of miR-137 and Spatial Learning and Memory Deficits.                                                                                                                                      | neuron; memory; forebrain                              | cell type; tissue; physiological process | [https://biofactoid.org/document/a6b4351d-b474-49d9-bc3d-f044513d5a0c](https://biofactoid.org/document/a6b4351d-b474-49d9-bc3d-f044513d5a0c) |
| Regulation of UCP1 and Mitochondrial Metabolism in Brown Adipose Tissue by Reversible Succinylation.                                                                                                                                                         | Brown adipose tissue                                   | tissue                                   | [https://biofactoid.org/document/bd602c8d-3484-497b-a417-149e82d1363a](https://biofactoid.org/document/bd602c8d-3484-497b-a417-149e82d1363a) |
| Sen1 Is Recruited to Replication Forks via Ctf4 and Mrc1 and Promotes Genome Stability.                                                                                                                                                                      | fork progression; genome stability                     | cellular process                         | [https://biofactoid.org/document/78c48450-6316-4f6d-a1d2-5e6190483c03](https://biofactoid.org/document/78c48450-6316-4f6d-a1d2-5e6190483c03) |
| TGF-β-Induced Phosphorylation of Usp9X Stabilizes Ankyrin-G and Regulates Dendritic Spine Development and Maintenance.                                                                                                                                       | neurodevelopment; dendrite spine                       | developmental process; tissue            | [https://biofactoid.org/document/02efa85e-d414-448b-b780-b1475c9c17cb](https://biofactoid.org/document/02efa85e-d414-448b-b780-b1475c9c17cb) |
| NRBP1-Containing CRL2/CRL4A Regulates Amyloid β Production by Targeting BRI2 and BRI3 for Degradation.                                                                                                                                                       | Alzheimer's disease (AD)                               | disease                                  | [https://biofactoid.org/document/7d452a55-234e-47a7-aed2-33646f2a2e9d](https://biofactoid.org/document/7d452a55-234e-47a7-aed2-33646f2a2e9d) |
| The E3 Ubiquitin Ligase SYVN1 Ubiquitinates Atlastins to Remodel the Endoplasmic Reticulum Network.                                                                                                                                                          | ER; hereditary spastic paraplegia (HSP)                | disease; cell location                   | [https://biofactoid.org/document/fa887136-e0fd-4ec2-bff5-da16f6ba568d](https://biofactoid.org/document/fa887136-e0fd-4ec2-bff5-da16f6ba568d) |
| Phosphorylated RB Promotes Cancer Immunity by Inhibiting NF-κB Activation and PD-L1 Expression.                                                                                                                                                              | cancer immune evasion                                  | disease                                  | [https://biofactoid.org/document/10eb6d9d-c13f-496d-92b0-26a85806770b](https://biofactoid.org/document/10eb6d9d-c13f-496d-92b0-26a85806770b) |
| Noncanonical Modulation of the eIF2 Pathway Controls an Increase in Local Translation during Neural Wiring.                                                                                                                                                  | neuron; translation                                    | cell type; cellular process              | [https://biofactoid.org/document/41598c53-d698-48fc-a3bf-2633dafc1990](https://biofactoid.org/document/41598c53-d698-48fc-a3bf-2633dafc1990) |
| Helicase Subunit Cdc45 Targets the Checkpoint Kinase Rad53 to Both Replication Initiation and Elongation Complexes after Fork Stalling.                                                                                                                      | Meier-Gorlin syndrome; DNA checkpoint                  | disease; cellular process                | [https://biofactoid.org/document/8dff2666-0547-4cee-a498-80f39d1fc0e9](https://biofactoid.org/document/8dff2666-0547-4cee-a498-80f39d1fc0e9) |
| The Splicing Factor hnRNP M Is a Critical Regulator of Innate Immune Gene Expression in Macrophages.                                                                                                                                                         | macrophage; innate immunity                            | cell type; physiological process         | [https://biofactoid.org/document/6ddab5e5-aa9a-46bd-ab55-54faf022511c](https://biofactoid.org/document/6ddab5e5-aa9a-46bd-ab55-54faf022511c) |
| Regulation of BMP4/Dpp retrotranslocation and signaling by deglycosylation                                                                                                                                                                                   | endoplasmic reticulum-associated degradation           | cellular location; cellular process      | [https://biofactoid.org/document/ade3f548-1f25-4e6a-81de-00d36473d2d2](https://biofactoid.org/document/ade3f548-1f25-4e6a-81de-00d36473d2d2) |
| PD-1 and BTLA regulate T cell signaling differentially and only partially through SHP1 and SHP2.                                                                                                                                                             | T cells; cancer                                        | cell type; disease                       | [https://biofactoid.org/document/8438dc95-b72e-4daa-97e1-48b3981c1683](https://biofactoid.org/document/8438dc95-b72e-4daa-97e1-48b3981c1683) |
| Nanog safeguards early embryogenesis against global activation of maternal β-catenin activity by interfering with TCF factors.                                                                                                                               | maternal-zygotic transition (MZT)                      | developmental process                    | [https://biofactoid.org/document/00c4c002-467a-47d0-b56c-1db2220fc69e](https://biofactoid.org/document/00c4c002-467a-47d0-b56c-1db2220fc69e) |
| Phosphorylation of the microtubule-severing AAA+ enzyme Katanin regulates C. elegans embryo development.                                                                                                                                                     | meiotic spindle assembly                               | cellular process                         | [https://biofactoid.org/document/8ba80a9a-95a8-47ca-ad56-e9cc77d986f0](https://biofactoid.org/document/8ba80a9a-95a8-47ca-ad56-e9cc77d986f0) |
| An adipokine feedback regulating diurnal food intake rhythms in mice.                                                                                                                                                                                        | diurnal feeding rhythms; mediobasal hypothalamus (MBH) | physiological process; organ             | [https://biofactoid.org/document/1ce5fbc5-93cb-4346-aac2-00cb8a9021f2](https://biofactoid.org/document/1ce5fbc5-93cb-4346-aac2-00cb8a9021f2) |
| The Interaction of the Tumor Suppressor FAM46C with p62 and FNDC3 Proteins Integrates Protein and Secretory Homeostasis.                                                                                                                                     | ER; import, folding, protein secretion                 | cellular location; cellular process      | [https://biofactoid.org/document/0aa40bef-39e9-42d6-8a6f-f582cdee5d9a](https://biofactoid.org/document/0aa40bef-39e9-42d6-8a6f-f582cdee5d9a) |
| NCBP3 positively impacts mRNA biogenesis.                                                                                                                                                                                                                    | nuclear export of polyadenylated RNAs                  | cellular process                         | [https://biofactoid.org/document/da73b771-6113-4f95-bb6d-17aff30aff83](https://biofactoid.org/document/da73b771-6113-4f95-bb6d-17aff30aff83) |
| Endothelial Scaffolding Protein ENH (Enigma Homolog Protein) Promotes PHLPP2 (Pleckstrin Homology Domain and Leucine-Rich Repeat Protein Phosphatase 2)-Mediated Dephosphorylation of AKT1 and eNOS (Endothelial NO Synthase) Promoting Vascular Remodeling. | arteries; coronary artery disease                      | tissue; disease                          | [https://biofactoid.org/document/a4dd6b45-af1b-407c-9f0e-8d6ff9ae557e](https://biofactoid.org/document/a4dd6b45-af1b-407c-9f0e-8d6ff9ae557e) |

**Comment by jvwong** [comment]
My first impressions, looking at the documents above are:

- If I were asked for a contextual blurb/phrase, I would just paste in the title. The title is pretty much designed for this.
- There are cases where the title doesn't or can't get specific enough on detail of context
- I found it most nature to add tags, rather than come up with a blurb

**Comment by jvwong** [comment]
todo -- 

- try some different placeholder texts here, keep the software impl
- later think about tokenizing and using in Twitter
