### ISSUE TITLE
Remove the grounding popover for complexes

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#516]
Complexes won't be grounded so they won't use the same UI as we have now.  We also will be changing the entity info UI for this issue: https://github.com/PathwayCommons/factoid/issues/504

So for now, it's best to just disable showing the popovers when clicking a compound node.

**Comment by jvwong** [comment]
Human nature being what it is, user might, given the freedom, use this feature to depict any number of biological concepts for which it was never intended.  

Consider:
  - cellular compartment
  - groups of genes or gene products (AND/OR)
  - generic entities
  - anything where people are used to seeing a box?

Wirth keeping this in mind if we're not explicitly disambiguating.

**Comment by maxkfranz** [comment]
I think the compartment case is likely the most problematic one.

To play devil's advocate:  If we find users generally tend to put entities into compound nodes for both compartments and complexes, then could we use compound nodes for both concepts?  It may suffice to allow a user to "ground" a compound node to a complex or a compartment.

**Comment by maxkfranz** [comment]
I'll take this one, since it's related to this issue: Ground a named node by default #504
