### ISSUE TITLE
Document (contributor) admin

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#524]
- Dashboard summary of documents 
  - complete, incomplete, submitted
  - metadata: author name, paper name
  - link to document viewer, etc.
  - metrics : measure how successful the process / editor are
- View document edit history
- Automate process (e.g. sending emails at right times, reminder emails)

**Comment by maxkfranz** [comment]
See https://github.com/PathwayCommons/factoid/tree/management-panel

That branch has a stubbed-out admin page

**Comment by jvwong** [comment]
Stuff we might want to store:

- context: How that document came to be created, for instance, via signup page or journal
- correspondence: Did an email invitation/reminder get sent? 
- ...

**Comment by maxkfranz** [comment]
Ref : https://github.com/PathwayCommons/factoid/blob/f34b221b9c82379e69b4d182a5625ee65569fe17/src/client/components/document-management.js#L143-L176

**Comment by jvwong** [comment]
#573 will break the admin panel temporarily but that's fine because we should settle on a model JSON schema before fixing it.
