### ISSUE TITLE
Onboarding (Revisited)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#532]
(Below is lifted from various sources...)

## Goals

The first time a user faces the app, it should 
  - briefly communicate what this app can achieve for the user
  - sell it once more by highlighting essential features, so the user is eager to explore and use them towards their goal

## Previous approaches 

From a user standpoint, videos (#444) and tours (#365, #368) can tend to be viewed as tedious comprehensive instructions ('read the manual') that are boring, lengthy, and provide  content that is unlikely to be recalled at the time it is required. Worse, these types of approaches, including the common app 'slide panels', serve as roadblocks to the **actual** tasks that must be performed.  

From a development standpoint, comprehensive videos are tours are incredibly difficult to  maintain, and can become  out of date with a single feature update.

## 'Justin time' education

Provide prompts and tips for essential tasks at the precise time they are required by a user, thereby allowing users to learn while **doing**. This idea can have productive ties to 'gamification' and 'assistants' when directed towards the onboarding problem. Modularizes and reduces maintenance burden - you update the stuff impacted by your feature alone.

> ### Maximize the Value of Empty States
> Empty state is a very natural point to inject some onboarding to continue guiding users along. Instead of leaving it blank, you should use it efficiently— to guide, educate, and prompt.
> ### Introduce Success States
> Let your users feel great when they get to their first win
> The moment a user completes an important task for the first time is a great opportunity for you to create a positive emotional connection between them and your app.

## Where to start?

- Welcome panel (1)
- Create an entity

## Refs
https://www.youtube.com/watch?time_continue=128&v=8dIIM9j1BSY
https://uxplanet.org/best-practices-for-onboarding-92f3a9f0b21a

**Comment by maxkfranz** [comment]
The how-to comic strip idea:

<img width="674" alt="Screen Shot 2019-08-07 at 1 25 27 PM" src="https://user-images.githubusercontent.com/989043/62643847-dbd37c00-b916-11e9-8839-f971cc99570b.png">

**Comment by maxkfranz** [comment]
Minor improvements to the comic strip idea:

<img width="672" alt="Screen Shot 2019-08-07 at 1 35 16 PM" src="https://user-images.githubusercontent.com/989043/62644497-3e794780-b918-11e9-8263-da4454c4744f.png">

**Comment by jvwong** [comment]
Cool - what are you using to make those cartoons?

**Comment by jvwong** [comment]
Also do we care about mobile?

**Comment by maxkfranz** [comment]
Since the icon of the cursor is a hand, I think it could work for mobile as well.  I used [Graphic](https://graphic.com).  I've shared the file with you in Google Drive.

**Comment by jvwong** [comment]
Note: Can consider some of the early concepts in #160

**Comment by maxkfranz** [comment]
This change addresses this point:

> briefly communicate what this app can achieve for the user

We show the user what value is offered by completing the pathway figure.  It also gives a better sense of the sort of overall pathway that he should create.

We can also use this third panel in the user contribution cycle slide deck to concretely show sharing.

![factoid-howto-comic2](https://user-images.githubusercontent.com/989043/62783601-c2ebd780-ba8a-11e9-94e4-0ba98400365a.png)

**Comment by maxkfranz** [comment]
Components 

- Welcome line underneath the title of the paper -- basically a welcome/tagline message
- Comic how-to infographic in the centre of the screen
- Some dismiss button at the bottom of the screen
- When dismissed, minimise to the logo menu.
- Automatically dismiss after creating a node.

**Comment by jvwong** [comment]
Minor brush up of text and made it more concrete.
![welcome-onboard](https://user-images.githubusercontent.com/4706307/63026678-9c0e1680-be79-11e9-8cbc-a6e8fd950676.png)

**Comment by jvwong** [comment]
Welcome 'splash':

![welcome-aboard-splash](https://user-images.githubusercontent.com/4706307/63030672-b4356400-be80-11e9-872c-338f3344e690.png)

**Comment by maxkfranz** [comment]
Some comments: 

(1) "Add your genes and chemicals" is good, but maybe we could tweak the wording slightly to include other types even if not explicitly.  We could use something simple like "Add your genes, chemicals, etc."  This helps to avoid questions about other types that we do support.

(2) I think the mockup is in line with what I had in mind, but seeing it makes me think that we should split up the three panels into separate images.  We can use those separate images to align the panels dynamically based on the screen dimensions.  For example, the large screen you have in the mockup could have the first two panels on the left and the third panel on the right to better use horizontal space.  Using a flexbox layout should make this automatic.  Separating out the images will also have the benefit of allowing us to modify the captions under each one without modifying the images themselves.  We don't need to separate the images or modify the mockup now, but it's useful to keep in mind for implementation.

**Comment by jvwong** [comment]
> (1) "Add your genes and chemicals" is good, but maybe we could...

I wonder if this is a good place for a '?' button  that could declare these  exhaustively. There is a lot we don't support or represent. This also goes for the other panels. 

> (2) I think the mockup is in line with what I had in mind, but seeing it makes me think that we should split up the three panels into separate images.

sure

**Comment by maxkfranz** [comment]
@jvwong Attach the SVG

**Comment by jvwong** [comment]
[welcome-aboard.zip](https://github.com/PathwayCommons/factoid/files/3584535/welcome-aboard.zip)

**Comment by maxkfranz** [comment]
Preview of work-in-progress UI:

![Screen Shot 2019-09-24 at 11 27 29 AM](https://user-images.githubusercontent.com/989043/65525966-5142de00-debe-11e9-81df-0cfb6b44722f.png)

**Comment by maxkfranz** [comment]
Here's a newer preview:

![Screen Shot 2019-09-26 at 12 02 14 PM](https://user-images.githubusercontent.com/989043/65705772-10320180-e057-11e9-978c-199dbe78a804.png)

**Comment by jvwong** [comment]
Panel svgs with 1. text as curves 2. faded arrow in panel 2

[welcome-aboard.zip](https://github.com/PathwayCommons/factoid/files/3672197/welcome-aboard.zip)
