### ISSUE TITLE
Landing page (revisited)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#534]
## Description

**Q: What is the name of the feature?**

A: Landing page

**Q: What does this feature enable the user to do?**

A: 

- Communicate to users
  - Value proposition
    - Benefits they can derive
    - Killer features
  - Basic facts 
    - What Factoid is
    - Eligibility 
    - What the author who signs up should expect
    - Data types Factoid aims to collect
  - Broader vision 
    - Connecting researchers with knowledge articles and other researchers 
- Link to a concrete example
    - Shareable summary
    - Editor
- Obtain data regarding 
  - Contributor
    - Email
  - Articles
    - Journal
    - Citation information
    - Unique identifier (PubMed [Central] ID / DOI) 
- Provide contact information in the form of 
  - Help forum 
  - Email 

**Q: What information must the user provide to use the feature?**

A:     
- Email
- Unique identifier (PubMed [Central] ID / DOI) 

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: 

**Q: How does this feature affect each class of user (persona)?**

- User 
  - Article author: 
    - Understand concept and concrete value
    - Call to action as contributor
  - Publisher
    - Understand concept and concrete value
  - Peer-reviewer (grant, article), Researcher
    - Understand concept and concrete value
    - Immediately able to view examples of user-facing software

### Mockup

![New Mockup 1 (Alternate 728u)](https://user-images.githubusercontent.com/4706307/63182022-84709280-c01f-11e9-9ee5-3cca00eb49c9.png)

### Details

Accompanying should be a  a process for validating submitted data and edge cases...
 
Related to #176 #224 #239 #242 #430

**Comment by maxkfranz** [comment]
The call-to-action should be "get started".

**Comment by sacdallago** [comment]
I would still ad an optional orchid id. For the rest, looks very nice!

Like:

> Killer features

:smile:

**Comment by sacdallago** [comment]
The idea is that often email addresses change, affiliations change, names change (getting married etc.). The orchid-id is unique to the person, throughout his/her life (even if they don't update it; as long as they _use it_ in their publications it's an easy match). Ideally you can send a message via orchid and the person gets it on whatever email they are using now.

In theory, orchid updates your profile automatically from scorpus, you just need to accept the updates (so no need for manual paper entry). More often than not nowadays the submission process for manuscripts allows to put orchid ids for authors. It also should update your employment automatically given that the uni you work at does integrate with whatever system it is. And if you input an employment (e.g. HMS) and the uni doesn't have you in their database, they can remove the false info.

**Comment by jvwong** [comment]
Add logos for University affiliations.

**Comment by jvwong** [comment]
svgs for title ('biofactoid') and title + tag (biofactoid\n summarize . share . discover)
[title_svgs.zip](https://github.com/PathwayCommons/factoid/files/3622805/title_svgs.zip)

**Comment by jvwong** [comment]
Branding and logo idea: Ties into ideas of sharing, networks, community, bee ...
![logo](https://user-images.githubusercontent.com/4706307/65160873-92417b00-da04-11e9-923d-c695e38c9fd5.png)

**Comment by jvwong** [comment]
![institutions](https://user-images.githubusercontent.com/4706307/66590329-8c037200-eb5e-11e9-982c-a5e00bde4fc5.png)

**Comment by sacdallago** [comment]
Just a thought: I am officially TUM, and being part of this project, I do carry that affiliation with me. If it's of interest (e.g. to increase international visibility, TUM is ranked pretty high globally (61) and EU wide), here's the logo:

![T--LMU-TUM_Munich--tum-logo](https://user-images.githubusercontent.com/6240943/66654501-a3179200-ec3a-11e9-8085-4af0566be736.png)
