### ISSUE TITLE
Author invitation

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#549]
## Description

**Q: What is the name of the feature?**

A:  Reply email to author request via signup

**Q: What does this feature enable the user to do?**

A: Receive an invitation with a link to their editable document 

**Q: What information must the user provide to use the feature?**

A: See landing page (#534)

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Should support HTML and, eventually text-only versions of instructions that would inform them of the purpose of the email and provide a way to navigate to their editable document 

**Q: How does this feature affect each class of user (persona)?**

A: The target user is an article author who has initiated a request to contribute (valid PubMed, email). Presumably, the author has understood the project goal, so can be assumed to be knowledgeable of Factoid and has more than passing interest. They may, however, still not completely in detail each step they must undertake (e.g. network editor).

## Specification

![email](https://user-images.githubusercontent.com/4706307/64723370-6a02cb00-d49e-11e9-9494-1acf2a5c5799.png)

### Details

- MailJet 
  - Transactional template named 'Author signup template'
- Ignore for the moment
  - template variables (e.g. paper title etc)
  - text-only version
  - dummy links and buttons (social etc)

**Comment by jvwong** [comment]
@cannin I updated the design.

**Comment by maxkfranz** [comment]
Here's an image that could be incorporated into the background of the banner image:

![conf-bg-img](https://user-images.githubusercontent.com/989043/65053023-51306480-d939-11e9-9d87-5a9f20c413f9.jpg)

**Comment by jvwong** [comment]
![email](https://user-images.githubusercontent.com/4706307/65066384-4635fe00-d952-11e9-8c4e-2951e15d4d41.png)

**Comment by gbader** [comment]
I like the photo, but it is a bit too blurry.

**Comment by maxkfranz** [comment]
I wanted to make the people anonymous with the blur.  It also allows a foreground to stand out better.  I'll replace the even blur with a depth of field effect.

**Comment by maxkfranz** [comment]
With DOF:

![banner-image-dof](https://user-images.githubusercontent.com/989043/65180366-b4e68a80-da2a-11e9-8a2f-f14f00989dbc.jpg)

With logo:

![banner-image-dof-logo](https://user-images.githubusercontent.com/989043/65181738-b6658200-da2d-11e9-858e-189ba66de3cc.jpg)

**Comment by jvwong** [comment]
Had to bump up the title size for mobile:

![email_desktop](https://user-images.githubusercontent.com/4706307/65246603-ea3bb880-dabc-11e9-97c6-bcb36315a558.png)

![email_mobile](https://user-images.githubusercontent.com/4706307/65246612-ee67d600-dabc-11e9-987b-22bc3b741d39.png)

**Comment by maxkfranz** [comment]
Here's a more flexible banner.  The bottom is blacked out a bit so you can combine it with the logo more flexibly.

![banner-bottom-black](https://user-images.githubusercontent.com/989043/65546367-64b56f80-dee5-11e9-9bfe-93c1f2667f1c.jpg)
