### ISSUE TITLE
Post-submission follow-up with author

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#554]
## Description

**Q: What is the name of the feature?**

A:  Post-submission follow-up email to author. 

**Q: What does this feature enable the user to do?**

A:  Several offerings:

- Immediate 
  - Confirm they're 'done' their task 
  - Convey appreciation 
  - Enable them to locate their contribution
  - Enable them to share 

- Future
  - Enable them to contribute again 
  - Offer relevant, related data ('You might also be interested in')
  - Direct them to other offerings (search?)

**Q: What information must the user provide to use the feature?**

A: Submitted document

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Should support HTML and, eventually text-only versions of instructions

**Q: How does this feature affect each class of user (persona)?**

A: The target user is an article author who has successfully submitted a document. Presumably, the author has understood the project and completely aware of details of the contributing a pathway. They may not be fully aware of where what they might be able to do next.

This should be general to any contributor regardless of their point of entry:
  1. journal pilot invitation
  2. author signup page
  - ... 

## Specification

---
- Header:  branding [abbreviated]
- Body: 
  - congrats, thanks
  - preview of summary
  - see/share links 
- Footer: Contact/About/credits [see 'Author signup template']

### Details

- MailJet 
  - Transactional template named 'Author post-submission template'
- Ignore for the moment
  - template variables 
  - text-only version
  - dummy links and buttons

**Comment by jvwong** [comment]
v1:

![image](https://user-images.githubusercontent.com/4706307/65176512-e8251b80-da22-11e9-8fc9-97d840230cd1.png)

**Comment by maxkfranz** [comment]
FYI: I don't think we have www subdomains set up.  They're kind of dated now anyway.

**Comment by jvwong** [comment]
v2: 
![email_reply](https://user-images.githubusercontent.com/4706307/65273238-aeb9e200-daee-11e9-9fc3-a617bd52a38f.png)

**Comment by jvwong** [comment]
![Uploading image.png…]()
