### ISSUE TITLE
MailJet integration

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#555]
## Description

**Q: What is the name of the feature?**

A: Mailjet integration

**Q: What does this feature enable the user to do?**

A: Send emails to potential contributors via MailJet

**Q: What information must the user provide to use the feature?**

A: Email address and article information (i.e. PMID). Tied to #534 

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: 
- [x] MailJet account
- [x] Requires published templates. See #554 #549.
- MailJet account notes on email send rate :
  > A temporary sending limit of 200 emails per hour is currently applied to your account. Please contact our support to remove it. Learn more about limits.

### Details

Use MailJet's [Send API](https://dev.mailjet.com/reference/email/send-emails/)

**Comment by maxkfranz** [comment]
Note: Currently, we are using SMTP rather than the HTTP API.

**Comment by maxkfranz** [comment]
@jvwong 

Do you find your nodemailer approach works sufficiently with the Mailjet templates, or do you think we should use the Mailjet API directly?

**Comment by jvwong** [comment]
I think i've got something respectable working with nodemailer. I'll post my PR ASAP.

Advantage of going SMTP route is that if we decide to switch off Mailjet for whatever reason (e.g. they go belly up, go paid only), we'll be able to transition easier. Maybe next guy doesn't have HTTP.

**Comment by maxkfranz** [comment]
Let's do an in-person demo tomorrow.
