### ISSUE TITLE
Docker & Puppeteer config & README.md

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#586]
In order to generate images for sharing, the server needs to use Puppeteer.  Puppeteer won't work with Docker without some additional setup.  See https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by maxkfranz** [comment]
I've confirmed that installing the recommended packages allows for the unstable CI server to generate images properly.

E.g.: https://unstable.factoid.baderlab.org/api/document/demo.png

**Comment by maxkfranz** [comment]
This may be an alternative: https://github.com/browserless/chrome#puppeteer

**Comment by maxkfranz** [comment]
Also: https://github.com/deepsweet/chromium-headless-remote

**Comment by jvwong** [comment]
Updates to `docker-compose.yml` required. Also, place a Docker compose .env file with production settings in a private remote, for instance, [BaderLab websites](https://github.com/BaderLab/sysadmin/tree/master/websites) 

Notes to self:
  - Docker-compose
    - Environment
      - Add
        - email
          - `EMAIL_ENABLED`
          - `SMTP_USER`
          - `SMTP_HOST`
          - `SMTP_PASSWORD`
        - twitter
          - `TWITTER_CONSUMER_KEY`
          - `TWITTER_CONSUMER_SECRET`
          - `TWITTER_ACCESS_TOKEN_KEY`
          - `TWITTER_ACCESS_TOKEN_SECRET`
          - `TWITTER_ACCOUNT_NAME`
        - `NCBI_EUTILS_API_KEY`
      - Omit
        - `USE_PC_GROUNDING_SEARCH`

**Comment by jvwong** [comment]
Got all this working locally. Put the production settings in the [sysadmin](https://github.com/BaderLab/sysadmin/blob/master/websites/factoid.md) remote.

I'll wait until testing /debugging is done to test the live post-to Twitter because I'll need to take over unstable.factoid.baderlab.org url. Plus we'll need to tag/release any Docker images.
