### ISSUE TITLE
Case: 'Try it out' doc for limited, specific groups  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#613]
## Description

**Q: What is the name of the feature?**

A: 'Try it out' 

**Q: What does this feature enable the user to do?**

A: A user should be able to access a document via URL and edit as they so desire in order to experience first hand pathway creation.  

**Q: What information must the user provide to use the feature?**

A: none.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: The user would either be sent this link by a Biofactoid team member directly or it can be made available to specific users in a limited fashion. The document and its elements would be ephemeral.

**Q: How does this feature affect each class of user (persona)?**

A: This case would be beneficial for demonstrating the capabilities to an interested party. This could include, for instance, Reactome curators, colleagues at a conference, funding referees, editors etc. It would be very inefficient to have to coordinate all these cases via the admin in a  development app. It would be disconcerting and confusing to provide a demo link in which another person was/did edit.

### Mockup

//TODO

### Details

//TODO

**Comment by maxkfranz** [comment]
Let's just use unstable for now
