### ISSUE TITLE
Add-back 'Submit'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#627]
## Description

**Q: What is the name of the feature?**

A: Submit (document) button

**Q: What does this feature enable the user to do?**

A: Enables a user to signify that the contents of their document is complete. 

**Q: What information must the user provide to use the feature?**

A: Action: Click button and confirm. 

**Q: How does this feature affect each class of user (persona)?**

A: This issue emerged from user testing:

> - "'Share' sounds like publish"; "'Submit' is clearer"
> - Submit button? 
> - "What do I do now"? "How do I save"?
> - How do I know if it is saved? I want to save it.

### Mockup

A 'Submit' button existed before it was [replaced with the 'Share'](https://github.com/PathwayCommons/factoid/commit/6711cfa8ac032cbf7f03d0ec19716823bf96dbfa#diff-6d22f404077099f53dfe11bd2b197e13). Should update the onboarding cartoon to reflect changes to the workflow.
 

### Details

Flow control
  - User clicks Submit
  - Confirmation message shown
  - Upon confirmation,
    -  Submit is disabled and text replaced with 'Submitted'
  - Optional
    - Share to @biofactoid Twitter - but what about the 'blurb'?
  - Follow-up email sent 

NB: I don't believe that the act of settings a document 'submitted' status should be coupled to email sending and/or posting to Twitter. Consider an admin page, where we wish to alter the doc status flag or other cases we wish to work 'behind the scenes'.

Related to #620, #592, #532

**Comment by maxkfranz** [comment]
Possible improvements:

- [ ] The post-submission text could be revised in style and content. It would be nice to have a checkmark, and the whitespace at the top and bottom of the panel could be removed. The text itself seems a bit conditional to me ("should" versus "will"). The actions at the bottom could be separated and made more direct.
- [ ] It would be good feedback to the user for the button to turn green after submission, especially if you consider the action to be "publish".
- [ ] We may want to go directly to "published" and skip "submitted" by default. It's better for a user to see his summary right away, and we can manually demote a document from "published" to "submitted" using the admin interface --- as needed.

**Comment by jvwong** [comment]
NB: 

I thought this was a bug but it may be a feature: If the editor is open, an admin-driven update to 'status=submitted' results in a follow-up email request. This is probably OK.
