### ISSUE TITLE
Onboarding: Update tutorial to reflect workflow and complex   

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#628]
## Description

**Q: What is the name of the feature?**

A: Onboarding tutorial (cartoon) 

**Q: What does this feature enable the user to do?**
**Q: What information must the user provide to use the feature?**
**Q: What are the applicable constraints, e.g. compatibility or performance?**
**Q: How does this feature affect each class of user (persona)?**

See #532

A: This issue emerged from user testing and feedback.

> - Completion
>   - Expect save or submit action
> - Complex/compound
>   - Unaware of existence
>   - Creation and destruction has behaviours not easily discovered

### Mockup

//TODO

### Details

- Inform user about when and how to complete the editing phase (e.g. 'Submit')
- Make user aware and guide re: complexes
- other?

Related to #532 #627

**Comment by jvwong** [comment]
![welcome-aboard](https://user-images.githubusercontent.com/4706307/73854035-d68cb680-47ff-11ea-9e44-46d2df940d23.png)

**Comment by maxkfranz** [comment]
Note for later: make sure that the svgs for the last two have the same viewport dimensions when exporting

**Comment by jvwong** [comment]
Maybe this is a good place to mention how things are saved?

**Comment by maxkfranz** [comment]
Two notes:

(1) I think that, for most people, the fourth panel will be too abstract to understand.  We should probably just show an example summary for one document.  Details, like where the summary can be explored or shared, would be better suited to the caption.

(2) I think that we're already presenting a lot of information on this view.  I wonder whether most people would read a message about saving here.

We can discuss in more detail tomorrow.

**Comment by jvwong** [comment]
Fair enough, I think the share to twitter thing is still a hypothesis, until we can put it in front of people.

**Comment by jvwong** [comment]
So far:

![image](https://user-images.githubusercontent.com/4706307/74165984-e2a7b800-4bf3-11ea-9e6c-5d64c41952b4.png)
