### ISSUE TITLE
The homepage is broken after recent PRs

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#667]
See http://unstable.factoid.baderlab.org/

![Screen Shot 2020-03-11 at 1 46 31 PM](https://user-images.githubusercontent.com/989043/76447254-bb810980-639e-11ea-8a2a-a1771d798c40.png)

**Comment by jvwong** [comment]
Homepage looks to doc 'status' to determine if it should be published to the front page.

After #663, that gets removed in the read-only response from `/api/document`. Let's just expose 'status', no big deal.
