### ISSUE TITLE
Complexes are erroneously shown as incomplete by submit UI

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#670]
![Screen Shot 2020-03-11 at 1 51 55 PM](https://user-images.githubusercontent.com/989043/76447735-89bc7280-639f-11ea-9ce7-cb936b3402a1.png)

**Comment by jvwong** [comment]
I recall one idea is to auto-populate name, i.e. `rad51:mdm2`

**Comment by maxkfranz** [comment]
Yes, that's a good idea for a general improvement.

The bug would happen either way.  In the example image, note that the complex is named.  For some reason, even a named complex isn't considered completed.  If I were to guess I'd say it's probably looking for grounding association data, and complexes never have that data.

**Comment by maxkfranz** [comment]
For now: Don't restrict complexes -- just ignore in the list

Later: Automatic, default complex name
