### ISSUE TITLE
Provide immediate access to doc upon task completion

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#675]
## Description

**Q: What is the name of the feature?**

A: Provide immediate access to doc upon task completion

**Q: What does this feature enable the user to do?**

A: Upon signup, provide a editable document link.  

**Q: What information must the user provide to use the feature?**

A: Same as signup.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Errors in input (email), possibly missing article information (PubMed).

**Q: How does this feature affect each class of user (persona)?**

A: This eases the path towards accepting data input; removes friction and temporal delay associated with having to login, find, read and launch via email. 

### Mockup

Essentially a near copy of the email:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/4706307/76650239-8b6d6e00-6538-11ea-91b0-56e56f23476c.png">

### Details

- Look into reusing the TaskView component
- Part of the signup assistant series.

**Comment by maxkfranz** [comment]
Let's test this once on unstable before closing

**Comment by jvwong** [comment]
Not sure if 'ridiculously long titles' is a case worth handling, but maybe I could combine it with the [suggested  text](https://github.com/PathwayCommons/factoid/pull/687#issuecomment-601363504): 

<img width="1476" alt="Screenshot at Mar 20 12-50-34" src="https://user-images.githubusercontent.com/4706307/77186543-6e411e00-6aa9-11ea-8e99-f809836c2339.png">

**Comment by maxkfranz** [comment]
Let’s just truncate for now. The text stuff isn’t important
