### ISSUE TITLE
Error directly loading the demo with a clean DB

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#676]
1. Delete everything in rethinkdb.
1. Start the server: `npm run watch`
1. Go to [http://localhost:3000/demo](http://localhost:3000/demo)

Note the errors: 

Client: 

```
An error occurred livening the doc Error: No response from database for ID demo
```
 
Server: 

```
info:    POST /api/document 200 122.084 ms - -
info:    Mocking email transport
info:    Email sent to: author@example.com; Caught by Ethereal: https://ethereal.email/message/XnEnyNZt0AzxGDUFXnEny7GpSgyZ.uYGAAAAAZVocBq0DIZRxMPGtL7eT8g
```

@jvwong, I suspect that recent changes re. 'demo' homepage invitations and/or emails is related.

**Comment by jvwong** [comment]
- Editor POST to `/api/document/`: Server calls `res.end` before doc created.
