### ISSUE TITLE
Mobile sharing

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#680]
## Description

**Q: What is the name of the feature?**

A: Mobile sharing

**Q: What does this feature enable the user to do?**

A: A user can share a paper's summary to any sharing-enabled app on the user's phone.

**Q: What information must the user provide to use the feature?**

A: 

- Which app to share to
- Optional user-specified text to share along with the summary

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: 

- The share feature works only on mobile devices.
- The share feature works only when an HTTPS address is used.  All `http://...` addresses should be forwarded automatically to `https://...`.  Plain HTTP should be forbidden by the prod server.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: A biologist may share the summary of his recent paper or a paper of a colleague.
- Editor: An editor might use this feature to share the summary of interesting, recent papers.
- Computational biologist: "
- Curator: "

### Mockup

A share button opens the native share UI for the mobile device.  Here is an example: https://mdn.github.io/dom-examples/web-share/

### Details

This approach allows us to support any social platform installed on the user's phone, using the user's own account.  This, coupled with a mobile-first design philosophy for the explorer view, makes this approach scalable for sharing in the long term.  Here are some example platforms that would be supported out of the box:

- Twitter
- ResearchGate
- LinkedIn
- Slack
- Email
- Text

**Comment by jvwong** [comment]
Sorta related: Are we still planning on auto-sharing to @biofactoid on publish?

**Comment by maxkfranz** [comment]
Yes, but that probably should be a separate issue/PR

**Comment by maxkfranz** [comment]
Related: https://github.com/PathwayCommons/factoid/issues/671

The share icon could take the place of the submit button, with the submit button moved to the bottom of the screen.

**Comment by cannin** [comment]
@maxkfranz @jvwong I don't understand the user workflow. A user draws the network on their desktop and then jumps on their phone to share it? Seems like a "pain point". Giving people a link to a downloadable image of their pathway seems like an easier starting point than an experimental feature only supported on 1 desktop browser and not even Firefox Android. This should be a very low priority; people can copy/paste a link.

**Comment by jvwong** [comment]
> @maxkfranz @jvwong I don't understand the user workflow. A user draws the network on their desktop and then jumps on their phone to share it? Seems like a "pain point". Giving people a link to a downloadable image of their pathway seems like an easier starting point than an experimental feature only supported on 1 desktop browser and not even Firefox Android. This should be a very low priority; people can copy/paste a link.

I think there's two scenarios:
- A researcher, on their phone, sees a pathway in the 'explorer' 
  - Let them share:  *this* issue/feature
- An author has composed/submitted their own pathway (i.e. desktop)
  - Let them share: TODO issue (see 'submitted' Tasks panel)

**Comment by sacdallago** [comment]
Jumping in here: I don't see how either of those scenarios need to have a dedicated coding effort from our side, especially given other priorities.

- Chrome/Firefox/Safari/Opera/... on phones have a share feature built in (not talking about API, talking about the actual "share" button somewhere in the browser UI) which most people are familiar with and know already: that's how 90% of the content shared on whatsapp gets sent
- On computers: most people click on the URI bar and the browser ~automatically selects~ the entire URI for them. Actions needed after that: copy-paste.


If you really wanna be redundant: you can have a human friendly (e.g. a slug instead of the db hash) link pop up in the explorer view which can be clicked and automatically is selected for copy-paste (same as the browser does for you already. YouTube does it this way on computer browser!)


I think the feature discussed here should have extremely low priority.

**Comment by maxkfranz** [comment]
This is more of a behavioural issue than a technical one.  If you’re having trouble understanding how this feature could provide high ROI (low input, high impact), then I could explain it to you in more detail in one of our calls.  

There are other efforts that are much lower ROI that would be better candidates for reevaluation.  While your efficiency idea is good generally, it’s important that it’s applied in the right places.

**Comment by cannin** [comment]
We should postpone this until one of our calls then. As presented here the idea has not been discussed and @maxkfranz is willing to explain on the next call. Thoughts @gbader?
