### ISSUE TITLE
Related papers system

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#681]
## Description

**Q: What is the name of the feature?**

A: Related papers

**Q: What does this feature enable the user to do?**

A: The goal is to develop a system to return a ranked list of articles, given one or more interactions from Biofactoid (participants, relationship).

**Q: What information must the user provide to use the feature?**

A: There are at least two cases: 1. Those related to the entire pathway 2. Those related to a particular interaction 

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: The key issue is providing a source of articles that covers the organisms in Factoid, achieving a reasonable degree of specificity (reduce 'noise' / irrelevant material) via data source selection filtering and ranking.   

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: Provides supporting articles for a given pathway or interaction of interest. Brings in related information that may not have been aware of.
- Author: Added value to their pathway data contribution 'for free'; delivers on the promise of integrating their data with a larger body of knowledge
- Curator: See biologist.

### Mockup

see #683 

### Details

- Query: This is the input, an interaction from Biofactoid 
- Source: These are the sources of articles. We propose to draw from PubMed, INDRA (which draws from other databases + REACH) and the Biofactoid database itself
- Output: This should be a ranked list of ‘documents’. Each doc referenced a unique article ID, one or more interactions with ‘entities’, ‘relation’, ‘source’, etc.  

![image](https://user-images.githubusercontent.com/4706307/79898884-f896dd80-83d9-11ea-85b1-1eeb0c0f5720.png)

There is a more in-depth scoping doc with basic requirements [JW].

**Comment by cannin** [comment]
@maxkfranz @jvwong Potentially useful, but I don't think we have discussed this much. 

* What is the source of the related papers? Only existing factoid papers? 
* Could it be offloaded through a call to the PC API or a just opening a new tab with a PC search?

**Comment by maxkfranz** [comment]
It would be ideal from a technical standpoint if the related papers could be generated only from factoid data.  However, that provides low utility for early users:  There isn’t much data yet.  We need to focus on how to provide high utility to early adopters.  We should show related papers from a large set of the latest articles from Pubmed, or a similar large-scale, multi-organism source.

Can PC data give information on a paper level, rather than a pathway or database level?  Pubmed data already has information on a per paper level, and it contains the list of entity labels within that data.  Unless PC supports similar functionality, it’s not as useful for this particular feature.  It might be more conducive to a more pathway-centric feature — like related pathways.

**Comment by cannin** [comment]
@metincansiper @maxkfranz I don't want to derail anything that has already been discussed. If this is the same as the Indra idea then fine. If not then a PC API call using a PATHSFROMTO graph query followed by extracting any mentioned papers would use established components and simplify development.

**Comment by jvwong** [comment]
> @metincansiper @maxkfranz I don't want to derail anything that has already been discussed. If this is the same as the Indra idea then fine. 

Not the same, identically the 'INDRA' idea. Let me fill in description tmrw.

**Comment by jvwong** [comment]
Issue: Update fetchPubmed service to allow greater number of records to be retrieved from NCBI PubMed EUTILS

**Comment by jvwong** [comment]
@metincansiper  

INDRA Note: [Statement `evidence` can have attribute `pmid` and/or `text_refs`] (https://indra.readthedocs.io/en/latest/modules/statements.html?highlight=text_refs#indra.statements.statements.Evidence)

e.g. Agents [p53, p21](https://db.indra.bio/latest/statements/from_agents?agent0=11998@HGNC&agent1=1784@HGNC&format=json-js)
```json
{ ...
  "statements": {
  ...
  "-1083127553788573": {
      "type": "IncreaseAmount",
      "subj": {
        "name": "TP53",
        "activity": {
          "activity_type": "transcription",
          "is_active": true
        },
        "db_refs": {
          "UP": "P04637",
          "HGNC": "11998"
        }
      },
      "obj": {
        "name": "CDKN1A",
        "db_refs": {
          "UP": "P38936",
          "HGNC": "1784"
        }
      },
      "belief": 1,
      "id": "8e78f0a4-f74d-4dd2-adfe-fe3ae13ecc84",
      "matches_hash": "-1083127553788573",
      "evidence": [
        {
          "source_api": "biopax",
          "pmid": "15546879",
          "source_id": "http://pathwaycommons.org/pc11/Control_7fd32ceffa67bbdac0deb1ee4c2a44f0",
          "annotations": {
            "source_sub_id": "ctd",
            "agents": {
              "raw_text": [
                null,
                null
              ]
            },
            "prior_uuids": [
              "76df2301-5647-4541-ad80-faafece8ad23"
            ]
          },
          "epistemics": {
            "direct": true
          },
          "text_refs": {},
          "source_hash": "1802689699905903764"
        },
        ...
    ]
   }
 }
}
```

**Comment by metincansiper** [comment]
>INDRA Note: [Statement evidence can have attribute pmid and/or text_refs]

@jvwong 

```
{
"source_api":"sparser",
"text":"A number of small molecules and peptides have been identified that impair the interaction of p53 with mdm2, an important negative regulator of p53 stability xref .",
"annotations":{
"found_by":"INTERACT",
"agents":{
"raw_text":[
"mdm2",
"p53"
]
},
"prior_uuids":[
"60f26e80-8d04-4469-a66b-84e47850717c"
],
"content_source":"pmc_oa"
},
"text_refs":{
"PMID":"29549331",
"TRID":28410408,
"PMCID":"PMC5856786",
"DOI":"10.1038/S41467-018-03441-3",
"TCID":19594497,
"SOURCE":"pmc_oa",
"RID":20300019594497,
"READER":"SPARSER"
},
"source_hash":-8986311491555069000,
"pmid":"29549331"
}
```
The one aboe is an example evidence

We already use the pmids. We use the pmid from the root pmid field instead of the one under text references field. I was assuming that they must be the same (I may be wrong though). Do you mean we should use other things like "TRID", "PMCID" etc.?

**Comment by jvwong** [comment]
There seems to be 2 cases where a PMID is made available:

- Case 1: 
  - e.g. `evidence[i].text_refs.PMID`
  - I believe this case occurs when source_api is an NLP 
- Case 2: 
  - `evidence[j].pmid`
  - This is the most other source_api, e.g. Pathway Commons

**Comment by jvwong** [comment]
OK I just realized you are already getting pmids via Case 2. There's nothing more to do.

**Comment by jvwong** [comment]
Let's close and move to more specific issues/features.
