### ISSUE TITLE
Paper metadata display: explorer view

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#683]
## Description

**Q: What is the name of the feature?**

A: Paper metadata display panel

**Q: What does this feature enable the user to do?**

A: This panel allows the user to explore information related to the paper.  It provides global information about the document, while the network view provides local information about the document.

**Q: What information must the user provide to use the feature?**

A: The document must be previously associated, by the author, with a PubMed ID in order for the metadata to be generated and displayed.  The reader does not need to provide any information.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: 

- The PubMed metadata must have been previously loaded into the system.
- Any analysis needed to generate information shown in the panel must be immediately available upon loading the view.  Expensive data must be precomputed.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: For producer/contributors, this delivers on the promise that the pathway data will be linked to their article. This provides concrete value as attribution (author list) and avenue that can contribute to awareness of their article. Similarly for consumers, it makes clear that the network data they see is 'from' the article and by the author. The article metadata also helps give readers critical context  that is otherwise very difficult to capture in structured languages.    
- Editor: Seeing the journal and article prominently featured with hyperlinks is an excellent way to both increase awareness among potential readers/subscribers but also drive traffic to their articles. This is also an ideal place to realize journal branding. 
- Curator: These are consumers, see above
- Computational biologist: This data is already included in the doc JSON

### Mockup

Here is a mockup of the explore view panel, which may contain expanded paper metadata.

The view on large screens (desktop, tablets):

![factoid-explore-panel page 1](https://user-images.githubusercontent.com/989043/77087997-3323e980-69da-11ea-9725-9066b2730083.jpg)

The view on small screens (mobile):

![factoid-explore-panel page 2](https://user-images.githubusercontent.com/989043/77088108-5484d580-69da-11ea-8cb3-d4781661f68f.jpg)

### Details

- The panel replaces the metadata (e.g. title) summary that is normally shown in the editor.
- The panel can hold any paper-level information about the document, such as related papers (#681).
- The panel is of relatively consistent width, regardless of the device's screen size.  This allows for well-fitted, consistent content on both desktop and mobile.
- Paper metadata included in the panel
  - Title
  - Full author list
  - Journal info
  - Abstract
  - Related papers
  - ... More TODO

**Comment by jvwong** [comment]
I was envisioning 'borrowing' the Google Map mobile experience for prioritizing article metadata:

- Initial panel/page load
  - Abbreviated journal reference hyperlinked to *publisher* site (`Mol. Cell 75 (2019)`),  journal icon (when supported)
  - Full title 
- Expanded
  - Full reference hyperlinked to *publisher* site (e.g. `Molecular Cell. vol 75, iss 2, pp372-281.E5, July 25, 2019`)
  - Full title
  - Collapsible author list hyperlinked to PubMed search (see #636); can be comically long
  - Full abstract/summary
  - Link outs (PMC, PubMed)
  - Keywords
  
Other:  dicey, but PubMed improves over time adding terms, referernces.

**Comment by maxkfranz** [comment]
In this design, it's abbreviated by area.  Instead of clicking to see more, you just have to scroll.  Just scrolling is easier and more obvious, especially on mobile.

**Comment by maxkfranz** [comment]
Instead of 'Initial panel/page load', I see that list as for the editor view.  The author doesn't need any of the extras, and the abbreviations are fine.

Instead of 'Expanded', I see that list as for the read-only explorer view.  The reader wants to see the explorer for this list of information (metadata, related papers) in the first place, so we should show it right away.  The figures don't take up much space, so we have the screen real estate for it anyway.

**Comment by jvwong** [comment]
I've been brainwashed by Google. Can you point to an example site/app that uses scrolling?

**Comment by maxkfranz** [comment]
There are lots of examples of panels with just scrolling. Apple Music is a simple example. You don’t have to expand the panel to see all the songs. You just scroll the list. 

![52716B47-817B-42CE-9E5C-60A454FECE29](https://user-images.githubusercontent.com/989043/77197657-f7615080-6abb-11ea-90cd-8bca7007538b.png)

**Comment by maxkfranz** [comment]
Video:

https://drive.google.com/file/d/1qw4-s9ZcnUvVQrxjTV4iSbIeNB3u-2Gg/view?usp=sharing
