### ISSUE TITLE
Tweet to @biofactoid when a document status is set to publish

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#686]
## Description

**Q: What is the name of the feature?**

A: Tweet it  

**Q: What does this feature enable the user to do?**

A: View and share their submitted pathway via Twitter

**Q: What information must the user provide to use the feature?**

A: Submit their document.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: The document should achieve a status of 'published'. 

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: This feature enables users to view and share their work on a well-used platform. It gives them an immediate sense that their work can be accessed. It provides a means to increase the visibility of their work. Ideally this is linked and provides an avenue to  a value-added 'explore view'.

### Mockup & Details

> describe how the automatic tweet is shown to the user in thank-you emails.  This could act as a CTA to retweet or independently share via mobile social apps.

#### A note to self about the 'lifecycle' of a document:

![Notebook](https://user-images.githubusercontent.com/4706307/77357430-8a012a00-6d1e-11ea-99b5-c7401940b655.png)

**Comment by jvwong** [comment]
> describe how the automatic tweet is shown to the user in thank-you emails. This could act as a CTA to retweet or independently share via mobile social apps.

@maxkfranz not sure if we're on the same page here with the Tweet

**Comment by maxkfranz** [comment]
Let's discuss tomorrw

**Comment by jvwong** [comment]
- Email: this is a separate concern from this issue, which deals with this codebase
- Admin: Link to Tweet would be nice

**Comment by maxkfranz** [comment]
@jvwong Does the system tweet at all right now?  If not, this should probably be included in the current iteration (0.8) rather than the initial explorer iteration (0.9).

**Comment by jvwong** [comment]
> @jvwong Does the system tweet at all right now? If not, this should probably be included in the current iteration (0.8) rather than the initial explorer iteration (0.9).

No tweeting. Done. I'm just testing my branch..

**Comment by jvwong** [comment]
I updated the 'follow-up' email template on Mailjet to look like this:

<img width="471" alt="image" src="https://user-images.githubusercontent.com/4706307/77576592-d463e180-6eab-11ea-9590-5833ff1ac22b.png">


- Images not displayed in client:

<img width="477" alt="image" src="https://user-images.githubusercontent.com/4706307/77576641-e8a7de80-6eab-11ea-8ebb-c37b0fcb80f2.png">
