### ISSUE TITLE
Tag & release 0.8.0: patch release for next steps with Mol. Cell

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#695]
Ref : https://github.com/PathwayCommons/factoid/milestone/12

**Comment by maxkfranz** [comment]
@jvwong Looks like there's just #692 remaining with PR #696.  I think that should be it for 0.8.  Unless you have any objections, I'll tag and merge 0.8 once #696 is merged in.

Then we can deploy the app to prod, and Emek's lab member should be able to do that curation and testing that we talked about.

**Comment by jvwong** [comment]
Do it.

**Comment by maxkfranz** [comment]
Ready to go https://github.com/PathwayCommons/factoid/pull/697

**Comment by jvwong** [comment]
OK I can kick it off onto unstable.factoid.baderlab.org and use master.factoid.baderlab.org to try out the dockerization. ASAP.

**Comment by maxkfranz** [comment]
The unstable one isn't that important.  It will build overnight.  The docker/prod stuff is important though

**Comment by jvwong** [comment]
I have https://master.factoid.baderlab.org/ up and running with factoid (0.8.0) and the latest tagged version of everything else. It is configured with the development config settings, namely Tweets to https://twitter.com/TestAcc87711534. I repopulated db with the current production data dump.
