### ISSUE TITLE
SARS-Cov-2  support

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#699]
# Approach 

1. Provide article information
2. Provide expected pathway 
3. Provide Factoid manually-created document
4. Issues
 
## 1. Article information
SARS-CoV-2 Cell Entry Depends on ACE2 and TMPRSS2 and Is Blocked by a Clinically Proven Protease Inhibitor [Hoffmann et al. Cell. 2020 Mar 4. pii: S0092-8674(20)30229-4. [Epub ahead of print]](https://linkinghub.elsevier.com/retrieve/pii/S0092-8674(20)30229-4). Hoffmann M, Kleine-Weber H, Schroeder S, Krüger N, Herrler T, Erichsen S, Schiergens TS, Herrler G, Wu NH, Nitsche A, Müller MA, Drosten C, Pöhlmann S.
![image](https://user-images.githubusercontent.com/4706307/77968508-7ffaa080-72b5-11ea-99de-f677d8d37ba6.png)

## 2. Factoid manually-created document
![image](https://user-images.githubusercontent.com/4706307/78038934-7287f980-733b-11ea-9af3-19facc1071bc.png)

## 3. Issues

- Support for SARS-Cov-2 [genes](https://www.ncbi.nlm.nih.gov/gene/?term=txid2697049[Organism:noexp]) or [proteins](https://covid-19.uniprot.org/uniprotkb?query=*), in particular, (S)pike protein
- In this case, experimental conditions necessitate only a ACE2 peptidase protein fragment is used
- No 'cleavage' relation for 'TMPRSS2' and 'S'
- No compartments (host, virus)
- Difficult to express macro processes, i.e. 'receptor-mediated endocytosis/entry'

**Comment by jvwong** [comment]
Similar story for  [Structure, Function, and Antigenicity of the SARS- CoV-2 Spike Glycoprotein](https://www.sciencedirect.com/science/article/pii/S0092867420302622?via%3Dihub) Walls et al., 2020, Cell 180, 1–12

**Comment by jvwong** [comment]
[Cryo-EM structure of the 2019-nCoV spike in the prefusion conformation](https://science.sciencemag.org/content/367/6483/1260) Wrapp et al Science  13 Mar 2020: Vol. 367, Issue 6483, pp. 1260-1263

![image](https://user-images.githubusercontent.com/4706307/78058896-fef3e580-7356-11ea-93fd-027bb442f1a9.png)

**Comment by jvwong** [comment]
[Structural basis for the recognition of SARS-CoV-2 by full-length human ACE2](https://science.sciencemag.org/content/367/6485/1444) Yan et al. Science  27 Mar 2020: Vol. 367, Issue 6485, pp. 1444-1448
![image](https://user-images.githubusercontent.com/4706307/78059671-4038c500-7358-11ea-89df-e754db5e23a2.png)


- Full length ACE2 protein

**Comment by jvwong** [comment]
Issues related to Biofactoid support:

- Need to support genes from many viruses
  - Most of what is known relates to other, previously studied coronaviruses (MERS, SARS-Cov)and often other related and un-related viruses, which may or may not extrapolate 
- Very idiosyncratic biology related to viruses
  - Self-splicing proteins (NSPs) that arise from open reading frames
  - Translational reading frame slippage
- Detailed post-translational modification ( glycosylation,  residues in the spike )
- Email 
  - invitations:  Need to generate this text distinct from the journal and signup case. Perhaps update the email system to be more generic rather than 'hardcoded' text in the template.

**Comment by maxkfranz** [comment]
> Need to support genes from many viruses

These viruses have distinct taxon IDs, and we decided to only support [a predefined set of organisms](https://github.com/PathwayCommons/grounding-search/blob/v0.2.0/src/server/datasource/organisms.js#L44-L54).  To support this, a new root organism must be added, with the strains specified in a way similar to E. coli.

**Comment by jvwong** [comment]
> > Need to support genes from many viruses
> 
> These viruses have distinct taxon IDs, and we decided to only support [a predefined set of organisms](https://github.com/PathwayCommons/grounding-search/blob/v0.2.0/src/server/datasource/organisms.js#L44-L54). To support this, a new root organism must be added, with the strains specified in a way similar to E. coli.

FYI: https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2697049

**Comment by maxkfranz** [comment]
This query gives a good sense of a "spike" or "S" result (but not taking into account any ranking): https://www.ncbi.nlm.nih.gov/gene/?term=spike+glycoprotein

**Comment by jvwong** [comment]
Sorry I edited above. The SARS-COV-2 genes are there, but most people will want to draw parallels with earlier coronaviruses and related, since well, we know squat. The issue with grounding to 'genes' is that viruses are rather tricky in using one 'gene' to encode a bunch of proteins, hence the uniprot stuff.

**Comment by maxkfranz** [comment]
The root organism for the virus would be more consistent with how other organisms are specified: [694009](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Info&id=694009&lvl=3&lin=f&keep=1&srchmode=1&unlock) instead of [2697049](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2697049)

**Comment by maxkfranz** [comment]
Does NCBI have a list of proteins associated with each gene entry in its data?  I imagine you could have more specificity in the UI if the gene identifier maps to multiple proteins and the user wants to specify a particular one.

**Comment by jvwong** [comment]
Let's take this from the start. 

1. Below is the SARS-CoV-2 Genome [Gordon et al bioRxiv](https://doi.org/10.1101/2020.03.22.002386). DNA (black); Gene/mRNAs (orange); proteins (blue, red, green) 
<img width="836" alt="image" src="https://user-images.githubusercontent.com/4706307/78164250-7a1cd080-7417-11ea-96f5-092888c57354.png">

2. 'Taxonomy'
  - [Category of 'Severe acute respiratory syndrome-related coronavirus'](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?mode=Undef&id=694009&lvl=3&keep=1&srchmode=1&unlock)
      - [SARS-COV-2](https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=2697049)

3. 'Genes' (i.e. expressed DNA regions) for SARS-COV-2
  - [HTML link](https://www.ncbi.nlm.nih.gov/gene/?term=txid2697049[Organism:noexp])
  - [EUTILS link](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=taxonomy&db=gene&retmode=json&id=2697049)


4. Proteins associated with the gene/mRNA 'ORF1ab' (orange region in figure)
  - [HTML link](https://www.ncbi.nlm.nih.gov/gene/?term=43740578#general-protein-info)
  - [EUTILS link](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?dbfrom=gene&db=protein&linkname=gene_protein_refseq&idtype=gi&retmode=json&id=43740578) 


Links: NCBI EUTILS ['ELINK'](https://www.ncbi.nlm.nih.gov/books/NBK25499/#chapter4.ELink)

**Comment by maxkfranz** [comment]
Let's spec out the details in the grounding service repo in an issue.  We need to decide on things like

- what the root organism should be,
- what the display name of the organism family should be,
- what filters may be needed, and
- edge cases (e.g. does "S" work well when the organism is indexed, even though it's only one character).

**Comment by jvwong** [comment]
In testing driving, I think there may be a strong argument to add-back organism filtering:
do show a selector when the search list is available. I found it frustrating to look for an e.g. Drosophila gene and have to zing past a whole bunch of unrelated species, even thought their names are closer.

**Comment by jvwong** [comment]
> Let's spec out the details in the grounding service repo in an issue. We need to decide on things like
> 
>     * what the root organism should be,
> 
>     * what the display name of the organism family should be,
> 
>     * what filters may be needed, and
> 
>     * edge cases (e.g. does "S" work well when the organism is indexed, even though it's only one character).

I'm moving this issue to that remote....

**Comment by jvwong** [comment]
> Issues related to Biofactoid support:
> 
>     * Need to support genes from many viruses
>       
>       * Most of what is known relates to other, previously studied coronaviruses (MERS, SARS-Cov)and often other related and un-related viruses, which may or may not extrapolate
>
