### ISSUE TITLE
Feedback: Homepage tweaks 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#702]
## Description

**Q: What is the name of the feature?**

A: Homepage updates

**Q: What does this feature enable the user to do?**

A: Improve the 'narrative', the clarity of the content and the access to information.  

### Mockup

//TODO

### Details

- Carousel
  - Text ‘article’ vs ‘pathway’  or both (interaction + pathways)

- Middle text: Is this for me?
  - ‘chemical and genes’
  - popup or tooltip
    - ‘Is it for me’?
    - ‘Get more information’
- Laptop image: How does it work?
  - focus is on editing here, which opposes the read-only views presented atop
  - ‘How it works’ 

- Call to action (aka 'Get Started')
  - Users who want to get started right away (not naive)
  - Message: 
    - ‘Please enter info below’
    - ‘Email me the link’
    - ‘Add my article’
    - ondone
      - ‘We’ve shared by email’

**Comment by maxkfranz** [comment]
Logging ideas from previous call:

- There should be three distinct sections:
  - (1) We show what the project provides to users with concrete examples of the summaries.
  - (2) We show how it's quick and easy to put in your paper, with a simple GIF-like video.
  - (3) We show our clout and intentions: We highlight the paper, with linkouts, a graphical abstract, etc.
- There should be a CTA button in each section.
- Some menu links, like contact, should also be at the top.

**Comment by jvwong** [comment]
![Home](https://user-images.githubusercontent.com/4706307/80640885-0da2ea80-8a32-11ea-889c-b36b2a785ee8.png)

**Comment by maxkfranz** [comment]
Some notes:

- Anything underneath the carousel of factoids will get overlapped.  Maybe the 'get started' button could go on the top-right.
- The text in the top section, under the carousel, is a lot like the tagline.  Could we update the tagline to include everything we want to say?
- A link to the paper in the third section would be useful.
- The main purpose of the second section is to show that the tool is quick and easy for authors.  Maybe something along the lines of the following: "Our tool makes it easy for authors to input the molecular interactions in their papers.  Create your shareable biofactoid for your paper in just a few minutes."

**Comment by jvwong** [comment]
![Home](https://user-images.githubusercontent.com/4706307/80817038-a6567900-8b9e-11ea-9aff-b3f57010004b.png)

**Comment by maxkfranz** [comment]
@jvwong -- would you please upload a good copy of the 'your pathway to share and explore' section?  We also need a background for that section.  Did you have anything in mind?

**Comment by maxkfranz** [comment]
Basically a high-res version of this, if it's finalised:

<img width="353" alt="Screen Shot 2020-05-12 at 5 20 08 PM" src="https://user-images.githubusercontent.com/989043/81746642-dcd0a580-9474-11ea-9dbf-63a46508158e.png">

**Comment by jvwong** [comment]
@maxkfranz What do you think? A little busier, trying to emphasize 'Your data is linked'

![welcome-aboard2_low-res](https://user-images.githubusercontent.com/4706307/81836672-cb89a680-9511-11ea-9997-666f37897829.png)

**Comment by maxkfranz** [comment]
Looks good.  Some ideas:

- It would be good to have a transparent png background, with only the circles filled in white.
- It may look a bit more aesthetically pleasing if the surrounding circles were more symmetric in their placement.
- We should probably limit the cartoon hand-printed font to the centre circle.

**Comment by jvwong** [comment]
OK this is full size:

![homepage-linked](https://user-images.githubusercontent.com/4706307/81860472-cc7fff80-9534-11ea-8841-ff133562445a.png)

**Comment by maxkfranz** [comment]
Looks good.

Maybe I wasn't clear initially, but I think it's fine to have labels for each of the surrounding circles.  They're important to understand what each one represents.  I just meant that it would be good to use a different font, like Helvetica.

**Comment by jvwong** [comment]
Yeah, I was having a vidid dream that some were too abstract (article')..will update

**Comment by jvwong** [comment]
A little splash of color and labels:

![homepage-linked](https://user-images.githubusercontent.com/4706307/81951635-68604880-95d3-11ea-86b9-e9f53674f4c1.png)

**Comment by jvwong** [comment]
- Try text, logically organized 
- add text for funding source(s) (i.e. Reactome; NIHGRI)

**Comment by jvwong** [comment]
![homepage-linked](https://user-images.githubusercontent.com/4706307/82071927-c446d200-96a4-11ea-8b35-4d9753b84d99.png)

**Comment by sacdallago** [comment]
I much prefer this latter view.

While I get the network idea above, in my experience those types of visualizations add more confusion than they offer insights, no matter how well you design them. In general: interactive "expandable" information sources seem to be already "too complex" and "overloading" for most people I have had to deal with.

What I would suggest is a static approach, like the one you pasted above, where there's a bit of a graphic that reminds people what the goal of this is (networks, links,...), but someone can simply "read" without having to hover or click stuff.

**Comment by jvwong** [comment]
TODO - CTA 'RequestForm' text update.
