### ISSUE TITLE
Edit submitted factoid: disable?

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#707]
## Description

**Q: What is the name of the feature?**

A: Disable editing of submitted factoid

### Details

It seems (from http://biofactoid.org/demo) that submitted factoids can still be edited. Once a submitted factoid is edited, there's no option to "re-submit it". This feels counter intuitive to me: either don't allow to edit, or allow to "amend", or allow to notify that a change is needed.

**Comment by jvwong** [comment]
Yeah I would rather lock this down, it can be manually undone if there's a problem.

**Comment by jvwong** [comment]
Based upon our Tuesday discussions, I think this falls under the category of dealing with issues when they become clear problems. This also applies to the issue of authenticating author contributions, spam - let's see what happens  when we actually get users.
