### ISSUE TITLE
Offer contributed data as bulk file for download 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#717]
## Description

**Q: What is the name of the feature?**

A: Bulk data files 

**Q: What does this feature enable the user to do?**

A: Download files containing pathway data in various formats 

**Q: What information must the user provide to use the feature?**

A: n/a

**Q: How does this feature affect each class of user (persona)?**

A: This is targeted mainly at computational biologists for data analysis applications and other biological databases that may wish to integrate this data.

### Details

- Make available for download
  - BioPAX
  - SIF
  - SBGNML
  - JSON
- Download site?

**Comment by metincansiper** [comment]
@jvwong 
- Do we want them to be both downloadable seperately and as bulk?
- Should the bulk file be a zip file that constains all of the exported files for each format?

**Comment by jvwong** [comment]
> @jvwong
> 
>     * Do we want them to be both downloadable seperately and as bulk?
> 
>     * Should the bulk file be a zip file that constains all of the exported files for each format?

I would say export one single ('bulk') file for each format. See [PC](https://www.pathwaycommons.org/archives/PC2/v12/).

Possible exception is SBGNML: is this even worth exporting? This is where the webservice was useful.

**Comment by metincansiper** [comment]
>I would say export one single ('bulk') file for each format. 

Do you mean one single bulk file that contains each of the formats. I mean something like:

```

- modelid.zip
   - modelid.owl
   - modelid.sif
   - modelid.json

```

The naming would be different.

**Comment by jvwong** [comment]
I meant one single file for each format, zipped:

```
- biofactoid.owl.zip
- biofactoid.sif.zip
- ...
```

**Comment by metincansiper** [comment]
But will there be only one file compressed in each zip?

**Comment by jvwong** [comment]
Yes. Does that make sense?

**Comment by metincansiper** [comment]
Yes actually I guess the only concern is probably decreasing the file size. Initially I thought that we will have a zip file that will include all since we mentioned a "bulk" file. Do you want me to add UI items to download that zip files?

**Comment by jvwong** [comment]
Just create the data dumps for now and we can talk about where to download later...

**Comment by metincansiper** [comment]
Sorry, I am still confused then. What I have initally thought was that we would create these files per document upon user request. 

Now I suspect that you want to create each of these for all document together I mean ``biofactoid.owl.zip`` will include the owl files for each documents. That is why you want data dumps to be created before hand.

Which one is correct?

**Comment by maxkfranz** [comment]
If it’s simpler, I think it’s fine to have one file per factoid in a zip. Basically just reuse the existing export and zip the files together

**Comment by metincansiper** [comment]
>If it’s simpler, I think it’s fine to have one file per factoid in a zip. Basically just reuse the existing export and zip the files together

@maxkfranz probably the easiest way would be getting the a request for exporting a zip for a document/factioid at a time. I mean a user would want to export the zip file for the document. Then we can use the existing services to create files for each format and combine them in a zip. Then download that zip. Does that sound fine?

**Comment by maxkfranz** [comment]
I think that the case for all data for all factoids is the important one here.  A computational biologist who wants info for a particular document can already use the existing API pretty well.

Having zips within zips would be annoying for users.  Just having all factoid data in a one flat zip is fine, e.g.

- biofactoid-bulk.zip
  - id1.biopax
  - id1.sif
  - id1.txt
  - id2.biopax
  - id2.sif
  - id2.txt
  - …

You could just write all the individual files to a directory somewhere and then zip up the dir.  It would be good to offer caching for this route (e.g. the cache is valid for a week), so you’ll probably need to write the zip to disk anyway.

**Comment by metincansiper** [comment]
@maxkfranz Is there any already existing factoid api for retrieving all the documents? I wanted to make sure before I implement such a service. I see that there is ``http://localhost:3000/api/document/`` but it gives me an error when I navigate to that address (``Error: The type 'expression' is invalid for element creation``).

**Comment by maxkfranz** [comment]
I think there’s a GET route for that:

http://unstable.factoid.baderlab.org/api/#/Document/get_api_document

**Comment by metincansiper** [comment]
It was probably not working for me since my existing db would have some documents not compatible with  the current model. I tried to delete the existing database and run factoid again. It works now.

**Comment by jvwong** [comment]
I just want to clarify for myself 1. formats that are being generated ('to format y') and 2.  the source data ('from format x)':

- BioPAX (from Factoid)
- SBGNML (from Factoid/BioPAX)

Here's where I get confused when it comes to 'SIF' vs 'TXT': 

- SIF: Is this from BioPAX? 
- TXT: Is this to 'Extended SIF' or is this the Factoid 'toText' output?

**Comment by metincansiper** [comment]
>I just want to clarify for myself 1. formats that are being generated ('to format y') and 2. the source data ('from format x)':
BioPAX (from Factoid)
SBGNML (from Factoid/BioPAX)
Here's where I get confused when it comes to 'SIF' vs 'TXT':
SIF: Is this from BioPAX?
TXT: Is this to 'Extended SIF' or is this the Factoid 'toText' output?

- I actually do not know anyway of exporting to SIF from factoid. I see that it is in the issue description. probably, that is why I just repeated that. However, I guess that it may not be available.
- About TXT I was planning to use factoid ``toText``.
- @jvwong you were not sure about the SBGNMl do you want it to be included?

**Comment by jvwong** [comment]
>     * I actually do not know anyway of exporting to SIF from factoid. I see that it is in the issue description. probably, that is why I just repeated that. However, I guess that it may not be available.
> 
>     * About TXT I was planning to use factoid `toText`.

- I don't believe `toText` output will be appropriate. In this case, the participant `name` is provided by the user. Also must consider complexes.
- Using the participant association `name` sounds good but these are not intended on being unique across species. So we may consider the NCBI GENE ID? Also must handle complexes.
- Perhaps the least guesswork involves converting from BioPAX? Also see #724.

>     * @jvwong you were not sure about the SBGNMl do you want it to be included?

I don't see any harm in providing this format since we already have the converter.

**Comment by metincansiper** [comment]
>I don't believe toText output will be appropriate. In this case, the participant name is provided by the user. Also must consider complexes.
Using the participant association name sounds good but these are not intended on being unique across species. So we may consider the NCBI GENE ID? Also must handle complexes.

But is what you suggested about updating what txt export content will be. If so maybe we can think it out of this issue. I mean this issue may involve the txt converter anyways but we may have a new issue for upadting that content.

**Comment by jvwong** [comment]
Sure, let's move the SIF/TXT output to another issue.
