### ISSUE TITLE
BioPAX export: Additional attributes

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#724]
## Description

**Q: What is the name of the feature?**

A: Augmenting the BioPAX export data for each pathway

**Q: What does this feature enable the user to do?**

A: Transfers existing useful detail in Biofactoid model to export  

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: BioPAX L3

**Q: How does this feature affect each class of user (persona)?**

A: This generally improves the level of detail available in BioPAX for each pathway

### Details

I noticed some additions to consider:

- Xrefs
  - Including the author's article as bp:PublicationXref
  - Including bp:UnificationXrefs for genes (NCBI's dbXrefs)
- Grouping interactions as bp:Pathway
- Other
  - name/displayName (this is important in how pathways are indexed in PC)
  - organism
- PhysicalEntity type
  - grounding service now provides [`typeOfGene`](https://www.ncbi.nlm.nih.gov/data_specs/dtd/NCBI_Entrezgene.mod.dtd) for NCBI Gene records, to take the guessing out of which subclass to map to (RNA, Protein)  

Would value someone to spot check or use some of the export for this issue and point out any issues.

**Comment by metincansiper** [comment]
>Including bp:UnificationXrefs for genes (NCBI's dbXrefs)

Currently, we are using bp:RelationshipXref with id and namespace of entity from factoid.Based on that: should we keep using the same thing where dbxref is missing? Should we totally switch to bp:UnificationXrefs?

>name/displayName (this is important in how pathways are indexed in PC)

I think we are already doing this.

>grounding service now provides typeOfGene for NCBI Gene records, to take the guessing out of which subclass to map to (RNA, Protein)

We must be doing this with the updates in unsatble branch. Is what you mean different than that?

>Grouping interactions as bp:Pathway

 I could not understand this. The factoid interactions corresponds to the templates that is documented in  a google doc. That templates yields to set of bp:interaction's and their members and relations to each other. Where should we use bp:Pathway?

**Comment by jvwong** [comment]
> > Including bp:UnificationXrefs for genes (NCBI's dbXrefs)
> 
> Currently, we are using bp:RelationshipXref with id and namespace of entity from factoid.Based on that: should we keep using the same thing where dbxref is missing? Should we totally switch to bp:UnificationXrefs?
> 

My mistake, I meant `bp:RelationshipXref` for each dbXrefs, if available.

> > grounding service now provides typeOfGene for NCBI Gene records, to take the guessing out of which subclass to map to (RNA, Protein)
> 
> We must be doing this with the updates in unsatble branch. Is what you mean different than that?
> 

The [grounding-search](https://github.com/PathwayCommons/grounding-search/commit/44966ebfecc80b3dd4a058454752725dafa1f7e2) now provides this field. When available, you can use a subclass (Protein, RNA) rather than the `bp:PhysicalEntity`. Does that make sense?

> > name/displayName (this is important in how pathways are indexed in PC)
> 
> I think we are already doing this.
> 
> > Grouping interactions as bp:Pathway
> 
> I could not understand this. The factoid interactions corresponds to the templates that is documented in a google doc. That templates yields to set of bp:interaction's and their members and relations to each other. Where should we use bp:Pathway?

I think these are all related. How would we attach the PubMedID/organism/displayName to BioPAX exported from a single Biofactoid document?

**Comment by cannin** [comment]
@metincansiper Something that might be useful in testing the BioPAX output. Here is a Java Groovy script to download, validate, and convert to SIF documents from Factoid: https://gist.github.com/cannin/6456e0a2785d18e3236f674168e07179 (Groovy makes it easier to try things out without compiling and I embed commands to grab needed dependencies). 

Also, check this example for several the questions asked: 

https://github.com/BioPAX/specification/blob/master/Level3/examples/biopax3-short-metabolic-pathway.owl

Specifically, the questions around defining: PubMedID/organism/displayName and using Pathway

**Comment by metincansiper** [comment]
Thanks @cannin 

About the bp:Pathway usage I think what I can do is:
- Add a bp:Pathway. 
- For each factoid template (if I am not wrong at the end each of them yields to a bp:Interaction or subclass) add a bp:PathwayComponent and add that component to the bp:Pathway.

@jvwong @cannin Does that sound correct?

**Comment by cannin** [comment]
@metincansiper Yes PathwayComponents in Pathways with PathwayComponents linked to particular Interactions. Make sure whatever you make validates (see my previous message).

**Comment by metincansiper** [comment]
>The grounding-search now provides this field. When available, you can use a subclass (Protein, RNA) rather than the bp:PhysicalEntity. Does that make sense?

@jvwong Okay but we were already assuming that this type is available in a way (with a default and user were able to choose another type). Therefore, I think that it must already be handled there should not be need for any change about that.

**Comment by jvwong** [comment]
> > The grounding-search now provides this field. When available, you can use a subclass (Protein, RNA) rather than the bp:PhysicalEntity. Does that make sense?
> 
> @jvwong Okay but we were already assuming that this type is available in a way (with a default and user were able to choose another type). Therefore, I think that it must already be handled there should not be need for any change about that.

We don't actually use the `typeOfGene` information in factoid. But you can use it if you want.

**Comment by metincansiper** [comment]
> We don't actually use the typeOfGene information in factoid. But you can use it if you want.

Okay my assumption was that the gene type is determined by that in factoid. If that was the case we would use what ever the gene type is.

How is your plan on using ``typeOfGene`` data? 

- As I mentioned I was imagining that it would be used to set the gene type of factoid entities (I mean the currently existing type) (as independent from biopax work). Then no further change is needed for biopax export. This is the option seems the most clear to me.
- Only for biopax export read the ``typeOfGene``. However, in that case what to do with the existing gene type in factoid? Maybe use the existing gene type if ``typeOfGene`` is missing (would it be missing sometimes)?

**Comment by metincansiper** [comment]
About the organisms in the example biopax document of @cannin there is only one organism with id of ``taxon_562`` but it is not associated to anything. Should we just define the organisms existing in the factoid document and no need to associate them to anything?

**Comment by cannin** [comment]
@metincansiper it is good enough that taxon_562 is part of a bp:UnificationXref that specifies the database and ID.

**Comment by metincansiper** [comment]
>@metincansiper it is good enough that taxon_562 is part of a bp:UnificationXref that specifies the database and ID.

Okay, I was meaning specifically about associating the organism with an entity to specify that the entity has that organism. I guess no need for that.

**Comment by cannin** [comment]
@metincansiper I think this is the important one that defines the Pathway to EColi: https://github.com/BioPAX/specification/blob/d55724377d6eec1251075d2012bedcbdb8df48b4/Level3/examples/biopax3-short-metabolic-pathway.owl#L529 it just happens to be defined elsewhere (in the Protein). I assume all Factoid at this point represents only one organism.

**Comment by metincansiper** [comment]
Okay, I understand. Thanks!

**Comment by metincansiper** [comment]
>Ok that's fine.

If so I beleive that what to do about that requires making some desicions like whether to enable users to be able to update the type of gene as they can do now. And I beleive it is not directly related to this issue. I am creating another issue to handle that.

**Comment by metincansiper** [comment]
>Including bp:UnificationXrefs for genes (NCBI's dbXrefs)

@jvwong will we check if the dbXref is from hgnc as we do for the indra queries?

**Comment by jvwong** [comment]
> > Including bp:UnificationXrefs for genes (NCBI's dbXrefs)
> 
> @jvwong will we check if the dbXref is from hgnc as we do for the indra queries?

Is there any reason not to include all of them? We cover many organisms. For example, this arabadopsis gene:

```json
{
  "namespace": "ncbi",
  "type": "ggp",
  "id": "831889",
  "organism": "3702",
  "organismName": "Arabidopsis thaliana",
  "name": "EIN2",
  "synonyms": [
    "ATEIN2",
    "CKR1",
    "CYTOKININ RESISTANT 1",
    "ENHANCED RESPONSE TO ABA3",
    "ERA3",
    "ETHYLENE INSENSITIVE 2",
    "F12E4.10",
    "F12E4_10",
    "ORE2",
    "ORE3",
    "ORESARA 2",
    "ORESARA 3",
    "PIR2",
    "NRAMP metal ion transporter family protein"
  ],
  "dbXrefs": [
    {
      "db": "Araport",
      "id": "AT5G03280"
    },
    {
      "db": "TAIR",
      "id": "AT5G03280"
    }
  ],
  "typeOfGene": "protein-coding"
}
```

**Comment by metincansiper** [comment]
> Is there any reason not to include all of them? 

No actually I just wanted to make sure since we use only hgnc for indra.

**Comment by metincansiper** [comment]
@cannin I tried to run the script as ``groovy factoidBiopaxValidator.groovy``. It gives the following errors. Am I running it wrong?

```
org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 62: The current scope already contains a variable of the name file
 @ line 62, column 6.
   File file = new File(validatorFile);
        ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 29: unable to resolve class org.biopax.validator.BiopaxValidatorClient.RetFormat
 @ line 29, column 1.
   import org.biopax.validator.BiopaxValidatorClient.RetFormat;
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 26: unable to resolve class org.biopax.paxtools.pattern.miner.SIFEnum
 @ line 26, column 1.
   import org.biopax.paxtools.pattern.miner.SIFEnum; 
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 23: unable to resolve class org.biopax.paxtools.io.SimpleIOHandler
 @ line 23, column 1.
   import org.biopax.paxtools.io.SimpleIOHandler;
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 28: unable to resolve class org.biopax.validator.BiopaxValidatorClient
 @ line 28, column 1.
   import org.biopax.validator.BiopaxValidatorClient;
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 30: unable to resolve class org.biopax.validator.jaxb.ValidatorResponse
 @ line 30, column 1.
   import org.biopax.validator.jaxb.ValidatorResponse;
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 22: unable to resolve class org.biopax.paxtools.io.BioPAXIOHandler
 @ line 22, column 1.
   import org.biopax.paxtools.io.BioPAXIOHandler;
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 24: unable to resolve class org.biopax.paxtools.model.Model
 @ line 24, column 1.
   import org.biopax.paxtools.model.Model;
   ^

/Users/siperm/Downloads/factoidBiopaxValidator.groovy: 25: unable to resolve class org.biopax.paxtools.pattern.miner.SIFSearcher
 @ line 25, column 1.
   import org.biopax.paxtools.pattern.miner.SIFSearcher; 
   ^

9 errors
```

**Comment by cannin** [comment]
@metincansiper Check the Gist again: 

https://gist.github.com/cannin/6456e0a2785d18e3236f674168e07179 

I added instructions. There is a trick between running it as a script versus interactive. If not clear, let's have a quick chat.

**Comment by metincansiper** [comment]
@cannin I run the file by updating the urls so that it would point to my localhost instead of unstable factoid to test it with my local changes.

It printed out the sif file below:

```
urn:miriam:chebi:15422	used-to-produce	urn:miriam:chebi:16761
urn:miriam:chebi:15422	consumption-controlled-by	urn:miriam:uniprot:P06493
urn:miriam:chebi:15422	consumption-controlled-by	urn:miriam:uniprot:P36507
urn:miriam:chebi:15422	consumption-controlled-by	urn:miriam:uniprot:Q02750
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P01111
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P01112
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P01116
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P04049
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P31946
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:P36507
urn:miriam:chebi:15996	chemical-affects	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:P05231
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P05231
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:P08887
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P08887
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P23458
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:O60674	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:O60674	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P01112
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01111	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01111	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01112	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01112	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P01116	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P01116	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P04049	in-complex-with	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P04049	neighbor-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P04049	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P04049	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P04049	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P04049	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P08887
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P08887
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P05231	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P05231	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P06493	controls-production-of	urn:miriam:chebi:16761
urn:miriam:uniprot:P06493	controls-phosphorylation-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P06493	controls-state-change-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P06493	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:P23458
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P08887	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P08887	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P23458	neighbor-of	urn:miriam:uniprot:P29597
urn:miriam:uniprot:P23458	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P23458	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P23458	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P23458	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P27361	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P27361	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P28482	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P28482	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P29597	in-complex-with	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P29597	neighbor-of	urn:miriam:uniprot:P40189
urn:miriam:uniprot:P29597	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P29597	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P31946	in-complex-with	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P31946	neighbor-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:P31946	in-complex-with	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P31946	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	controls-production-of	urn:miriam:chebi:16761
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P01111
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P01112
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P28482
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:P36507	controls-phosphorylation-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	controls-state-change-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	controls-transport-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P36507	neighbor-of	urn:miriam:uniprot:Q02750
urn:miriam:uniprot:P40189	in-complex-with	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:P40189	neighbor-of	urn:miriam:uniprot:Q06124
urn:miriam:uniprot:Q02750	controls-production-of	urn:miriam:chebi:16761
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P01111
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P01112
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P01116
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P04049
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P27361
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P31946
urn:miriam:uniprot:Q02750	controls-phosphorylation-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:Q02750	controls-state-change-of	urn:miriam:uniprot:P36507
urn:miriam:uniprot:Q02750	controls-transport-of	urn:miriam:uniprot:P36507
```

**Comment by cannin** [comment]
@metincansiper good, the goal should be export a SIF that makes sense in the context of the Factoid input and is valid
