### ISSUE TITLE
Grounding: Cannot 'Select better match for X'

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#736]
In a manual grounding of a node, the option to 'Select a better match for "X"' does not provide a the additional list of entity records. 

Reproduce:
  - Add entity
  - Type "p53"
  - Click Select a better match for "p53"

The tooltip simply closes.

**Comment by jvwong** [comment]
This actually applies to the edge tooltip as well

**Comment by maxkfranz** [comment]
It seems to be universal.  I’ve taken a look and I may have a fix
