### ISSUE TITLE
Using ``typeOfGene`` property coming from grounding search service

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#737]
## Description

Use ``typeOfGene`` data provided by the grounding search.

**Current behaviour**

``typeOfGene`` coming from grouding search service is not used. The entity type is assigned to the default value of ``ggp`` (if I am not wrong).

**Expected behaviour**

- Use ``typeOfGene`` that is coming from grounding search service to determine the type of factoid entities.

That causes the following questions:

- Whether to keep enabling users to update the type of gene?
- The mapping between ``typeOfGene`` coming from grounding search service and factoid entity types?
- Whether to keep having entity type of ``ggp`` (maybe highly dependent on the answers to the other questions above)?

**Comment by metincansiper** [comment]
@jvwong this is the issue that I mentioned in #724. I think that the answers to the questions in the issue description is important to go forward.

**Comment by jvwong** [comment]
Some background research. 

```
===========================================================================
gene_info                                       recalculated daily
---------------------------------------------------------------------------
...
type of gene:
           the type assigned to the gene according to the list of options
           provided in https://www.ncbi.nlm.nih.gov/IEB/ToolBox/CPP_DOC/lxr/source/src/objects/entrezgene/entrezgene.asn

...
```

Mappings between models:

| type of gene                 | Description                         | Factoid type    |
|------------------------|---------------------------| --------------|
| unknown (0)                  |                                            |ggp                 |
| tRNA    (1)                      |  Transfer RNA                    | rna                 |
|  rRNA    (2)                    |  Ribosomal  RNA               | rna                  |
| snRNA   (3)                   |  Small nuclear RNA            | rna                  |
| scRNA   (4)                   |   small conditional RNA     | rna                  |
| snoRNA  (5)                  |  Small nucleolar RNAs       | rna                 |
| protein-coding (6)        |                                           | protein            |
| pseudo  (7)                   | pseudo                              | dna                 |
| transposon  (8)            |  transposable element      | dna                 |
| miscRNA  (9)                |  miscellaneous RNA          | rna                  |
|  ncRNA (10)                  |  non-coding RNA               | rna                  |
|  biological-region (11)  |                                            | ggp                 |
|  other (255)                  |                                           |  ggp                 |


This issue is also related to #682.

**Comment by jvwong** [comment]
>     * Whether to keep enabling users to update the type of gene?
>
>     * Whether to keep having entity type of `ggp` (maybe highly dependent on the answers to the other questions above)?

The grounding gene type radio and the presence of  `ggp` should all stay. 

The question is: Is it worth trying to guess the type in Factoid? On one hand, we could be wrong (e.g. we default TP53 to a protein, but in reality the user wanted RNA). On other hand, leaving everything as ggp is a little vague.

**Comment by metincansiper** [comment]
>What’s the motivation to remove it?

Actually no motivation based on the other responses. However, initially I suspected that we would be considering ``typeOfGene`` as something that we directly rely on rather then still expecting users to be able to update it. If that was the case there would have been a motivation to remove ggp since I beleive ggp is coming handy mostly when the type is kind of uncertain.

**Comment by metincansiper** [comment]
I see that ``type`` field is still provided by the grounding search service.``typeOfGene`` is also provided now. I guess ``typeOfGene`` would be missing in a lot of cases. So, I will override the ``type`` by using ``typeOfGene`` field and the mapping that Jeff provided if ``typeOfGene`` is available. Else, I will keep using the ``type`` field as is. 

Does that sound right?

**Comment by jvwong** [comment]
> I see that `type` field is still provided by the grounding search service.`typeOfGene` is also provided now. I guess `typeOfGene` would be missing in a lot of cases. 

Why do you believe `typeOfGene` be missing in a lot of cases?

> So, I will override the `type` by using `typeOfGene` field and the mapping that Jeff provided if `typeOfGene` is available. Else, I will keep using the `type` field as is.

Makes sense to me. The mappings default to `ggp` anyways, so its still there.

**Comment by metincansiper** [comment]
>Why do you believe typeOfGene be missing in a lot of cases?

I do not know enough to say a lot actually but if I am not wrong it is not always available. For this case the main point is more of about whether it is always available or not.

**Comment by jvwong** [comment]
I think that the `type of gene` will always exist, but it may be 'unknown' or any of the values in the first column of the table.

**Comment by metincansiper** [comment]
I tried to access it as ``entity.association().typeOfGene`` which returns ``undefined``. Therefore, I thought that it is not supposed to be available always. Also, if it is supposed to be always available how we will use the ``type`` property as ``typeOfGene`` would override it.

**Comment by jvwong** [comment]
Are you pointing it at `GROUNDING_SEARCH_BASE_URL=https://master.grounding.baderlab.org` ? 

The prod instance `https://grounding.baderlab.org` won't have this info.

**Comment by metincansiper** [comment]
Okay, looks like it is available in that way. Then, is there ant usage of ``tyoe`` property now?

**Comment by maxkfranz** [comment]
> Okay, looks like it is available in that way. Then, is there any usage of type property now?

Yes, there is.  [The `type` is an enum](https://github.com/PathwayCommons/factoid/blob/unstable/src/model/element/entity-type.js), and the definition of that enum should not change.  The enum values are there to allow the user to make a choice of type.  `typeOfGene` should remain separate (e.g. `type` should not be set to values like `protein-coding`).

Right now everything from NCBI is set as `ggp` by default, but you can use a different enum value as the default on a case by case basis.  Jeff's table outlines the mapping of `typeOfGene` to default `type`.  The mapping in that table probably won't be correct for every user's paper, so it's important that users are able to manually override the enum value.

**Comment by metincansiper** [comment]
>Yes, there is. The type is an enum, and the definition of that enum should not change. The enum values are there to allow the user to make a choice of type. typeOfGene should remain separate (e.g. type should not be set to values like protein-coding).

Actually, what I mean was not that. I was meaning the ``type`` property that is provided by the grounding search service, not the one in factoid. The grounding search service provides both of ``type`` and ``typeOfGene`` properties. Currently ``type`` is being used to determine the entity type in factoid. What I understand from the discussion here is that I must use ``typeOfGene`` to determine the type in factoid rather than using the ``type`` field.

Therefore, I was wondering if there will still be any usage of the ``type`` field that is provided by the grounding search.

**Comment by metincansiper** [comment]
Shall I close this issue as the related commit is merged?
