### ISSUE TITLE
Related Papers: Search aborts when (PubMed) metadata is missing

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#738]
This concerns retrieving related papers for a given non-empty document. There are two tasks:
  - 1. Retrieve articles (INDRA), based upon the interaction participants present
  - 2. Sort articles (semantic-search), using metadata from the document's associated article

Major issue: If there is no article metadata associated with the document (no abstract), the `searchRelatedPapers` service returns immediately (empty list). The suggestion is to retrieve  articles (i) independent of the ability to sort (ii).

Minor: When no abstract, `searchRelatedPapers`  returns array rather than Promise. This leads to error `searchRelatedPapers( ... ).then is not a function` in no abstract cases and fails to engage the catch in `updateRelatedPapers`

**Comment by gbader** [comment]
Maybe in the future we could generate some text for the similarity search to work on - something like converting the factoid data to some sentences using templates.

**Comment by maxkfranz** [comment]
A text exporter like that already exists, so it may be worth a shot trying this soon. I’m not sure how effectively the templated text would work in place of a real abstract, but it’s probably better than nothing.
