### ISSUE TITLE
Pubmed query flakiness

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#741]
Pubmed queries can return no results, even when there's a perfect match in their database.  This makes it impossible to associate a factoid with an article.  For example, consider the following article:

[Wild-type p53 Oligomerizes More Efficiently Than p53 Hot-Spot Mutants and Overcomes Mutant p53 Gain-Of-Function via a "Dominant-Positive" Mechanism](https://pubmed.ncbi.nlm.nih.gov/30174797)

If you search using the API and the exact title, you get no results.  If you search using the Pubmed search box, you go directly to the paper.  I suspect the NCBI query format is to blame.  It uses a SQL-like query, but that doesn't fit our use case.  It helps in some cases to set the query to use `field=title`, but it doesn't seem to solve the issue completely.

We could just scrape the the new Pubmed search page instead of using the E-utilities search API, e.g.:

https://pubmed.ncbi.nlm.nih.gov/?term=Wild-type+p53+Oligomerizes+More+Efficiently+Than+p53+Hot-Spot+Mutants+and+Overcomes+Mutant+p53+Gain-Of-Function+via+a+%22Dominant-Positive%22+Mechanism

The results page includes a `<meta>` tag that includes the article ID for tools and search engines.  This might not be quite as clean of a solution as using the API directly, but it would be simple and reliable.

Based on some testing with random article titles in Pubmed,  it seems that a not insignificant number of titles fail with the API approach.  I think that it's worth a shot to try scraping since it's cheap to implement.

This approach may also resolve the missing metadata issues (#729, #738) to a large degree.  The results page also includes meta tags for the author list, the journal name, abstract, etc.  Further, articles are published to the Pubmed UI faster than they are available in the API.

**Comment by gbader** [comment]
What about using Google?  It will probably do a better job finding the pubmed ID or DOI or other metadata from a standard database based on the title.

**Comment by maxkfranz** [comment]
The scraping method would only be necessary once per paper, at the time that the user clicks the CTA button on the homepage.  Any heavy tasks, like refresh cron jobs, would be able to use the Pubmed API normally.

The meta tags in the new Pubmed UI strongly suggest that expect these kinds of queries are expected -- that's the purpose of those tags.  Would the people at Pubmed really be against such infrequent requests?  We're not talking about scraping all of Pubmed with thousands of successive requests here:  It's one little request once in a while.

**Comment by maxkfranz** [comment]
> Another to consider is CrossRef. For example, search for journal article by 'bibliographic' info:

This looks great, but I wonder how many journals and institutions have signed up.  Pubmed seems like the most universal source, but we may end up using several sources in the longterm.  Each source has different weaknesses.  For example, Google Scholar might be the fastest but it probably has a lower amount of information with an unreliable method.  CrossRef may be more reliable, but it probably doesn't include every new paper.

Pubmed scraping and Crossref are the lowest hanging fruit of the three.

**Comment by gbader** [comment]
Here's a type of query I was thinking about for Google, where we limit the search to pubmed:

Wild-type p53 Oligomerizes More Efficiently Than p53 Hot-Spot Mutants and Overcomes Mutant p53 Gain-Of-Function via a "Dominant-Positive" Mechanism site:ncbi.nlm.nih.gov

This should find the paper at the top of the list every time if it exists. We could at least follow the first link to pubmed and check that the title is similar enough to the user entered one.  Maybe we could think of a feature later where we ask the user to validate the metadata that comes back similarly to how we do it with entity grounding. And if we can't find anything in the usual sources, then the user could enter the information manually.

**Comment by maxkfranz** [comment]
Google has an API, with several restrictions: https://developers.google.com/custom-search/v1/overview

Google will generally block you if you try to scrape their search results, and the threshold is pretty low.

**Comment by jvwong** [comment]
Action item [jw]: Email EUTILS help desk

**Comment by jvwong** [comment]
NLM Support kindly requests that we do not use the web interface for retrieval of citation data in this way.

**Comment by maxkfranz** [comment]
For now, the most pragmatic improvement that we can make unilaterally is to set `field: 'title'`.  That doesn't fix everything, but it's an improvement.

It's unset right now:

https://github.com/PathwayCommons/factoid/blob/8f477774b67b1e36bb15b620fa12a07a10d1f20f/src/server/routes/api/document/pubmed/searchPubmed.js#L9-L18

**Comment by jvwong** [comment]
That search module needs updating. We had all kinds of wild ideas, but should accept:

- exact title
- PubMed uid
- DOI
