### ISSUE TITLE
On submit: Wait for server response (Tweet) before showing done panel

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#743]
The submit panel should wait for the server to respond before showing the 'done' panel. In particular, assess the status of the Tweet information.

This was previously implemented, but may have been lost in refactoring.

Refs https://github.com/PathwayCommons/factoid/issues/742#issuecomment-638926526

**Comment by jvwong** [comment]
I'm still not nailing doc updates happening on the client vs server, in particular doc status (i.e. 'submitted')....

**Comment by maxkfranz** [comment]
If this issue is difficult to pinpoint, we could do a review of the existing code on a screen-share call

**Comment by jvwong** [comment]
@maxkfranz OK, this is my mount everest. I think we need to talk about this.

**Comment by jvwong** [comment]
Tweet: As far as I can tell, the round trip from client submit --> server --> db is fine. 

However, the  client (tasks.js) seems to be holding onto a stale version of 'document' so it doesn't see the 'tweet'.

**Comment by jvwong** [comment]
nevermind this was a build issue.
