### ISSUE TITLE
INDRA: Queries randomly fail

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#780]
Sometimes INDRA queries randomly fail.  E.g., see @jvwong's example document: https://github.com/PathwayCommons/factoid/pull/777#issuecomment-658975666

Sometimes the queries go through just fine.  Other times, INDRA dies: 

```
Unable to retrieve the indra staments for the entity 19102@HGNC
```

**Comment by jvwong** [comment]
Yes, this morning it was giving off a server error for https://db.indra.bio/latest/statements/from_agents?agent0=CD21@TEXT&agent1=IL-6@TEXT&format=json-js but now it worked

**Comment by maxkfranz** [comment]
Just now I'm getting it failing about half of the time.

**Comment by pagreene** [comment]
@maxkfranz What errors are you getting, specifically?

**Comment by maxkfranz** [comment]
@pagreene, I don't see any details about the error, but it looks like the request might not be getting a response.   @metincansiper, would you be able to track down the specific error?

**Comment by metincansiper** [comment]
No actually I have not coincided the time it was failing.

**Comment by metincansiper** [comment]
@pagreene we are considering to switch to stable version of Indra as it is suggested over Slack. Our main concern is whether there is a big difference in the data for the stable version versus latest version. Do you have any idea about that?

**Comment by pagreene** [comment]
The data will be different, and in particular the content you get from stable is at this point many months old. On the other hand, we are (a) looking to update stable in the near future, but (b) latest should generally be _pretty_ stable generally.

**Comment by maxkfranz** [comment]
At this point, we're prioritising new articles for our related articles feature.  So for now, it's preferable to have fresh data.

**Comment by jvwong** [comment]
This one ([`agent0=19102@HGNC`](https://db.indra.bio/latest/statements/from_agents?agent0=19102@HGNC&format=json-js)) is failing consistently:

```sh
> GET /latest/statements/from_agents?agent0=19102%40HGNC&format=json-js HTTP/2
> Host: db.indra.bio
> user-agent: insomnia/2020.3.3
> accept: */*

* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!

< HTTP/2 502 
< content-type: application/json
< content-length: 36
< date: Mon, 20 Jul 2020 19:53:45 GMT
< x-amzn-requestid: ec7f8c61-f46b-45d7-b296-5efb9fa823ff
< x-amzn-errortype: InternalServerErrorException
< x-amz-apigw-id: P_NqdE8DIAMFXBw=
< x-cache: Error from cloudfront
< via: 1.1 3f97ce77b80aa342632c43cea94d6262.cloudfront.net (CloudFront)
< x-amz-cf-pop: YTO50-C2
< x-amz-cf-id: d4YF52Bkt8vaNJ8Km2T33-dLBM5FAUDYPY4J1SMesi6GNyfxODSvPQ==
```

**Comment by pagreene** [comment]
It looks like there are a couple possible issues you are facing. The API logs suggest that the core issue is that the Query is too large. That said, the particular query you show above was successful for me. The HTML version however was not, but for a different reason for which we already have a fix that simply hasn't been pushed to the deployed version yet (I am doing that now).

**Comment by jvwong** [comment]
> It looks like there are a couple possible issues you are facing. The API logs suggest that the core issue is that the Query is too large. That said, the particular query you show above was successful for me. The HTML version however was not, but for a different reason for which we already have a fix that simply hasn't been pushed to the deployed version yet (I am doing that now).

It works for me from a browser (Firefox, 78.0.2 (64-bit); Chrome Version 84.0.4147.89 (Official Build) (64-bit)) but not with my Mac client (Insomnia Version 2020.3.3 (2020.3.3)), and I see it working in our app, at least we are getting results.

I guess I can just use the browser too check

**Comment by pagreene** [comment]
Could you try your query on `db.indra.bio/dev` and tell me if that works?

**Comment by jvwong** [comment]
That didn't work on my Insomnia client:

```
* Preparing request to https://db.indra.bio/dev/statements/from_agents?agent0=19102%40HGNC&format=json-js
* Current time is 2020-07-20T20:28:52.615Z
* Using libcurl/7.69.1 OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.7 libidn2/2.1.1 libssh2/1.9.0 nghttp2/1.40.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Disable SSL validation
* Enable cookie sending with jar of 0 cookies
* 9 bytes stray data read before trying h2 connection
* Found bundle for host db.indra.bio: 0x7fe79107acc0 [can multiplex]
* Re-using existing connection! (#1) with host db.indra.bio
* Connected to db.indra.bio (13.226.143.18) port 443 (#1)
* Using Stream ID: 3 (easy handle 0x7fe77f1f1000)

> GET /dev/statements/from_agents?agent0=19102%40HGNC&format=json-js HTTP/2
> Host: db.indra.bio
> user-agent: insomnia/2020.3.3
> accept: */*

< HTTP/2 502 
< content-type: application/json
< content-length: 36
< date: Mon, 20 Jul 2020 20:28:59 GMT
< x-amzn-requestid: 6fda9e2e-6b81-4f6c-b9c8-273902ea9a10
< x-amzn-errortype: InternalServerErrorException
< x-amz-apigw-id: P_S07GyjIAMFZ5w=
< x-cache: Error from cloudfront
< via: 1.1 415bce851abed41a15ccdf56a782926a.cloudfront.net (CloudFront)
< x-amz-cf-pop: YTO50-C2
< x-amz-cf-id: I_EcJcKQG1wu77lYF5fF_IQGzcqeWWVtcL1nbdE7Y84VgXVpFnR8Yg==
```

**Comment by pagreene** [comment]
There seems to be something special about insomnia that is causing this. I can replicate the issue you're having when I run the query in `insomnia` (I've never used it before, and so never would have thought to test it). Somehow it seems insomnia is compelling the API to produce a larger result than it would otherwise, and this is _after_ the result has left the Python Flask API. The last thing our code does is report on the size of the response to try to address this very issue, but the size at that point is the same.

Looking some more, _it seems that insomnia is somehow forcing the API to not compress the response_, which is causing the issue. I have no idea how it is doing that, or why, but there's your problem.

**Comment by gbader** [comment]
Jeff - modern browsers request compressed content via the http-accept-gzip flag. When they do this, the web server will compress the content.  If you're using a download tool that doesn't do this, you will get uncompressed content. So whenever downloading over HTTP, if you want it to be fast, the http-accept-gzip should always be turned on. see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding

**Comment by jvwong** [comment]
OK yes that did the trick!
