### ISSUE TITLE
Related Papers: Improving robustness by providing fallback and recovering upon initial failure  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#785]
Background: The related papers feature relies upon external (third-party) services to obtain information about PubMed articles used to populate the Factoid document and subsequently the explorer view (UI).

Issue:  The article information may not be available at the time of request, which in this case, follows immediately after document submission through the editor. The relevant document data will not be updated and there is no further attempt to retrieve this information. Another side-effect is that explorer view displays a persistent 'waiting'-type message.  

- Requirements
  - Provide a fallback when the system is unable to retrieve articles externally
    - At least remove the 'infinite spinner' 
    - Could consider informative note or even back-up data for users
  - Attempt to retrieve articles for documents where a related-paper update has not been achieved
    - My experience is that INDRA retrieval failures can persist for prolonged periods (minutes)
    - We do have a cron service that we could make use of 

Refs #780, feedback from @cannin

**Comment by maxkfranz** [comment]
Here's a document that fails repeatedly: https://unstable.factoid.baderlab.org/document/a6051ebc-216b-4513-b19a-d29f266cee8e

**Comment by maxkfranz** [comment]
Non-human text queries seem to be more fragile, but sometimes they work if you retry soon after the failure (i.e. within seconds).  Something like this may be a simple mitigation for this case: https://www.npmjs.com/package/fetch-retry

For longer error durations, the same approach could be used with a slightly different strategy (e.g. try three times quickly, then try again every few minutes).

We may also reconsider using a different, more reliable version of Indra.

**Comment by maxkfranz** [comment]
@metincansiper, would you be able to evaluate the fetch-retry approach with your Indra queries?

**Comment by jvwong** [comment]
> Here's a document that fails repeatedly: https://unstable.factoid.baderlab.org/document/a6051ebc-216b-4513-b19a-d29f266cee8e

I can reproduce locally. Getting a lot of these in response from INDRA: 

```json
{"message":"Endpoint request timed out"}
```

Also, as I recall, Promise.all is an 'all or none' with regards to success/error.

**Comment by jvwong** [comment]
For the above pathway, once I hit submit with anything below 4 interactions I got successful results back. Above 3 interactions, it gives me that error and the whole thing dies.

**Comment by maxkfranz** [comment]
(1) It can happen even with a single interaction. Larger pathways would then increase the probability of overall failure, because there are more chances for individual failure.

(2) There is also the possibility of failure due to load. 

A simple retry approach would address (1) well, but more complexity (e.g. backoff or a queue) would be necessary in the case of (2).  I suspect we have both (1) and (2).

**Comment by maxkfranz** [comment]
Notes:

- This may be an opportunity to leverage AppSignal.  Related papers errors could be logged as critical errors, with notifications.  Even if our mitigations aren't 100%, at least we'd be able to respond to errors right away.
- We should reevaluate the use of the older version of Indra.

**Comment by metincansiper** [comment]
@maxkfranz @jvwong 

I could not make it work for the document that Jeff mentioned by using ``fetch-retry``. Then, I realized that it gives no error when I query related papers for each factoid element and the whole document synchronously as in the PR #793. 

With #793 the examle document of Jeff gives no error but finds no related papers neither in entities level nor in document level. I tried another factoid document with TP53 and MDM2 it worked fine though.

**Comment by metincansiper** [comment]
I realized that no problem in making the query for the elements all together. However, the problem occurs when the query for the whole document is done asynchronously with the queries with the elements. Therefore, I kept doing the queries for the elements asynchronously and made the query for the whole document right after that. I updated the PR in that way.

**Comment by maxkfranz** [comment]
I'm seeing individual (per-node) Indra query errors from time to time.  #793 has made things better, but occasionally there are still fetch errors.  @metincansiper, do you think it would make sense to revisit the simple fetch retry approach?

**Comment by jvwong** [comment]
Yeah i got errors yesterday submitting documents with 1 interaction.

**Comment by maxkfranz** [comment]
> Yeah i got errors yesterday submitting documents with 1 interaction.

I also had a single-interaction document fail.  One of the queries for a single protein failed.

**Comment by maxkfranz** [comment]
Here's one example:

```
error:   Unable to retrieve the indra staments for the entity 11892@HGNC
error:    TypeError: Cannot convert undefined or null to object
```

<img width="655" alt="Screen Shot 2020-08-19 at 11 02 37" src="https://user-images.githubusercontent.com/989043/90651880-8dd0a400-e20b-11ea-8663-3264608f163c.png">
<img width="655" alt="Screen Shot 2020-08-19 at 11 02 43" src="https://user-images.githubusercontent.com/989043/90651885-8f01d100-e20b-11ea-8661-8517c437ec19.png">

**Comment by metincansiper** [comment]
@maxkfranz I created #817 that makes use of ``fetch-retry``. However, the example that you show have been working for me with the regular ``fetch`` library as well in all of the few trials.

**Comment by maxkfranz** [comment]
Yes, it's a bit random.  Sometimes it works OK, sometimes not.  Since the mitigation is simple, it's probably best to just merge it in so everyone can test it on unstable.
