### ISSUE TITLE
Post submission popover has overflowing URL

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#787]
<img width="515" alt="Screen Shot 2020-07-28 at 14 18 23" src="https://user-images.githubusercontent.com/989043/88705254-43ad4480-d0dd-11ea-8a53-fc70fd2fb8b1.png">

**Comment by jvwong** [comment]
Two more things I noticed:

1. The link is gone in Safari (Version 13.1.1 (15609.2.9.1.2))
<img width="330" alt="image" src="https://user-images.githubusercontent.com/4706307/88818913-48313600-d18d-11ea-860f-93214965657d.png">

2. The horizontal bar is shifted

**Comment by jvwong** [comment]
What browser are you using for the initial issue image? I can't reproduce that.

**Comment by maxkfranz** [comment]
Chrome
