### ISSUE TITLE
Grounding Organism: Erroneous entries available in dropdown  

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#794]
In some cases, when a node is grounded, entries appear in the Organism drop-down that are not organisms. 

### To Reproduce

- Create and label node 'S'
- Select better match from Drosophila melanogaster:
  - Synonyms 'CG4385Dmel\CG4385E(Raf)2BEC2-2EK2-2S-PBl(2)21EbStar/asteroidES2-4fltr'
- Click 'Organism' drop down selector

Seems like the top search hits (chebi) get pushed into this list.

<img width="467" alt="image" src="https://user-images.githubusercontent.com/4706307/89795380-53258800-daf6-11ea-9190-e4d59e7b623d.png">

**Comment by maxkfranz** [comment]
@metincansiper, would you take a look at this one?

**Comment by jvwong** [comment]
Let me integrate changes around #798 first, so that we can take care all any additional problems around having sars-sov-2 proteins in the results sets

**Comment by metincansiper** [comment]
>@metincansiper, would you take a look at this one?

Sure, I am looking at it.

**Comment by metincansiper** [comment]
> Let me integrate changes around #798 first, so that we can take care all any additional problems around having sars-sov-2 proteins in the results sets

Okay, I can look to figure out what is wrong and can make the actual change after you are done with it.
