### ISSUE TITLE
Look in PubMed search results for a match to an author's paperId

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#795]
Factoid should be matching an article when it is returned as an element of the uid results from NCBI ESEARCH. There are edge cases where this is not happening:

Example failure:  
- ['A SARS-CoV-2 protein interaction map reveals targets for drug repurposing' Nature. 2020 Jul;583(7816):459-468.  2020 ](https://pubmed.ncbi.nlm.nih.gov/32353859/]

The reason for the failure is that we used a heuristic for a 'match': One result returned from ESEARCH is a match, otherwise there is no match.

In this case, ESEARCH returns 2 uids, one for the article above and one for the corresponding bioRxiv preprint ([A SARS-CoV-2-Human Protein-Protein Interaction Map Reveals Drug Targets and Potential Drug-Repurposing](https://pubmed.ncbi.nlm.nih.gov/32511329/)). If you do a search for the bioRxiv preprint title, you get a single matching result.

**Comment by jvwong** [comment]
This is not a bug but rather expected behaviour. 

I mistakenly assumed that I integrated changes discussed as part of #764, that is [Look in the top ESEARCH hits for a match](https://github.com/PathwayCommons/factoid/pull/764#pullrequestreview-444916006). Right now we just throw if a single UID isn't returned from PubMed.

I think this branch (#764) is worth updating because of the  growing presence of valid matches that get returned alongside other articles (ie. bioRXiv preprints corresponding to the article - see above; https://github.com/PathwayCommons/factoid/pull/764#issuecomment-662676037). Last I left that PR branch, the strategy was (new stuff in bold):

- Categorize  user's `paperId` type (`DOI`, `PMID`, `TITLE`) then search PubMed 
- **Look through (top 10) search hits for matching article**

**Comment by maxkfranz** [comment]
Makes sense to merge #764, as long as the Crossref stuff isn't active yet.

**Comment by jvwong** [comment]
The code has diverged too much, I just have a simpler one-file PR I'll put up that looks at the search results.
