### ISSUE TITLE
Related papers: Seed articles

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#801]
#### Background

A few issues surrounding the related papers, both technically and from a quality standpoint:

- Articles retrieved based upon querying with for a entity (gene, chemical), are frankly less than relevant #782 #784
- New papers, generally with novel interactions, will be padded with these entity-based papers
- Desire to provide/display related papers ASAP
- INDRA can fail, with no strategy for recovery
- What a 'document'-level related paper is, is unclear; currently a reshuffling of network-based papers

#### Requirements

Ideally, we'd like to have a set of 'seed' related articles that are relevant to the paper, from a relatively stable service, that can also be used to add-upon with subsequent queries for related papers (i.e. INDRA), and are available right away. 

#### Proposed

When an author inputs their article title, we populate the document with article information. The suggestion is to immediately retrieve pmids linked to the paper via [ELINK](https://dataguide.nlm.nih.gov/eutilities/utilities.html#elink):

- article types
  - related
  - papers citing (incoming)
  - references (outgoing
  - reviews
  - also viewed

Notes: Can configure to return date range (published less than 100 days ago) or any subset (citing this article). An article from Mol Cell published 6 days ago [returned 130 pmids](https://eutils.ncbi.nlm.nih.gov/entrez/eutils/elink.fcgi?id=32755595&retmode=json&db=pubmed&dbfrom=pubmed).  

PS: The service also provides the ability to link from 'UID' (gene/protein) to articles, that is, can be used to seed the entity-level papers.

**Comment by maxkfranz** [comment]
> Desire to provide/display related papers ASAP

It would be great to get Elink related papers shown without having to wait for Indra results.  We may have several phases:

(1) Elink results are just appended to the regular workflow.  This covers Indra failures and requires minimal structural changes.

(2) Elink results are queried and sorted independently from Indra results.  This allows for showing related papers quicker after submission.  This requires more structural changes, and there are UX concerns (i.e. the list refreshes twice).

For now, it may be more prudent to just focus on phase (1).

**Comment by jvwong** [comment]
Task plan:

- [ ] Implement ELINK service wrapper(s)
  - link from
    - db=gene uid(s)
    - db=pubmed uid(s)
- [ ] Update related papers retrieval
  - TODO - need to consider appending pmids with INDRA data
