### ISSUE TITLE
Article data is sometimes being not available while exporting to biopax

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#821]
I am meaning the variable in this line (https://github.com/PathwayCommons/factoid/blob/unstable/src/model/document/document.js#L474). So far I was able to reproduce the issue only in some of the documents where a pubmed id or title is not specified upon the creation of Factoid document.

**Comment by jvwong** [comment]
You're correct. I created the `citation` attribute (https://github.com/PathwayCommons/factoid/blob/unstable/src/model/document/document.js#L212) and generally access anything to do with the article I need there. If there's no pubmed ID found, it inserts the user's input into `title`

**Comment by maxkfranz** [comment]
The motivation for the separation of that data is to reduce coupling.  If you use the Pubmed data directly, it's fragile to changes on Pubmed's side.  Also, the processed `citation` is generally more convenient to use.

**Comment by metincansiper** [comment]
Okay, should I set the ``pubId`` and ``pubDb`` variables here and the next line (https://github.com/PathwayCommons/factoid/blob/unstable/src/model/document/document.js#L475) as ``undefined`` when ``articleData`` is not available by https://github.com/PathwayCommons/factoid/blob/unstable/src/model/document/document.js#L474?

**Comment by maxkfranz** [comment]
Yes, it's generally better to use `citation` everywhere possible.

**Comment by maxkfranz** [comment]
@metincansiper, do you need any more information re. this issue from me or @jvwong?  I think it's fine to use the `citation` data and fall back on `null` when particular fields are unavailable.

**Comment by metincansiper** [comment]
@maxkfranz @jvwong  if I see that ``citation`` data includes ``pmId`` field. ``article`` data was providing both ``id`` and ``idType`` I think ``idType`` would have values like ``pubmed``. Is it always supposed to be ``pubmed``? If so can I just use the ``pmId`` from ``citation`` as ``pubId`` and set ``pubDb`` always as ``pubmed``?

**Comment by jvwong** [comment]
> Is it always supposed to be `pubmed`

The `document.article().PubmedData.ArticleIdList` field can have different IdTypes: https://dtd.nlm.nih.gov/ncbi/pubmed/doc/out/180101/el-ArticleId.html

In fact , I think you point out a bug in the code (L474), as the array needs to be filtered for `IdType` === `pubmed` 

https://github.com/PathwayCommons/factoid/blob/c73aa65cfa0ce37f23f912831a1d0fe8d928b420/src/model/document/document.js#L474-L478


>  If so can I just use the pmId from citation as pubId and set pubDb always as pubmed?

This would work, but the value of `document.citation().pmid` might be `null`. For example, someone input an article title that we can't find in Pubmed.

**Comment by metincansiper** [comment]
>This would work, but the value of document.citation().pmid might be null. For example, someone input an article title that we can't find in Pubmed.

``articleData.id`` can also be empty. Are ``articleData.id`` and ``document.citation().pmid`` being ``null`` at the same cases?

**Comment by jvwong** [comment]
> articleData.id can also be empty. Are articleData.id and document.citation().pmid being null at the same cases?

Short answer: Yes.


Longer answer:
- Case: An author enters an article, and we can't find the article in PubMed,
  -  Provide a mock `PubMedArticle` where the `PubmedData.ArticleIdList` is an empty array: https://github.com/PathwayCommons/factoid/blob/c73aa65cfa0ce37f23f912831a1d0fe8d928b420/src/util/pubmed.js#L180
  - Insert the author input `articleId` as the `MedlineCitation.Article.ArticleTitle` 
  - document.citation() just looks in the mock object to get the data

**Comment by maxkfranz** [comment]
Options:

(1) Omit missing data in the biopax.

(2) Filter out documents that have missing data.  The biopax is unavailable until the pubmed metadata is refreshed by the cron job (in a day or so -- no big deal).

Option (1) is preferable, but I think (2) is fine if (1) is not tractable.

**Comment by metincansiper** [comment]
I created #830 for this. It works like (1) the java code was already suitable for(1).
