### ISSUE TITLE
Entity tooltip, shows erroneous entries for organism selector

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#822]
There are still strange entries popping up in the entity tooltip selector. This time, I observed multiples of the same species with different text in parentheses.

Reproduce by adding entity, labelling 'U6' and inspecting the Organism drop down:

<img width="430" alt="image" src="https://user-images.githubusercontent.com/4706307/92157798-ef426680-edf8-11ea-86dc-ef323f299aea.png">

**Comment by maxkfranz** [comment]
As you know, some organisms have completely ambiguous gene names, where several genes have the exact same name. U6 and P53 are examples for drosophila. They only differ by the ‘official’ NCBI name and (to some degree) synonyms. 

Those ambiguous options must be available, either in the existing organism dropdown or in an additional ‘which p53’ dropdown (i.e. if the selected organism is ambiguous, then a second disambiguation dropdown is shown).

**Comment by maxkfranz** [comment]
Something like this (in-progress):

<img width="441" alt="Screen Shot 2020-09-09 at 18 00 00" src="https://user-images.githubusercontent.com/989043/92659464-69299280-f2c6-11ea-8963-d2613d6aa31e.png">

<img width="460" alt="Screen Shot 2020-09-09 at 18 01 34" src="https://user-images.githubusercontent.com/989043/92659536-88282480-f2c6-11ea-9731-c36da685f192.png">

**Comment by jvwong** [comment]
I'm realizing the reason I'm raising all these issues, is that I am misinterpreting how this drop-down works or it's intention. I just assumed the organism dropdown was selecting 'orthologues', that is, a 'similar' gene from different organisms. However, its almost acting like a 'shortcut' for the 'Select a better match'? 

I noted a while back that having an 'organism' selector of some sort can be helpful. But the current version will be confusing to biologists (like me).

**Comment by jvwong** [comment]
Maybe for now, we just display the organism of the entry? Later we can revisit the idea of constraining the search to a given organism, which I think can be helpful.
