### ISSUE TITLE
Admin: Allow manual refresh of all related papers data

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#827]
Right now, the admin only hooks into the function for updating doc-level related papers, the same one use when an article is first entered into the system. 

Allow admin to trigger the a network-level search for related papers

Notes:

**Comment by maxkfranz** [comment]
@jvwong, removing this from the milestone, unless you think it's easy to add it in today.

**Comment by jvwong** [comment]
Will look now..

**Comment by jvwong** [comment]
yeah let's punt this to the next version, it won't affect what users will see if INDRA holds up.

**Comment by maxkfranz** [comment]
I think you can still just demote the doc `status` and then resubmit if you really need to retry Indra.

**Comment by maxkfranz** [comment]
Maybe just use something like an `update = { op: 'refresh', name: 'relatedPapers' }` that kicks off only `updateRelatedPapers()`:

https://github.com/PathwayCommons/factoid/blob/68639511867120229ae61c9555d3a4793f66b823/src/server/routes/api/document/index.js#L1411-L1433

**Comment by jvwong** [comment]
makes sense. Also should add to the cron in `update.js`
