### ISSUE TITLE
Prod builds of homepage place logo too close to text on small screens

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#829]
Only affects small screens, like iphone:

<img width="569" alt="Screen Shot 2020-09-14 at 9 28 09 AM" src="https://user-images.githubusercontent.com/989043/93091987-d5ace480-f66c-11ea-8c0e-d9f819080c2c.png">

The 'recently shared articles' label could also stand to be a bit closer to the carousel on small screens.

**Comment by jvwong** [comment]
I saw this on Firefox v28 for iOS: 
<img src="https://user-images.githubusercontent.com/4706307/93093004-2e30b180-f66e-11ea-9815-417eda668866.jpg"  height="400px" />
