### ISSUE TITLE
Release 0.10.1

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#834]
- [x] Create 0.10.1 release PR
  - [x] Tag 0.10.1 in PR
  - [x] Merge to master
- [x] Update docker images
- [x] Deploy

**Comment by jvwong** [comment]
I always get confused with tags - did you create them and push them up?

**Comment by maxkfranz** [comment]
I omitted the tag in case you wanted to cherry-pick in #827.  One minute

**Comment by maxkfranz** [comment]
OK, 6379a433 should be tagged v0.10.1

**Comment by jvwong** [comment]
OK the Docker kicked off, will swap out soon, try it out and send out emails tomo.
