### ISSUE TITLE
PC-2-factoid: Supplementing the Factoid database with curated interactions

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#836]
## Description

**Q: What is the name of the feature?**

A: Add to Factoid database documents, created from an external (existing) database 

**Q: What does this feature enable the user to do?**

A: Access more (expert-)curated interactions supported by literature via Factoid 

**Q: What are the applicable constraints, e.g. compatibility or performance?**

- General criteria for selecting external datasource to create Factoid documents: 
  - Interactions tied directly to publication (pmid)
  - Interactions supported by (low-throughput) evidence
  - Interaction types that are in-line with the Factoid model 
  - Data available, in usable format

**Q: How does this feature affect each class of user (persona)?**

There are a few benefits to introducing external data into Factoid database:

  a) 'Frame-out' the Factoid app with useful, quality, curated data
  b) A lot is data for older articles that wouldn’t otherwise be curated
  c) Can serve as pre-made Factoids that we can ask the authors to ‘verify’
  d) Begins the idea of unifying PC and Factoid (search/import)
 
## Specification

- Input
  - Datasource: PhosphositePlus looks like it might fit the general selection criteria (above)
- Output
  - For each PMID, a representation of a Factoid document 
  - Compatible with batch entry into Factoid

### Details

1. Fetch data file

My first thought is to use [PhosphositePlus (PSP) PC BioPAX](https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.psp.BIOPAX.owl.gz)

2. Filter Interactions

- By experimental evidence
  - PSP provides information about the type of experimental procedure used to verify the interaction and we would want only keep those referencing with 'Low-throughput papers (LTP)' approaches
    - i.e. `bp:Evidence` with `bp:evidenceCode` one of
      - mutation analysis (MI:0074)
      - identification by antibody (MI:0421)
      - western blot (MI:0113)

3. Group interactions

Factoid documents are one-to-one with articles, and interactions are added to an article/document. So in this case, interactions would have to be grouped under the same PMID. Not sure how many PSP interactions fall under the same PMID, and I wouldn't merge genes/interactions in output

4. Map to document JSON

- Use the document API for import: `doc.fromJson(obj)`
- Refer to the JSON format from the files in the zip download as a reference: https://biofactoid.org/api/document/zip
- Main fields are
  - `id` : new uuid
  - `elements`: new uuid
  - `secret` (might be generated for you)
- Create a new document with POST /api/document
  - This route should accept a new `elements` field so you can specify the proteins and interactions (`elements` should just be in the json format)
  - Alternative 1: Import using `doc.fromJson()`
  - Alternative 2: 
    - Create the `Elements` using the element API
    - Use the element factory (src/model/element/factory)
    - Once you have the concrete element object, use the methods in the object to correspond to the posted `elements` json

https://github.com/PathwayCommons/factoid/blob/d145d5735e34e719acd8ed380786e9f6bec79a86/src/server/routes/api/document/index.js#L1239-L1265

5. Load into Factoid

- We will need additional UI in the admin interface to add new documents from biopax (new + button)
- We will need to use the existing services re. "submission" in order to update the doc state (e.g. published) and to get metadata (e.g. pubmed info)
  - Some of the workflow for the submission PATCH service will have change (e.g. no tweet, no email, ...)

### Notes

- Might want to tag such documents by database source so they can be filtered / removed (maybe a new metadata field, using the metadata API in `Document`)
- Convert uniprot ids or use as-is?

**Comment by maxkfranz** [comment]
https://github.com/PathwayCommons/factoid/blob/v0.10.1/src/server/routes/api/document/index.js#L1239-L1265

**Comment by metincansiper** [comment]
@jvwong Is the evidence code that you mention like the ``eco`` in the following?

```
<bp:RelationshipXref rdf:ID="RelationshipXref_3595accc-f8ba-485c-abae-5b241ba43b55http___www_humanmetabolism_org__relationshipxref_1089218069">
 <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc12/RelationshipXref_3595accc-f8ba-485c-abae-5b241ba43b55http___www_humanmetabolism_org__relationshipxref_1089218069</bp:comment>
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">ECO:0000000</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">evidence code ontology</bp:db>
</bp:RelationshipXref>
```

**Comment by jvwong** [comment]
> @jvwong Is the evidence code that you mention like the `eco` in the following?
> 
> ```
> <bp:RelationshipXref rdf:ID="RelationshipXref_3595accc-f8ba-485c-abae-5b241ba43b55http___www_humanmetabolism_org__relationshipxref_1089218069">
>  <bp:comment rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">REPLACED http://pathwaycommons.org/pc12/RelationshipXref_3595accc-f8ba-485c-abae-5b241ba43b55http___www_humanmetabolism_org__relationshipxref_1089218069</bp:comment>
>  <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">ECO:0000000</bp:id>
>  <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">evidence code ontology</bp:db>
> </bp:RelationshipXref>
> ```

Not sure what you are asking. The evidence codes for PhosphoSitePlus are from MI ontology

```xml
<bp:EvidenceCodeVocabulary rdf:ID="EvidenceCodeVocabulary_8e1e80bfab79984903b7e3804345048e">
 <bp:xref rdf:resource="#UnificationXref_molecular_interactions_ontology_MI_0421" />
 <bp:term rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">identification by antibody</bp:term>
</bp:EvidenceCodeVocabulary>

...

<bp:EvidenceCodeVocabulary rdf:ID="EvidenceCodeVocabulary_71fe7be44e80879bb8505ec68b171f5c">
 <bp:xref rdf:resource="#UnificationXref_molecular_interactions_ontology_MI_0113" />
 <bp:term rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">western blot</bp:term>
</bp:EvidenceCodeVocabulary>
```

**Comment by metincansiper** [comment]
>Not sure what you are asking. The evidence codes for PhosphoSitePlus are from MI ontology

Okay, actually it was obvious. I was actually looking for something similar but for some reason I got confused later. Now, I see that.

**Comment by metincansiper** [comment]
As reflected in biopax section of factoid binary interactions document: to reflect a factoid interaction we sometimes create a biopax interaction and another one that is the controlled of that interaction. Therefore, I selected the biopax interactions who is not the controlled of another biopax interaction as my root interactions. Then, looked for some patterns starting from these roots. Therefore, I also make the evidence/evidence code based filtering on these root interactions.

The problem is that: in the PhosphoSitePlus biopax file there are some interactions associated with evidences but all of these are controlled of some other interactions. In another word, none of the root interactions have any evidence. Therefore, I end up with having no interaction passing through the filter. 

Does my approach to get started with root interactions sounds right? If that sounds right should I consider checking the evidence of controlled interactions as well when the root interaction does not have any evidence?

**Comment by maxkfranz** [comment]
A lot of candidates probably are controller-controlled.  Have you revisited the 'Factoid binary interaction types' document.  That describes the conversion rules.  You'd just have to go in the opposite direction.

**Comment by jvwong** [comment]
PSP puts all the PublicationXref and Evidence attributes on the controlled interaction.

**Comment by metincansiper** [comment]
>A lot of candidates probably are controller-controlled. Have you revisited the 'Factoid binary interaction types' document. That describes the conversion rules. You'd just have to go in the opposite direction.

Yes, I did so.

>PSP puts all the PublicationXref and Evidence attributes on the controlled interaction.

Okay, I was thinking that they would be in the controller. Then, I can check the controlled interaction.

**Comment by metincansiper** [comment]
>PSP puts all the PublicationXref and Evidence attributes on the controlled interaction.

Considering the factoid binary interaction types there is a type of ``MolecularInteraction`` which cannot have a controlled. In this case if I eliminate the interactions that does not have evidence then I will always be skipping ``MolecularInteraction``. Also, since you mentioned that the PublicationXref is also stored in the controller, we will be skipping that anyways. Should I delete the case that considers the ``MolecularInteraction`` since it will never work in practice?

**Comment by jvwong** [comment]
> > PSP puts all the PublicationXref and Evidence attributes on the controlled interaction.
> 
> Considering the factoid binary interaction types there is a type of `MolecularInteraction` which cannot have a controlled. In this case if I eliminate the interactions that does not have evidence then I will always be skipping `MolecularInteraction`. Also, since you mentioned that the PublicationXref is also stored in the controller, we will be skipping that anyways. Should I delete the case that considers the `MolecularInteraction` since it will never work in practice?

The important criteria are:
 - 1. Has a pubmed id
 - 2. Has evidence that refers to a 'low throughput' experimental technique

**Comment by metincansiper** [comment]
The json format I currently have is the following:

```
{
"2026614": [
    {
      "type": "protein",
      "name": "INSR",
      "association": {
        "dbXrefs": [
          
        ]
      },
      "id": "e94119f1-a386-4838-a294-f7427b6dd727"
    },
    {
      "type": "protein",
      "name": "INSR iso2",
      "association": {
        "dbXrefs": [
          
        ]
      },
      "id": "fe885c5c-6b77-495c-9ce1-669c1175cb8d"
    },
    {
      "type": "interaction",
      "association": "interaction",
      "entries": [
        {
          "id": "e94119f1-a386-4838-a294-f7427b6dd727"
        },
        {
          "id": "fe885c5c-6b77-495c-9ce1-669c1175cb8d",
          "group": "positive"
        }
      ],
      "id": "58918a65-3df4-4573-911d-8be4d18c233d"
    }
  ]
}
```

I could not find any entity in the PhosphoSitePlus file where a physicalentity have xrefs. Do you think it would make sense to eliminate the physicalentity xrefs corresponding to associtation.dbXrefs in the example above?

Anything else looking wrong in the format?

**Comment by metincansiper** [comment]
I added an ``elements`` parameter to the service as discussed here. Then I wanted to test it with the following script:

```
const fetch = require('node-fetch');

var jsonStr = `
[
  {
    "type": "protein",
    "name": "TP53",
    "id": "e94119f1-a386-4838-a294-f7427b6dd721"
  },
  {
    "type": "protein",
    "name": "MDM2",
    "id": "fe885c5c-6b77-495c-9ce1-669c1175cb8z"
  },
  {
    "type": "interaction",
    "association": "interaction",
    "entries": [
      {
        "id": "e94119f1-a386-4838-a294-f7427b6dd721"
      },
      {
        "id": "fe885c5c-6b77-495c-9ce1-669c1175cb8z",
        "group": "positive"
      }
    ],
    "id": "58918a65-3df4-4573-911d-8be4d18c233z"
  }
]
`;

var elements = JSON.parse(jsonStr);
const body = { elements };

fetch('http://localhost:3000/api/document', {
        method: 'post',
        body:    JSON.stringify(body),
        headers: { 'Content-Type': 'application/json' },
    })
    .then(res => console.log(res));

```

All the elements are added with success and I guess the nodes are kind of associated with the names from json but I have the following view at the end:

<img width="636" alt="Screen Shot 2020-10-07 at 1 23 57 PM" src="https://user-images.githubusercontent.com/6534865/95384190-192bf480-08a1-11eb-9a00-6582b91b9080.png">

@maxkfranz I only have the entity name and no association for the entity. Even if the entity would not be associated with anything I would expect to see the list of matches instead of this  warning when a node is clicked. Anything I must do about that in server side or it is something to be handled on node tap event seperately?

**Comment by jvwong** [comment]
I've tried to configure the 'master.factoid.baderlab.org' instance to the best of my knowledge but you should double check:

https://github.com/BaderLab/sysadmin/blob/master/websites/factoid.md#master-instance-settings

**Comment by maxkfranz** [comment]
Looks OK

**Comment by jvwong** [comment]
@metincansiper I am trying to test this locally. Is there any specific setup requirements that you have used to test this? 

This is mine:
```
factoid branch: unstable
factoid-converters branch: master
grounding-search branch: master
URL: https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.psp.BIOPAX.owl.gz
```

I was getting some weird errors (creating a bunch of 'secret' tables) so just need to know if there are any details.

**Comment by jvwong** [comment]
There two errors I'm seeing upon POST to `/api/document`:

1. Freshly created database / no documents exists:

In this case the app throws a bunch of Reql errors and seems to try to create multiple secret tables.

<img src="https://user-images.githubusercontent.com/4706307/101822364-35454f80-3af7-11eb-9525-e5bab6669903.png" height="350px"/>

2.  If at least one existing document in database:

```
info:    Updating document-level related papers for doc 77246bc4-58a0-45b5-9cb7-dc27912ebd15
info:    POST /api/document 200 3208.757 ms - 36332
error:   Error getRelPprsForDoc: HTTPStatusError: Too Many Requests (429)
info:    Updating network-level related papers for doc 77246bc4-58a0-45b5-9cb7-dc27912ebd15
error:   Aggregate get failed
error:    FetchError: invalid json response body at http://localhost:3011/get reason: Unexpected end of JSON input
    at /.../factoid/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 0)
....
```

**Comment by metincansiper** [comment]
@jvwong I see a similar error. Something maybe broken I am looking into it.

**Comment by metincansiper** [comment]
@jvwong I found out the problem causing the error of ``FetchError: invalid json response body at http://localhost:3011/get reason: Unexpected end of JSON input``. Grounding search get service is giving error for some option/options. The one I detected is ``{"id":"P29678","namespace":"uniprot"};``. It works well for the options ``{"id":"16818","namespace":"ncbi"}``. I do not know if it is a problem specific to uniprot entities. 

Would there be an issue with the grounding search service. I used the following code to try things out independent from the factoid code:

```
const fetch = require('node-fetch');
// working:
const opts = {"id":"16818","namespace":"ncbi"};
// error:
// const opts = {"id":"P29678","namespace":"uniprot"};
const url = 'http://localhost:3002/get';
fetch( url, {
  method: 'POST',
  body: JSON.stringify(opts),
  headers: {
    'Content-Type': 'application/json'
  }
} )
.then( res => res.json() )
.then( console.log );

```

**Comment by jvwong** [comment]
The UniProt accession P29678 points to a organism 'rabbit' https://www.uniprot.org/uniprot/P29678 which is not among the supported organisms. The stuff from PSP BioPAX is all human, so looks like some mapping went wrong?

**Comment by metincansiper** [comment]
>The UniProt accession P29678 points to a organism 'rabbit' https://www.uniprot.org/uniprot/P29678 which is not among the supported organisms. The stuff from PSP BioPAX is all human, so looks like some mapping went wrong?

@jvwong since it has the uniprot namespace it must not be the result of mapping but the it must be the input for the mapping. Therefore, I suspect if it would actually be coming from PSP file in a way. However, the file cannot be downloaded now. Is it related to the network issue that you mentioned?

**Comment by jvwong** [comment]
Yeah all our VMs are totally messed up including PC. Ill let you know when
its back up but might be a few days?

**Comment by metincansiper** [comment]
>The UniProt accession P29678 points to a organism 'rabbit' https://www.uniprot.org/uniprot/P29678 which is not among the supported organisms. The stuff from PSP BioPAX is all human, so looks like some mapping went wrong?

@jvwong I found it in PSP Biopax file:

```
<bp:UnificationXref rdf:ID="UnificationXref_uniprot_knowledgebase_P29678">
 <bp:id rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">P29678</bp:id>
 <bp:db rdf:datatype = "http://www.w3.org/2001/XMLSchema#string">uniprot knowledgebase</bp:db>
</bp:UnificationXref>
```

**Comment by jvwong** [comment]
OK I see an example of this: https://apps.pathwaycommons.org/pathways?uri=http://pathwaycommons.org/pc12/Catalysis_61738de4a156b1f6b48691e258df24bb

**Comment by metincansiper** [comment]
>OK I see an example of this: https://apps.pathwaycommons.org/pathways?uri=http://pathwaycommons.org/pc12/Catalysis_61738de4a156b1f6b48691e258df24bb

@jvwong then should we just skip the non human genes?

**Comment by jvwong** [comment]
> > OK I see an example of this: https://apps.pathwaycommons.org/pathways?uri=http://pathwaycommons.org/pc12/Catalysis_61738de4a156b1f6b48691e258df24bb
> 
> @jvwong then should we just skip the non human genes?

We do support some non-human species (below). 

```js
onst SORTED_MAIN_ORGANISMS = [
  new Organism(2697049, 'SARS-CoV-2'),
  new Organism(227984, 'SARS-CoV'),
  new Organism(9606, 'Homo sapiens'),
  new Organism(10090, 'Mus musculus'),
  new Organism(ROOT_STRAINS.SCERVISIAE, 'Saccharomyces cervisiae', SCERVISIAE_STRAIN_IDS),
  new Organism(7227, 'Drosophila melanogaster'),
  new Organism(ROOT_STRAINS.ECOLI, 'Escherichia coli', ECOLI_STRAIN_IDS),
  new Organism(6239, 'Caenorhabditis elegans'),
  new Organism(3702, 'Arabidopsis thaliana'),
  new Organism(10116, 'Rattus norvegicus'),
  new Organism(7955, 'Danio rerio')
];
```
https://github.com/PathwayCommons/grounding-search/blob/master/src/server/datasource/organisms.js#L44-L56

**Comment by metincansiper** [comment]
>We do support some non-human species (below).

Okay, I will make the filtering for that organism assuming that grounding search would work fine with them all.

**Comment by metincansiper** [comment]
@jvwong I made some work to eliminate the unsupported organisms (I did not commit it yet). However, grounding search is still not working for some supported organisms. One example I found is this gene with human organism: https://www.uniprot.org/uniprot/P06213 (``{"id":"P06213","namespace":"uniprot"}``). Also, the search for ncbi is also failing in some cases. The cases I checked were having human organism: (https://www.ncbi.nlm.nih.gov/gene/1956 and https://www.ncbi.nlm.nih.gov/gene/4610).

**Comment by jvwong** [comment]
What are you trying to search for again?

**Comment by maxkfranz** [comment]
https://grounding.baderlab.org doesn't seem like it's working and https://master.grounding.baderlab.org/ looks like it's down.  Maybe there's another issue with the cluster

**Comment by jvwong** [comment]
- https://grounding.baderlab.org/search is working for me
- https://master.grounding.baderlab.org/ is down again because of download issues. I have a prototype for dump restore that I've been meaning to finish...

**Comment by metincansiper** [comment]
>What are you trying to search for again?

I am getting the ncbi grounding for the genes coming from the PSP file. First I make a mapping to ncbi id then I make call the grounding search for the mapped ncbi id. In case the original xref is from uniprot I am making the uniprot the ncbi mapping using  the grounding search as well. I can tell that the problem is grounding search is failing for some parameters like ``{"id":"P06213","namespace":"uniprot"}``, ``{"id":"1956","namespace":"ncbi"}``, ``{"id":"4610","namespace":"ncbi"}``. All of which represents human genes.

**Comment by metincansiper** [comment]
>https://grounding.baderlab.org doesn't seem like it's working and https://master.grounding.baderlab.org/ looks like it's down. Maybe there's another issue with the cluster

I am also seeing that https://master.grounding.baderlab.org/ is being down frequently. Therefore, I was running grounding search in my localhost.

**Comment by jvwong** [comment]
> > https://grounding.baderlab.org doesn't seem like it's working and https://master.grounding.baderlab.org/ looks like it's down. Maybe there's another issue with the cluster
> 
> I am also seeing that https://master.grounding.baderlab.org/ is being down frequently. Therefore, I was running grounding search in my localhost.

It's timing out when trying to download ncbi/uniprot/chebi data. I'll put something up ASAP.

**Comment by metincansiper** [comment]
BTW the code updates I made to filter out the unsupported organisms are in this branch (https://github.com/PathwayCommons/factoid/tree/supplement_db_filter). I did not make a PR since the filtering does not look enough for now as I mentioned as:

>I made some work to eliminate the unsupported organisms (I did not commit it yet). However, grounding search is still not working for some supported organisms. One example I found is this gene with human organism: https://www.uniprot.org/uniprot/P06213 ({"id":"P06213","namespace":"uniprot"}). Also, the search for ncbi is also failing in some cases. The cases I checked were having human organism: (https://www.ncbi.nlm.nih.gov/gene/1956 and https://www.ncbi.nlm.nih.gov/gene/4610).

**Comment by jvwong** [comment]
> BTW the code updates I made to filter out the unsupported organisms are in this branch (https://github.com/PathwayCommons/factoid/tree/supplement_db_filter). I did not make a PR since the filtering does not look enough for now as I mentioned as:
> 
> > I made some work to eliminate the unsupported organisms (I did not commit it yet). However, grounding search is still not working for some supported organisms. One example I found is this gene with human organism: https://www.uniprot.org/uniprot/P06213 ({"id":"P06213","namespace":"uniprot"}). Also, the search for ncbi is also failing in some cases. The cases I checked were having human organism: (https://www.ncbi.nlm.nih.gov/gene/1956 and https://www.ncbi.nlm.nih.gov/gene/4610).

1. I tried this PhosphoSitePlus BioPAX conversion with your new branch and a local instance of everything (grounding, converter, index, db). INDRA can't handle all the requests and ends up complaining about too many requests (429), then to 'Unavailable' the to Internal Server error.
2. I can't reproduce your 'grounding search' errors. These all work fine for me.

**Comment by metincansiper** [comment]
>I can't reproduce your 'grounding search' errors. These all work fine for me.

Yes I they worked for me too. I remember like they were not working in the pas t but maybe I just made something wrong in the past. I do not know.

>I tried this PhosphoSitePlus BioPAX conversion with your new branch and a local instance of everything (grounding, converter, index, db). INDRA can't handle all the requests and ends up complaining about too many requests (429), then to 'Unavailable' the to Internal Server error.

@jvwong @maxkfranz the speed was not so important for this service. Am I right about that?

**Comment by jvwong** [comment]
No speed doesn't matter at all. Maybe there's a way to filter the documents a little more as well.

**Comment by metincansiper** [comment]
@jvwong I am looking into ``Too Many Requests (429)`` but while doing that I again coincided some cases where grounding service is failing. One of them is ``{"id":"P00517","namespace":"uniprot"}``. The cases I reported as not working in the past is working for me now but I see that new cases not working now.

**Comment by jvwong** [comment]
> P00517

That's unsupported organism: Bos taurus (Bovine)
https://www.uniprot.org/uniprot/P00517

**Comment by metincansiper** [comment]
>That's unsupported organism: Bos taurus (Bovine)
>https://www.uniprot.org/uniprot/P00517

Yes, sorry for the confusion. I checked it and see that the I mistakenly undid the code I added for organism filtering and I did not check the organism since I was relying on the organism filtering.

**Comment by metincansiper** [comment]
I created #940 referencing this issue.
