### ISSUE TITLE
Links to external resources used for grounding in explore view

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#837]
## Description

**Q: What is the name of the feature?**

A: links to external resources used for grounding in explore view

**Q: What does this feature enable the user to do?**

A: Navigate to NCBI or Chebi

**Q: What information must the user provide to use the feature?**

A: None

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: None

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: From Chebi/Pubchem you could buy the compund via external companies; via NCBI you might get some more info about gene/org/...
- Editor: No change
- Computational biologist: None (as I expect people to use the export instead of the web app for CB pipelines)
- Curator: No change

### Details

I think it would be useful to allow x-ref jumping from within factoid. E.g. if I want to "explore" and go look at a protein's sequence, I am currently forced to: click on node, look at the synonyms (since the name on the node might be something made up by the user), copy-paste text in NCBI or UniProt, make sure I foung the right entity.

![image](https://user-images.githubusercontent.com/6240943/93878101-d16e7000-fcd9-11ea-803e-1a2d71023866.png)
![image](https://user-images.githubusercontent.com/6240943/93878124-da5f4180-fcd9-11ea-94e9-ca9655c51693.png)

**Comment by jvwong** [comment]
I think you're looking at unstable.factoid.baderlab.org:

We updated the grounding service so only newer documents created in Factoid after a certain date (~August 14 2020) will indeed have those hyperlinks. The prod instance data was migrated so its OK. Should probably just delete all the data in unstable.

https://github.com/PathwayCommons/grounding-search/pull/77
https://github.com/PathwayCommons/grounding-search/issues/75

**Comment by jvwong** [comment]
![image](https://user-images.githubusercontent.com/4706307/93879716-3d38e480-fcaa-11ea-8943-eab7799d5456.png)

**Comment by sacdallago** [comment]
Ah, excellent!

I was indeed a bit surpised. But happy it's only such a minor thing. Sorry for bothering ;)
