### ISSUE TITLE
Improve visibility via search (Google)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#842]
## Description

**Q: What is the name of the feature?**

A: Search engine optimization

**Q: What does this feature enable the user to do?**

A: Find and discover documents in search engines (text, image, snippets)

**Q: What information must the user provide to use the feature?**

A: Keywords, article title

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Need to explicitly provide URLs for each document

## Specification

Will the following work?

- `/`
  - Provide a robots.txt
    - [Intro to robots.txt](https://support.google.com/webmasters/answer/6062608?hl=en)
    - [Google reference](https://developers.google.com/search/reference/robots_txt)
    - Provide a site map with list of (read-only) published document URLs
      - [Google site map reference](https://support.google.com/webmasters/answer/183668?hl=en)
  - Down the road, can simply have an archive page, much like any journal 
- `/document/{id}`
  - We already do this for Twitter cards so same idea
  - various meta tags
- Google is already indexing the documents, probably from Twitter: https://www.google.com/search?q=site%3Abiofactoid.org

### Details

//TODO

- Routing
  - add `/robots.txt`

- [`<meta>` tags](https://support.google.com/webmasters/answer/35624?visit_id=636880082951453933-4272044119&rd=1)
    - [Special tags that Google understands](https://support.google.com/webmasters/answer/79812?hl=en)
    - <head><title>
    - <meta> description
    - <meta> author
    - <meta> robots
    
- Structured data
  - [Article](https://developers.google.com/search/docs/data-types/article#non-amp) rich snippets

- Support search bar via `site:biofactoid.org ras interacts with raf`

**Comment by maxkfranz** [comment]
Example rich snippet for https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880

```
<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "http://schema.org",
  "@type" : "Article",
  "name" : "p27 controls Ragulator and mTOR activity in amino acid-deprived cells to regulate the autophagy-lysosomal pathway and coordinate cell cycle and cell growth.",
  "author" : {
    "@type" : "Person",
    "name" : "Ada NowosadPauline JeannotCaroline CallotJustine CreffRenaud Thierry PercheyCarine JoffrePatrice CodognoStephane ManentiArnaud Besson"
  },
  "datePublished" : "2020-09-25",
  "image" : "https://biofactoid.org/api/document/e1e4b079-258d-4258-b5a2-3a665046d880.png",
  "articleBody" : "Autophagy is a catabolic process whereby cytoplasmic components are degraded within lysosomes, allowing cells to maintain energy homeostasis during nutrient depletion. Several studies reported that the CDK inhibitor p27Kip1 promotes starvation-induced autophagy by an unknown mechanism. Here we find that p27 controls autophagy via an mTORC1-dependent mechanism in amino acid-deprived cells. During prolonged starvation, a fraction of p27 is recruited to lysosomes, where it interacts with LAMTOR1, a component of the Ragulator complex required for mTORC1 activation. Binding of p27 to LAMTOR1 prevents Ragulator assembly and mTORC1 activation, promoting autophagy. Conversely, p27-/- cells exhibit elevated mTORC1 signalling as well as impaired lysosomal activity and autophagy. This is associated with cytoplasmic sequestration of TFEB, preventing induction of the lysosomal genes required for lysosome function. LAMTOR1 silencing or mTOR inhibition restores autophagy and induces apoptosis in p27-/- cells. Together, these results reveal a direct coordinated regulation between the cell cycle and cell growth machineries.",
  "url" : "https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880"
}
</script>
```

Refer to https://www.google.com/webmasters/markup-helper/

**Comment by maxkfranz** [comment]
Example meta tags for https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880:

```html
<head>
  <title>p27 controls Ragulator and mTOR activity in amino acid-deprived cells to regulate the autophagy-lysosomal pathway and coordinate cell cycle and cell growth : Biofactoid</title>
  <meta name="description" content="p27Kip1 binds with LAMTOR1." />
  <meta name="robots" content="all" />
  <meta name="author" content="Ada Nowosad, Pauline Jeannot, Caroline Callot, Justine Creff, Renaud Thierry Perchey, Carine JoffrePatrice Codogno, Stephane Manenti, Arnaud Besson">
  <meta name="keywords" content="some, general, biofactoid, keywords">
</head>
```

- Include tool description in title or description, e.g. 'Explore with Biofactoid'
- Maybe include authors in title
- The keywords probably aren't that useful (i.e. not indexed)

**Comment by jvwong** [comment]
> Example rich snippet for https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880
> 
> ```
> 
> <script type="application/ld+json">
> {
>   "@context" : "http://schema.org",
>   "@type" : "Article",
>   "name" : "p27 controls Ragulator and mTOR activity in amino acid-deprived cells to regulate the autophagy-lysosomal pathway and coordinate cell cycle and cell growth.",
>   "author" : {
>     "@type" : "Person",
>     "name" : "Ada Nowosad, Pauline Jeannot, Caroline Callot, Justine Creff, Renaud Thierry Perchey, Carine JoffrePatrice Codogno, Stephane Manenti, Arnaud Besson"
>   },
>   "datePublished" : "2020-09-25",
>   "image" : "https://biofactoid.org/api/document/e1e4b079-258d-4258-b5a2-3a665046d880.png",
>   "articleBody" : "Autophagy is a catabolic process whereby cytoplasmic components are degraded within lysosomes, allowing cells to maintain energy homeostasis during nutrient depletion. Several studies reported that the CDK inhibitor p27Kip1 promotes starvation-induced autophagy by an unknown mechanism. Here we find that p27 controls autophagy via an mTORC1-dependent mechanism in amino acid-deprived cells. During prolonged starvation, a fraction of p27 is recruited to lysosomes, where it interacts with LAMTOR1, a component of the Ragulator complex required for mTORC1 activation. Binding of p27 to LAMTOR1 prevents Ragulator assembly and mTORC1 activation, promoting autophagy. Conversely, p27-/- cells exhibit elevated mTORC1 signalling as well as impaired lysosomal activity and autophagy. This is associated with cytoplasmic sequestration of TFEB, preventing induction of the lysosomal genes required for lysosome function. LAMTOR1 silencing or mTOR inhibition restores autophagy and induces apoptosis in p27-/- cells. Together, these results reveal a direct coordinated regulation between the cell cycle and cell growth machineries.",
>   "url" : "https://biofactoid.org/document/e1e4b079-258d-4258-b5a2-3a665046d880"
> }
> </script>
> ```
> 
>     * Refer to https://www.google.com/webmasters/markup-helper/
> 
>     * Author may have to be an array.  See https://webmasters.stackexchange.com/questions/90187/schema-org-book-with-multiple-authors-using-json-ld

I was also looking at https://developers.google.com/search/docs/data-types/article#non-amp which has `headline`, `dateModified`.

Should this ld+json be mapped manually, or is there some npm package to use.

**Comment by maxkfranz** [comment]
This is the full list: https://schema.org/Article

The Google tool generated those fields, so those are probably the main ones used in search results.  Best to test with this on unstable: https://search.google.com/structured-data/testing-tool

> Should this ld+json be mapped manually, or is there some npm package to use.

Probably best to just use the above example as a template and parameterise it.

**Comment by maxkfranz** [comment]
Re. search:

- A new nav link (i.e. 'Search') at the top right could be added that opens a tippy with a search bar.
- The CTA in the 'Researchers' section gets renamed to 'Search biofactoids'.  This also opens a tippy with a search bar.
- The search bar just opens a new tab to Google with `site:biofactoid.org my keywords here`

**Comment by maxkfranz** [comment]
We should also consider the visibility of the homepage.  Its metatags and search metadata should be updated to be more in line with the updated copy and CTA.  Something like 'Authors use Biofactoid to create digital profiles of scientific discoveries in their articles and connect them to related research.  Create your article profile with Biofactoid today!'

**Comment by jvwong** [comment]
> We should also consider the visibility of the homepage. Its metatags and search metadata should be updated to be more in line with the updated copy and CTA. Something like 'Authors use Biofactoid to create digital profiles of scientific discoveries in their articles and connect them to related research. Create your article profile with Biofactoid today!'

Related is homepage URL conversion to Twitter card : no image

**Comment by maxkfranz** [comment]
Note: The sitemap should be generated dynamically as a route.  It should use the same data as `/documents`, sorted most-recent first.

**Comment by maxkfranz** [comment]
/`robots.txt` should look something like this:

```
User-agent: *
Allow: /

Sitemap: https://biofactoid.org/api/sitemap.xml
```

**Comment by jvwong** [comment]
Good news is we're generally getting in the top 8 if you search the title

Bad news is I had to use the search console to get the sitemap indexed, and Google doesn't seem to care about our rich results etc.

**Comment by maxkfranz** [comment]
> Google doesn't seem to care about our rich results etc.


Any info here? https://support.google.com/webmasters/answer/7552505?hl=en

**Comment by jvwong** [comment]
Regarding the rich results: No clear answer. My best guess is that this isn't the type of content Google cares about when it comes to 'articles'.

What we can try: Include images in the sitemap https://support.google.com/webmasters/answer/178636?hl=en&ref_topic=2370565

**Comment by maxkfranz** [comment]
Some sites that have rich tags don't get shown as a rich result on Google, even for some popular sites.  Google may have a curated whitelist (e.g. NY Times, Washington Post) to avoid spam cards.

**Comment by jvwong** [comment]
Yes, I suspect they're more interested in 'recent' topics of general interest. You won't even see rich results for NY times articles that are even a little old.
