### ISSUE TITLE
Document post-mortem: Missing metadata and misc problems 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#851]
PubMed: [Coordinated Conformational Processing of the Tumor Suppressor Protein p53 by the Hsp70 and Hsp90 Chaperone Machineries](https://pubmed.ncbi.nlm.nih.gov/31027879/)
Document URL: https://biofactoid.org/document/e3ad1fe0-7cc9-4075-b9a7-32626ce0c2ff

Problems

- 1. Biofactoid could not identify their article based on author input
  -  Author added variant of the PubMed indexed title `Coordinated conformational processing of p53 by the Hsp70 and Hsp90 chaperones machineries`  
  - It's worth noting that EUTILS ESEARCH returns nothing;  PubMed website returns the correct article
  
- 2. No related papers 
  - Document: No PubMedID 
  - Network: INDRA responded with `504: Gateway Timeout`  

- 3. Display in carousel is different than explorer 
  - Carousel:

<img src="https://user-images.githubusercontent.com/4706307/94934103-48092b80-0499-11eb-8b44-f38c82c0f0d5.png" width="200px" />
 
- explorer
<img src="https://user-images.githubusercontent.com/4706307/94934239-7981f700-0499-11eb-8bf7-9e0ebc7ce038.png"  width="200px" />

**Comment by maxkfranz** [comment]
Re. (iii): Did the user submit early, or might this have been related to the previous status values?

Re. (ii): Is this a one-off Indra issue for this document (https://biofactoid.org/document/a6b4351d-b474-49d9-bc3d-f044513d5a0c)?  Could Metin add more retries to the Indra queries to resolve this?  Or is this a reproducible error for the document specifically?

Another issue (iv): Is there the wrong grounding for this document https://biofactoid.org/document/aa18ee18-a78f-4d46-a244-9a6dc97bb238 ?  'Cofilin' doesn't exist for mouse in NCBI.  Only 'cofilin-1' exists for mouse as the closest synonym.

**Comment by jvwong** [comment]
> Re. (iii): Did the user submit early, or might this have been related to the previous status values?

Likely submitted followed by editing. I told one user that didn't like their submission that they could still edit the document via the same link.

> Re. (ii): Is this a one-off Indra issue for this document (https://biofactoid.org/document/a6b4351d-b474-49d9-bc3d-f044513d5a0c)? Could Metin add more retries to the Indra queries to resolve this? Or is this a reproducible error for the document specifically?

One-off: I could update successfully by refreshing from the admin.

**Comment by jvwong** [comment]
> Another issue (iv): Is there the wrong grounding for this document https://biofactoid.org/document/aa18ee18-a78f-4d46-a244-9a6dc97bb238 ? 'Cofilin' doesn't exist for mouse in NCBI. Only 'cofilin-1' exists for mouse as the closest synonym.

yeah probably mouse cofilin-1

**Comment by maxkfranz** [comment]
> > Another issue (iv): Is there the wrong grounding for this document https://biofactoid.org/document/aa18ee18-a78f-4d46-a244-9a6dc97bb238 ? 'Cofilin' doesn't exist for mouse in NCBI. Only 'cofilin-1' exists for mouse as the closest synonym.
> 
> yeah probably mouse cofilin-1

We could add to the patch file, but only if we’re sure users would always want cofilin-1 and not something like cofilin-2.

**Comment by jvwong** [comment]
> > Another issue (iv): Is there the wrong grounding for this document https://biofactoid.org/document/aa18ee18-a78f-4d46-a244-9a6dc97bb238 ? 'Cofilin' doesn't exist for mouse in NCBI. Only 'cofilin-1' exists for mouse as the closest synonym.
> 
> yeah probably mouse cofilin-1

See #861

**Comment by jvwong** [comment]
> Re. (iii): Did the user submit early, or might this have been related to the previous status values?

Happened again with https://biofactoid.org/document/b2b68594-0ab2-4fdb-8305-3631b7b40319

<img src="https://biofactoid.org/api/document/b2b68594-0ab2-4fdb-8305-3631b7b40319.png" height="300px" />

**Comment by jvwong** [comment]
@maxkfranz re: author editing after the doc after a png has been created/cached

- one idea is to cache the doc `lastEditedDate` with the doc id to see if the .png needs to be (re)generated ?

**Comment by maxkfranz** [comment]
You'd want the timestamp in the cache, not with the ID as the key.  But that would work for these cases where the user fiddles with things post-submission.

In future, we may also want a general interval-based cache clearing (e.g. nightly) to catch invalidations that aren't user edits (e.g. via admin ui).

**Comment by maxkfranz** [comment]
You can get the interval behaviour by just setting `maxAge`: https://www.npmjs.com/package/lru-cache

**Comment by jvwong** [comment]
I think this png issue is the only actionable item here.

**Comment by maxkfranz** [comment]
(iv) can be addressed by the patch file in the grounding service.

https://github.com/PathwayCommons/grounding-search/issues/84

**Comment by maxkfranz** [comment]
Problems summary:

- Indra fails (this issue and #845)
  - Action: Retry more aggressively #865 
- Images are stale (this issue)
  - Action:  Clear out cache #864 
- Pubmed queries are unreliable (#845 and this issue)
  - Action: TODO
- Groundings are unexpected
  - Action:  Amend patch file with better synonyms on a case-by-case basis https://github.com/PathwayCommons/grounding-search/issues/84

**Comment by maxkfranz** [comment]
Closing, as the main action items are complete.  Future enhancements can be addressed on a case-by-case basis.
