### ISSUE TITLE
Grounding: Entity organism preference / mixed organisms for genes 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#861]
There have been two cases whereby a user has  added genes from different organisms. Turns out this is not what the user intended.

Enhancement is a (non-blocking) message to the author that they have added bioentities from >=1 organism.

**Comment by maxkfranz** [comment]
Popover for grounding:  This organism is different than the other proteins you have (human).  __Did you mean X (human)__?

**Comment by jvwong** [comment]
NCBI gene method:

```
ID: 21803 | transforming growth factor, beta 1 [Mus musculus (house mouse)]
```

**Comment by jvwong** [comment]
> - Warn user when factoid contains multiple organisms
>   - Change “Warnings” to “tips” or alike -- more friendly
