### ISSUE TITLE
Effect property of Deubiquitination class may have a typo

### ISSUE THREAD

**Issue by metincansiper** [PathwayCommons/factoid#862]
In this line (https://github.com/PathwayCommons/factoid/blob/unstable/src/model/element/interaction-type/deubiquitination.js#L5) the variable ``EFFECT `` is set to "deubiquitination". I beleive it must be "deubiquitinated" as following how the effects are named in other similar classes. Is that just a typo or an exception?

**Comment by maxkfranz** [comment]
It looks like a typo, when compared to the other modification interactions.
