### ISSUE TITLE
Grounding tooltip: Showing different organism 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#867]
I've noticed that when I label a gene, the display organism (title) and the one displayed in the dropdown are different. I believe the actual assigned grounding is the one in the title so the dropdown may be lagging?

- Reproduce: 
  - Add entity
  - Label 'Smad3'

<img src="https://user-images.githubusercontent.com/4706307/95601280-3c7dad80-0a21-11eb-974d-f8eefbf596f4.png" height="250px" />

If you click off and on the entity, the organisms are back in sync

<img src="https://user-images.githubusercontent.com/4706307/95601585-a8601600-0a21-11eb-8e8d-3a63d14179fc.png" height="250px" />

**Comment by maxkfranz** [comment]
The grounding server looks like it’s down: https://master.grounding.baderlab.org/search?q=smad3 <https://master.grounding.baderlab.org/search?q=smad3> 

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by jvwong** [comment]
For this issue, my instance is pointed at prod.

For the master.grounding - I guess it couldn't get ncbi, but I'll boot it back up. 

```
error:   Failed to apply update on source 'ncbi'
error:    message=Timeout while connecting to server, stack=Error: Timeout while connecting to server
```

**Comment by maxkfranz** [comment]
You can't test on unstable without that instance up.

**Comment by maxkfranz** [comment]
See https://github.com/PathwayCommons/factoid/pull/869.

I think 4eee4b6 should resolve what you mentioned, but the bigger issue is 
79c9ca3.  Your example should be smad3 human for a one-node doc.
