### ISSUE TITLE
Puppeteer errors

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#874]
The unstable and docker instances cannot generate network snapshots via puppeteer.

Last time this happened, the [instructions for Puppeteer on Docker](https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#running-puppeteer-in-docker) had changed, but not sure that's the case this time.

Docker errors:
 ```
Error: Failed to launch chrome!
...app/node_modules/puppeteer/.local-chromium/linux-686378/chrome-linux/chrome: error while loading shared libraries: libXtst.so.6: cannot open shared object file: No such file or directory
```

Unstable instance:
```
Error: Evaluation failed: TypeError: cy.style is not a function
    at __puppeteer_evaluation_script__:7:10
...
```

**Comment by jvwong** [comment]
A rebuild of the 0.11.0 tag Docker image now gives the error.

**Comment by maxkfranz** [comment]
The docker file doesn't specify which version of Chrome to use.

It should do something like this:

```
apt-get install -y google-chrome-stable=1.2.3
```

I'm not sure what version would work with our version of puppeteer.  An alternative would be to update puppeteer, but I think that cytosnap uses an old version (1.x).

**Comment by jvwong** [comment]
The thing is, unstable.factoid.baderlab.org doesn't work anymore?

**Comment by maxkfranz** [comment]
Every time you deploy, you're installing a new chrome.

**Comment by maxkfranz** [comment]
You could try installing the apt dependencies manually instead of using 'google-chrome-stable':

```
gconf-service
libasound2
libatk1.0-0
libatk-bridge2.0-0
libc6
libcairo2
libcups2
libdbus-1-3
libexpat1
libfontconfig1
libgcc1
libgconf-2-4
libgdk-pixbuf2.0-0
libglib2.0-0
libgtk-3-0
libnspr4
libpango-1.0-0
libpangocairo-1.0-0
libstdc++6
libx11-6
libx11-xcb1
libxcb1
libxcomposite1
libxcursor1
libxdamage1
libxext6
libxfixes3
libxi6
libxrandr2
libxrender1
libxss1
libxtst6
ca-certificates
fonts-liberation
libappindicator1
libnss3
lsb-release
xdg-utils
wget
```

See https://github.com/puppeteer/puppeteer/blob/v1.20.0/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix (n.b. must refer to v1.20.0 tag)

**Comment by maxkfranz** [comment]
This looks like the corresponding version of Chrome: Chromium 78.0.3882.0 - Puppeteer v1.20.0

**Comment by maxkfranz** [comment]
Another consideration is this /dev/shm warning: https://github.com/puppeteer/puppeteer/blob/v1.20.0/docs/troubleshooting.md#tips

**Comment by jvwong** [comment]
I just installed the missing library: libxtst6 

I'll try the docker instance via master.factoid.baderlab.org to make sure its worth tagging.

I'll have to figure out something with unstable.factoid.baderlab.org

**Comment by maxkfranz** [comment]
> You could try installing the apt dependencies manually instead of using 'google-chrome-stable':
> 
> ```
> gconf-service
> libasound2
> libatk1.0-0
> libatk-bridge2.0-0
> libc6
> libcairo2
> libcups2
> libdbus-1-3
> libexpat1
> libfontconfig1
> libgcc1
> libgconf-2-4
> libgdk-pixbuf2.0-0
> libglib2.0-0
> libgtk-3-0
> libnspr4
> libpango-1.0-0
> libpangocairo-1.0-0
> libstdc++6
> libx11-6
> libx11-xcb1
> libxcb1
> libxcomposite1
> libxcursor1
> libxdamage1
> libxext6
> libxfixes3
> libxi6
> libxrandr2
> libxrender1
> libxss1
> libxtst6
> ca-certificates
> fonts-liberation
> libappindicator1
> libnss3
> lsb-release
> xdg-utils
> wget
> ```
> 
> See https://github.com/puppeteer/puppeteer/blob/v1.20.0/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-unix (n.b. must refer to v1.20.0 tag)

I installed these packages, and restarted unstable.  It looks fine.

**Comment by maxkfranz** [comment]
The dockerfile should probably look like this:

```
# v10 is the latest LTS
FROM node:10.15.3

# Allow user configuration of variable at build-time using --build-arg flag
# See src/client-env-vars.json
ARG NODE_ENV
ARG BASE_URL

# Initialize environment and override with build-time flag, if set
ENV NODE_ENV ${NODE_ENV:-production}

# Create an unprivileged user w/ home directory
RUN groupadd appuser \
  && useradd --gid appuser --shell /bin/bash --create-home appuser

# Create app directory
RUN mkdir -p /home/appuser/app
WORKDIR /home/appuser/app

# Copy in source code
COPY . /home/appuser/app

# Install app dependencies
# Puppeteer requirements
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 libxtst6 gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Note: NODE_ENV is development so that dev deps are installed
RUN NODE_ENV=development npm install

# Build project
RUN npm run clean
RUN npm run build

# Expose port
EXPOSE 3000

# Change ownership of the app to the unprivileged user
RUN chown appuser:appuser -R /home/appuser/app
USER appuser

# Apply start commands
COPY entrypoint.sh /
CMD ["/entrypoint.sh"]

```

**Comment by jvwong** [comment]
OK I'll put all of those dependencies in explicitly. To be continued...
