### ISSUE TITLE
Third party author attribution

### ISSUE THREAD

**Issue by sacdallago** [PathwayCommons/factoid#882]
## Description

**Q: What is the name of the feature?**

A: Third party author attribution

**Q: What does this feature enable the user to do?**

A: put their name (or no name?) as the curator of a biofactoid? Robot if it's a robot?

**Q: What information must the user provide to use the feature?**

A: Name

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: None

**Comment by jvwong** [comment]
I had this listed under https://github.com/PathwayCommons/factoid/issues/729#issuecomment-691251884
