### ISSUE TITLE
Editor on mobile: Not adapting to orientation change

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#896]
In editor, shifting to portrait from landscape leaves the bottom of the screen cutoff, apparently at the same place as in landscape.

Reproduce this on Firefox (29.1 (3022)), Chrome (86.0.4240.93) (iphone / ipad).

<img src="https://user-images.githubusercontent.com/4706307/98569999-f1092a00-2280-11eb-9d4b-e68666cc32c3.PNG" height="400px" />

**Comment by maxkfranz** [comment]
Browsers other than Safari used a crippled web view on iOS.  Firefox and Chrome are essentially second-class citizens on iOS, and their marketshare is very low.  These browsers frequently have new bugs like this, so it's generally a losing battle of attrition.

If you're using Firefox or Chrome yourself and you've noticed an easy workaround, then it may make sense to address this.  In general, the cost-benefit trade-off doesn't make sense to spend time testing on Firefox and Chrome on iOS.

**Comment by maxkfranz** [comment]
You could try a debounce here, assuming WkWebView doesn't fire the event at the right time:

https://github.com/PathwayCommons/factoid/blob/57b5929ccd76cc2b5eb728f9c9c2564c561dd7e9/src/client/components/editor/index.js#L562-L564

If that doesn't resolve it, then it's probably not worth the time.

**Comment by jvwong** [comment]
let's punt unless someone thinks its a problem.
