### ISSUE TITLE
Post hoc specification of the paper in a factoid

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#901]
## Description

**Q: What is the name of the feature?**

A: Post hoc specification of the paper

**Q: What does this feature enable the user to do?**

A: The author may specify which paper is associated with a factoid after the creation of the document.

**Q: What information must the user provide to use the feature?**

A: The title of the paper.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: The paper must be specified before the document is submitted.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: An author is able to experiment with the Biofactoid editor UI before deciding what paper his or her factoid is about.
- Editor: N/A
- Computational biologist: N/A
- Curator: N/A

### Mockup

- In the submission popover, there is the form to specify the paper.  This is shown only for documents that are created without an associated paper.
- Documents that are missing an associated paper show a title like 'Set the title of your paper'.  That title is displayed as a clickable link.  
  - By clicking that link, the author is given a popover that allows him or her to specify the paper's title -- similar to the home page.  
  - The yellow button may say something different than the home page, like 'OK'.  
  - If we already have the email address of the user, then that text field can be omitted.
  - The name of the author should be provided in the same form.  If the author's name is already stored in the system (e.g. they entered the system through an email addressed to them), then that field can be omitted.

<img width="294" alt="Screen Shot 2020-11-12 at 16 52 57" src="https://user-images.githubusercontent.com/989043/99000600-887fae80-2507-11eb-891f-b17e162fdb8f.png">

### Details

Description:

- An author may specify the paper of an associated factoid by clicking the 'Set the title of your paper' link -- which is located where the paper's title would normally be.
- An author is blocked from submitting the document until the factoid has an associated paper.  The paper association UI can be shown in the submission popover to address this.
- The author info form now contains the following fields:
  - Author name
  - Email address
  - Article title

Tasks:

- [x] Modify the existing home page author info popover (to create a new factoid).
  - [x] Add author name to the existing popover.
  - [x] Add the option to customise the yellow button text
  - [x] Add the option to customise the action on click of the yellow submit button
  - [x] Make the component reusable, outside of the home page in a separate file
- [x] Reuse the popover on the editor (show on click for empty titles)
  - [x] Add popover in the editor
  - [x] Autofill the form fields that may already be stored in the model (i.e. email case where we send the message to a particular author, but we don't know the paper yet)
    - [x] Author name
    - [x] Author email

**Comment by maxkfranz** [comment]
FYI @sacdallago

**Comment by jvwong** [comment]
This is related to #729 and #887

**Comment by maxkfranz** [comment]
@metincansiper, could you take a look at this one after https://github.com/PathwayCommons/factoid/pull/910#issuecomment-737277779 ?  Thanks
