### ISSUE TITLE
Tag 0.13.0 

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#902]
This should follow #770 which depends on preprint upload

**Comment by jvwong** [comment]
Only question for me is do we want the email-related papers to go live? I can always switch off

**Comment by maxkfranz** [comment]
Let’s leave it off for now on prod. Let’s coordinate a day next week to turn it on. We can try it out with an article that we curate, and we can try it with an admin refresh on an old factoid. 

It’s easy to switch it on and off, so we can leave it on after we’ve double checked everything on prod

**Comment by jvwong** [comment]
OK it's up.
