### ISSUE TITLE
Automatic connection of researcher profiles

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#907]
## Description

**Q: What is the name of the feature?**

A: Automatic connection of researcher profiles with a Biofactoid article summary

**Q: What does this feature enable the user to do?**

A: The reader of an article summary can click through on an author's name to see that author's profile, with other articles etc.

**Q: What information must the user provide to use the feature?**

A: The author must provide the title of the article.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: Not all authors may have a profile on systems like ORCID.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: Can use an article summary to explore more thoroughly.  The article summary becomes more of a fully-fledged hub.
- Editor: N/A
- Computational biologist: N/A
- Curator: N/A

### Mockup

Currently, the author list in an article summary is not clickable.  This feature would make it so that each author that has a profile (e.g. on ORCID) would have a link on their name.  Clicking the link would open the author's external profile in a new tab.

### Details

- [ORCID allows for finding author profiles via article DOI.](https://members.orcid.org/api/resources/find-myresearchers)
- Each article summary contains the article's DOI, so author ORCID IDs can be found automatically.
- This information should be populated on document creation, where a title is specified at creation.  This information should be refreshed on submission, in case the title was not specified at creation (i.e. #901 ).
- There may be author profiles, other than ORCID, that we consider.

**Comment by maxkfranz** [comment]
@metincansiper, could you investigate this issue?

**Comment by metincansiper** [comment]
>@metincansiper, could you investigate this issue?

I am looking into it

**Comment by maxkfranz** [comment]
@metincansiper 

See https://github.com/PathwayCommons/factoid/pull/910#issuecomment-737277779
