### ISSUE TITLE
Supplementing document data with an article's corresponding author email

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#919]
PubMed may not index the corresponding author emails whereas associated PubMedCentral article may. The proposal is to retrieve this information if it exists.

This directly affects the email related papers authors feature, as evidenced below:

- Article: [SLC19A1 Is an Importer of the Immunotransmitter cGAMP.](https://biofactoid.org/document/7826fd5b-d5af-4f4c-9645-de5264907272)
  - Referenced articles: 39
  - Published within last 5 years: 11
  - Not review: 10
  - Contact available: 4

Now with respect to this case, a lot of the papers missing contact info were Nature Publishing Group who seem not to put their emails in PubMed for whatever reason. 

potential issues: 

  - Identifying authors between PMC and pubmed: Just look at names?
  - PMC entry may not exist
  -...

**Comment by jvwong** [comment]
Also look at CrossRef to see if emails are here.

**Comment by jvwong** [comment]
FYI I did a sample of 17 of the existing docs on prod (30) and counted the potential number emails sent out / document:

4, 1, 2, 0, 13, 0, 12, 12, 5, 11, 23, 0, 4, 0, 7, 0, 0

**Comment by maxkfranz** [comment]
That’s great. The average is about 5 (small sample though). Any average >=1 is good to start with

**Comment by jvwong** [comment]
Journals of note that provide emails only through PMC: 

- eLife  
- PLoS Biology
