### ISSUE TITLE
One-click editor link for related papers emails

### ISSUE THREAD

**Issue by maxkfranz** [PathwayCommons/factoid#925]
## Description

**Q: What is the name of the feature?**

A: One-click editor link for related papers emails

**Q: What does this feature enable the user to do?**

A: When a prospective user receives a related papers email, they can start creating a factoid right away by clicking a link in the email.

**Q: What information must the user provide to use the feature?**

A: The user must specify the paper associated with their factoid, within the editor.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: The submission validation must check that the paper's title is specified for the factoid.

**Q: How does this feature affect each class of user (persona)?**

A:

- Biologist: A prospective user who learns about Biofactoid by email can create a new article profile by just clicking the CTA.
- Editor: N/A
- Computational biologist: N/A
- Curator: N/A

### Mockup

Here is an example of the email, as it stands today:

> Dear John Doe,
> 
> Biofactoid (biofactoid.org) is an academic project whose mission is to connect biological research. Biofactoid digitally captures the molecular interactions within articles, and it connects these articles to social media, relevant literature, and widely-used biological research apps. Biofactoid empowers researchers to discover novel findings and to connect with other researchers.
> 
> A new article profile has been published that cites your article, Lorem ipsum.
> 
> J. Schmoe et al. have published Dolor sit amet (A. Journal), where A binds to B.
> 
> Authors use Biofactoid to create interactive profiles of the discoveries in their research, and you can explore the article profile that J. Schmoe et al. have just created on Biofactoid.
> 
> Connect your own findings with other researchers by adding your own article profile to Biofactoid. It takes only a few minutes, and once added, your article will be discoverable, shareable, and app-accessible. Connect your research to the world by creating your article profile today!
> 
> The Biofactoid Team
> Bader Lab at the University of Toronto
> Sander Lab at Harvard
> The Pathway and Omics Lab at the University of Oregon

The sentence, "Connect your research to the world by creating your article profile today!", is currently a CTA that links to the Biofactoid home page.  This link would be replaced with a link to an empty document that the user can edit right away.  Each link must be unique per email.

### Details

- [x] Change the link in the email template.  The link should be passed to the template.
- [x] The server should generate a new empty document with corresponding editor links for each related papers email that is sent.

Ref.

- Novel interaction notification #858
- Post hoc specification of the paper in a factoid #901

**Comment by jvwong** [comment]
I'm starting to believe that the requirements for this feature and the requirements for a 'article triage' feature are overlapping quite a bit:
  - Accept a list of PMIDs
  - Retrieve the article title, abstract, email and other metadata
  - Identify new interactions in the article
  - Prepare a list of documents related to the suitable articles (ranked, possibly manually created if suitable) 
  - Retrieve the email of the author 
  - Send an email, possibly with a link to the document

I'd like a UI, much like the admin where these things can be manually tracked and accepted/trashed

To be continued.

**Comment by maxkfranz** [comment]
Differences to consider:

> I'm starting to believe that the requirements for this feature and the requirements for a 'article triage' feature are overlapping quite a bit:
> 
> * Identify articles of interest

This may differ in the triage case versus the notification case

> * Retrieve article PMIDs

Same

> * Retrieve the article title, abstract, email and other metadata

Same

> * Identify new interactions in the article

The target article is different in the case of the notification

> * Prepare a list of documents related to the suitable articles (ranked, possibly manually created if suitable)

This may also apply to notifications, giving the recipient a set of suggested articles to contribute.

> * Retrieve the email of the author

Same

> * Send an email, possibly with a link to the document

Same

> 
> I'd like a UI, much like the admin where these things can be manually tracked and accepted/trashed
> 
> To be continued.

**Comment by maxkfranz** [comment]
These emails should be turned on in prod soon

**Comment by jvwong** [comment]
> > * Retrieve the email of the author
> 
> Same

See #919  also
