### ISSUE TITLE
Network Explorer: Interaction information

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#937]
## Description

**Q: What is the name of the feature?**

A: Network Explorer: Interaction information

**Q: What does this feature enable the user to do?**

A: Identify  "at a glance" what relevant interaction evidence an article contains; provide more context. Enable users to triage articles.

**Q: What information must the user provide to use the feature?**

A: Select element within the Explorer network.

**Q: What are the applicable constraints, e.g. compatibility or performance?**

A: We've got more experience with INDRA, so look out for edge cases:

- A large number of interactions (INDRA 'statements') are returned and must be triaged
- No interactions (statements) are returned
- A large amount of papers (evidence) is returned and must be triaged 
- How to deal with two types of papers/evidence:
  -  No text snippet available
  - Text snippet available

**Q: How does this feature affect each class of user (persona)?**

A: I considered this question from a biologists point of view. It was never clear to me why articles were being displayed for a selected interaction or participant. To find out exactly why, at least in a couple of cases I followed up on, would require perhaps a few hours. It also helps to know the type of article (review, research), for greater context. 

From a wider perspective, its clear that we should strive to offer information that is unique and 'sticky'. There's really interesting stuff from INDRA we're already retrieving, its just a matter of using it. By the same token, we'll be able to judge more easily when the items we're offering are of poor quality (and so will users).

### Mockup

I'm using Ben/John's entry (Sorger) as a worked example: [Encoding Growth Factor Identity in the Temporal Dynamics of FOXO3 under the Combinatorial Control of ERK and AKT Kinases. Cell Syst 6 2018](https://biofactoid.org/document/3d2a77ba-55c1-463b-aff3-9acaa0307b62)

#### Case I: Evidence for interaction 

![Evidence available](https://user-images.githubusercontent.com/4706307/108256979-2d73de00-712c-11eb-88ce-c92ac226834d.png)

Notes:
- Tell me that its a review is important and can help contextualize a text snippet

#### Case II: No evidence

The point here really is that if its a truly novel interaction, we should be explicit about this, rather than "back-fill" other papers into this section or view it as some failure of the approach. Just say "nothing here to see".

### Details

Getting data from INDRA is mostly the same, but the changes are downstream:

- Retrieve statements from INDRA by search via participant Uniprot ID (`/statements/from_agents`) 
- Sort statements:
  - Interaction text (template, e.g. "AKT1 inhibits FOXO3 via phosphorylation") vs.
  - English version of statement (`/assemblers/english`, e.g. "AKT phosphorylates FOXO3 on T32.")
- Sort evidence
  -  Interaction text (template, e.g. "AKT1 inhibits FOXO3 via phosphorylation") vs.
  - Case
    - text snippet (e.g. "Knockdown of either AKT1 or AKT2 in Hella cells seems to reduce FoxO3 phosphorylation equally well \[43\].”)
    - no snippet: Title/abstract

## Future

- Document-level related snipppets/papers
- Deep linking to document text
- Shareable links for snipppets

**Comment by jvwong** [comment]
I created a prototype in https://github.com/PathwayCommons/factoid/tree/iss937_interaction-info. 

### Document-level

No data changes. I felt that if we're sticking to presenting paper text (rather than images/networks, which we initially intended for the grid-view) then we have the opportunity to cleanup a bit:

![Screenshot_2021-04-01 Encoding Growth Factor Identity in the Temporal Dynamics of FOXO3 under the Combinatorial Control of  (1)](https://user-images.githubusercontent.com/4706307/113333460-748aec80-92f0-11eb-9ad8-bca38c4f6b38.png)


### Network-level

Data - This has some major-changes to the 'relatedPapers' data. Rather than just paper info, the INDRA module gathers  'interactions' along with supporting papers (evidence), which includes text excerpts. I haven't done any additional ranking with semantic search (yet), so the results are how they come out of INDRA, i.e. statements ordered by decreasing amounts of evidence.

UI - There's some good, bad and ugly here:
  - Good: The text, excerpts and 'Review' badge give explicit clues to a user the reasons they are being shown this paper and determine if they are interested in finding out more 
  - Bad: 'Show more articles' doesn't go anywhere yet
  - Ugly: Repeated excerpts. I tried to aggregate these but you can see the one below (AKT1 inhibits FOXO3) has slightly different characters in the excerpt

![Screenshot_2021-04-01 Encoding Growth Factor Identity in the Temporal Dynamics of FOXO3 under the Combinatorial Control of ](https://user-images.githubusercontent.com/4706307/113333948-14487a80-92f1-11eb-90b9-1572c6a91abb.png)

**Comment by maxkfranz** [comment]
> Ugly: Repeated excerpts. I tried to aggregate these but you can see the one below (AKT1 inhibits FOXO3) has slightly different characters in the excerpt

There are text similarity functions that could be reused from the grounding search service.  If the text is very similar, then the duplicates could be discarded.

**Comment by jvwong** [comment]
<img width="966" alt="Screenshot at Jun 15 12-58-05" src="https://user-images.githubusercontent.com/4706307/122093728-5bff7e00-cdd9-11eb-8623-b49c4b1fa335.png">

@maxkfranz  I used [string-similarity](https://www.npmjs.com/package/string-similarity) to reduce the redundancy in text snippets. A couple more notes about the red box:

1. Experimenting with passing datasource (e.g. Pathway Commons; red box), when it is relevant (e.g. not NLP/REACH). Related to ideas around branding, connecting data that came up around search
2. `Show more articles` isn't implemented but I'm wondering if this PR (to be posted) is getting too big and this should just be cut for now?

I'm gonna post a PR...

**Comment by maxkfranz** [comment]
Looks interesting.  Some points to consider:

- Mobile / small screen / touch device support.  This design uses a lot of horizontal space.  Is it responsive?  What if I'm a desktop user who wants to put two windows side-by-side on a normal 13" macbook?
- Show more articles:  As a user, I don't want to click just to see a few of the best results.  I just want to see them.  If I want to see more than the most important ones, then I don't mind clicking.

**Comment by jvwong** [comment]
>  Mobile / small screen / touch device support.  This design uses a lot of horizontal space.  Is it responsive?  What if I'm a desktop user who wants to put two windows side-by-side on a normal 13" macbook?

### iPhone-size screen

- in this case the flex box just goes from row to column:

<img src="https://user-images.githubusercontent.com/4706307/122277943-70647900-ceb4-11eb-8e8a-a071694de441.png" height="550px" />

### side-by-side view

- two different elements of the same network selected

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/4706307/122278775-48294a00-ceb5-11eb-9015-24370d27f47e.png">

>  Show more articles:  As a user, I don't want to click just to see a few of the best results.  I just want to see them.  If I want to see more than the most important ones, then I don't mind clicking.

- ok, gotta think about this more

**Comment by jvwong** [comment]
On a related note: Do we need to store all of the PubMed information for each article in the database in this case?

The underlying issue is the rather large size of Rethinkdb database dumps. I think there was an old issue where we looked at the reason for the size of the docs: https://github.com/PathwayCommons/factoid/issues/939

**Comment by maxkfranz** [comment]
If the results are cached, the user sees everything in the UI immediately (Pubmed metadata, related papers, etc.). If queries are slow or unreliable, then caching helps to alleviate those issues and improve UX. 

Might also some parts of the app assume that all submitted docs have full  Pubmed metadata?

For backups, I suppose we could specifically omit cached data. However, it could be slow or problematic to requery for that info in the event that we need to restore a backup. This may be an area to use varied backup levels over time: The most recent backup may contain everything, but older backups may omit the caches. 

For now, is this a high priority?  Disk space is cheap. Complexity and time are expensive

**Comment by gbader** [comment]
This is a low priority, but a first step would be to inventory the data stored and make sure it is real/important.
