### ISSUE TITLE
Article not in PubMed - back to CrossRef (again)

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#961]
There are edge cases in using PubMed as an article search engine, including preprints and in rare cases, articles that simply can't be found in PubMed:

Case in point, someone tried to enter this into bioactoid.org and it came back as not found: [Higher prevalence of homologous recombination deficiency in tumors from African Americans versus European Americans. Nature Cancer volume 1, pages112–121(2020)](https://www.nature.com/articles/s43018-019-0009-7)

I recall we use Crossref already, could think about falling back to this somehow.

**Comment by gbader** [comment]
New journals are not in PubMed - it takes quite a while for them to 
build up to be included.  Nature Cancer is a new journal.

**Comment by jvwong** [comment]
Related to #955 - that is, an article may not have a PMID assigned.

**Comment by jvwong** [comment]
From what I could tell, this seems to be an edge case: There are a few articles from the first 2 issues of the journal (begun in 2020) that fall though the cracks and the example above is one of them.

**Comment by jvwong** [comment]
Opening this up, yet again, for reconsideration in light of (a) requirement to support authors and their articles at or near publication (e.g. eLife) (b) the general momentum towards preprints. 

Not sure when PubMed will get on board fully (https://www.ncbi.nlm.nih.gov/pmc/about/nihpreprints/) 

> Pilot Status
> Phase 2 of the NIH Preprint Pilot launched January 30, 2023. Phase 2 includes all preprints that
> 
> 1. Acknowledge direct NIH support and/or have an NIH-affiliated author; and
> 2. Are posted to an [eligible preprint server](https://www.ncbi.nlm.nih.gov/pmc/about/nihpreprints/#eligible) on January 1, 2023 or later.

**Comment by jvwong** [comment]
Notes for [Europe PMC Articles WS](https://europepmc.org/RestfulWebService) for preprint support.

- Sources
  - [21 preprint servers](https://europepmc.org/Preprints), including bioRxiv and medRxiv
- Recency 
  - bioRxiv records indexed  < 36 hours following posting
  - Indexing on CrossRef ~24 hours
- Data
  - [metadata available](https://europepmc.org/docs/EBI_Europe_PMC_Web_Service_Reference.pdf )
  - equivalent to CrossRef 
- Stability
  - ?
- Search
  - DOI, title and a [whole bunch of other fields](https://www.ebi.ac.uk/europepmc/webservices/rest/fields)

**Comment by jvwong** [comment]
I haven't found this to be a problem with eLife contributors so far so closing until it is.

**Comment by jvwong** [comment]
Of course, as soon as I close this reviewed manuscript gets submitted :)

**Comment by jvwong** [comment]
Issue items for related PRs:
  - [ ] CrossRef: helper service to access web service API
  - [x] Explorer support for articles with DOI (no PMID) (see #1196)
  - [ ] CrossRef: post-processing to prioritize and format search hits from web service API

**Comment by maxkfranz** [comment]
The PRs look good.  Merged.

**Comment by jvwong** [comment]
Further considerations when adding preprint support

Updating records (i.e. cron)
  - Harmonizing
    - Cases 
    - Same: CrossRef record and PubMed record
      - Can recognize by DOI, overwrite is probably OK
    - Related: CrossRef record and published PubMed record 
      - Do not overwrite

Other
   - storing relational information (is preprint of, etc)

**Comment by maxkfranz** [comment]
Would an overwrite delete all the previous ‘pubmed’ data, or would it be a merge?  Do you see a use case for merging?  Deletion would be simpler.

Another alternative is to store the original, raw data from each source so you could always recover or merge in future, i.e.

- `pubmed` stores the processed data the app expects
- `rawPubmed` stores the original, raw PubMed data
- `rawCrossRef` stores the original, raw CrossRef data

I think straightforward deletion is the simplest approach, but let me know if you see a use case for the other approaches.

**Comment by jvwong** [comment]
> Would an overwrite delete all the previous ‘pubmed’ data, or would it be a merge? Do you see a use case for merging? Deletion would be simpler.
> 
> Another alternative is to store the original, raw data from each source so you could always recover or merge in future, i.e.
> 
> * `pubmed` stores the processed data the app expects
> * `rawPubmed` stores the original, raw PubMed data
> * `rawCrossRef` stores the original, raw CrossRef data
> 
> I think straightforward deletion is the simplest approach, but let me know if you see a use case for the other approaches.

This (CRON updates/disambiguation of papers) deserves a separate issue, apart from CrossRef (todo). 

One latent bug that has emerged is: PubMed will now index  preprints from bioRxiv/medRxiv authored by those NIH-funded, so, e.g. someone could add a bioRxiv paper picked up by PubMed and if it was published somewhere with the same title (i.e. author input) it would get overwritten.

**Comment by jvwong** [comment]
Notes on PubMed and CrossRef

|Source  |ID Type                  |Article type attribute                 |Publishers Supported                    |Relations                |
|--------|-------------------------|---------------------------------------|----------------------------------------|-------------------------|
|PubMed  |PubMed uid               |<PublicationType> (MESH: D000076942)   |bioRxiv; medRxiv; arXiv; Research Square|child, parent            |
|CrossRef|Digital Object Identifier|type: posted-content; subtype: preprint|multiple (members)                      |child, parent, equivalent|

**Comment by jvwong** [comment]
Folding further updates into #1201
