### ISSUE TITLE
Review: Results of importing PSP BioPAX to Biofactoid

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#962]
Initial review of the results from importing (PhosphositePlus) BioPAX objects into Biofactoid.

- Setup 
  -  Local instances of factoid and [factoid-converters](https://github.com/PathwayCommons/factoid-converters)(master)
  - Input: https://www.pathwaycommons.org/archives/PC2/v12/PathwayCommons12.psp.BIOPAX.owl.gz 

### Import Rate

So far I'm about 45 minutes in and I'm seeing around 20 documents imported. Best guess why: Some of the documents created have 5-10 interactions, and the major bottleneck is the INDRA search, which can take up to 20 seconds for a single interaction. 

Aside: I've tried to limit the maximum number of results coming back in  https://github.com/PathwayCommons/factoid/tree/iss937_interaction-info. 

### Errors

A couple of instances of semanticsearch errors:

```
error:   Error getRelPprsForDoc: FetchError: invalid json response body at https://semanticsearch.baderlab.org/ reason: Unexpected token I in JSON at position 0
```

- ids
  - c82512ef-97ab-4d67-b285-b5ecf7ea4cd9
  - d2c9d2aa-56c4-4cf3-a44e-9aba1bde10de
  - b1f1b988-afb3-40ce-96f9-6988e3943c3d

### Samples and issues

I'll post these in the discussion below....

Related to #836

**Comment by jvwong** [comment]
<img src="https://user-images.githubusercontent.com/4706307/113597382-9f838200-9609-11eb-9d74-f6dc95ca3eba.png" height="350px" />

- redundancy in interactions (PDGFRB activates PDGFRB x7)
- missing citation info (see #955)

**Comment by jvwong** [comment]
<img src="https://user-images.githubusercontent.com/4706307/113598009-80d1bb00-960a-11eb-9826-e660e6123f5f.png" height="350px" />

- failed document-level related papers - why?

**Comment by jvwong** [comment]
<img src="https://user-images.githubusercontent.com/4706307/113598622-69470200-960b-11eb-8a9e-c94ed509b558.png" height="350px" />

- article with > 21 interactions???

**Comment by jvwong** [comment]
Also, regarding the input, I don't think it makes sense to have the client hold onto the the server connection while this process completes:

https://github.com/PathwayCommons/factoid/blob/3371008cc06657e0ce4da18fa5f8279c6d5fc68f/src/server/routes/api/document/index.js#L1873-L1876

**Comment by maxkfranz** [comment]
> <img alt="" height="350px" src="https://user-images.githubusercontent.com/4706307/113598009-80d1bb00-960a-11eb-9826-e660e6123f5f.png">
> 
> * failed document-level related papers - why?

Perhaps the set of duplicate interactions and the total number of interactions is hitting a service request limit.

**Comment by jvwong** [comment]
From the initial issue description, the error for 

>     * c82512ef-97ab-4d67-b285-b5ecf7ea4cd9

 didn't arise when I manually refreshed from the admin. 

Biological correctness:
  - 'Mixed' species (EGFR human, CAMKII rat), which is a red flag - Check this
  - The edge terminator looks opposite of what's indicated in the abstract 

![image](https://user-images.githubusercontent.com/4706307/113728951-8ab7f480-96c4-11eb-92b4-549f7c8538d0.png)

**Comment by jvwong** [comment]
Summarizing some of the observations from a sampling of auto-created documents from PhsophositePlus BioPAX (v12):

- Conceptual
  - Redundancy in interactions in factoid may in some cases reflect unique interactions in originating BioPAX
    - e.g. different feature (amino acid site) modified in the same controlled protein
  - Publications/evidence associated with a controlled interaction are intended to reference one/some but not all controllers 
    - e.g. A --> B, and C --> B: Where multiple papers are attached to B, and only one provides evidence for interaction with A  
  - factoid-2-bioPAX is lossy
    - We made a decision to play fast and loose with t-bar and arrow heads, which don't necessarily translate to BioPAX but people love them and they are used universally

- Technical
  - The conversion takes a while, some of this is by design to not overload services (2 minutes), some of this has to do with the number of interactions that come back for any one document (see above)
  - Having the admin/client hang on to a server connection for (hours/days?) is problematic
 
FYI @metincansiper

**Comment by jvwong** [comment]
I don't believe there's interest in back-filling, and more interest in actual author data. Close for now.
