### ISSUE TITLE
Grounding: The data source name should be made clear to user

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#969]
This issue relates to the editor node tool-tip association information that is displayed. We provide this information to help users editing their document decide if we have correctly matched the top database hit from the grounding search.   

Background: Currently, the user input is reused as the entity name of the top hit. The reasoning behind this decision is that it can sometimes be confusing to users if the grounding database provides an odd or not commonly used 'name' (which we use in the entity search results 2 onwards). One example is estrogen receptor, almost universally referred to as 'ER' has an offiical name 'ESR1' ([NCBI Gene 2099](https://identifiers.org/ncbigene:2099)).

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4706307/117188070-a3dac080-adaa-11eb-94cc-45075e99f39f.png">

Issue: This is a case where the ground is clearly incorrect, but the database name is informative, but nonetheless discarded. 

<img width="350" alt="image" src="https://user-images.githubusercontent.com/4706307/117188223-d1276e80-adaa-11eb-892d-3ebc636943f3.png">
 
In the latter case, the ChEBI name is [`Soman`](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:9195) which would be helpful for the user to have, or would at least give them pause.

**Comment by jvwong** [comment]
Simple approach is to include Official Name/CheEBI Name in the top hit under 'synonyms'.

<img src="https://user-images.githubusercontent.com/4706307/117193129-7ee94c00-adb0-11eb-9560-b507e020c69f.png"  width="350px" />

**Comment by maxkfranz** [comment]
Yeah, I think we discussed that option at some point, but it wasn’t a priority since we didn’t have compelling example entities.

More specifically, the rule may be: If the typed name is not the same as the official name, then we add the official name to the start of the synonym list.  This avoids duplication when there’s an exact match.
