### ISSUE TITLE
GitHub workflows for Docker Hub images

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#983]
Looks like Docker is disabling autobuilds now: https://www.docker.com/blog/changes-to-docker-hub-autobuilds/ 

Will likely need to do this on our end and push up.

**Comment by gbader** [comment]
are we on the open source plan?

**Comment by jvwong** [comment]
no but I can try to ask them

**Comment by jvwong** [comment]
OK submitted request to Docker Hub for OSS status.

**Comment by jvwong** [comment]
Autobuilds are still working past their June 18, 2021 date.

**Comment by jvwong** [comment]
Actually this got disabled, will follow up again.

**Comment by jvwong** [comment]
Docker responded, currently under review by Docker staff (contact A. Suaruez)

**Comment by jvwong** [comment]
> Hello Jeffrey,
>
> Welcome to the Docker Open Source Program!  We are very excited to have you as a part of our great community.  We have allow-listed your namespace "pathwaycommons" and this should come into effect in the next week or so. With this allowed-listing, the Docker data pull rate policies that went into effect last November, will not apply to the users pulling images from your namespace.  
>
> Thank you for your support for Docker and your open source contributions.
>
> Many thanks,
>
>
> Docker Marketing Team.

**Comment by jvwong** [comment]
OK we're back in business with autobuilds.
