### ISSUE TITLE
Network-level related papers: Fallback when external service fails

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#985]
Background: Related to [Regulation of mRNA export through API5 and nuclear FGF2 interaction. Nucleic Acids Res 48 2020](https://biofactoid.org/document/8e17bc30-b426-4ee1-addc-33067caabc8f) explorer view, network-level related papers.

- Issue: Some of the entities (e.g. eIF4, LRPPRC) and edges have no related papers associated with them.

- Reproducing this bug: I can reproduce locally with database dump. The offending items have no `relatedPapers` attribute set in the db.

Logs:

```
info:    Updating network-level related papers for doc 8e17bc30-b426-4ee1-addc-33067caabc8f
info:    PATCH /api/document/8e17bc30-b426-4ee1-addc-33067caabc8f/<secret> - - ms - -
error:   Null response for http://api.indra.bio:8000/assemblers/english
info:    Retrying, attempt 1
info:    Updating document-level related papers for doc 8e17bc30-b426-4ee1-addc-33067caabc8f
info:    Finished updating document-level related papers
info:    Updating network-level related papers for doc 8e17bc30-b426-4ee1-addc-33067caabc8f
error:   Null response for http://api.indra.bio:8000/assemblers/english
info:    Retrying, attempt 2
info:    PATCH /api/document/8e17bc30-b426-4ee1-addc-33067caabc8f/<secret> - - ms - -

error:   Null response for http://api.indra.bio:8000/assemblers/english
info:    Retrying, attempt 1
error:   Null response for http://api.indra.bio:8000/assemblers/english
info:    Retrying, attempt 3
....

```

**Comment by jvwong** [comment]
related to #937

**Comment by jvwong** [comment]
Doesn't look like the INDRA endpoint (http://api.indra.bio:8000) is reachable. Should have some sane fallback.

**Comment by jvwong** [comment]
INDRA endpoint came back up, related papers OK now --- but this issue is still valid: Should have fallback when services fail.

**Comment by maxkfranz** [comment]
Isn't the related papers refresh cron job turned on?  It should just fix itself on the next run, assuming that Indra is up.

**Comment by jvwong** [comment]
The cron job is off because I wanted to include a fallback (https://github.com/PathwayCommons/factoid/pull/916) - so I can turn it back on. 

I'd like to turn all these things back on in the Digital Ocean version (either staging(master) / prod).

**Comment by jvwong** [comment]
The  CRON schedule is specified as part of https://github.com/PathwayCommons/factoid-docker-config.
