### ISSUE TITLE
Editor: Warning when attempting to close tab on unsubmitted network

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#992]
> 5. Please consider updating Biofactoid so it includes the functionality to ask about closing the window before a submission is submitted (currently if one accidentally clicks the 'close' button, it simply closes).

**Comment by maxkfranz** [comment]
See

- https://developer.mozilla.org/en-US/docs/Web/API/Window/beforeunload_event
- https://developers.google.com/web/updates/2018/07/page-lifecycle-api#the-beforeunload-event
