### ISSUE TITLE
CRON: Delete demo docs

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/factoid#997]
Should be self-explanatory. Can identify demo docs via `DEMO_SECRET`.

Related to #995

**Comment by gbader** [comment]
this should not delete just created docs, so the docs should have a defined lifetime before they are deleted.

**Comment by jvwong** [comment]
Good point, generally we have a lot of stuff (auto-emailed related-author docs, user-initiated but old/abandoned) along with demos  that we'll have to figure out how to handle.

**Comment by jvwong** [comment]
How to consider docs for automated removal:

i) Trashed docs 
Remove immediately

ii) Demo docs
Remove after short period of inactivity
 
ii) Initiated docs
//TODO

**Comment by jvwong** [comment]
There seems to be a bug in the document `lastEditedDate` type. 

In general, it looks like docs with no entries/unedited are type `PTYPE<TIME>` vs `STRING` for ones with entries/edited, but there are exceptions (e.g. 2013fc15-ddb3-4f6c-8d83-911dc7af4f1d; 159f2c80-eb33-4ef4-94be-867216479041)

**Comment by jvwong** [comment]
I'm guessing the time types are reflecting whether this was set in browser (updateLastEditedDate) vs server?

**Comment by maxkfranz** [comment]
It's NoSQL, so it depends on the value you send to the DB.  Regardless of where the inconsistency is, the API (probably the `Document`) should simply enforce a normalisation.

**Comment by jvwong** [comment]
> It's NoSQL, so it depends on the value you send to the DB. Regardless of where the inconsistency is, the API (probably the `Document`) should simply enforce a normalisation.

OK I'll look at this.

Back to the main issue - is it better to simply update these docs we don't want as 'trashed' or delete them entirely?

**Comment by maxkfranz** [comment]
I'm fine leaving the documents marked as 'trashed' in the DB for now.  It's not like they're using up that much space, right?  As long as demo docs and trashed docs aren't accessible in the BioPAX data exports, I think that's the main thing.

**Comment by jvwong** [comment]
I like trashing option better. Always easy to clear those out.
